# Copyright (C) 2026, Princeton University.
# This source code is licensed under the BSD 3-Clause license found in the LICENSE file in the root directory of this source tree.

# Authors: Alexander Raistrick

from typing import NamedTuple

import procfunc as pf
from procfunc.nodes import types as t

__all__ = [
    "curve_to_mesh_with_uv",
    "curve_to_noncyclic",
    "fillet_mask",
]


class _CurveToMeshWithUvResult(NamedTuple):
    mesh: pf.ProcNode[pf.MeshObject]
    vector: pf.ProcNode[pf.Vector]


@pf.nodes.node_function
def curve_to_mesh_with_uv(
    curve: pf.ProcNode[pf.CurveObject],
    profile: pf.ProcNode[pf.CurveObject],
    fill_caps: t.SocketOrVal[bool] = False,
) -> _CurveToMeshWithUvResult:
    # Code generated by procfunc v0.12.0

    input_index = pf.nodes.geo.input_index()

    index_on_curve = pf.nodes.geo.capture_attribute(geometry=curve, index=input_index)

    spline_parameter = pf.nodes.geo.spline_parameter()

    length_on_curve = pf.nodes.geo.capture_attribute(
        geometry=index_on_curve.geometry,
        length=spline_parameter.length,
    )

    spline_parameter_1 = pf.nodes.geo.spline_parameter()

    capture_attribute = pf.nodes.geo.capture_attribute(
        geometry=profile, length=spline_parameter_1.length
    )

    to_mesh = pf.nodes.geo.curve_to_mesh(
        curve=length_on_curve.geometry,
        profile_curve=capture_attribute.geometry,
        fill_caps=fill_caps,
    )

    corner_in_mesh = pf.nodes.geo.input_index()

    face_of_corner = pf.nodes.geo.face_of_corner(corner_in_mesh)

    is_frontwards_edge = pf.nodes.func.greater_than(a=face_of_corner.index_in_face, b=1)
    is_connected_start = pf.nodes.func.equal(a=0, b=index_on_curve.index)

    vector_x_switch = pf.nodes.func.boolean_and(
        a=is_frontwards_edge, b=is_connected_start
    )

    curve_length = pf.nodes.geo.curve_length(index_on_curve.geometry)

    replace_last_with_length = pf.nodes.func.switch(
        switch=vector_x_switch, a=length_on_curve.length, b=curve_length
    )

    vector = pf.nodes.math.combine_xyz(
        x=replace_last_with_length, y=capture_attribute.length
    )

    store_named_attribute = pf.nodes.geo.store_named_attribute(
        domain="CORNER",
        geometry=to_mesh,
        name="UVMap",
        value=vector,
        data_type="FLOAT2",
    )
    return _CurveToMeshWithUvResult(
        mesh=store_named_attribute,
        vector=vector,
    )


class _FilletMaskResult(NamedTuple):
    curve: pf.ProcNode[pf.CurveObject]
    is_fillet_point: pf.ProcNode[bool]
    is_flat_point: pf.ProcNode[bool]
    orig_point_idx: pf.ProcNode[int]


@pf.nodes.node_function
def fillet_mask(
    geometry: pf.ProcNode[pf.CurveObject],
    selection: t.SocketOrVal[bool],
    fillet_vertices: t.SocketOrVal[int],
    radius: t.SocketOrVal[float],
) -> _FilletMaskResult:
    # Code generated by procfunc v0.16.0

    capture_attribute = pf.nodes.geo.capture_attribute(
        geometry=geometry, value=selection
    )

    fillet_no_rad = pf.nodes.geo.fillet_curve_poly(
        curve=capture_attribute.geometry,
        radius=1e-06,
        limit_radius=True,
        count=fillet_vertices,
    )
    fillet_with_rad = pf.nodes.geo.fillet_curve_poly(
        curve=capture_attribute.geometry,
        radius=radius + 1e-05,
        limit_radius=True,
        count=fillet_vertices,
    )

    input_position = pf.nodes.geo.input_position()
    input_index = pf.nodes.geo.input_index()

    query_fillet_pos = pf.nodes.geo.sample_index(
        geometry=fillet_with_rad,
        index=input_index,
        value=input_position,
    )

    selective_apply_fillet = pf.nodes.geo.set_position(
        geometry=fillet_no_rad,
        selection=capture_attribute.value,
        position=query_fillet_pos,
    )

    input_index_1 = pf.nodes.geo.input_index()

    is_flat_point_is_fillet_edge_a_b = fillet_vertices.astype(dtype=float) + 1.0
    is_flat_point_is_fillet_edge_a = pf.nodes.math.floor_mod(
        a=input_index_1.astype(dtype=float),
        b=is_flat_point_is_fillet_edge_a_b,
    )
    is_flat_point_is_fillet_edge = pf.nodes.func.equal(
        a=is_flat_point_is_fillet_edge_a, b=1.0, epsilon=0.01
    )

    capture_attribute_1 = pf.nodes.geo.capture_attribute(
        geometry=selective_apply_fillet,
        is_fillet_edge=is_flat_point_is_fillet_edge,
    )

    curve_value = pf.nodes.math.floor(
        input_index_1.astype(dtype=float) / is_flat_point_is_fillet_edge_a_b
    )

    capture_attribute_2 = pf.nodes.geo.capture_attribute(
        geometry=capture_attribute_1.geometry,
        value=curve_value.astype(dtype=int),
    )

    is_fillet_point = pf.nodes.func.boolean_not(capture_attribute_1.is_fillet_edge)
    return _FilletMaskResult(
        curve=capture_attribute_2.geometry,
        is_fillet_point=is_fillet_point,
        is_flat_point=capture_attribute_1.is_fillet_edge,
        orig_point_idx=capture_attribute_2.value,
    )


@pf.nodes.node_function
def curve_to_noncyclic(
    input: pf.ProcNode[pf.CurveObject],
) -> pf.ProcNode[pf.CurveObject]:
    # Code generated by procfunc v0.16.0

    curve_line = pf.nodes.geo.curve_line(start=(0, 0, 0), end=(0, 0, 1))

    attribute_domain_size = pf.nodes.geo.attribute_domain_size(
        geometry=input, component="CURVE"
    )

    count = attribute_domain_size.point_count.astype(dtype=float) + 1.0

    resample_curve_count = pf.nodes.geo.resample_curve_count(
        curve=curve_line,
        count=count.astype(dtype=int),
    )

    input_position = pf.nodes.geo.input_position()
    input_index = pf.nodes.geo.input_index()

    sample_index_index = pf.nodes.math.floor_mod(
        a=input_index.astype(dtype=float),
        b=attribute_domain_size.point_count.astype(dtype=float),
    )
    sample_index = pf.nodes.geo.sample_index(
        geometry=input,
        index=sample_index_index.astype(dtype=int),
        value=input_position,
    )

    set_position = pf.nodes.geo.set_position(
        geometry=resample_curve_count, position=sample_index
    )
    return set_position
