# Copyright (C) 2026, Princeton University.
# This source code is licensed under the BSD 3-Clause license found in the LICENSE file in the root directory of this source tree.

# Authors: Karhan Kayan, Alexander Raistrick

import procfunc as pf


@pf.nodes.node_function
def instance(
    parent: pf.ProcNode[pf.MeshObject],
    child: pf.ProcNode[pf.Collection],
    seed: pf.ProcNode[int] = 0,
    density: pf.ProcNode[float] = 2.0,
    distance_min: pf.ProcNode[float] = 0.0,
    offset: pf.ProcNode[pf.Vector] = (0, 0, 0.002),
) -> pf.ProcNode:
    input_normal = pf.nodes.geo.input_normal()

    instance_0_selection = pf.nodes.func.greater_than(a=input_normal.z, b=0.9)

    distribute_points_on_faces = pf.nodes.geo.distribute_points_on_faces_poisson(
        mesh=parent,
        selection=instance_0_selection,
        seed=seed,
        density_factor=density,
        distance_min=distance_min,
    )
    instance_0_z = pf.nodes.func.random_value(max=6.283185)
    instance_1 = pf.nodes.math.combine_xyz(z=instance_0_z)

    child_options = pf.nodes.geo.collection_info(child, separate_children=True)

    instance_on_points = pf.nodes.geo.instance_on_points(
        points=distribute_points_on_faces.points,
        instance=child_options,
        pick_instance=True,
        rotation=instance_1.astype(dtype=pf.Euler),
    )

    lifted = pf.nodes.geo.transform(
        instance_on_points, translation=offset, rotation=(0, 0, 0), scale=(1, 1, 1)
    )

    return lifted


def instanced_objects(
    rng: pf.RNG,
    parent: pf.MeshObject,
    child: pf.Collection,
    density: float = 2.0,
    distance_min: float = 0.0,
    offset: tuple[float, float, float] = (0, 0, 0.002),
) -> list[pf.MeshObject]:
    instanced_geometry = instance(
        parent=parent,
        child=child,
        seed=int(pf.random.randint(rng, 0, 2**31 - 1)),
        density=density,
        distance_min=distance_min,
        offset=offset,
    )
    aliases = pf.nodes.to_aliases(instanced_geometry)
    for alias in aliases:
        alias.item().matrix_world = (
            parent.item().matrix_world @ alias.item().matrix_world
        )
    return aliases


if __name__ == "__main__":
    # Code generated by procfunc v0.18.0-ifg

    parent = pf.ops.primitives.mesh_cube()
    child = pf.ops.primitives.mesh_uv_sphere(radius=0.1)
    instance_result = instance(parent=parent, child=child)
