# Copyright (C) 2026, Princeton University.
# This source code is licensed under the BSD 3-Clause license found in the LICENSE file in the root directory of this source tree.

# Authors: Alexander Raistrick

import procfunc as pf
from procfunc.nodes import types as t

__all__ = [
    "offset_spacing",
]


@pf.nodes.node_function
def offset_spacing(
    seed: t.SocketOrVal[int],
    dimension: t.SocketOrVal[float],
    index: t.SocketOrVal[int],
    vertices: t.SocketOrVal[int],
    max_offset_pct: t.SocketOrVal[float],
) -> pf.ProcNode[float]:
    # Code generated by procfunc v0.12.0

    a_1 = pf.nodes.func.random_value(
        min=max_offset_pct * -0.5,
        max=0.5 * max_offset_pct,
        id=index,
        seed=seed,
    )
    a_0 = dimension / vertices.astype(dtype=float)
    b_1 = pf.nodes.func.not_equal(a=index.astype(dtype=float), b=0.0, epsilon=0.001)
    b_0 = pf.nodes.func.not_equal(
        a=index.astype(dtype=float),
        b=vertices.astype(dtype=float) - 1.0,
        epsilon=0.001,
    )

    multiply = (a_1 * a_0) * b_1.astype(dtype=float) * b_0.astype(dtype=float)
    return multiply
