from typing import NamedTuple

import procfunc as pf
from procfunc.nodes import types as t


class DisplacementLayerResult(NamedTuple):
    height: pf.ProcNode[float]
    displacement: t.SocketOrVal[pf.Vector]


@pf.nodes.node_function
def noise_displacement(
    vector: t.SocketOrVal[pf.Vector] = (0.0, 0.0, 0.0),
    w: t.SocketOrVal[float] = 0.0,
    size: t.SocketOrVal[float] = 1.0,
    detail: t.SocketOrVal[float] = 2.0,
    lacunarity: t.SocketOrVal[float] = 2.0,
) -> pf.ProcNode[float]:
    # Code generated by procfunc v0.3.0

    result_0_value = pf.nodes.shader.noise(
        vector=vector,
        w=w,
        scale=2.0 / size,
        detail=detail,
        lacunarity=lacunarity,
        noise_dimensions="4D",
    )

    map_range = pf.nodes.func.map_range(
        value=result_0_value.fac, from_min=0.2, from_max=0.8
    )
    return map_range


@pf.nodes.node_function
def fractal_chip(
    vector: t.SocketOrVal[pf.Vector],
    w: t.SocketOrVal[float] = 0.0,
    size: t.SocketOrVal[float] = 0.0,
    levels: t.SocketOrVal[float] = 0.0,
    fractal_step_size: t.SocketOrVal[float] = 0.0,
) -> DisplacementLayerResult:
    # Code generated by procfunc v0.3.0

    height_numerator_vector = pf.nodes.math.vector_scale(
        vector=vector, scale=1.0 / size
    )
    height_numerator_w = w / size
    height_numerator_17 = pf.nodes.shader.voronoi_distance(
        vector=height_numerator_vector,
        w=height_numerator_w,
        scale=1.0,
        voronoi_dimensions="4D",
    )
    height_numerator_16 = pf.nodes.math.clamp(levels + 0.0)
    height_numerator_15 = pf.nodes.shader.voronoi_distance(
        vector=height_numerator_vector,
        w=height_numerator_w + 10.0,
        scale=fractal_step_size,
        voronoi_dimensions="4D",
    )
    height_denominator_7 = 1.0 / fractal_step_size
    height_numerator_14 = height_numerator_16 * (
        height_numerator_15 * height_denominator_7
    )
    height_numerator_13 = pf.nodes.math.clamp(levels - 1.0)
    height_numerator_12 = pf.nodes.shader.voronoi_distance(
        vector=height_numerator_vector,
        w=height_numerator_w + 20.0,
        scale=fractal_step_size**2.0,
        voronoi_dimensions="4D",
    )
    height_denominator_6 = height_denominator_7**2.0
    height_numerator_11 = height_numerator_12 * height_denominator_6
    height_numerator_10 = (height_numerator_17 + height_numerator_14) + (
        height_numerator_13 * height_numerator_11
    )
    height_numerator_9 = pf.nodes.math.clamp(levels - 2.0)
    height_numerator_8 = pf.nodes.shader.voronoi_distance(
        vector=height_numerator_vector,
        w=height_numerator_w + 30.0,
        scale=(fractal_step_size**2.0) * fractal_step_size,
        voronoi_dimensions="4D",
    )
    height_numerator_7 = (
        height_numerator_9
        * height_numerator_8
        * (height_denominator_6 * height_denominator_7)
    )
    height_numerator_6 = pf.nodes.math.clamp(levels - 3.0)
    height_numerator_5 = pf.nodes.shader.voronoi_distance(
        vector=height_numerator_vector,
        w=height_numerator_w + 40.0,
        scale=(fractal_step_size**2.0) * fractal_step_size * fractal_step_size,
        voronoi_dimensions="4D",
    )
    height_denominator_5 = (
        height_denominator_6 * height_denominator_7
    ) * height_denominator_7
    height_numerator_4 = height_numerator_5 * height_denominator_5
    height_numerator_3 = (height_numerator_10 + height_numerator_7) + (
        height_numerator_6 * height_numerator_4
    )
    height_numerator_2 = pf.nodes.math.clamp(levels - 4.0)
    height_numerator_1 = pf.nodes.shader.voronoi_distance(
        vector=height_numerator_vector,
        w=height_numerator_w + 50.0,
        scale=(fractal_step_size**2.0)
        * fractal_step_size
        * fractal_step_size
        * fractal_step_size,
        voronoi_dimensions="4D",
    )
    height_numerator = (
        height_numerator_2
        * height_numerator_1
        * (height_denominator_5 * height_denominator_7)
    )
    height_denominator_4 = height_numerator_16 * height_denominator_7
    height_denominator_3 = (height_denominator_4 + 1.0) + (
        height_denominator_6 * height_numerator_13
    )
    height_denominator_2 = (
        height_denominator_6 * height_denominator_7
    ) * height_numerator_9
    height_denominator_1 = (height_denominator_3 + height_denominator_2) + (
        height_denominator_5 * height_numerator_6
    )
    height_denominator = (
        height_denominator_5 * height_denominator_7
    ) * height_numerator_2
    height = (height_numerator_3 + height_numerator) / (
        height_denominator_1 + height_denominator
    )
    return DisplacementLayerResult(
        height=height,
        displacement=vector,
    )


@pf.nodes.node_function
def fractal_chip_truncated(
    vector: t.SocketOrVal[pf.Vector],
    w: t.SocketOrVal[float] = 0.0,
    size: t.SocketOrVal[float] = 0.0,
    levels: t.SocketOrVal[float] = 0.0,
    fractal_step_size: t.SocketOrVal[float] = 0.0,
) -> DisplacementLayerResult:
    # Same as fractal_chip but drops the deepest octave (the
    # height_numerator_1 branch gated by clamp(levels - 4)). That branch is
    # weighted by 1/fractal_step_size^5 — the smallest-amplitude detail in
    # the fractal. Saves ~13 nodes per call (one voronoi_distance, one
    # clamp, plus the math chain feeding it). Use when the caller does not
    # need the finest octave of the fractal — for granite minerals at
    # levels<=5 the visual difference is subtle and the node-budget savings
    # let granite-using materials clear the shader-complexity threshold.
    height_numerator_vector = pf.nodes.math.vector_scale(
        vector=vector, scale=1.0 / size
    )
    height_numerator_w = w / size
    height_numerator_17 = pf.nodes.shader.voronoi_distance(
        vector=height_numerator_vector,
        w=height_numerator_w,
        scale=1.0,
        voronoi_dimensions="4D",
    )
    height_numerator_16 = pf.nodes.math.clamp(levels + 0.0)
    height_numerator_15 = pf.nodes.shader.voronoi_distance(
        vector=height_numerator_vector,
        w=height_numerator_w + 10.0,
        scale=fractal_step_size,
        voronoi_dimensions="4D",
    )
    height_denominator_7 = 1.0 / fractal_step_size
    height_numerator_14 = height_numerator_16 * (
        height_numerator_15 * height_denominator_7
    )
    height_numerator_13 = pf.nodes.math.clamp(levels - 1.0)
    height_numerator_12 = pf.nodes.shader.voronoi_distance(
        vector=height_numerator_vector,
        w=height_numerator_w + 20.0,
        scale=fractal_step_size**2.0,
        voronoi_dimensions="4D",
    )
    height_denominator_6 = height_denominator_7**2.0
    height_numerator_11 = height_numerator_12 * height_denominator_6
    height_numerator_10 = (height_numerator_17 + height_numerator_14) + (
        height_numerator_13 * height_numerator_11
    )
    height_numerator_9 = pf.nodes.math.clamp(levels - 2.0)
    height_numerator_8 = pf.nodes.shader.voronoi_distance(
        vector=height_numerator_vector,
        w=height_numerator_w + 30.0,
        scale=(fractal_step_size**2.0) * fractal_step_size,
        voronoi_dimensions="4D",
    )
    height_numerator_7 = (
        height_numerator_9
        * height_numerator_8
        * (height_denominator_6 * height_denominator_7)
    )
    height_numerator_6 = pf.nodes.math.clamp(levels - 3.0)
    height_numerator_5 = pf.nodes.shader.voronoi_distance(
        vector=height_numerator_vector,
        w=height_numerator_w + 40.0,
        scale=(fractal_step_size**2.0) * fractal_step_size * fractal_step_size,
        voronoi_dimensions="4D",
    )
    height_denominator_5 = (
        height_denominator_6 * height_denominator_7
    ) * height_denominator_7
    height_numerator_4 = height_numerator_5 * height_denominator_5
    height_numerator_3 = (height_numerator_10 + height_numerator_7) + (
        height_numerator_6 * height_numerator_4
    )
    height_denominator_4 = height_numerator_16 * height_denominator_7
    height_denominator_3 = (height_denominator_4 + 1.0) + (
        height_denominator_6 * height_numerator_13
    )
    height_denominator_2 = (
        height_denominator_6 * height_denominator_7
    ) * height_numerator_9
    height_denominator_1 = (height_denominator_3 + height_denominator_2) + (
        height_denominator_5 * height_numerator_6
    )
    height = height_numerator_3 / height_denominator_1
    return DisplacementLayerResult(
        height=height,
        displacement=vector,
    )


@pf.nodes.node_function
def voronoi_displacement(
    vector: t.SocketOrVal[pf.Vector] = (0.0, 0.0, 0.0),
    w: t.SocketOrVal[float] = 0.0,
    size: t.SocketOrVal[float] = 0.0,
    detail: t.SocketOrVal[float] = 0.0,
    lacunarity: t.SocketOrVal[float] = 0.0,
) -> pf.ProcNode[float]:
    # Code generated by procfunc v0.3.0

    result_0_numerator_scale_3 = 2.0 / size
    result_0_numerator_21 = pf.nodes.shader.voronoi(
        vector=vector,
        w=w,
        scale=result_0_numerator_scale_3,
        normalize=True,
        voronoi_dimensions="4D",
    )
    result_0_numerator_20 = pf.nodes.func.mix(
        a=result_0_numerator_21.distance,
        b=1.0 - result_0_numerator_21.distance,
    )
    result_0_numerator_19 = pf.nodes.math.clamp(detail + 0.0)
    result_0_numerator_w_3 = 10.0 * size
    result_0_numerator_18 = pf.nodes.shader.voronoi(
        vector=vector,
        w=w + result_0_numerator_w_3,
        scale=result_0_numerator_scale_3 * lacunarity,
        normalize=True,
        voronoi_dimensions="4D",
    )
    result_0_numerator_17 = pf.nodes.func.mix(
        a=result_0_numerator_18.distance,
        b=1.0 - result_0_numerator_18.distance,
    )
    result_0_denominator_7 = 1.0 / lacunarity
    result_0_numerator_16 = result_0_numerator_19 * (
        result_0_numerator_17 * result_0_denominator_7
    )
    result_0_numerator_15 = pf.nodes.math.clamp(detail - 1.0)
    result_0_denominator_6 = result_0_denominator_7**2.0
    result_0_numerator_14 = 0.5 * result_0_denominator_6
    result_0_numerator_13 = (result_0_numerator_20 + result_0_numerator_16) + (
        result_0_numerator_15 * result_0_numerator_14
    )
    result_0_numerator_12 = pf.nodes.math.clamp(detail - 2.0)
    result_0_numerator_w_2 = 30.0 * size
    result_0_numerator_scale_2 = (lacunarity**2.0) * lacunarity
    result_0_numerator_11 = pf.nodes.shader.voronoi(
        vector=vector,
        w=w + result_0_numerator_w_2,
        scale=result_0_numerator_scale_3 * result_0_numerator_scale_2,
        normalize=True,
        voronoi_dimensions="4D",
    )
    result_0_numerator_10 = pf.nodes.func.mix(
        a=result_0_numerator_11.distance,
        b=1.0 - result_0_numerator_11.distance,
    )
    result_0_numerator_9 = (
        result_0_numerator_12
        * result_0_numerator_10
        * (result_0_denominator_6 * result_0_denominator_7)
    )
    result_0_numerator_8 = pf.nodes.math.clamp(detail - 3.0)
    result_0_numerator_w_1 = 40.0 * size
    result_0_numerator_scale_1 = result_0_numerator_scale_2 * lacunarity
    result_0_numerator_7 = pf.nodes.shader.voronoi(
        vector=vector,
        w=w + result_0_numerator_w_1,
        scale=result_0_numerator_scale_3 * result_0_numerator_scale_1,
        normalize=True,
        voronoi_dimensions="4D",
    )
    result_0_numerator_6 = pf.nodes.func.mix(
        a=result_0_numerator_7.distance,
        b=1.0 - result_0_numerator_7.distance,
    )
    result_0_denominator_5 = (
        result_0_denominator_6 * result_0_denominator_7
    ) * result_0_denominator_7
    result_0_numerator_5 = result_0_numerator_6 * result_0_denominator_5
    result_0_numerator_4 = (result_0_numerator_13 + result_0_numerator_9) + (
        result_0_numerator_8 * result_0_numerator_5
    )
    result_0_numerator_3 = pf.nodes.math.clamp(detail - 4.0)
    result_0_numerator_w = 50.0 * size
    result_0_numerator_scale = result_0_numerator_scale_1 * lacunarity
    result_0_numerator_2 = pf.nodes.shader.voronoi(
        vector=vector,
        w=w + result_0_numerator_w,
        scale=result_0_numerator_scale_3 * result_0_numerator_scale,
        normalize=True,
        voronoi_dimensions="4D",
    )
    result_0_numerator_1 = pf.nodes.func.mix(
        a=result_0_numerator_2.distance,
        b=1.0 - result_0_numerator_2.distance,
    )
    result_0_numerator = (
        result_0_numerator_3
        * result_0_numerator_1
        * (result_0_denominator_5 * result_0_denominator_7)
    )
    result_0_denominator_4 = result_0_numerator_19 * result_0_denominator_7
    result_0_denominator_3 = (result_0_denominator_4 + 1.0) + (
        result_0_denominator_6 * result_0_numerator_15
    )
    result_0_denominator_2 = (
        result_0_denominator_6 * result_0_denominator_7
    ) * result_0_numerator_12
    result_0_denominator_1 = (result_0_denominator_3 + result_0_denominator_2) + (
        result_0_denominator_5 * result_0_numerator_8
    )
    result_0_denominator = (
        result_0_denominator_5 * result_0_denominator_7
    ) * result_0_numerator_3

    divide = (result_0_numerator_4 + result_0_numerator) / (
        result_0_denominator_1 + result_0_denominator
    )
    return divide


@pf.nodes.node_function
def chip_displacement(
    vector: t.SocketOrVal[pf.Vector] = (0.0, 0.0, 0.0),
    w: t.SocketOrVal[float] = 0.0,
    size: t.SocketOrVal[float] = 0.0,
    detail: t.SocketOrVal[float] = 0.0,
    lacunarity: t.SocketOrVal[float] = 0.0,
) -> pf.ProcNode[float]:
    # Code generated by procfunc v0.3.0

    result_0_numerator_scale_4 = 2.0 / size
    result_0_numerator_17 = pf.nodes.shader.voronoi_distance(
        vector=vector,
        w=w,
        scale=result_0_numerator_scale_4,
        normalize=True,
        voronoi_dimensions="4D",
    )
    result_0_numerator_16 = pf.nodes.math.clamp(detail + 0.0)
    result_0_numerator_w_4 = 10.0 * size
    result_0_numerator_15 = pf.nodes.shader.voronoi_distance(
        vector=vector,
        w=w + result_0_numerator_w_4,
        scale=result_0_numerator_scale_4 * lacunarity,
        normalize=True,
        voronoi_dimensions="4D",
    )
    result_0_denominator_7 = 1.0 / lacunarity
    result_0_numerator_14 = result_0_numerator_16 * (
        result_0_numerator_15 * result_0_denominator_7
    )
    result_0_numerator_13 = pf.nodes.math.clamp(detail - 1.0)
    result_0_numerator_w_3 = 20.0 * size
    result_0_numerator_scale_3 = lacunarity**2.0
    result_0_numerator_12 = pf.nodes.shader.voronoi_distance(
        vector=vector,
        w=w + result_0_numerator_w_3,
        scale=result_0_numerator_scale_4 * result_0_numerator_scale_3,
        normalize=True,
        voronoi_dimensions="4D",
    )
    result_0_denominator_6 = result_0_denominator_7**2.0
    result_0_numerator_11 = result_0_numerator_12 * result_0_denominator_6
    result_0_numerator_10 = (result_0_numerator_17 + result_0_numerator_14) + (
        result_0_numerator_13 * result_0_numerator_11
    )
    result_0_numerator_9 = pf.nodes.math.clamp(detail - 2.0)
    result_0_numerator_w_2 = 30.0 * size
    result_0_numerator_scale_2 = result_0_numerator_scale_3 * lacunarity
    result_0_numerator_8 = pf.nodes.shader.voronoi_distance(
        vector=vector,
        w=w + result_0_numerator_w_2,
        scale=result_0_numerator_scale_4 * result_0_numerator_scale_2,
        normalize=True,
        voronoi_dimensions="4D",
    )
    result_0_numerator_7 = (
        result_0_numerator_9
        * result_0_numerator_8
        * (result_0_denominator_6 * result_0_denominator_7)
    )
    result_0_numerator_6 = pf.nodes.math.clamp(detail - 3.0)
    result_0_numerator_w_1 = 40.0 * size
    result_0_numerator_scale_1 = result_0_numerator_scale_2 * lacunarity
    result_0_numerator_5 = pf.nodes.shader.voronoi_distance(
        vector=vector,
        w=w + result_0_numerator_w_1,
        scale=result_0_numerator_scale_4 * result_0_numerator_scale_1,
        normalize=True,
        voronoi_dimensions="4D",
    )
    result_0_denominator_5 = (
        result_0_denominator_6 * result_0_denominator_7
    ) * result_0_denominator_7
    result_0_numerator_4 = result_0_numerator_5 * result_0_denominator_5
    result_0_numerator_3 = (result_0_numerator_10 + result_0_numerator_7) + (
        result_0_numerator_6 * result_0_numerator_4
    )
    result_0_numerator_2 = pf.nodes.math.clamp(detail - 4.0)
    result_0_numerator_w = 50.0 * size
    result_0_numerator_scale = result_0_numerator_scale_1 * lacunarity
    result_0_numerator_1 = pf.nodes.shader.voronoi_distance(
        vector=vector,
        w=w + result_0_numerator_w,
        scale=result_0_numerator_scale_4 * result_0_numerator_scale,
        normalize=True,
        voronoi_dimensions="4D",
    )
    result_0_numerator = (
        result_0_numerator_2
        * result_0_numerator_1
        * (result_0_denominator_5 * result_0_denominator_7)
    )
    result_0_denominator_4 = result_0_numerator_16 * result_0_denominator_7
    result_0_denominator_3 = (result_0_denominator_4 + 1.0) + (
        result_0_denominator_6 * result_0_numerator_13
    )
    result_0_denominator_2 = (
        result_0_denominator_6 * result_0_denominator_7
    ) * result_0_numerator_9
    result_0_denominator_1 = (result_0_denominator_3 + result_0_denominator_2) + (
        result_0_denominator_5 * result_0_numerator_6
    )
    result_0_denominator = (
        result_0_denominator_5 * result_0_denominator_7
    ) * result_0_numerator_2

    divide = (result_0_numerator_3 + result_0_numerator) / (
        result_0_denominator_1 + result_0_denominator
    )
    return divide
