import procfunc as pf
from procfunc.nodes import types as t


@pf.nodes.node_function
def offset_spacing(
    seed: t.SocketOrVal[int],
    dimension: t.SocketOrVal[float],
    index: t.SocketOrVal[int],
    vertices: t.SocketOrVal[int],
    max_offset_pct: t.SocketOrVal[float],
) -> pf.ProcNode[float]:
    # Code generated by procfunc v0.12.0

    result_0_a_1 = pf.nodes.func.random_value(
        min=max_offset_pct * -0.5,
        max=0.5 * max_offset_pct,
        id=index,
        seed=seed,
    )
    result_0_a_0 = dimension / vertices.astype(dtype=float)
    result_0_b_1 = pf.nodes.func.not_equal(
        a=index.astype(dtype=float), b=0.0, epsilon=0.001
    )
    result_0_b_0 = pf.nodes.func.not_equal(
        a=index.astype(dtype=float),
        b=vertices.astype(dtype=float) - 1.0,
        epsilon=0.001,
    )

    multiply = (
        (result_0_a_1 * result_0_a_0)
        * result_0_b_1.astype(dtype=float)
        * result_0_b_0.astype(dtype=float)
    )
    return multiply
