repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.14.5 # pinned to same version as pyproject.toml
  hooks:
    # Run the linter.
    - id: ruff-check
      types_or: [ python, pyi ]
      args: [ --fix ]
    - id: ruff-check
      types_or: [ python, pyi ]
      args: [ --select=I001, "--fix"]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi ]
