# Copyright (C) 2026, Princeton University.
# This source code is licensed under the BSD 3-Clause license found in the LICENSE file in the root directory of this source tree.

# Transpiled into procfunc/v2 format by Alexander Raistrick

import functools
from typing import NamedTuple

import procfunc as pf
from procfunc.nodes import types as t

from infinigen2.shaders.util.coord import coord_warp

__all__ = [
    "carpet_noisy_preset",
    "carpet_noisy_rand",
    "carpet_rand",
    "carpet_streaks_faint_preset",
    "carpet_streaks_faint_rand",
    "carpet_streaks_right_angle_preset",
    "carpet_streaks_right_angle_rand",
    "carpet_streaks_short_preset",
    "carpet_streaks_short_rand",
]

# --- Node functions (verbatim from transpiler) ---


@pf.nodes.node_function
def _linear_to_round(
    value: t.SocketOrVal[float],
) -> pf.ProcNode[float]:
    # Code generated by procfunc v0.20.0
    value_value = pf.nodes.math.absolute(value - 0.5)

    value = pf.nodes.math.acos(value_value * 2.0)
    sin = pf.nodes.math.sin(value)

    return sin


class _CarpetWeaverResult(NamedTuple):
    color: pf.ProcNode[pf.Color]
    thread_id: pf.ProcNode[float]
    cell_id: pf.ProcNode[pf.Vector]
    thread_mask: pf.ProcNode[float]
    thread_uv: pf.ProcNode[pf.Vector]
    alpha: pf.ProcNode[float]
    height: pf.ProcNode[float]


@pf.nodes.node_function
def _carpet_weaver(
    vector: t.SocketOrVal[pf.Vector],
    randomize_uv: t.SocketOrVal[float],
    random_seed: t.SocketOrVal[float],
    warp_warp_color: t.SocketOrVal[pf.Color],
    warp_warp_thickness: t.SocketOrVal[float],
    warp_warp_gab: t.SocketOrVal[float],
    warp_warp_height: t.SocketOrVal[float],
    warp_warp_height_variation: t.SocketOrVal[float],
    weft_weft_color: t.SocketOrVal[pf.Color],
    weft_weft_thickness: t.SocketOrVal[float],
    weft_weft_gab: t.SocketOrVal[float],
    weft_weft_height: t.SocketOrVal[float],
    weft_weft_height_variation: t.SocketOrVal[float],
) -> _CarpetWeaverResult:
    # Code generated by procfunc v0.20.0
    thread_id_b_increment = warp_warp_thickness + warp_warp_gab

    warp_uv_x = pf.nodes.math.floor_mod(a=vector.x, b=thread_id_b_increment)

    linear_to_round_value = pf.nodes.math.map_range(
        value=warp_uv_x, from_max=warp_warp_thickness
    )
    linear_to_round_result = _linear_to_round(value=linear_to_round_value)
    warp_value_b_a = pf.nodes.math.floor_mod(a=vector.x, b=thread_id_b_increment * 2.0)

    warp_value_b = warp_value_b_a > thread_id_b_increment
    thread_id_a_increment = weft_weft_thickness + weft_weft_gab

    warp_value = vector.y + (warp_value_b * thread_id_a_increment)

    warp_increment = thread_id_a_increment * 2.0
    linear_value_value_1 = pf.nodes.math.floor_mod(a=warp_value, b=warp_increment)

    linear_value_from_max = weft_weft_gab * 2.0
    linear_value_2 = pf.nodes.math.map_range(
        value=linear_value_value_1,
        from_max=weft_weft_thickness + linear_value_from_max,
    )
    linear_to_round_result_1 = _linear_to_round(value=linear_value_2)
    thread_mask_a = (
        linear_to_round_result * linear_to_round_result_1
    ) * warp_warp_height

    weft_uv_x = pf.nodes.math.floor_mod(a=vector.y, b=thread_id_a_increment)

    linear_value_1 = pf.nodes.math.map_range(
        value=weft_uv_x,
        from_max=thread_id_a_increment,
        from_min=weft_weft_gab,
    )
    linear_to_round_result_2 = _linear_to_round(value=linear_value_1)
    weft_value_b_a = pf.nodes.math.floor_mod(a=vector.y, b=thread_id_a_increment * 2.0)

    weft_value_b = weft_value_b_a > thread_id_a_increment
    weft_value = vector.x + (weft_value_b * thread_id_b_increment)
    weft_increment = thread_id_b_increment * 2.0
    linear_value_value_0 = pf.nodes.math.floor_mod(a=weft_value, b=weft_increment)

    linear_value_0 = pf.nodes.math.map_range(
        value=linear_value_value_0,
        from_max=weft_increment,
        from_min=warp_warp_thickness,
    )
    linear_to_round_result_3 = _linear_to_round(value=linear_value_0)
    thread_mask_b = weft_weft_height * (
        linear_to_round_result_2 * linear_to_round_result_3
    )

    thread_mask = thread_mask_a > thread_mask_b
    color_0_vector = pf.nodes.color.mix_rgb(
        factor=thread_mask, a=weft_weft_color, b=warp_warp_color
    )

    alpha_a = pf.nodes.math.maximum(a=thread_mask_a, b=thread_mask_b)

    alpha = alpha_a > 0.0
    color_1 = pf.nodes.math.vector_scale(
        vector=color_0_vector.astype(dtype=pf.Vector),
        scale=alpha,
    )

    color = color_1.astype(dtype=pf.Color)
    thread_id_a = pf.nodes.math.snap(value=vector.y, increment=thread_id_a_increment)

    thread_id_b = pf.nodes.math.snap(value=vector.x, increment=thread_id_b_increment)
    thread_id = pf.nodes.math.mix(a=thread_id_a, b=thread_id_b, factor=thread_mask)
    cell_id_a_vector = pf.nodes.math.combine_xyz(
        x=warp_warp_thickness, y=weft_weft_thickness
    )

    cell_id_a = pf.nodes.math.vector_scale(vector=cell_id_a_vector, scale=0.5)
    weft_cell_id_x = pf.nodes.math.snap(value=weft_value, increment=weft_increment)

    weft_cell_id = pf.nodes.math.combine_xyz(x=weft_cell_id_x, y=thread_id_a)
    warp_cell_id_y = pf.nodes.math.snap(value=warp_value, increment=warp_increment)

    warp_cell_id = pf.nodes.math.combine_xyz(x=thread_id_b, y=warp_cell_id_y)
    cell_id = pf.nodes.math.mix(
        a=cell_id_a + weft_cell_id, b=warp_cell_id, factor=thread_mask
    )

    white_noise_vector = pf.nodes.math.combine_xyz(x=thread_id, y=random_seed)

    white_noise = pf.nodes.texture.white_noise(
        vector=white_noise_vector, noise_dimensions="2D"
    )
    thread_uv_a_a_0 = pf.nodes.math.combine_xyz(
        x=white_noise.color.astype(dtype=pf.Vector).y,
        y=white_noise.color.astype(dtype=pf.Vector).z,
    )
    thread_uv_a_1 = thread_uv_a_a_0 - (0.5, 0.5, 0.0)
    thread_uv_a_0 = randomize_uv.astype(dtype=pf.Vector) * (10.0, 100.0, 0.0)
    weft_uv = pf.nodes.math.combine_xyz(x=weft_uv_x, y=vector.x)
    warp_uv = pf.nodes.math.combine_xyz(x=warp_uv_x, y=vector.y)
    thread_uv_1 = pf.nodes.math.mix(a=weft_uv, b=warp_uv, factor=thread_mask)
    thread_uv = (thread_uv_a_1 * thread_uv_a_0) + thread_uv_1

    height_a_factor = pf.nodes.math.mix(
        a=weft_weft_height_variation,
        b=warp_warp_height_variation,
        factor=thread_mask,
    )
    height_a = pf.nodes.math.mix(
        a=1.0,
        b=white_noise.color.astype(dtype=pf.Vector).x,
        factor=height_a_factor,
    )
    height = height_a * alpha_a
    return _CarpetWeaverResult(
        color, thread_id, cell_id, thread_mask, thread_uv, alpha, height
    )


class _CarpetCellRandomizerResult(NamedTuple):
    color: pf.ProcNode[pf.Color]
    cell_id: t.SocketOrVal[pf.Vector]
    thread_mask: t.SocketOrVal[float]


@pf.nodes.node_function
def _carpet_cell_randomizer(
    color: t.SocketOrVal[pf.Color],
    cell_id: t.SocketOrVal[pf.Vector],
    thread_mask: t.SocketOrVal[float],
    alpha_warp: t.SocketOrVal[float],
    alpha_weft: t.SocketOrVal[float],
    coverage: t.SocketOrVal[float],
    color_settings_color_1: t.SocketOrVal[pf.Color],
    color_settings_color_2: t.SocketOrVal[pf.Color],
    color_settings_spread: t.SocketOrVal[float],
    color_settings_blending: t.SocketOrVal[float],
    noise_settings_type: t.SocketOrVal[float],
    noise_settings_seed: t.SocketOrVal[float],
    noise_settings_size: t.SocketOrVal[float],
    noise_settings_stretch: t.SocketOrVal[pf.Vector],
    noise_settings_invert: t.SocketOrVal[float],
    noise_settings_detail: t.SocketOrVal[float],
    noise_settings_roughness: t.SocketOrVal[float],
    noise_settings_lacunarity: t.SocketOrVal[float],
) -> _CarpetCellRandomizerResult:
    # Code generated by procfunc v0.20.0
    color_factor_b_0 = 1.0 - thread_mask

    color_factor_1 = (thread_mask * alpha_warp) + (color_factor_b_0 * alpha_weft)
    color_a_factor = pf.nodes.math.clamp(noise_settings_type - 2.0)
    color_a_a_factor = pf.nodes.math.clamp(noise_settings_type - 1.0)
    voronoi_vector = cell_id / noise_settings_stretch

    white_noise = pf.nodes.texture.white_noise(
        vector=voronoi_vector,
        noise_dimensions="4D",
        w=noise_settings_seed,
    )

    voronoi_scale = 1.0 / noise_settings_size

    noise = pf.nodes.texture.noise(
        vector=voronoi_vector,
        scale=voronoi_scale,
        detail=noise_settings_detail,
        roughness=noise_settings_roughness,
        lacunarity=noise_settings_lacunarity,
        noise_dimensions="4D",
        w=noise_settings_seed,
    )

    color_a_a_b = pf.nodes.math.map_range(value=noise.fac, from_max=0.8, from_min=0.2)

    color_a_a = pf.nodes.math.mix(
        a=white_noise.fac, b=color_a_a_b, factor=color_a_a_factor
    )
    voronoi = pf.nodes.texture.voronoi(
        vector=voronoi_vector,
        scale=voronoi_scale,
        detail=noise_settings_detail,
        roughness=noise_settings_roughness,
        lacunarity=noise_settings_lacunarity,
        normalize=True,
        voronoi_dimensions="4D",
        w=noise_settings_seed,
    )

    color_a_0 = pf.nodes.math.mix(
        a=color_a_a, b=voronoi.distance, factor=color_a_factor
    )

    color_factor_a_value = pf.nodes.math.mix(
        a=color_a_0, b=1.0 - color_a_0, factor=noise_settings_invert
    )
    color_factor_a_from_min = pf.nodes.math.clamp(1.0 - coverage)
    color_factor_a_0 = pf.nodes.math.map_range(
        value=color_factor_a_value,
        from_min=color_factor_a_from_min,
    )
    color_factor_0 = color_factor_a_0 > 0.0
    color_b_numerator = pf.nodes.math.maximum(a=color_settings_blending, b=0.0001)
    color_b_1 = color_b_numerator / 2.0
    color_b_factor = pf.nodes.math.map_range(
        value=color_factor_a_0,
        from_max=color_settings_spread + color_b_1,
        from_min=color_settings_spread - color_b_1,
    )
    color_b_0 = pf.nodes.color.mix_rgb(
        factor=color_b_factor,
        a=color_settings_color_1,
        b=color_settings_color_2,
    )
    color_1 = pf.nodes.color.mix_rgb(
        factor=color_factor_1 * color_factor_0, a=color, b=color_b_0
    )
    return _CarpetCellRandomizerResult(color_1, cell_id, thread_mask)


class _CarpetThreadRandomizerResult(NamedTuple):
    color: pf.ProcNode[pf.Color]
    thread_id: t.SocketOrVal[float]
    thread_mask: t.SocketOrVal[float]


@pf.nodes.node_function
def _carpet_thread_randomizer(
    color: t.SocketOrVal[pf.Color],
    thread_id: t.SocketOrVal[float],
    thread_mask: t.SocketOrVal[float],
    alpha_warp: t.SocketOrVal[float],
    alpha_weft: t.SocketOrVal[float],
    coverage: t.SocketOrVal[float],
    color_settings_color_1: t.SocketOrVal[pf.Color],
    color_settings_color_2: t.SocketOrVal[pf.Color],
    color_settings_spread: t.SocketOrVal[float],
    color_settings_blending: t.SocketOrVal[float],
    noise_settings_type: t.SocketOrVal[float],
    noise_settings_seed: t.SocketOrVal[float],
    noise_settings_size: t.SocketOrVal[float],
    noise_settings_detail: t.SocketOrVal[float],
    noise_settings_roughness: t.SocketOrVal[float],
    noise_settings_lacunarity: t.SocketOrVal[float],
) -> _CarpetThreadRandomizerResult:
    # Code generated by procfunc v0.20.0
    color_factor_b_0 = 1.0 - thread_mask

    color_factor_2 = (thread_mask * alpha_warp) + (color_factor_b_0 * alpha_weft)
    color_factor_1 = pf.nodes.math.clamp(noise_settings_type - 1.0)
    white_noise_vector = pf.nodes.math.combine_xyz(x=thread_id, y=noise_settings_seed)

    white_noise = pf.nodes.texture.white_noise(
        vector=white_noise_vector, noise_dimensions="2D"
    )
    noise = pf.nodes.texture.noise(
        vector=white_noise_vector,
        scale=1.0 / noise_settings_size,
        detail=noise_settings_detail,
        roughness=noise_settings_roughness,
        lacunarity=noise_settings_lacunarity,
        noise_dimensions="2D",
    )

    color_b_2 = pf.nodes.math.map_range(value=noise.fac, from_max=0.8, from_min=0.2)

    color_factor_a_value = pf.nodes.math.mix(
        a=white_noise.fac, b=color_b_2, factor=color_factor_1
    )
    color_factor_a_from_min = pf.nodes.math.clamp(1.0 - coverage)
    color_factor_a_0 = pf.nodes.math.map_range(
        value=color_factor_a_value,
        from_min=color_factor_a_from_min,
    )
    color_factor_0 = color_factor_a_0 > 0.0
    color_b_numerator = pf.nodes.math.maximum(a=color_settings_blending, b=0.0001)
    color_b_1 = color_b_numerator / 2.0
    color_b_factor = pf.nodes.math.map_range(
        value=color_factor_a_0,
        from_max=color_settings_spread + color_b_1,
        from_min=color_settings_spread - color_b_1,
    )
    color_b_0 = pf.nodes.color.mix_rgb(
        factor=color_b_factor,
        a=color_settings_color_1,
        b=color_settings_color_2,
    )
    color_1 = pf.nodes.color.mix_rgb(
        factor=color_factor_2 * color_factor_0, a=color, b=color_b_0
    )
    return _CarpetThreadRandomizerResult(color_1, thread_id, thread_mask)


# --- Auto-generated distribution functions (from transpiler infer_nodegroup_distributions) ---


def _carpet_weaver_rand(
    rng: pf.RNG,
    vector: t.SocketOrVal[pf.Vector],
    warp_warp_color: t.SocketOrVal[pf.Color],
    weft_weft_color: t.SocketOrVal[pf.Color],
):
    # Code generated by procfunc v0.20.0
    randomize_uv = pf.random.uniform(rng, 0.0, 1.0)
    random_seed = 0.0
    warp_warp_thickness = 0.005
    warp_warp_gab = 0.0
    warp_warp_height = pf.random.uniform(rng, 0.003, 0.005)
    warp_warp_height_variation = pf.random.uniform(rng, 0.0, 1.0)
    weft_weft_thickness = pf.random.uniform(rng, 0.002, 0.005)
    weft_weft_gab = pf.random.uniform(rng, 0.0, 0.004)
    weft_weft_height = 0.003
    weft_weft_height_variation = pf.random.uniform(rng, 0.0, 1.0)
    carpet_weaver_result = _carpet_weaver(
        vector=vector,
        randomize_uv=randomize_uv,
        random_seed=random_seed,
        warp_warp_color=warp_warp_color,
        warp_warp_thickness=warp_warp_thickness,
        warp_warp_gab=warp_warp_gab,
        warp_warp_height=warp_warp_height,
        warp_warp_height_variation=warp_warp_height_variation,
        weft_weft_color=weft_weft_color,
        weft_weft_thickness=weft_weft_thickness,
        weft_weft_gab=weft_weft_gab,
        weft_weft_height=weft_weft_height,
        weft_weft_height_variation=weft_weft_height_variation,
    )
    return carpet_weaver_result


def carpet_noisy_rand(
    rng: pf.RNG,
    vector: t.SocketOrVal[pf.Vector],
    warp_warp_color: t.SocketOrVal[pf.Color],
    weft_weft_color: t.SocketOrVal[pf.Color],
    color_1: t.SocketOrVal[pf.Color],
    color_2: t.SocketOrVal[pf.Color],
):
    rng, rng_weaver, rng_noise_type = rng.spawn(3)
    weaver_result = _carpet_weaver_rand(
        rng_weaver,
        vector=vector,
        warp_warp_color=warp_warp_color,
        weft_weft_color=weft_weft_color,
    )
    result = _carpet_cell_randomizer(
        color=weaver_result.color,
        cell_id=weaver_result.cell_id,
        thread_mask=weaver_result.thread_mask,
        alpha_warp=pf.random.uniform(rng, 0.85, 1.0),
        alpha_weft=pf.random.uniform(rng, 0.85, 1.0),
        coverage=pf.random.uniform(rng, 0.45, 0.55),
        color_settings_color_1=color_1,
        color_settings_color_2=color_2,
        color_settings_spread=pf.random.uniform(rng, 0.3, 0.5),
        color_settings_blending=pf.random.uniform(rng, 0.05, 0.2),
        noise_settings_type=pf.control.choice(
            rng_noise_type, [(1.0, 1), (2.0, 1), (3.0, 1)]
        ),
        noise_settings_seed=pf.random.uniform(rng, 0.0, 5.3),
        noise_settings_size=pf.random.uniform(rng, 0.001, 0.00625),
        noise_settings_stretch=(1.0, 1.0, 1.0),
        noise_settings_invert=pf.random.uniform(rng, 0.0, 1.0),
        noise_settings_detail=pf.random.uniform(rng, 1.5, 2.0),
        noise_settings_roughness=0.5,
        noise_settings_lacunarity=2.0,
    )
    return result.color, weaver_result.alpha, weaver_result.height


def carpet_streaks_faint_rand(
    rng: pf.RNG,
    vector: t.SocketOrVal[pf.Vector],
    warp_warp_color: t.SocketOrVal[pf.Color],
    weft_weft_color: t.SocketOrVal[pf.Color],
    color_1: t.SocketOrVal[pf.Color],
    color_2: t.SocketOrVal[pf.Color],
):
    weaver_result = _carpet_weaver_rand(
        rng,
        vector=vector,
        warp_warp_color=warp_warp_color,
        weft_weft_color=weft_weft_color,
    )
    result = _carpet_thread_randomizer_rand(
        rng,
        color=weaver_result.color,
        thread_id=weaver_result.thread_id,
        thread_mask=weaver_result.thread_mask,
        color_settings_color_1=color_1,
        color_settings_color_2=color_2,
    )
    return result.color, weaver_result.alpha, weaver_result.height


def carpet_streaks_right_angle_rand(
    rng: pf.RNG,
    vector: t.SocketOrVal[pf.Vector],
    warp_warp_color: t.SocketOrVal[pf.Color],
    weft_weft_color: t.SocketOrVal[pf.Color],
    color_1: t.SocketOrVal[pf.Color],
    color_2: t.SocketOrVal[pf.Color],
):
    weaver_result = _carpet_weaver_rand(
        rng,
        vector=vector,
        warp_warp_color=warp_warp_color,
        weft_weft_color=weft_weft_color,
    )
    color = _carpet_right_angle_pattern(
        rng, weaver_result, weaver_result.cell_id, color_1, color_2
    )
    color = _thread_uv_noise_overlay_rand(
        rng, color=color, thread_uv=weaver_result.thread_uv
    )
    return color, weaver_result.alpha, weaver_result.height


def carpet_streaks_short_rand(
    rng: pf.RNG,
    vector: t.SocketOrVal[pf.Vector],
    warp_warp_color: t.SocketOrVal[pf.Color],
    weft_weft_color: t.SocketOrVal[pf.Color],
    color_1: t.SocketOrVal[pf.Color],
    color_2: t.SocketOrVal[pf.Color],
):
    rng, rng_weaver, rng_noise_type = rng.spawn(3)
    weaver_result = _carpet_weaver_rand(
        rng_weaver,
        vector=vector,
        warp_warp_color=warp_warp_color,
        weft_weft_color=weft_weft_color,
    )
    cell_id_y_squish = pf.random.uniform(rng, 10.0, 30.0)
    cell_id = weaver_result.cell_id / (1.0, cell_id_y_squish, 1.0)
    result = _carpet_cell_randomizer(
        color=weaver_result.color,
        cell_id=cell_id,
        thread_mask=weaver_result.thread_mask,
        alpha_warp=pf.random.uniform(rng, 0.3, 0.6),
        alpha_weft=pf.random.uniform(rng, 0.0, 0.2),
        coverage=pf.random.uniform(rng, 0.29, 0.40),
        color_settings_color_1=color_1,
        color_settings_color_2=color_2,
        color_settings_spread=pf.random.uniform(rng, 0.14, 0.3),
        color_settings_blending=pf.random.uniform(rng, 0.0001, 0.1),
        noise_settings_type=pf.control.choice(rng_noise_type, [(1.0, 1), (3.0, 2)]),
        noise_settings_seed=pf.random.uniform(rng, 0.0, 5.3),
        noise_settings_size=pf.random.uniform(rng, 0.01, 0.03),
        noise_settings_stretch=(1.0, 1.0, 1.0),
        noise_settings_invert=pf.random.uniform(rng, 0.0, 1.0),
        noise_settings_detail=pf.random.uniform(rng, 0.0, 1.5),
        noise_settings_roughness=0.5,
        noise_settings_lacunarity=2.0,
    )
    return result.color, weaver_result.alpha, weaver_result.height


def _carpet_thread_randomizer_rand(
    rng: pf.RNG,
    color: t.SocketOrVal[pf.Color],
    thread_id: t.SocketOrVal[float],
    thread_mask: t.SocketOrVal[float],
    color_settings_color_1: t.SocketOrVal[pf.Color],
    color_settings_color_2: t.SocketOrVal[pf.Color],
):
    # Manually written (only 1 preset sample, so transpiler couldn't infer ranges)
    alpha_warp = pf.random.uniform(rng, 0.1, 0.5)
    alpha_weft = pf.random.uniform(rng, 0.1, 0.5)
    coverage = pf.random.uniform(rng, 0.2, 0.5)
    color_settings_spread = pf.random.uniform(rng, 0.3, 0.7)
    color_settings_blending = pf.random.uniform(rng, 0.01, 0.1)
    noise_settings_type = 1.0
    noise_settings_seed = pf.random.uniform(rng, 0.0, 10.0)
    noise_settings_size = pf.random.uniform(rng, 0.02, 0.1)
    noise_settings_detail = pf.random.uniform(rng, 1.0, 4.0)
    noise_settings_roughness = 0.5
    noise_settings_lacunarity = 2.0
    carpet_thread_randomizer_result = _carpet_thread_randomizer(
        color=color,
        thread_id=thread_id,
        thread_mask=thread_mask,
        alpha_warp=alpha_warp,
        alpha_weft=alpha_weft,
        coverage=coverage,
        color_settings_color_1=color_settings_color_1,
        color_settings_color_2=color_settings_color_2,
        color_settings_spread=color_settings_spread,
        color_settings_blending=color_settings_blending,
        noise_settings_type=noise_settings_type,
        noise_settings_seed=noise_settings_seed,
        noise_settings_size=noise_settings_size,
        noise_settings_detail=noise_settings_detail,
        noise_settings_roughness=noise_settings_roughness,
        noise_settings_lacunarity=noise_settings_lacunarity,
    )
    return carpet_thread_randomizer_result


# --- Preset functions (verbatim from transpiler, with vector param + coord_warp remapping) ---


def carpet_noisy_preset(vector: pf.ProcNode[pf.Vector]):
    # Code generated by procfunc v0.20.0
    coord_warp_result = coord_warp(
        vector=vector, size=0.005, strength=1.0, detail=4.0, phase=0.0
    )
    carpet_weaver_warp_warp_color = pf.color.hsv_color((0.0, 0.0, 0.38))

    carpet_weaver_weft_weft_color = pf.color.hsv_color((0.0, 0.0, 0.056))
    carpet_weaver_result = _carpet_weaver(
        vector=coord_warp_result.vector,
        randomize_uv=0.0,
        random_seed=0.0,
        warp_warp_color=carpet_weaver_warp_warp_color,
        warp_warp_thickness=0.005,
        warp_warp_gab=0.0,
        warp_warp_height=0.005,
        warp_warp_height_variation=1.0,
        weft_weft_color=carpet_weaver_weft_weft_color,
        weft_weft_thickness=0.002,
        weft_weft_gab=0.002,
        weft_weft_height=0.003,
        weft_weft_height_variation=1.0,
    )
    carpet_cell_randomizer_color_settings_color_1 = pf.color.hsv_color(
        (0.0633, 0.7529, 0.437)
    )
    carpet_cell_randomizer_color_settings_color_0 = pf.color.hsv_color(
        (0.0275, 0.8835, 0.103)
    )
    carpet_cell_randomizer_result = _carpet_cell_randomizer(
        color=carpet_weaver_result.color,
        cell_id=carpet_weaver_result.cell_id,
        thread_mask=carpet_weaver_result.thread_mask,
        alpha_warp=1.0,
        alpha_weft=1.0,
        coverage=0.549975,
        color_settings_color_1=carpet_cell_randomizer_color_settings_color_1,
        color_settings_color_2=carpet_cell_randomizer_color_settings_color_0,
        color_settings_spread=0.5,
        color_settings_blending=0.068876,
        noise_settings_type=1.0,
        noise_settings_seed=0.0,
        noise_settings_size=0.05,
        noise_settings_stretch=(1.0, 1.0, 1.0),
        noise_settings_invert=0.0,
        noise_settings_detail=2.0,
        noise_settings_roughness=0.5,
        noise_settings_lacunarity=2.0,
    )
    principled = pf.nodes.shader.principled_bsdf(
        base_color=carpet_cell_randomizer_result.color,
        roughness=0.868182,
        subsurface_anisotropy=0.0,
        sheen_weight=0.168182,
        sheen_roughness=0.640909,
    )

    displacement = pf.nodes.shader.displacement(
        height=carpet_weaver_result.height,
        midlevel=0.0,
        normal=(0.0, 0.0, 0.0),
    )

    return pf.Material(surface=principled, displacement=displacement)


def carpet_streaks_faint_preset(vector: pf.ProcNode[pf.Vector]):
    # Code generated by procfunc v0.20.0
    coord_warp_result = coord_warp(
        vector=vector, size=0.005, strength=1.0, detail=4.0, phase=0.0
    )
    carpet_weaver_warp_warp_color = pf.color.hsv_color((0.0, 0.0, 0.095))

    carpet_weaver_weft_weft_color = pf.color.hsv_color((0.0, 0.0, 0.056))
    carpet_weaver_result = _carpet_weaver(
        vector=coord_warp_result.vector,
        randomize_uv=0.0,
        random_seed=0.0,
        warp_warp_color=carpet_weaver_warp_warp_color,
        warp_warp_thickness=0.005,
        warp_warp_gab=0.0,
        warp_warp_height=0.003,
        warp_warp_height_variation=0.0,
        weft_weft_color=carpet_weaver_weft_weft_color,
        weft_weft_thickness=0.005,
        weft_weft_gab=0.0,
        weft_weft_height=0.003,
        weft_weft_height_variation=0.0,
    )
    carpet_thread_randomizer_color_settings_color_1 = pf.color.hsv_color(
        (0.0633, 0.7529, 0.437)
    )
    carpet_thread_randomizer_color_settings_color_0 = pf.color.hsv_color(
        (0.0627, 0.5879, 0.199)
    )
    carpet_thread_randomizer_result = _carpet_thread_randomizer(
        color=carpet_weaver_result.color,
        thread_id=carpet_weaver_result.thread_id,
        thread_mask=carpet_weaver_result.thread_mask,
        alpha_warp=0.205479,
        alpha_weft=0.205479,
        coverage=0.294267,
        color_settings_color_1=carpet_thread_randomizer_color_settings_color_1,
        color_settings_color_2=carpet_thread_randomizer_color_settings_color_0,
        color_settings_spread=0.684932,
        color_settings_blending=0.014087,
        noise_settings_type=1.0,
        noise_settings_seed=5.3,
        noise_settings_size=0.05,
        noise_settings_detail=2.0,
        noise_settings_roughness=0.5,
        noise_settings_lacunarity=2.0,
    )
    principled = pf.nodes.shader.principled_bsdf(
        base_color=carpet_thread_randomizer_result.color,
        roughness=0.868182,
        alpha=carpet_weaver_result.alpha,
        subsurface_anisotropy=0.0,
        sheen_weight=0.168182,
        sheen_roughness=0.640909,
    )

    displacement = pf.nodes.shader.displacement(
        height=carpet_weaver_result.height,
        midlevel=0.0,
        normal=(0.0, 0.0, 0.0),
    )

    return pf.Material(surface=principled, displacement=displacement)


def carpet_streaks_right_angle_preset(vector: pf.ProcNode[pf.Vector]):
    # Code generated by procfunc v0.20.0
    coord_warp_result = coord_warp(
        vector=vector, size=0.0014, strength=3.0, detail=2.0, phase=0.0
    )
    coord_warp_result_1 = coord_warp(
        vector=coord_warp_result.vector,
        size=0.005,
        strength=3.0,
        detail=4.0,
        phase=0.0,
    )
    coord_warp_result_2 = coord_warp(
        vector=coord_warp_result_1.vector,
        size=0.04,
        strength=0.3,
        detail=2.0,
        phase=0.0,
    )
    carpet_weaver_warp_warp_color = pf.color.hsv_color((0.0857, 0.3684, 0.095))

    carpet_weaver_weft_weft_color = pf.color.hsv_color((0.0, 0.0, 0.026))
    carpet_weaver_result = _carpet_weaver(
        vector=coord_warp_result_2.vector,
        randomize_uv=1.0,
        random_seed=0.0,
        warp_warp_color=carpet_weaver_warp_warp_color,
        warp_warp_thickness=0.005,
        warp_warp_gab=0.0,
        warp_warp_height=0.003,
        warp_warp_height_variation=0.0,
        weft_weft_color=carpet_weaver_weft_weft_color,
        weft_weft_thickness=0.005,
        weft_weft_gab=0.0,
        weft_weft_height=0.003,
        weft_weft_height_variation=0.0,
    )
    carpet_cell_randomizer_color_settings_color_1 = pf.color.hsv_color(
        (0.0984, 0.4584, 0.842)
    )
    carpet_cell_randomizer_color_settings_color_0 = pf.color.hsv_color(
        (0.0435, 0.46, 0.05)
    )
    carpet_cell_randomizer_result = _carpet_cell_randomizer(
        color=carpet_weaver_result.color,
        cell_id=carpet_weaver_result.cell_id,
        thread_mask=carpet_weaver_result.thread_mask,
        alpha_warp=0.75,
        alpha_weft=0.0,
        coverage=0.338571,
        color_settings_color_1=carpet_cell_randomizer_color_settings_color_1,
        color_settings_color_2=carpet_cell_randomizer_color_settings_color_0,
        color_settings_spread=0.172571,
        color_settings_blending=0.468545,
        noise_settings_type=3.0,
        noise_settings_seed=1.1,
        noise_settings_size=0.01,
        noise_settings_stretch=(1.0, 100.0, 1.0),
        noise_settings_invert=1.0,
        noise_settings_detail=1.0,
        noise_settings_roughness=0.5,
        noise_settings_lacunarity=2.0,
    )
    carpet_color_settings_color_1 = pf.color.hsv_color((0.0984, 0.4584, 0.842))
    carpet_color_settings_color_0 = pf.color.hsv_color((0.0435, 0.46, 0.05))
    carpet_cell_randomizer_result_1 = _carpet_cell_randomizer(
        color=carpet_cell_randomizer_result.color,
        cell_id=carpet_cell_randomizer_result.cell_id,
        thread_mask=carpet_cell_randomizer_result.thread_mask,
        alpha_warp=0.0,
        alpha_weft=0.75,
        coverage=0.338571,
        color_settings_color_1=carpet_color_settings_color_1,
        color_settings_color_2=carpet_color_settings_color_0,
        color_settings_spread=0.172571,
        color_settings_blending=0.468545,
        noise_settings_type=3.0,
        noise_settings_seed=1.1,
        noise_settings_size=0.01,
        noise_settings_stretch=(100.0, 1.0, 1.0),
        noise_settings_invert=1.0,
        noise_settings_detail=1.0,
        noise_settings_roughness=0.5,
        noise_settings_lacunarity=2.0,
    )
    noise = pf.nodes.texture.noise(
        vector=carpet_weaver_result.thread_uv, scale=406.599976
    )
    surface_base_color_b = pf.nodes.math.map_range(
        value=noise.fac, from_max=0.7, from_min=0.3
    )
    surface_base_color = pf.nodes.color.mix_rgb(
        factor=0.841667,
        a=carpet_cell_randomizer_result_1.color,
        b=surface_base_color_b.astype(dtype=pf.Color),
        blend_type="SOFT_LIGHT",
    )
    principled = pf.nodes.shader.principled_bsdf(
        base_color=surface_base_color,
        roughness=0.868182,
        alpha=carpet_weaver_result.alpha,
        subsurface_anisotropy=0.0,
        sheen_weight=0.168182,
        sheen_roughness=0.640909,
    )

    displacement = pf.nodes.shader.displacement(
        height=carpet_weaver_result.height,
        midlevel=0.0,
        normal=(0.0, 0.0, 0.0),
    )

    return pf.Material(surface=principled, displacement=displacement)


def carpet_streaks_short_preset(vector: pf.ProcNode[pf.Vector]):
    # Code generated by procfunc v0.20.0
    coord_warp_result = coord_warp(
        vector=vector, size=0.005, strength=1.0, detail=4.0, phase=0.0
    )
    coord_warp_result_1 = coord_warp(
        vector=coord_warp_result.vector,
        size=0.04,
        strength=0.3,
        detail=2.0,
        phase=0.0,
    )
    carpet_weaver_warp_warp_color = pf.color.hsv_color((0.0, 0.0, 0.095))

    carpet_weaver_weft_weft_color = pf.color.hsv_color((0.0, 0.0, 0.056))
    carpet_weaver_result = _carpet_weaver(
        vector=coord_warp_result_1.vector,
        randomize_uv=0.0,
        random_seed=0.0,
        warp_warp_color=carpet_weaver_warp_warp_color,
        warp_warp_thickness=0.005,
        warp_warp_gab=0.0,
        warp_warp_height=0.003,
        warp_warp_height_variation=0.0,
        weft_weft_color=carpet_weaver_weft_weft_color,
        weft_weft_thickness=0.002,
        weft_weft_gab=0.004,
        weft_weft_height=0.003,
        weft_weft_height_variation=0.0,
    )
    carpet_cell_randomizer_color_settings_color_1 = pf.color.hsv_color(
        (0.0633, 0.7529, 0.437)
    )
    carpet_cell_randomizer_color_settings_color_0 = pf.color.hsv_color(
        (0.0627, 0.5879, 0.199)
    )
    carpet_cell_randomizer_result = _carpet_cell_randomizer(
        color=carpet_weaver_result.color,
        cell_id=carpet_weaver_result.cell_id / (1.0, 21.32, 1.0),
        thread_mask=carpet_weaver_result.thread_mask,
        alpha_warp=0.410959,
        alpha_weft=0.0,
        coverage=0.289041,
        color_settings_color_1=carpet_cell_randomizer_color_settings_color_1,
        color_settings_color_2=carpet_cell_randomizer_color_settings_color_0,
        color_settings_spread=0.141552,
        color_settings_blending=0.0001,
        noise_settings_type=3.0,
        noise_settings_seed=5.3,
        noise_settings_size=0.01,
        noise_settings_stretch=(1.0, 1.0, 1.0),
        noise_settings_invert=1.0,
        noise_settings_detail=0.0,
        noise_settings_roughness=0.5,
        noise_settings_lacunarity=2.0,
    )
    principled = pf.nodes.shader.principled_bsdf(
        base_color=carpet_cell_randomizer_result.color,
        roughness=0.868182,
        alpha=carpet_weaver_result.alpha,
        subsurface_anisotropy=0.0,
        sheen_weight=0.168182,
        sheen_roughness=0.640909,
    )

    displacement = pf.nodes.shader.displacement(
        height=carpet_weaver_result.height,
        midlevel=0.0,
        normal=(0.0, 0.0, 0.0),
    )

    return pf.Material(surface=principled, displacement=displacement)


# --- Presets and distribution ---


def _carpet_right_angle_pattern(
    rng: pf.RNG,
    weaver_result: _CarpetWeaverResult,
    cell_id: t.SocketOrVal[pf.Vector],
    color_1: t.SocketOrVal[pf.Color],
    color_2: t.SocketOrVal[pf.Color],
):
    """Two-pass orthogonal cell randomizer matching the right-angle preset."""
    shared_kw = dict(
        coverage=pf.random.uniform(rng, 0.28, 0.40),
        color_settings_spread=pf.random.uniform(rng, 0.13, 0.22),
        color_settings_blending=pf.random.uniform(rng, 0.3, 0.55),
        noise_settings_type=3.0,
        noise_settings_seed=pf.random.uniform(rng, 0.0, 5.0),
        noise_settings_size=pf.random.uniform(rng, 0.008, 0.015),
        noise_settings_invert=1.0,
        noise_settings_detail=pf.random.uniform(rng, 0.5, 2.0),
        noise_settings_roughness=0.5,
        noise_settings_lacunarity=2.0,
    )
    result = _carpet_cell_randomizer(
        color=weaver_result.color,
        cell_id=cell_id,
        thread_mask=weaver_result.thread_mask,
        alpha_warp=pf.random.uniform(rng, 0.5, 0.9),
        alpha_weft=0.0,
        noise_settings_stretch=(1.0, 100.0, 1.0),
        color_settings_color_1=color_1,
        color_settings_color_2=color_2,
        **shared_kw,
    )
    result2 = _carpet_cell_randomizer(
        color=result.color,
        cell_id=result.cell_id,
        thread_mask=result.thread_mask,
        alpha_warp=0.0,
        alpha_weft=pf.random.uniform(rng, 0.5, 0.9),
        noise_settings_stretch=(100.0, 1.0, 1.0),
        color_settings_color_1=color_1,
        color_settings_color_2=color_2,
        **shared_kw,
    )
    return result2.color


def _thread_uv_noise_overlay_rand(
    rng: pf.RNG,
    color: t.SocketOrVal[pf.Color],
    thread_uv: t.SocketOrVal[pf.Vector],
) -> pf.ProcNode[pf.Color]:
    strength = pf.random.uniform(rng, 0.5, 0.84)
    scale = pf.random.uniform(rng, 200.0, 600.0)
    noise = pf.nodes.texture.noise(vector=thread_uv, scale=scale)
    noise_mapped = pf.nodes.math.map_range(value=noise.fac, from_max=0.7, from_min=0.3)
    return pf.nodes.color.mix_rgb(
        factor=strength,
        a=color,
        b=noise_mapped.astype(dtype=pf.Color),
        blend_type="SOFT_LIGHT",
    )


def carpet_rand(
    rng: pf.RNG,
    vector: t.SocketOrVal[pf.Vector],
):
    rng, rng_style_choice, rb0, rb1, rb2, rb3 = rng.spawn(6)
    # Dedicated rngs per independent draw so codegen can't reorder them across consumers
    r_cw0, r_cw1, r_cw2, r_sat, r_hue, r_wsat, r_wval, r_weftval, r_pv1, r_pv2 = (
        rng.spawn(10)
    )
    r_rough, r_sheenw, r_sheenr = rng.spawn(3)
    # Shared coord_warps — all 3 scales run for every style with randomized strengths
    coord_warp_result = coord_warp(
        vector=vector,
        size=0.0014,
        strength=pf.random.uniform(r_cw0, 0.0, 3.0),
        detail=2.0,
        phase=0.0,
    )
    coord_warp_result = coord_warp(
        vector=coord_warp_result.vector,
        size=0.005,
        strength=pf.random.uniform(r_cw1, 0.0, 3.0),
        detail=4.0,
        phase=0.0,
    )
    coord_warp_result = coord_warp(
        vector=coord_warp_result.vector,
        size=0.04,
        strength=pf.random.uniform(r_cw2, 0.0, 0.3),
        detail=2.0,
        phase=0.0,
    )

    # Hue: gaussian centered on ~40° (orange-yellow), clipped to [0, 1]
    sat_base = pf.random.clip_gaussian(r_sat, 0.0, 0.25, 0.02, 0.95)
    hue = pf.random.clip_gaussian(r_hue, 40.0 / 360.0, 25.0 / 360.0, 0.0, 1.0)

    # Warp/weft: dark backing threads, low saturation
    warp_sat = pf.random.uniform(r_wsat, 0.0, 0.4)
    warp_val = pf.random.uniform(r_wval, 0.02, 0.15)
    warp_warp_color = pf.color.hsv_color(hue=hue, saturation=warp_sat, value=warp_val)
    weft_val = pf.random.uniform(r_weftval, 0.02, 0.08)
    weft_weft_color = pf.color.hsv_color(hue=hue, saturation=warp_sat, value=weft_val)

    # Pattern colors: color_1 is notably brighter than color_2 so noise pops visually
    pattern_sat = 0.4 + 0.5 * sat_base
    pattern_val_1 = (1 - 0.6 * sat_base) * pf.random.uniform(r_pv1, 0.35, 0.85)
    pattern_val_2 = pf.random.uniform(r_pv2, 0.02, 0.12)
    color_1 = pf.color.hsv_color(hue=hue, saturation=pattern_sat, value=pattern_val_1)
    color_2 = pf.color.hsv_color(hue=hue, saturation=pattern_sat, value=pattern_val_2)

    style_fn = pf.control.choice(
        rng_style_choice,
        [
            (functools.partial(carpet_noisy_rand, rb0), 1.0),
            (functools.partial(carpet_streaks_faint_rand, rb1), 1.0),
            (functools.partial(carpet_streaks_right_angle_rand, rb2), 1.0),
            (functools.partial(carpet_streaks_short_rand, rb3), 1.0),
        ],
    )
    style_result = style_fn(
        coord_warp_result.vector,
        warp_warp_color,
        weft_weft_color,
        color_1,
        color_2,
    )
    final_color = style_result[0]
    alpha = style_result[1]
    height = style_result[2]

    roughness = pf.random.clip_gaussian(r_rough, 0.868182, 0.1, 0.0, 1.0)
    sheen_weight = pf.random.clip_gaussian(r_sheenw, 0.168182, 0.1, 0.0, 1.0)
    sheen_roughness = pf.random.clip_gaussian(r_sheenr, 0.640909, 0.1, 0.0, 1.0)
    principled = pf.nodes.shader.principled_bsdf(
        base_color=final_color,
        roughness=roughness,
        alpha=alpha,
        subsurface_anisotropy=0.0,
        sheen_weight=sheen_weight,
        sheen_roughness=sheen_roughness,
    )

    displacement = pf.nodes.shader.displacement(
        height=height,
        midlevel=0.0,
        normal=(0.0, 0.0, 0.0),
    )

    return pf.Material(surface=principled, displacement=displacement)
