# Copyright (C) 2026, Princeton University.
# This source code is licensed under the BSD 3-Clause license found in the LICENSE file in the root directory of this source tree.

# Authors:
# - Lingjie Mei: original Infinigen v1 nodegroup (https://github.com/princeton-vl/infinigen/blob/05a09759fe9478595a3323ec2d6e26ce3513223f/infinigen/assets/materials/ceramic/ceramic.py)
# - Alexander Raistrick: transpile to procfunc/v2

import procfunc as pf
from procfunc.nodes import types as t

__all__ = [
    "ceramic",
    "ceramic_color_rand",
    "ceramic_rand",
]


@pf.nodes.node_function
def ceramic(
    vector: t.SocketOrVal[pf.Vector],
    base_color: t.SocketOrVal[pf.Color],
    roughness: t.SocketOrVal[float] = 0.3,
    displacement_height: t.SocketOrVal[float] = 0.002,
    displacement_scale: t.SocketOrVal[float] = 3.0,
) -> pf.Material:
    surface = pf.nodes.shader.principled_bsdf(
        base_color=base_color,
        roughness=roughness,
        subsurface_scale=1.0,
        subsurface_anisotropy=0.0,
        specular_ior_level=1.0,
        coat_weight=1.0,
        coat_roughness=roughness,
    )

    displacement_noise = pf.nodes.texture.noise(
        vector=vector,
        scale=displacement_scale,
    )
    displacement = pf.nodes.shader.displacement(
        height=displacement_height * displacement_noise.fac,
        midlevel=0.0,
        normal=(0.0, 0.0, 0.0),
    )
    return pf.Material(
        surface=surface,
        displacement=displacement,
    )


def ceramic_color_rand(rng: pf.RNG) -> pf.Color:
    hue = pf.random.uniform(rng, 0.0, 1.0)  # all hues
    val_pct = pf.random.clip_gaussian(rng, 0.6, 0.3, 0.1, 0.95)
    val = val_pct * 0.8
    sat = pf.random.uniform(rng, 0, 0.7) * (1 - val_pct)
    return pf.color.hsv_color(hue=hue, saturation=sat, value=val)


def ceramic_rand(
    rng: pf.RNG,
    vector: pf.ProcNode[pf.Vector],
    base_color: t.SocketOrVal[pf.Color] | None = None,
    displacement_height: t.SocketOrVal[float] | None = None,
    roughness: t.SocketOrVal[float] | None = None,
) -> pf.Material:
    if base_color is None:
        base_color = ceramic_color_rand(rng)
    if roughness is None:
        roughness = pf.random.clip_gaussian(rng, 0.25, 0.15, 0.05, 0.8)
    if displacement_height is None:
        displacement_height = pf.random.clip_gaussian(rng, 0.005, 0.004, 0.0, 0.01)
    displacement_scale = pf.random.uniform(rng, 3, 8)

    return ceramic(
        vector,
        base_color,
        roughness=roughness,
        displacement_height=displacement_height,
        displacement_scale=displacement_scale,
    )


def _shader_vase_ceramic():
    # Code generated by procfunc v0.3.0

    base_color_value = pf.color.hsv_to_rgba((0.0, 0.0, 0.067))

    surface_base_color = pf.nodes.math.constant(base_color_value)
    surface = pf.nodes.shader.principled_bsdf(
        base_color=surface_base_color,
        roughness=0.05,
        ior=1.47,
        subsurface_weight=0.3,
        subsurface_radius=(0.002, 0.002, 0.002),
        subsurface_scale=1.0,
        subsurface_anisotropy=0.2,
        specular_ior_level=0.2,
        coat_weight=0.5,
        coat_roughness=0.05,
    )
    return pf.Material(
        surface=surface,
        displacement=pf.nodes.math.constant((0.0, 0.0, 0.0)),
    )
