# Copyright (C) 2026, Princeton University.
# This source code is licensed under the BSD 3-Clause license found in the LICENSE file in the root directory of this source tree.

# Authors:
# - Erich Liang: original nodegroup
# - Alexander Raistrick: transpile to procfunc/v2

import logging
from typing import NamedTuple

import numpy as np
import procfunc as pf
from procfunc.nodes import types as t

__all__ = [
    "FabricResult",
    "fabric",
    "fabric_coarse_preset",
    "fabric_color_rand",
    "fabric_fine_preset",
    "fabric_rand",
    "fabric_translucent_rand",
]

logger = logging.getLogger(__name__)


class FabricResult(NamedTuple):
    surface: pf.ProcNode[pf.Shader]
    displacement: pf.ProcNode[pf.Vector]
    color: pf.ProcNode[pf.Color]
    thread_mask: pf.ProcNode[float]
    alpha: pf.ProcNode[float]


@pf.nodes.node_function
def fabric(
    vector: t.SocketOrVal[pf.Vector] = (0.0, 0.0, 0.0),
    size: t.SocketOrVal[float] = 1.0,
    size_variation: t.SocketOrVal[float] = 0.6,
    height_scale: t.SocketOrVal[float] = 1.0,
    height_variation: t.SocketOrVal[float] = 0.2,
    color: t.SocketOrVal[pf.Color] = pf.Color((0.5, 0.337, 0.252)),
    color_variation: t.SocketOrVal[float] = 0.2667,
    metallic: t.SocketOrVal[float] = 0.0,
    specular: t.SocketOrVal[float] = 0.25,
    roughness: t.SocketOrVal[float] = 0.3773,
    sheen_weight: t.SocketOrVal[float] = 0.5409,
    sheen_roughness: t.SocketOrVal[float] = 0.1409,
    gab: t.SocketOrVal[float] = 0.0,
) -> FabricResult:
    # Code generated by procfunc v0.3.0

    color_vector_2 = pf.nodes.math.vector_scale(vector=vector, scale=500.0 / size)
    color_x_1 = color_vector_2
    color_x_vector = pf.nodes.math.combine_xyz(color_x_1.x)
    color_x_scale = pf.nodes.math.constant(0.5)
    color_x = pf.nodes.texture.noise(
        vector=color_x_vector,
        scale=color_x_scale,
        detail=0.0,
        noise_dimensions="2D",
    )
    color_y_vector = pf.nodes.math.combine_xyz(x=color_x_1.y, y=100.0)
    color_y = pf.nodes.texture.noise(
        vector=color_y_vector,
        scale=color_x_scale,
        detail=0.0,
        noise_dimensions="2D",
    )
    color_vector_vector = pf.nodes.math.combine_xyz(x=color_x.fac, y=color_y.fac)
    color_vector_1 = pf.nodes.math.vector_scale(
        vector=color_vector_vector - (0.5, 0.5, 0.0),
        scale=size_variation,
    )
    color_vector = color_vector_2 + color_vector_1

    mask_vector_6 = pf.nodes.math.vector_fraction(color_vector + (0.0, 0.5, 0.0))
    mask_value_vector = pf.nodes.math.vector_absolute(mask_vector_6 - (0.5, 0.5, 0.0))

    thread_mask_value = pf.nodes.math.vector_scale(vector=mask_value_vector, scale=2.0)

    mask_vector_color = pf.nodes.math.map_range(
        value=(1.0, 1.0, 0.0) - thread_mask_value,
        from_min=gab.astype(dtype=pf.Vector),
        from_max=(1.0, 1.0, 1.0),
        to_min=(0.0, 0.0, 0.0),
        to_max=(1.0, 1.0, 1.0),
    )
    mask_vector_5 = pf.nodes.color.rgb_curve(
        color=mask_vector_color.astype(dtype=pf.Color),
        curves=[
            np.array([[0.0, 0.0], [1.0, 1.0]]),
            np.array([[0.0, 0.0], [1.0, 1.0]]),
            np.array([[0.0, 0.0], [1.0, 1.0]]),
            np.array([[0.0, 0.0], [0.1409, 0.375], [0.6091, 0.9], [1.0, 1.0]]),
        ],
        fac=1.0,
    )

    vector_vector_3 = pf.nodes.math.vector_scale(
        vector=color_vector + (0.0, 0.5, 0.0), scale=0.5
    )

    mask_vector_4 = pf.nodes.math.vector_fraction(vector_vector_3)

    vector_x_1 = mask_vector_4

    mask_vector_3 = pf.nodes.math.combine_xyz(
        x=vector_x_1.x > 0.5, y=vector_x_1.y > 0.5
    )

    vector_vector_2 = pf.nodes.math.vector_scale(vector=mask_vector_3, scale=0.5)

    mask_vector_x = color_vector
    mask_vector_2 = pf.nodes.math.combine_xyz(
        x=mask_vector_x.y, y=mask_vector_x.x + 0.5
    )

    vector_vector_1 = pf.nodes.math.vector_scale(vector=mask_vector_2, scale=0.5)

    mask_vector_1 = pf.nodes.math.vector_fraction(vector_vector_2 + vector_vector_1)
    mask_color_vector = pf.nodes.math.vector_absolute(mask_vector_1 - (0.5, 0.5, 0.0))
    mask_color_1 = pf.nodes.math.vector_scale(vector=mask_color_vector, scale=2.0)

    thread_mask_color = (1.0, 1.0, 0.0) - mask_color_1

    mask_vector_vector = pf.nodes.color.rgb_curve(
        color=thread_mask_color.astype(dtype=pf.Color),
        curves=[
            np.array([[0.0, 0.0], [1.0, 1.0]]),
            np.array([[0.0, 0.0], [1.0, 1.0]]),
            np.array([[0.0, 0.0], [1.0, 1.0]]),
            np.array([[0.0, 0.0], [0.25, 0.1], [0.75, 0.9], [1.0, 1.0]]),
        ],
        fac=1.0,
    )

    thread_mask_vector = pf.nodes.math.vector_scale(
        vector=mask_vector_5.astype(dtype=pf.Vector)
        * mask_vector_vector.astype(dtype=pf.Vector),
        scale=2.0,
    )
    thread_mask_1 = mask_vector_5.astype(dtype=pf.Vector) + thread_mask_vector
    thread_mask = thread_mask_1.x < thread_mask_1.y

    color_w_vector = pf.nodes.math.vector_floor(color_vector + (0.0, 0.5, 0.0))
    color_w = color_w_vector
    color_4 = pf.nodes.texture.white_noise(w=color_w.x, noise_dimensions="1D")
    color_3 = pf.nodes.texture.white_noise(w=color_w.y + 4.6, noise_dimensions="1D")
    color_2 = pf.nodes.math.mix(factor=thread_mask, a=color_4.fac, b=color_3.fac)
    color_1 = pf.nodes.color.mix_rgb(
        factor=color_variation,
        a=color,
        b=color_2.astype(dtype=pf.Color),
        blend_type="SOFT_LIGHT",
    )

    alpha_1 = pf.nodes.math.maximum(a=thread_mask_1.x, b=thread_mask_1.y)
    alpha = alpha_1 > 0.0

    shader = pf.nodes.shader.principled_bsdf(
        base_color=color_1,
        metallic=metallic,
        roughness=roughness,
        ior=1.45,
        alpha=alpha,
        transmission_weight=0.0,
        subsurface_weight=0.0,
        subsurface_anisotropy=0.0,
        specular_ior_level=specular,
        sheen_weight=sheen_weight,
        sheen_roughness=sheen_roughness,
    )
    displacement_vector = pf.nodes.math.combine_xyz(x=color_4.fac, y=color_3.fac)
    displacement_height_vector = pf.nodes.math.vector_scale(
        vector=displacement_vector, scale=height_variation
    )
    displacement_height_1 = displacement_height_vector * mask_vector_5.astype(
        dtype=pf.Vector
    )
    displacement_height = displacement_height_1.x + displacement_height_1.y
    displacement_scale = height_scale * 0.0002
    displacement = pf.nodes.shader.displacement(
        height=displacement_height + alpha_1,
        midlevel=0.0,
        scale=size * displacement_scale,
        normal=(0.0, 0.0, 0.0),
    )
    return FabricResult(
        surface=shader,
        displacement=displacement,
        color=color_1,
        thread_mask=thread_mask,
        alpha=alpha,
    )


def fabric_fine_preset(
    vector: pf.ProcNode[pf.Vector],
    color: t.SocketOrVal[pf.Color] = pf.Color((0.36, 0.30, 0.24)),
):
    fabric_result = fabric(
        vector=vector,
        size_variation=0.0,
        color=color,
        color_variation=0.25,
        gab=0.1,
    )
    return pf.Material(
        surface=fabric_result.surface,
        displacement=fabric_result.displacement,
    )


def fabric_coarse_preset(
    vector: pf.ProcNode[pf.Vector],
    color: t.SocketOrVal[pf.Color] = pf.Color((0.20, 0.12, 0.08)),
):
    # Code generated by procfunc v0.3.0

    fabric_result = fabric(
        vector=vector,
        size=3.0,
        size_variation=0.9,
        height_variation=1.0,
        color=color,
        color_variation=0.2,
        specular=0.2,
        roughness=0.75,
    )
    return pf.Material(
        surface=fabric_result.surface,
        displacement=fabric_result.displacement,
    )


def fabric_color_rand(
    rng: pf.RNG,
    value: t.SocketOrVal[float] | None = None,
) -> pf.Color:
    hue = pf.random.uniform(rng, 0.0, 1.0)
    saturation = pf.random.clip_gaussian(rng, 0.6, 0.32, 0.0, 0.7)
    if value is None:
        value = pf.random.uniform(rng, 0.0, 1.0)
    return pf.color.hsv_color(hue=hue, saturation=saturation, value=value)


def fabric_rand(
    rng: pf.RNG,
    vector: t.SocketOrVal[pf.Vector],
    base_color: t.SocketOrVal[pf.Color] | None = None,
):
    if base_color is None:
        base_color = fabric_color_rand(rng)

    size = pf.random.uniform(rng, 0.5, 2)
    size_variation = pf.random.uniform(rng, 0.0, 0.9)
    height_scale = pf.random.uniform(rng, 0.3, 0.6)
    height_variation = pf.random.uniform(rng, 0.2, 1.0)
    color_variation = pf.random.uniform(rng, 0.2, 0.25)
    metallic = 0.0
    specular = pf.random.uniform(rng, 0.2, 0.25)
    roughness = pf.random.clip_gaussian(rng, 0.7, 0.1, 0.6, 0.8)

    sheen_weight = pf.random.uniform(rng, 0.0, 1.0)
    sheen_roughness = pf.random.uniform(rng, 0.0, 0.1)
    gab = pf.random.uniform(rng, 0.0, 0.1)

    fabric_result = fabric(
        vector=vector,
        size=size,
        color=base_color,
        size_variation=size_variation,
        height_scale=height_scale,
        height_variation=height_variation,
        color_variation=color_variation,
        metallic=metallic,
        specular=specular,
        roughness=roughness,
        sheen_weight=sheen_weight,
        sheen_roughness=sheen_roughness,
        gab=gab,
    )
    return pf.Material(
        surface=fabric_result.surface,
        displacement=fabric_result.displacement,
    )


def fabric_translucent_rand(
    rng: pf.RNG,
    vector: t.SocketOrVal[pf.Vector],
    base_color: t.SocketOrVal[pf.Color] | None = None,
    translucency: float = 0.5,
) -> pf.Material:
    if base_color is None:
        base_color = fabric_color_rand(rng)
    material = fabric_rand(rng, vector, base_color=base_color)
    translucent = pf.nodes.shader.translucent_bsdf(color=base_color)
    surface = pf.nodes.shader.mix_shader(
        factor=translucency, a=material.surface, b=translucent
    )
    return pf.Material(surface=surface, displacement=material.displacement)
