# Copyright (C) 2026, Princeton University.
# This source code is licensed under the BSD 3-Clause license found in the LICENSE file in the root directory of this source tree.

# Transpiled into procfunc/v2 format by Alexander Raistrick

import numpy as np
import procfunc as pf
from procfunc.nodes import types as t

from infinigen2.shaders.util.coord import coord_warp

__all__ = [
    "paint",
    "paint_color_rand",
    "paint_rand",
    "paint_small_bumps_preset",
    "paint_splats_preset",
    "paint_spots_preset",
    "paint_strokes_preset",
]


@pf.nodes.node_function
def paint(
    vector: t.SocketOrVal[pf.Vector] = (0.0, 0.0, 0.0),
    color: t.SocketOrVal[pf.Color] = pf.Color((0.144, 0.144, 0.144)),
    metallic: t.SocketOrVal[float] = 0.0,
    roughness: t.SocketOrVal[float] = 0.5,
    specular_ior_level: t.SocketOrVal[float] = 0.5,
    bump_height: t.SocketOrVal[float] = 0.02,
    bump_size: t.SocketOrVal[float] = 0.02,
    bump_warp_size: t.SocketOrVal[float] = 0.04,
    bump_warp_strength: t.SocketOrVal[float] = 1.0,
    splat_height: t.SocketOrVal[float] = 0.01,
    splat_size: t.SocketOrVal[float] = 0.0,
    splat_width: t.SocketOrVal[float] = 0.55,
    splat_spread: t.SocketOrVal[float] = 0.6,
    splat_warp_size: t.SocketOrVal[float] = 0.3,
    splat_warp_strength: t.SocketOrVal[float] = 1.0,
    stroke_height: t.SocketOrVal[float] = 0.01,
    stroke_size: t.SocketOrVal[float] = 0.01,
    stroke_spread: t.SocketOrVal[float] = 1.0,
    stroke_length: t.SocketOrVal[float] = 0.0833,
    stroke_warp_size: t.SocketOrVal[float] = 0.5,
    stroke_warp_strength: t.SocketOrVal[float] = 0.82,
    globule_height: t.SocketOrVal[float] = 0.01,
    globule_size: t.SocketOrVal[float] = 0.01,
    globule_spread: t.SocketOrVal[float] = 1.0,
) -> pf.Material:
    # Code generated by procfunc v0.3.0

    surface = pf.nodes.shader.principled_bsdf(
        base_color=color,
        metallic=metallic,
        roughness=roughness,
        ior=1.45,
        subsurface_anisotropy=0.0,
        specular_ior_level=specular_ior_level,
    )

    coord_warp_result = coord_warp(
        vector=vector, size=bump_warp_size, strength=bump_warp_strength
    )

    displacement_value_1 = pf.nodes.texture.noise(
        vector=coord_warp_result.vector,
        scale=1.0 / bump_size,
        detail=4.0,
        noise_dimensions="2D",
    )
    displacement_height_value_4 = pf.nodes.math.map_range(
        value=displacement_value_1.fac, from_min=0.2, from_max=0.8
    )
    displacement_height_17 = pf.nodes.math.float_curve(
        value=displacement_height_value_4,
        curve=np.array([[0.0, 0.0], [0.5682, 0.2688], [1.0, 1.0]]),
        factor=1.0,
    )

    coord_warp_result_1 = coord_warp(
        vector=vector,
        size=splat_warp_size / 3.0,
        strength=splat_warp_strength * 2.0,
    )
    coord_warp_result_2 = coord_warp(
        vector=coord_warp_result_1.vector,
        size=splat_warp_size,
        strength=splat_warp_strength,
    )

    displacement_height_value_3 = pf.nodes.texture.voronoi(
        vector=coord_warp_result_2.vector,
        scale=1.0 / splat_size,
        voronoi_dimensions="2D",
    )

    height_from_min_2 = pf.nodes.math.maximum(a=splat_width, b=0.0001)

    displacement_height_16 = pf.nodes.math.map_range(
        value=displacement_height_value_3.distance,
        from_min=1.0 - height_from_min_2,
    )
    displacement_scale = splat_size * 4.0
    displacement_height_value_2 = pf.nodes.texture.noise(
        vector=vector,
        scale=1.0 / displacement_scale,
        detail=4.0,
        noise_dimensions="2D",
    )
    displacement_height_15 = pf.nodes.math.map_range(
        value=displacement_height_value_2.fac,
        from_min=0.2,
        from_max=0.8,
        to_min=0.2,
    )
    displacement_height_14 = pf.nodes.math.clamp(
        value=splat_spread, min=0.0001, max=0.9999
    )

    height_from_min_1 = pf.nodes.math.clamp(displacement_height_14 * 2.0)

    displacement_height_13 = pf.nodes.math.map_range(
        value=displacement_height_14,
        from_min=0.5,
        to_min=1.0,
        to_max=0.0,
    )
    displacement_height_12 = pf.nodes.math.map_range(
        value=displacement_height_15,
        from_min=1.0 - height_from_min_1,
        from_max=displacement_height_13,
    )
    displacement_height_11 = displacement_height_16 * displacement_height_12
    displacement_height_10 = (displacement_height_17 * bump_height) + (
        displacement_height_11 * splat_height
    )
    displacement_value_vector = pf.nodes.texture.noise(
        vector=vector, scale=1.0 / stroke_length, detail=0.0
    )
    displacement_value = displacement_value_vector.color.astype(dtype=pf.Vector)
    displacement_from_min_3 = pf.nodes.math.mix(factor=stroke_spread, a=0.9, b=0.2)
    displacement_from_max = pf.nodes.math.mix(factor=stroke_spread, a=1.0, b=0.6)
    displacement_height_value_1 = pf.nodes.math.map_range(
        value=displacement_value.x,
        from_min=displacement_from_min_3,
        from_max=displacement_from_max,
    )
    displacement_height_9 = pf.nodes.math.float_curve(
        value=displacement_height_value_1,
        curve=np.array([[0.0, 0.0], [0.1955, 0.0687], [0.7364, 0.875], [1.0, 1.0]]),
        factor=1.0,
    )
    displacement_height_8 = displacement_height_9 * stroke_height
    displacement_from_min_2 = pf.nodes.math.constant(0.6)
    displacement_from_min_numerator = pf.nodes.math.constant(0.25)
    displacement_from_min_1 = displacement_from_min_numerator / 2.0
    displacement_height_factor_1 = pf.nodes.math.map_range(
        value=displacement_value.y,
        from_min=displacement_from_min_2 - displacement_from_min_1,
        from_max=displacement_from_min_2 + displacement_from_min_1,
    )
    displacement_from_min = pf.nodes.math.constant(0.5)
    displacement_height_factor = pf.nodes.math.map_range(
        value=displacement_value.z,
        from_min=displacement_from_min - displacement_from_min_1,
        from_max=displacement_from_min + displacement_from_min_1,
    )

    coord_warp_result_3 = coord_warp(
        vector=vector,
        size=stroke_warp_size,
        strength=stroke_warp_strength,
        detail=2.0,
    )

    displacement_height_7 = pf.nodes.texture.noise(
        vector=coord_warp_result_3.vector * (1.0, 0.01, 1.0),
        scale=1.0 / stroke_size,
        noise_dimensions="2D",
    )

    coord_warp_result_4 = coord_warp(
        vector=vector,
        size=stroke_warp_size,
        strength=stroke_warp_strength,
        detail=2.0,
    )

    displacement_height_vector_3 = pf.nodes.math.vector_rotate_axis_angle(
        coord_warp_result_4.vector,
        axis=(0, 0, 1),
        angle=0.0,
        center=(0, 0, 0),
    )
    displacement_height_vector_2 = displacement_height_vector_3 * (1.0, 0.01, 1.0)
    displacement_height_6 = pf.nodes.texture.noise(
        vector=displacement_height_vector_2 + (55.5, 0.0, 0.0),
        scale=1.0 / stroke_size,
        noise_dimensions="2D",
    )
    displacement_height_5 = pf.nodes.math.mix(
        factor=displacement_height_factor,
        a=displacement_height_7.fac,
        b=displacement_height_6.fac,
    )

    coord_warp_result_5 = coord_warp(
        vector=vector,
        size=stroke_warp_size,
        strength=stroke_warp_strength,
        detail=2.0,
    )

    displacement_height_vector_1 = pf.nodes.math.vector_rotate_axis_angle(
        coord_warp_result_5.vector,
        axis=(0, 0, 1),
        angle=0.0,
        center=(0, 0, 0),
    )
    displacement_height_vector = displacement_height_vector_1 * (1.0, 0.01, 1.0)
    displacement_height_4 = pf.nodes.texture.noise(
        vector=displacement_height_vector + (-67.2, 0.0, 0.0),
        scale=1.0 / stroke_size,
        noise_dimensions="2D",
    )
    displacement_height_3 = pf.nodes.math.mix(
        factor=displacement_height_factor_1,
        a=displacement_height_5,
        b=displacement_height_4.fac,
    )

    coord_warp_result_6 = coord_warp(vector=vector, size=globule_size * 2.0, detail=1.0)

    displacement_height_value = pf.nodes.texture.voronoi(
        vector=coord_warp_result_6.vector,
        scale=1.0 / globule_size,
        detail=2.0,
        normalize=True,
    )
    displacement_height_2 = pf.nodes.math.map_range(
        value=1.0 - displacement_height_value.distance,
        from_min=0.56,
    )
    displacement_height_from_min = pf.nodes.math.minimum(
        a=1.0 - globule_spread, b=0.9999
    )
    displacement_height_1 = pf.nodes.math.map_range(
        value=displacement_height_2,
        from_min=displacement_height_from_min,
        to_max=globule_height * globule_spread,
    )
    displacement_height = (
        displacement_height_8 * displacement_height_3
    ) + displacement_height_1
    displacement = pf.nodes.shader.displacement(
        height=displacement_height_10 + displacement_height,
        midlevel=0.0,
        normal=(0.0, 0.0, 0.0),
    )
    return pf.Material(
        surface=surface,
        displacement=displacement,
    )


def paint_strokes_preset(
    vector: pf.ProcNode[pf.Vector],
) -> pf.Material:
    # Code generated by procfunc v0.1.0

    return paint(
        vector=vector,
        bump_height=0.003,
        bump_size=0.01,
        splat_height=0.003,
        splat_size=0.042,
        splat_width=0.4509,
        splat_warp_size=0.12,
        stroke_height=0.004,
        stroke_size=0.005,
        stroke_spread=0.8538,
        stroke_length=0.1,
        globule_height=0.0,
        globule_spread=0.5,
    )


def paint_spots_preset(
    vector: pf.ProcNode[pf.Vector],
) -> pf.Material:
    # Code generated by procfunc v0.1.0

    return paint(
        vector=vector,
        roughness=0.0708,
        specular_ior_level=0.3208,
        bump_height=0.001,
        bump_size=0.04,
        splat_height=0.0,
        splat_size=0.042,
        splat_width=0.4509,
        splat_warp_size=0.12,
        stroke_height=0.0,
        stroke_size=0.005,
        stroke_spread=0.8538,
        stroke_length=0.1,
        globule_height=0.003,
        globule_size=0.02,
        globule_spread=0.5,
    )


def paint_splats_preset(
    vector: pf.ProcNode[pf.Vector],
) -> pf.Material:
    # Code generated by procfunc v0.1.0

    return paint(
        vector=vector,
        roughness=0.6038,
        specular_ior_level=0.3774,
        bump_height=0.002,
        bump_size=0.01,
        splat_height=0.008,
        splat_size=0.02,
        splat_width=0.4717,
        splat_spread=0.5236,
        splat_warp_size=0.12,
        stroke_height=0.0,
        globule_height=0.0,
        globule_spread=0.5,
    )


def paint_small_bumps_preset(
    vector: pf.ProcNode[pf.Vector],
) -> pf.Material:
    # Code generated by procfunc v0.1.0

    return paint(
        vector=vector,
        roughness=0.6,
        specular_ior_level=0.275,
        bump_height=0.004,
        bump_size=0.008,
        bump_warp_size=0.02,
        splat_height=0.0,
        splat_size=0.05,
        stroke_height=0.0,
        globule_height=0.0,
        globule_spread=0.5,
    )


def paint_color_rand(
    rng: pf.RNG,
    value: float | None = None,
    saturation: float | None = None,
) -> pf.Color:
    hue = pf.random.uniform(rng, 0.0, 1.0)  # all hues

    if value is None:
        value = pf.random.clip_gaussian(rng, 0.6, 0.3, 0.1, 0.9)
    sat = pf.random.uniform(rng, 0, 0.5) * (1 - value) ** 2
    return pf.color.hsv_color(hue=hue, saturation=sat, value=value)


def paint_rand(
    rng: pf.RNG,
    vector: t.SocketOrVal[pf.Vector],
    displacement_pct: t.SocketOrVal[float] = 1.0,
    base_color: t.SocketOrVal[pf.Color] | None = None,
) -> pf.Material:
    # Code generated by procfunc v0.3.0

    r1, r2 = rng.spawn(2)

    if base_color is None:
        base_color = paint_color_rand(r1)

    metallic = 0.0
    roughness = pf.random.clip_gaussian(r2, 0.5, 0.3, 0.0708, 0.6038)
    specular_ior_level = pf.random.uniform(r2, 0.275, 0.5)
    bump_height = pf.random.uniform(r2, 0.0001, 0.005)
    bump_size = pf.random.uniform(r2, 0.005, 0.205)
    bump_warp_size = pf.random.uniform(r2, 0.01, 0.04)
    bump_warp_strength = 1.0
    splat_height = pf.random.uniform(r2, 0.0, 0.008) * displacement_pct
    splat_size = pf.random.uniform(rng, 0.02, 0.1)
    splat_width = pf.random.uniform(r2, 0.4509, 0.9335)
    splat_spread = pf.random.uniform(r2, 0.5236, 0.7767)
    splat_warp_size = pf.random.uniform(r2, 0.12, 0.3)
    splat_warp_strength = 1.0
    stroke_height = pf.random.uniform(r2, 0.0, 0.004)
    stroke_size = pf.random.uniform(r2, 0.005, 0.01) * displacement_pct
    stroke_spread = pf.random.uniform(r2, 0.8538, 1.0)
    stroke_length = pf.random.uniform(r2, 0.0833, 0.1) * displacement_pct
    stroke_warp_size = 0.5
    stroke_warp_strength = 0.82
    globule_height = pf.random.uniform(r2, 0.0, 0.003) * displacement_pct
    globule_size = pf.random.uniform(r2, 0.01, 0.02)
    globule_spread = 0.5

    paint_result = paint(
        vector=vector,
        color=base_color,
        metallic=metallic,
        roughness=roughness,
        specular_ior_level=specular_ior_level,
        bump_height=bump_height,
        bump_size=bump_size,
        bump_warp_size=bump_warp_size,
        bump_warp_strength=bump_warp_strength,
        splat_height=splat_height,
        splat_size=splat_size,
        splat_width=splat_width,
        splat_spread=splat_spread,
        splat_warp_size=splat_warp_size,
        splat_warp_strength=splat_warp_strength,
        stroke_height=stroke_height,
        stroke_size=stroke_size,
        stroke_spread=stroke_spread,
        stroke_length=stroke_length,
        stroke_warp_size=stroke_warp_size,
        stroke_warp_strength=stroke_warp_strength,
        globule_height=globule_height,
        globule_size=globule_size,
        globule_spread=globule_spread,
    )
    return paint_result
