import numpy as np
import procfunc as pf
from procfunc.nodes import types as nt


@pf.nodes.node_function
def colors_layering_5(
    color_1: nt.SocketOrVal[pf.Color] = pf.Color((0.5, 0.5, 0.5)),
    layer_2_alpha: nt.SocketOrVal[float] = 0.5,
    color_2: nt.SocketOrVal[pf.Color] = pf.Color((0.5, 0.5, 0.5)),
    layer_3_alpha: nt.SocketOrVal[float] = 0.5,
    color_3: nt.SocketOrVal[pf.Color] = pf.Color((0.5, 0.5, 0.5)),
    layer_4_alpha: nt.SocketOrVal[float] = 0.5,
    color_4: nt.SocketOrVal[pf.Color] = pf.Color((0.5, 0.5, 0.5)),
    layer_5_alpha: nt.SocketOrVal[float] = 0.5,
    color_5: nt.SocketOrVal[pf.Color] = pf.Color((0.5, 0.5, 0.5)),
) -> pf.ProcNode[pf.Color]:
    # Code generated by procfunc v0.1.0
    result_3 = pf.nodes.func.mix(factor=layer_2_alpha, a=color_1, b=color_2)

    result_2 = pf.nodes.func.mix(factor=layer_3_alpha, a=result_3, b=color_3)

    result_1 = pf.nodes.func.mix(factor=layer_4_alpha, a=result_2, b=color_4)

    result = pf.nodes.func.mix(factor=layer_5_alpha, a=result_1, b=color_5)

    return result


@pf.nodes.node_function
def values_layering_5(
    layer_1: nt.SocketOrVal[float] = 0.0,
    layer_2_alpha: nt.SocketOrVal[float] = 0.5,
    layer_2: nt.SocketOrVal[float] = 0.0,
    layer_3_alpha: nt.SocketOrVal[float] = 0.5,
    layer_3: nt.SocketOrVal[float] = 0.0,
    layer_4_alpha: nt.SocketOrVal[float] = 0.5,
    layer_4: nt.SocketOrVal[float] = 0.0,
    layer_5_alpha: nt.SocketOrVal[float] = 0.5,
    layer_5: nt.SocketOrVal[float] = 0.0,
) -> pf.ProcNode[float]:
    # Code generated by procfunc v0.1.0
    result_3 = pf.nodes.func.mix(factor=layer_2_alpha, a=layer_1, b=layer_2)

    result_2 = pf.nodes.func.mix(factor=layer_3_alpha, a=result_3, b=layer_3)

    result_1 = pf.nodes.func.mix(factor=layer_4_alpha, a=result_2, b=layer_4)

    result = pf.nodes.func.mix(factor=layer_5_alpha, a=result_1, b=layer_5)

    return result


@pf.nodes.node_function
def color_mix_4(
    map: nt.SocketOrVal[float] = 1.0,
    color_1: nt.SocketOrVal[pf.Color] = pf.Color((0.5, 0.3831, 0.264)),
    color_1_position: nt.SocketOrVal[float] = 0.1,
    color_2: nt.SocketOrVal[pf.Color] = pf.Color((0.2134, 0.117, 0.0651)),
    color_2_position: nt.SocketOrVal[float] = 0.2,
    color_3: nt.SocketOrVal[pf.Color] = pf.Color((0.094, 0.0531, 0.0307)),
    color_3_position: nt.SocketOrVal[float] = 0.3,
    color_4: nt.SocketOrVal[pf.Color] = pf.Color((0.0529, 0.0252, 0.0082)),
    color_4_position: nt.SocketOrVal[float] = 0.4,
) -> pf.ProcNode[pf.Color]:
    # Code generated by procfunc v0.1.0
    factor_value_2 = pf.nodes.func.map_range(
        value=map,
        from_min=color_3_position,
        from_max=color_4_position,
    )

    result_factor_2 = pf.nodes.func.float_curve(
        value=factor_value_2,
        curve=np.array([[0.0, 0.0], [0.1136, 0.0375], [0.8955, 0.9688], [1.0, 1.0]]),
    )

    factor_value_1 = pf.nodes.func.map_range(
        value=map,
        from_min=color_2_position,
        from_max=color_3_position,
    )

    result_factor_1 = pf.nodes.func.float_curve(
        value=factor_value_1,
        curve=np.array([[0.0, 0.0], [0.1136, 0.0375], [0.8955, 0.9688], [1.0, 1.0]]),
    )

    result_factor_value = pf.nodes.func.map_range(
        value=map,
        from_min=color_1_position,
        from_max=color_2_position,
    )

    result_factor = pf.nodes.func.float_curve(
        value=result_factor_value,
        curve=np.array([[0.0, 0.0], [0.1136, 0.0375], [0.8955, 0.9688], [1.0, 1.0]]),
    )

    result_2 = pf.nodes.func.mix(factor=result_factor, a=color_1, b=color_2)

    result_1 = pf.nodes.func.mix(factor=result_factor_1, a=result_2, b=color_3)

    result = pf.nodes.func.mix(factor=result_factor_2, a=result_1, b=color_4)

    return result
