from typing import NamedTuple

import procfunc as pf
from procfunc.nodes import types as t

from infinigen_v2.generators.shaders.util.coord import coord_warp, space_warp


class SplatsMaskResult(NamedTuple):
    mask: pf.ProcNode[float]


@pf.nodes.node_function
def splat_dots(
    vector: t.SocketOrVal[pf.Vector],
    size: t.SocketOrVal[float],
    detail: t.SocketOrVal[float],
    spread: t.SocketOrVal[float],
    smoothness: t.SocketOrVal[float],
    distortion_size: t.SocketOrVal[float],
    distortion_strength: t.SocketOrVal[float],
    distortion_detail: t.SocketOrVal[float],
    opacity: t.SocketOrVal[float],
    opacity_variation: t.SocketOrVal[float],
    seed: t.SocketOrVal[float],
    noise_settings_use_noise: t.SocketOrVal[float],
    noise_settings_noise_size: t.SocketOrVal[float],
    noise_settings_noise_detail: t.SocketOrVal[float],
    border_settings_border_thickness: t.SocketOrVal[float],
    border_settings_border_opacity: t.SocketOrVal[float],
) -> pf.ProcNode[float]:
    # Code generated by procfunc v0.13.3

    coord_warp_result = coord_warp(
        vector=vector / size.astype(dtype=pf.Vector),
        size=distortion_size / 100.0,
        strength=distortion_strength,
        detail=distortion_detail,
        phase=seed,
    )

    voronoi = pf.nodes.texture.voronoi(
        vector=coord_warp_result.vector,
        scale=100.0,
        detail=detail,
        normalize=True,
        voronoi_dimensions="4D",
        w=seed,
    )

    mask_0_a = pf.nodes.math.mix(
        a=1.0,
        b=voronoi.color.astype(dtype=pf.Vector).x,
        factor=opacity_variation,
    )

    noise = pf.nodes.texture.noise(
        vector=coord_warp_result.vector
        / noise_settings_noise_size.astype(dtype=pf.Vector),
        scale=100.0,
        detail=noise_settings_noise_detail,
        noise_dimensions="4D",
        w=voronoi.w,
    )

    mask_b_1 = pf.nodes.math.map_range(value=noise.fac, from_max=0.75, from_min=0.25)
    mask_a_0_b_1 = pf.nodes.math.mix(a=1.0, b=mask_b_1, factor=noise_settings_use_noise)
    mask_a_1 = opacity * mask_a_0_b_1
    mask_from_min = pf.nodes.math.mix(a=spread - 0.0001, b=0.0, factor=smoothness)
    mask_a_0_b_0 = pf.nodes.math.map_range(
        value=voronoi.distance,
        from_max=spread,
        from_min=mask_from_min,
        to_max=0.0,
        to_min=1.0,
    )
    mask_a = pf.nodes.math.clamp(mask_a_1 * mask_a_0_b_0)
    mask_value = pf.nodes.math.map_range(
        value=mask_a_0_b_0,
        from_max=border_settings_border_thickness,
    )
    mask_b_a_a = pf.nodes.math.absolute(mask_value - 0.5)
    mask_b_a = mask_b_a_a * 2.0
    mask_b_0 = (1.0 - mask_b_a) * border_settings_border_opacity
    mask_0_b = pf.nodes.math.clamp(mask_a + mask_b_0)
    mask_2 = mask_0_a * mask_0_b
    return mask_2


@pf.nodes.node_function
def streaks(
    vector: t.SocketOrVal[pf.Vector],
    size: t.SocketOrVal[float],
    spread: t.SocketOrVal[float],
    smoothness: t.SocketOrVal[float],
    vertical_length: t.SocketOrVal[float],
    vertical_spacing: t.SocketOrVal[float],
    distortion_size: t.SocketOrVal[float],
    distortion_strength: t.SocketOrVal[float],
    distortion_detail: t.SocketOrVal[float],
    opacity: t.SocketOrVal[float],
    rotation: t.SocketOrVal[pf.Vector],
    seed: t.SocketOrVal[float],
    noise_settings_use_noise: t.SocketOrVal[float],
    noise_settings_noise_size: t.SocketOrVal[float],
    noise_settings_noise_detail: t.SocketOrVal[float],
    border_settings_thickness: t.SocketOrVal[float],
    border_settings_opacity: t.SocketOrVal[float],
) -> pf.ProcNode[float]:
    # Code generated by procfunc v0.13.3

    noise_vector_vector_1 = pf.nodes.math.vector_rotate_euler(
        vector=vector + (0.0, 0.0, 0.0),
        rotation=rotation,
        center=(0, 0, 0),
    )
    noise_vector_vector_0 = size * 0.01

    coord_warp_result = coord_warp(
        vector=noise_vector_vector_1 / noise_vector_vector_0.astype(dtype=pf.Vector),
        size=distortion_size,
        strength=distortion_strength * 0.3,
        detail=distortion_detail * 0.5,
        phase=seed,
    )

    voronoi = pf.nodes.texture.voronoi(
        vector=coord_warp_result.vector,
        scale=0.5,
        normalize=True,
        voronoi_dimensions="2D",
    )

    mask_vector_w = (voronoi.color.astype(dtype=pf.Vector).x - 0.5) * 100.0

    space_warp_result = space_warp(
        vector=coord_warp_result.vector - voronoi.position,
        strength=distortion_strength,
        w=seed + mask_vector_w,
        size=distortion_size,
        detail=distortion_detail,
        roughness=0.5,
        lacunarity=2.0,
        distortion=0.0,
    )

    mask_a_base_value = pf.nodes.math.vector_length(
        space_warp_result.vector * (1.0, 1.0, 0.0)
    )
    mask_a_4 = pf.nodes.math.maximum(a=spread, b=0.0001)
    mask_a_base = pf.nodes.math.map_range(
        value=mask_a_base_value,
        from_max=mask_a_4 * 0.54,
        to_max=0.0,
        to_min=1.0,
    )
    mask_a_3 = mask_a_base**0.5
    mask_a_a_vector = pf.nodes.math.combine_xyz(
        x=voronoi.color.astype(dtype=pf.Vector).y, y=seed
    )

    white_noise = pf.nodes.texture.white_noise(
        vector=mask_a_a_vector, noise_dimensions="2D"
    )

    mask_a_2 = white_noise.fac - 0.5
    mask_0_vector = pf.nodes.math.combine_xyz(
        x=space_warp_result.vector.z, y=mask_a_2 * 49.899994
    )

    voronoi_1 = pf.nodes.texture.voronoi(
        vector=mask_0_vector,
        scale=1.0 / vertical_length,
        voronoi_dimensions="2D",
    )

    mask_factor = pf.nodes.math.minimum(a=vertical_spacing, b=0.9999)
    mask_b_base_from_min = pf.nodes.math.mix(a=0.0, b=0.89, factor=mask_factor)
    mask_b_base = pf.nodes.math.map_range(
        value=voronoi_1.distance,
        from_max=mask_b_base_from_min + 0.25,
        from_min=mask_b_base_from_min,
    )
    mask_b_1 = mask_b_base**0.5
    mask_base_value = pf.nodes.math.map_range(value=mask_a_3 * mask_b_1, from_min=0.28)
    mask_base_from_max = pf.nodes.math.maximum(a=smoothness, b=0.0001)
    mask_base = pf.nodes.math.map_range(
        value=mask_base_value, from_max=mask_base_from_max
    )
    mask_0_a_a = mask_base**2.0

    noise = pf.nodes.texture.noise(
        vector=coord_warp_result.vector,
        scale=1.0 / noise_settings_noise_size,
        detail=noise_settings_noise_detail,
        noise_dimensions="4D",
    )

    mask_a_1 = pf.nodes.math.map_range(value=noise.fac, from_max=0.75, from_min=0.25)
    mask_0_a_0 = pf.nodes.math.mix(
        a=mask_0_a_a,
        b=mask_a_1 * mask_0_a_a,
        factor=noise_settings_use_noise,
    )
    mask_a_from_max = pf.nodes.math.maximum(a=border_settings_thickness, b=0.0001)
    mask_a_0 = pf.nodes.math.map_range(value=mask_base_value, from_max=mask_a_from_max)
    mask_b_a = pf.nodes.math.absolute(mask_a_0 - 0.5)
    mask_b_0 = mask_b_a * 2.0
    mask_0_b_0 = pf.nodes.math.clamp(1.0 - mask_b_0)
    mask_2 = (opacity * mask_0_a_0) + (mask_0_b_0 * border_settings_opacity)
    return mask_2


def splats_metal_gradient(vector: t.SocketOrVal[pf.Vector]):
    # Code generated by procfunc v0.13.3

    coord = pf.nodes.shader.coord()

    splat_dots_spread = pf.nodes.math.map_range(
        value=coord.generated.z,
        from_max=0.7,
        from_min=0.3,
        to_max=0.18,
        to_min=0.55,
    )
    splat_dots_opacity = pf.nodes.math.map_range(
        value=coord.generated.z,
        from_max=0.7,
        from_min=0.3,
        to_max=0.1,
        to_min=0.2,
    )
    small_dots = splat_dots(
        vector=vector,
        size=0.05,
        detail=0.0,
        spread=splat_dots_spread,
        smoothness=0.262597,
        distortion_size=2.0,
        distortion_strength=2.0,
        distortion_detail=4.0,
        opacity=splat_dots_opacity,
        opacity_variation=1.0,
        seed=0.0,
        noise_settings_use_noise=0.0,
        noise_settings_noise_size=0.3,
        noise_settings_noise_detail=4.0,
        border_settings_border_thickness=0.636047,
        border_settings_border_opacity=0.0,
    )

    surface_factor_spread = pf.nodes.math.map_range(
        value=coord.generated.z,
        from_max=0.7,
        from_min=0.3,
        to_max=0.2,
        to_min=0.39,
    )
    surface_factor_opacity = pf.nodes.math.map_range(
        value=coord.generated.z,
        from_max=0.7,
        from_min=0.3,
        to_max=0.1,
        to_min=0.49,
    )

    large_dots = splat_dots(
        vector=vector,
        size=0.15,
        detail=1.0,
        spread=surface_factor_spread,
        smoothness=0.221899,
        distortion_size=1.0,
        distortion_strength=1.0,
        distortion_detail=4.0,
        opacity=surface_factor_opacity,
        opacity_variation=0.773256,
        seed=5.0,
        noise_settings_use_noise=0.0,
        noise_settings_noise_size=0.3,
        noise_settings_noise_detail=4.0,
        border_settings_border_thickness=0.636047,
        border_settings_border_opacity=0.284884,
    )

    mask = pf.nodes.math.clamp(small_dots)
    mask = pf.nodes.math.clamp(mask + large_dots)

    principled = pf.nodes.shader.principled_bsdf(
        base_color=pf.Color((0.526, 0.526, 0.526)),
        metallic=1.0,
        roughness=0.145455,
        subsurface_anisotropy=0.0,
    )

    diffuse = pf.nodes.shader.diffuse_bsdf(
        color=pf.Color((0.385, 0.385, 0.385)),
        normal=(0.0, 0.0, 0.0),
    )

    mix_shader = pf.nodes.shader.mix_shader(factor=mask, a=principled, b=diffuse)
    return pf.Material(
        surface=mix_shader,
        displacement=pf.nodes.math.constant((0.0, 0.0, 0.0)),
    )


def splats_cookware(vector: t.SocketOrVal[pf.Vector]):
    # Code generated by procfunc v0.13.3

    small_dots = splat_dots(
        vector=vector,
        size=0.05,
        detail=0.0,
        spread=0.329845,
        smoothness=0.41376,
        distortion_size=2.0,
        distortion_strength=2.0,
        distortion_detail=4.0,
        opacity=0.200388,
        opacity_variation=1.0,
        seed=0.0,
        noise_settings_use_noise=0.0,
        noise_settings_noise_size=0.3,
        noise_settings_noise_detail=4.0,
        border_settings_border_thickness=0.636047,
        border_settings_border_opacity=0.0,
    )

    medium_dots = splat_dots(
        vector=vector,
        size=0.1,
        detail=1.0,
        spread=0.475194,
        smoothness=0.471899,
        distortion_size=2.0,
        distortion_strength=2.0,
        distortion_detail=4.0,
        opacity=0.264341,
        opacity_variation=1.0,
        seed=1.5,
        noise_settings_use_noise=0.0,
        noise_settings_noise_size=0.3,
        noise_settings_noise_detail=4.0,
        border_settings_border_thickness=0.636047,
        border_settings_border_opacity=0.0,
    )

    large_dots = splat_dots(
        vector=vector,
        size=1.0,
        detail=0.0,
        spread=0.149612,
        smoothness=0.221899,
        distortion_size=0.6,
        distortion_strength=3.0,
        distortion_detail=2.0,
        opacity=0.563953,
        opacity_variation=1.0,
        seed=3.1,
        noise_settings_use_noise=1.0,
        noise_settings_noise_size=0.3,
        noise_settings_noise_detail=4.0,
        border_settings_border_thickness=0.636047,
        border_settings_border_opacity=0.511628,
    )

    long_dots = splat_dots(
        vector=vector,
        size=1.0,
        detail=0.0,
        spread=0.19031,
        smoothness=0.221899,
        distortion_size=2.0,
        distortion_strength=3.0,
        distortion_detail=3.8,
        opacity=0.587209,
        opacity_variation=1.0,
        seed=9.799999,
        noise_settings_use_noise=1.0,
        noise_settings_noise_size=0.3,
        noise_settings_noise_detail=4.0,
        border_settings_border_thickness=0.636047,
        border_settings_border_opacity=0.511628,
    )

    mask = pf.nodes.math.clamp(small_dots)
    mask = pf.nodes.math.clamp(mask + medium_dots)
    mask = pf.nodes.math.clamp(mask + large_dots)
    mask = pf.nodes.math.clamp(mask + long_dots)

    principled = pf.nodes.shader.principled_bsdf(
        base_color=pf.Color((0.526, 0.526, 0.526)),
        metallic=1.0,
        roughness=0.145455,
        subsurface_anisotropy=0.0,
    )

    diffuse = pf.nodes.shader.diffuse_bsdf(
        color=pf.Color((0.549, 0.549, 0.549)),
        normal=(0.0, 0.0, 0.0),
    )

    mix_shader = pf.nodes.shader.mix_shader(factor=mask, a=principled, b=diffuse)
    return pf.Material(
        surface=mix_shader,
        displacement=pf.nodes.math.constant((0.0, 0.0, 0.0)),
    )


def splats_spots(vector: t.SocketOrVal[pf.Vector]):
    # Code generated by procfunc v0.13.3

    small_dots = splat_dots(
        vector=vector,
        size=0.05,
        detail=0.0,
        spread=0.254264,
        smoothness=0.262597,
        distortion_size=2.0,
        distortion_strength=2.0,
        distortion_detail=4.0,
        opacity=0.305039,
        opacity_variation=1.0,
        seed=0.0,
        noise_settings_use_noise=0.0,
        noise_settings_noise_size=0.3,
        noise_settings_noise_detail=4.0,
        border_settings_border_thickness=0.636047,
        border_settings_border_opacity=0.0,
    )
    large_dots = splat_dots(
        vector=vector,
        size=0.64,
        detail=2.0,
        spread=0.207752,
        smoothness=0.291667,
        distortion_size=1.0,
        distortion_strength=1.0,
        distortion_detail=2.0,
        opacity=0.767442,
        opacity_variation=0.343023,
        seed=3.1,
        noise_settings_use_noise=1.0,
        noise_settings_noise_size=0.3,
        noise_settings_noise_detail=4.0,
        border_settings_border_thickness=0.636047,
        border_settings_border_opacity=0.203488,
    )

    mask = pf.nodes.math.clamp(small_dots)
    mask = pf.nodes.math.clamp(mask + large_dots)

    principled = pf.nodes.shader.principled_bsdf(
        base_color=pf.Color((0.526, 0.526, 0.526)),
        metallic=1.0,
        roughness=0.145455,
        subsurface_anisotropy=0.0,
    )

    diffuse = pf.nodes.shader.diffuse_bsdf(
        color=pf.Color((0.549, 0.549, 0.549)),
        normal=(0.0, 0.0, 0.0),
    )

    mix_shader = pf.nodes.shader.mix_shader(factor=mask, a=principled, b=diffuse)
    return pf.Material(
        surface=mix_shader,
        displacement=pf.nodes.math.constant((0.0, 0.0, 0.0)),
    )


def splats_metal_mask(vector: t.SocketOrVal[pf.Vector]) -> pf.ProcNode[float]:
    small_dots = splat_dots(
        vector=vector,
        size=0.05,
        detail=0.0,
        spread=0.35,
        smoothness=0.262597,
        distortion_size=2.0,
        distortion_strength=2.0,
        distortion_detail=4.0,
        opacity=0.15,
        opacity_variation=1.0,
        seed=0.0,
        noise_settings_use_noise=0.0,
        noise_settings_noise_size=0.3,
        noise_settings_noise_detail=4.0,
        border_settings_border_thickness=0.636047,
        border_settings_border_opacity=0.0,
    )

    large_dots = splat_dots(
        vector=vector,
        size=0.15,
        detail=1.0,
        spread=0.3,
        smoothness=0.221899,
        distortion_size=1.0,
        distortion_strength=1.0,
        distortion_detail=4.0,
        opacity=0.3,
        opacity_variation=0.773256,
        seed=5.0,
        noise_settings_use_noise=0.0,
        noise_settings_noise_size=0.3,
        noise_settings_noise_detail=4.0,
        border_settings_border_thickness=0.636047,
        border_settings_border_opacity=0.284884,
    )

    mask = pf.nodes.math.clamp(small_dots)
    mask = pf.nodes.math.clamp(mask + large_dots)
    return mask


def splats_cookware_mask(vector: t.SocketOrVal[pf.Vector]) -> pf.ProcNode[float]:
    small_dots = splat_dots(
        vector=vector,
        size=0.05,
        detail=0.0,
        spread=0.329845,
        smoothness=0.41376,
        distortion_size=2.0,
        distortion_strength=2.0,
        distortion_detail=4.0,
        opacity=0.200388,
        opacity_variation=1.0,
        seed=0.0,
        noise_settings_use_noise=0.0,
        noise_settings_noise_size=0.3,
        noise_settings_noise_detail=4.0,
        border_settings_border_thickness=0.636047,
        border_settings_border_opacity=0.0,
    )

    medium_dots = splat_dots(
        vector=vector,
        size=0.1,
        detail=1.0,
        spread=0.475194,
        smoothness=0.471899,
        distortion_size=2.0,
        distortion_strength=2.0,
        distortion_detail=4.0,
        opacity=0.264341,
        opacity_variation=1.0,
        seed=1.5,
        noise_settings_use_noise=0.0,
        noise_settings_noise_size=0.3,
        noise_settings_noise_detail=4.0,
        border_settings_border_thickness=0.636047,
        border_settings_border_opacity=0.0,
    )

    large_dots = splat_dots(
        vector=vector,
        size=1.0,
        detail=0.0,
        spread=0.149612,
        smoothness=0.221899,
        distortion_size=0.6,
        distortion_strength=3.0,
        distortion_detail=2.0,
        opacity=0.563953,
        opacity_variation=1.0,
        seed=3.1,
        noise_settings_use_noise=1.0,
        noise_settings_noise_size=0.3,
        noise_settings_noise_detail=4.0,
        border_settings_border_thickness=0.636047,
        border_settings_border_opacity=0.511628,
    )

    long_dots = splat_dots(
        vector=vector,
        size=1.0,
        detail=0.0,
        spread=0.19031,
        smoothness=0.221899,
        distortion_size=2.0,
        distortion_strength=3.0,
        distortion_detail=3.8,
        opacity=0.587209,
        opacity_variation=1.0,
        seed=9.799999,
        noise_settings_use_noise=1.0,
        noise_settings_noise_size=0.3,
        noise_settings_noise_detail=4.0,
        border_settings_border_thickness=0.636047,
        border_settings_border_opacity=0.511628,
    )

    mask = pf.nodes.math.clamp(small_dots)
    mask = pf.nodes.math.clamp(mask + medium_dots)
    mask = pf.nodes.math.clamp(mask + large_dots)
    mask = pf.nodes.math.clamp(mask + long_dots)
    return mask


def splats_spots_mask(vector: t.SocketOrVal[pf.Vector]) -> pf.ProcNode[float]:
    small_dots = splat_dots(
        vector=vector,
        size=0.05,
        detail=0.0,
        spread=0.254264,
        smoothness=0.262597,
        distortion_size=2.0,
        distortion_strength=2.0,
        distortion_detail=4.0,
        opacity=0.305039,
        opacity_variation=1.0,
        seed=0.0,
        noise_settings_use_noise=0.0,
        noise_settings_noise_size=0.3,
        noise_settings_noise_detail=4.0,
        border_settings_border_thickness=0.636047,
        border_settings_border_opacity=0.0,
    )
    large_dots = splat_dots(
        vector=vector,
        size=0.64,
        detail=2.0,
        spread=0.207752,
        smoothness=0.291667,
        distortion_size=1.0,
        distortion_strength=1.0,
        distortion_detail=2.0,
        opacity=0.767442,
        opacity_variation=0.343023,
        seed=3.1,
        noise_settings_use_noise=1.0,
        noise_settings_noise_size=0.3,
        noise_settings_noise_detail=4.0,
        border_settings_border_thickness=0.636047,
        border_settings_border_opacity=0.203488,
    )

    mask = pf.nodes.math.clamp(small_dots)
    mask = pf.nodes.math.clamp(mask + large_dots)
    return mask


def splats_streaks_mask(vector: t.SocketOrVal[pf.Vector]) -> pf.ProcNode[float]:
    dots_1 = splat_dots(
        vector=vector,
        size=0.1,
        detail=0.0,
        spread=0.201938,
        smoothness=0.291667,
        distortion_size=3.0,
        distortion_strength=2.0,
        distortion_detail=4.0,
        opacity=0.089922,
        opacity_variation=0.333333,
        seed=0.0,
        noise_settings_use_noise=0.0,
        noise_settings_noise_size=0.3,
        noise_settings_noise_detail=4.0,
        border_settings_border_thickness=0.636047,
        border_settings_border_opacity=0.0,
    )
    dots_2 = splat_dots(
        vector=vector,
        size=0.2,
        detail=0.0,
        spread=0.167054,
        smoothness=0.291667,
        distortion_size=1.0,
        distortion_strength=2.0,
        distortion_detail=2.0,
        opacity=0.252713,
        opacity_variation=0.333333,
        seed=3.1,
        noise_settings_use_noise=0.843023,
        noise_settings_noise_size=0.3,
        noise_settings_noise_detail=4.0,
        border_settings_border_thickness=0.636047,
        border_settings_border_opacity=0.261628,
    )

    streaks_1 = streaks(
        vector=vector,
        size=0.25,
        spread=0.689655,
        smoothness=0.159483,
        vertical_length=4.699999,
        vertical_spacing=0.0,
        distortion_size=4.6,
        distortion_strength=0.8,
        distortion_detail=6.8,
        opacity=0.172414,
        rotation=(0.0, -0.0663, 0.0),
        seed=6.7,
        noise_settings_use_noise=1.0,
        noise_settings_noise_size=0.3,
        noise_settings_noise_detail=4.0,
        border_settings_thickness=0.175287,
        border_settings_opacity=0.183908,
    )
    streaks_2 = streaks(
        vector=vector,
        size=0.3,
        spread=0.367816,
        smoothness=0.159483,
        vertical_length=4.699999,
        vertical_spacing=0.247126,
        distortion_size=5.3,
        distortion_strength=1.6,
        distortion_detail=4.0,
        opacity=0.137931,
        rotation=(0.0, 1.5708, 0.0),
        seed=6.7,
        noise_settings_use_noise=1.0,
        noise_settings_noise_size=0.3,
        noise_settings_noise_detail=4.0,
        border_settings_thickness=0.175287,
        border_settings_opacity=0.183908,
    )
    streaks_3 = streaks(
        vector=vector,
        size=0.5,
        spread=0.310345,
        smoothness=0.159483,
        vertical_length=4.799999,
        vertical_spacing=0.051724,
        distortion_size=2.7,
        distortion_strength=2.1,
        distortion_detail=4.0,
        opacity=0.086207,
        rotation=(0.0, 0.9215, 0.0),
        seed=6.7,
        noise_settings_use_noise=1.0,
        noise_settings_noise_size=0.3,
        noise_settings_noise_detail=4.0,
        border_settings_thickness=0.175287,
        border_settings_opacity=0.183908,
    )

    mask = pf.nodes.math.clamp(dots_1)
    mask = pf.nodes.math.clamp(mask + dots_2)
    mask = pf.nodes.math.clamp(mask + streaks_1)
    mask = pf.nodes.math.clamp(mask + streaks_2)
    mask = pf.nodes.math.clamp(mask + streaks_3)
    return mask


def splats_streaks(vector: t.SocketOrVal[pf.Vector]):
    mask = splats_streaks_mask(vector=vector)

    principled = pf.nodes.shader.principled_bsdf(
        base_color=pf.Color((0.526, 0.526, 0.526)),
        metallic=1.0,
        roughness=0.145455,
        subsurface_anisotropy=0.0,
    )

    diffuse = pf.nodes.shader.diffuse_bsdf(
        color=pf.Color((0.549, 0.549, 0.549)),
        normal=(0.0, 0.0, 0.0),
    )

    mix_shader = pf.nodes.shader.mix_shader(factor=mask, a=principled, b=diffuse)
    return pf.Material(
        surface=mix_shader,
        displacement=pf.nodes.math.constant((0.0, 0.0, 0.0)),
    )


def splats_mask_presets(
    rng: pf.RNG,
    vector: t.SocketOrVal[pf.Vector],
) -> SplatsMaskResult:
    func = pf.control.choice(
        rng,
        [
            (splats_metal_mask, 1.0),
            (splats_cookware_mask, 1.0),
            (splats_spots_mask, 1.0),
            (splats_streaks_mask, 3.0),
        ],
    )
    return SplatsMaskResult(mask=func(vector=vector))


def metal_base_material(vector: t.SocketOrVal[pf.Vector]):
    principled = pf.nodes.shader.principled_bsdf(
        base_color=pf.color.hsv_color(hue=0.0, saturation=0.0, value=0.526),
        metallic=1.0,
        roughness=0.145455,
    )
    return principled


def splats_base_material(vector: t.SocketOrVal[pf.Vector]):
    principled = pf.nodes.shader.diffuse_bsdf(
        color=pf.color.hsv_color(hue=0.49, saturation=0.0, value=0.386),
        roughness=0.0,
    )
    return principled


def metal_splats_presets(rng: pf.RNG, vector):
    del vector
    coord = pf.nodes.shader.coord()
    mask = splats_mask_presets(rng=rng, vector=coord.object).mask
    diffuse = splats_base_material(vector=coord.object)
    metal = metal_base_material(vector=coord.object)
    mix_shader = pf.nodes.shader.mix_shader(factor=mask, a=metal, b=diffuse)
    return pf.Material(
        surface=mix_shader,
        displacement=pf.nodes.math.constant((0.0, 0.0, 0.0)),
    )


def splat_dots_distribution(
    rng: pf.RNG,
    vector: t.SocketOrVal[pf.Vector],
    spread: t.SocketOrVal[float] | None = None,
    opacity: t.SocketOrVal[float] | None = None,
    size: t.SocketOrVal[float] | None = None,
):
    if spread is None:
        spread = pf.random.clip_gaussian(rng, 0.15, 0.07, 0.05, 0.4)
    if opacity is None:
        opacity = pf.random.clip_gaussian(rng, 0.15, 0.2, 0.05, 0.7)
    if size is None:
        size = pf.random.uniform(rng, 0.05, 0.3)

    detail = pf.control.choice(rng, [(0.0, 2.0), (1.0, 1.0), (2.0, 0.5)])
    smoothness = pf.random.uniform(rng, 0.262597, 0.41376)
    distortion_size = pf.random.uniform(rng, 2.0, 3.0)
    distortion_strength = pf.random.uniform(rng, 1.0, 3.0)
    distortion_detail = 4.0
    opacity_variation = pf.random.uniform(rng, 0.333333, 1.0)
    seed = pf.random.uniform(rng, 0.0, 100.0)
    noise_settings_use_noise = pf.control.choice(rng, [(0.0, 1.0), (1.0, 1.0)])
    noise_settings_noise_size = 0.3
    noise_settings_noise_detail = 4.0
    border_settings_border_thickness = 0.636047
    border_settings_border_opacity = 0.0

    return splat_dots(
        vector=vector,
        size=size,
        detail=detail,
        spread=spread,
        smoothness=smoothness,
        distortion_size=distortion_size,
        distortion_strength=distortion_strength,
        distortion_detail=distortion_detail,
        opacity=opacity,
        opacity_variation=opacity_variation,
        seed=seed,
        noise_settings_use_noise=noise_settings_use_noise,
        noise_settings_noise_size=noise_settings_noise_size,
        noise_settings_noise_detail=noise_settings_noise_detail,
        border_settings_border_thickness=border_settings_border_thickness,
        border_settings_border_opacity=border_settings_border_opacity,
    )


def splats_streaks_distribution(
    rng: pf.RNG,
    vector: t.SocketOrVal[pf.Vector],
    size: t.SocketOrVal[float] | None = None,
) -> pf.ProcNode[float]:
    if size is None:
        size = pf.random.uniform(rng, 0.25, 0.5)

    spread = pf.random.uniform(rng, 0.310345, 0.689655)
    vertical_length = pf.random.uniform(rng, 4.699999, 4.799999)
    vertical_spacing = pf.random.uniform(rng, 0.0, 0.247126)
    distortion_size = pf.random.uniform(rng, 2.7, 5.3)
    distortion_strength = pf.random.uniform(rng, 0.8, 2.1)
    distortion_detail = pf.random.uniform(rng, 4.0, 6.8)
    opacity = pf.random.uniform(rng, 0.086207, 0.172414)
    rotation_y = pf.random.uniform(rng, -0.0663, 1.5708)
    seed = pf.random.uniform(rng, 0.0, 100.0)

    return streaks(
        vector=vector,
        size=size,
        spread=spread,
        smoothness=0.159483,
        vertical_length=vertical_length,
        vertical_spacing=vertical_spacing,
        distortion_size=distortion_size,
        distortion_strength=distortion_strength,
        distortion_detail=distortion_detail,
        opacity=opacity,
        rotation=(0.0, rotation_y, 0.0),
        seed=seed,
        noise_settings_use_noise=1.0,
        noise_settings_noise_size=0.3,
        noise_settings_noise_detail=4.0,
        border_settings_thickness=0.175287,
        border_settings_opacity=0.183908,
    )


def uv_gradient_distribution(
    rng: pf.RNG,
    vector: t.SocketOrVal[pf.Vector],
    gradient_fac: t.SocketOrVal[float] | None = None,
    gradient_start: t.SocketOrVal[float] | None = None,
    gradient_end: t.SocketOrVal[float] | None = None,
) -> pf.ProcNode[float]:
    if gradient_fac is None:
        gradient_fac = vector.y
    if gradient_start is None:
        gradient_start = pf.control.choice(rng, [(0.0, 0.5), (1.0, 0.5)])
    if gradient_end is None:
        gradient_end = pf.random.uniform(rng, 0.0, 1.0)

    return pf.nodes.math.map_range(
        value=gradient_fac,
        from_min=gradient_start,
        from_max=gradient_end,
    )


def splats_mask_distribution(
    rng: pf.RNG,
    vector: t.SocketOrVal[pf.Vector],
    size: t.SocketOrVal[float] | None = None,
    allow_gradient: bool = False,
    gradient_fac: t.SocketOrVal[float] | None = None,
    gradient_start: t.SocketOrVal[float] | None = None,
    gradient_end: t.SocketOrVal[float] | None = None,
) -> SplatsMaskResult:
    if size is None:
        size = pf.random.clip_gaussian(rng, 2, 4, 0.5, 10)

    initial_size = size * pf.random.uniform(rng, 0.5, 1.5)
    mask = splat_dots_distribution(rng=rng, vector=vector, size=initial_size)
    mask = mask + splat_dots_distribution(rng=rng, vector=vector)

    for _i in range(3):
        size = size * pf.random.uniform(rng, 0.5, 1.5)
        newmask = pf.control.choice(
            rng,
            [
                (splat_dots_distribution, 1.0),
                (splats_streaks_distribution, 1.0),
                (lambda *_, **__: 0.0, 1.0),
            ],
        )(rng, vector, size=size)
        mask = mask + newmask

    if allow_gradient:
        gradient = uv_gradient_distribution(
            rng=rng,
            vector=vector,
            gradient_fac=gradient_fac,
            gradient_start=gradient_start,
            gradient_end=gradient_end,
        )
        mask = pf.nodes.math.clamp(mask * gradient)

    return SplatsMaskResult(mask=mask)
