# Copyright (C) 2026, Princeton University.
# This source code is licensed under the BSD 3-Clause license found in the LICENSE file in the root directory of this source tree.

# Authors: Alexander Raistrick

import procfunc as pf

from infinigen2.shaders.base_materials import paint as paint_material
from infinigen2.shaders.base_materials.paint import paint, paint_rand
from infinigen2.shaders.masks import cracks
from infinigen2.shaders.masks.cracks import (
    cracks_flakes_preset,
)

__all__ = [
    "cracked_paint_overlay_rand",
    "paint_overlay_rand",
]


def _paint_weartear_flakes(
    vector: pf.ProcNode[pf.Vector],
):
    # Code generated by procfunc v0.3.0

    paint_result = paint(
        vector=vector,
        base_color=pf.Color((0.086, 0.069, 0.042)),
        bump_height=0.0001,
        bump_size=0.005,
        bump_warp_size=0.01,
        splat_height=0.0005,
        splat_size=0.025,
        splat_width=0.4656,
        splat_spread=0.7273,
        splat_warp_size=0.15,
        stroke_height=0.0,
        globule_height=0.0,
        globule_spread=0.5,
    )

    wear_and_tear_result = cracks_flakes_preset(
        vector=vector,
        displacement_b=paint_result.displacement,
    )

    surface_1 = pf.nodes.shader.diffuse_bsdf(
        color=pf.Color((0.029, 0.022, 0.019)),
        normal=(0.0, 0.0, 0.0),
    )
    surface = pf.nodes.shader.mix_shader(
        factor=wear_and_tear_result,
        a=surface_1,
        b=paint_result.surface,
    )

    displacement_1 = pf.nodes.shader.displacement(
        height=-0.0005, midlevel=0.0, normal=(0.0, 0.0, 0.0)
    )
    displacement = pf.nodes.math.mix(
        factor=wear_and_tear_result,
        a=displacement_1,
        b=paint_result.displacement,
    )
    return pf.Material(
        surface=surface,
        displacement=displacement,
    )


def cracked_paint_overlay_rand(
    rng: pf.RNG,
    vector: pf.ProcNode[pf.Vector],
    material: pf.Material,
) -> pf.Material:
    """Aged paint coat over an existing material: a fresh paint layer cracks and
    flakes away to reveal the underlying surface through the crack mask."""
    rng_paint, rng_cracks = rng.spawn(2)
    paint_value = pf.random.clip_gaussian(rng_paint, 0.5, 0.4, 0.1, 0.9)
    color = paint_material.paint_color_rand(rng_paint, value=paint_value)
    paint_coat = paint_rand(rng_paint, vector, base_color=color)
    mask = cracks.cracks_rand(
        rng_cracks,
        vector,
        displacement_a=material.displacement,
        displacement_b=paint_coat.displacement,
        height_threshold=0.0,
    ).mask
    return paint_overlay_rand(
        rng_cracks, vector, material=material, paint=paint_coat, mask=mask
    )


def paint_overlay_rand(
    rng: pf.RNG,
    vector: pf.ProcNode[pf.Vector],
    material: pf.Material,
    paint: pf.Material | None = None,
    mask: pf.ProcNode[float] | None = None,
) -> pf.Material:
    rc, rv = rng.spawn(2)

    if paint is None:
        paint = paint_rand(rv, vector)

    if mask is None:
        return pf.Material(
            surface=paint.surface,
            displacement=paint.displacement + material.displacement,
        )

    surface = pf.nodes.shader.mix_shader(
        factor=mask,
        a=material.surface,
        b=paint.surface,
    )

    paint_thickness_displacement = pf.nodes.shader.displacement(
        height=pf.random.uniform(rv, 0.00001, 0.0001),
        midlevel=0.0,
        normal=(0.0, 0.0, 0.0),
    )

    displacement = pf.nodes.math.mix(
        factor=mask,
        a=material.displacement,
        b=material.displacement + paint.displacement + paint_thickness_displacement,
    )

    return pf.Material(
        surface=surface,
        displacement=displacement,
    )
