# Copyright (C) 2026, Princeton University.
# This source code is licensed under the BSD 3-Clause license found in the LICENSE file in the root directory of this source tree.

# Authors: Alexander Raistrick

from typing import NamedTuple

import procfunc as pf
from procfunc.nodes import types as t

__all__ = [
    "CoordWarpResult",
    "SpaceWarpResult",
    "coord_warp",
    "space_warp",
]


class CoordWarpResult(NamedTuple):
    vector: pf.ProcNode[pf.Vector]
    fac: pf.ProcNode[float]


@pf.nodes.node_function
def coord_warp(
    vector: t.SocketOrVal[pf.Vector] = (0.0, 0.0, 0.0),
    size: t.SocketOrVal[float] = 0.1,
    strength: t.SocketOrVal[float] = 0.5,
    detail: t.SocketOrVal[float] = 4.0,
    phase: t.SocketOrVal[float] = 0.0,
) -> CoordWarpResult:
    # Code generated by procfunc v0.3.0

    vector_3 = pf.nodes.math.combine_xyz(z=phase)

    fac = pf.nodes.texture.noise(
        vector=vector + vector_3, scale=1.0 / size, detail=detail
    )

    vector_2 = pf.nodes.math.vector_scale(
        vector=fac.color.astype(dtype=pf.Vector) - (0.5, 0.5, 0.5),
        scale=size * strength,
    )
    vector_1 = (vector + vector_3) + vector_2
    return CoordWarpResult(
        vector=vector_1,
        fac=fac.fac,
    )


class SpaceWarpResult(NamedTuple):
    vector: pf.ProcNode[pf.Vector]
    fac: pf.ProcNode[float]


@pf.nodes.node_function
def space_warp(
    vector: t.SocketOrVal[pf.Vector] = (0.0, 0.0, 0.0),
    strength: t.SocketOrVal[float] = 1.0,
    w: t.SocketOrVal[float] = 0.0,
    size: t.SocketOrVal[float] = 100.0,
    detail: t.SocketOrVal[float] = 2.0,
    roughness: t.SocketOrVal[float] = 0.5,
    lacunarity: t.SocketOrVal[float] = 2.0,
    distortion: t.SocketOrVal[float] = 0.0,
) -> SpaceWarpResult:
    # Code generated by procfunc v0.3.0

    fac_roughness = pf.nodes.math.clamp(roughness)
    fac = pf.nodes.texture.noise(
        vector=vector,
        w=w,
        scale=0.5 / size,
        detail=detail,
        roughness=fac_roughness,
        lacunarity=lacunarity,
        distortion=distortion,
        noise_dimensions="4D",
    )

    vector_2 = pf.nodes.math.vector_scale(
        vector=fac.color.astype(dtype=pf.Vector) - (0.5, 0.5, 0.5),
        scale=strength * size,
    )
    vector_1 = vector + vector_2
    return SpaceWarpResult(
        vector=vector_1,
        fac=fac.fac,
    )
