# Copyright (C) 2026, Princeton University.
# This source code is licensed under the BSD 3-Clause license found in the LICENSE file in the root directory of this source tree.

# Transpiled into procfunc/v2 format by Alexander Raistrick

import numpy as np
import procfunc as pf
from procfunc.nodes import types as t

from infinigen2.shaders.util.coord import coord_warp

__all__ = [
    "brick_concrete",
    "brick_concrete_color_rand",
    "brick_concrete_grout_rand",
    "brick_concrete_rand",
]


@pf.nodes.node_function
def brick_concrete(
    vector: t.SocketOrVal[pf.Vector] = (0.0, 0.0, 0.0),
    color: t.SocketOrVal[pf.Color] = pf.Color((0.577, 0.07, 0.045)),
    roughness: t.SocketOrVal[float] = 0.5,
    specular_ior_level: t.SocketOrVal[float] = 0.5,
    stretch_x: t.SocketOrVal[float] = 1.8,
    stretch_y: t.SocketOrVal[float] = 1.0,
    distortion_size: t.SocketOrVal[float] = 0.1,
    distortion_strength: t.SocketOrVal[float] = 0.5,
    color_noise_1: t.SocketOrVal[float] = 0.25,
    color_noise_1_size: t.SocketOrVal[float] = 0.2,
    color_noise_1_spread: t.SocketOrVal[float] = 0.5,
    color_noise_1_sharpness: t.SocketOrVal[float] = 0.5,
    color_noise_2: t.SocketOrVal[float] = 0.25,
    color_noise_2_size: t.SocketOrVal[float] = 0.0667,
    color_noise_2_spread: t.SocketOrVal[float] = 0.5,
    color_noise_2_sharpness: t.SocketOrVal[float] = 0.5,
    color_dots: t.SocketOrVal[float] = 0.47,
    color_dot_size: t.SocketOrVal[float] = 0.0222,
    color_dot_spread: t.SocketOrVal[float] = 0.81,
    color_dot_sharpness: t.SocketOrVal[float] = 0.5,
    color_micro_grain_variation: t.SocketOrVal[float] = 0.5167,
    color_grain_size: t.SocketOrVal[float] = 0.005,
    displacement_noise_size: t.SocketOrVal[float] = 1.0,
    displacement_noise_height: t.SocketOrVal[float] = 0.01,
    displacement_hole_size: t.SocketOrVal[float] = 1.0,
    displacement_hole_depth: t.SocketOrVal[float] = 0.02,
    displacement_chip_size: t.SocketOrVal[float] = 1.0,
    displacement_chip_spread: t.SocketOrVal[float] = 0.56,
    displacement_chip_depth: t.SocketOrVal[float] = 0.04,
    displacement_additional_height: t.SocketOrVal[float] = 0.0,
) -> pf.Material:
    # Code generated by procfunc v0.3.0

    color_vector_vector = pf.nodes.math.combine_xyz(x=stretch_x, y=stretch_y, z=1.0)

    coord_warp_result = coord_warp(
        vector=vector / color_vector_vector,
        size=distortion_size,
        strength=distortion_strength,
    )

    color_vector_value_1 = pf.nodes.texture.noise(
        vector=coord_warp_result.vector,
        scale=1.0 / color_noise_1_size,
        detail=6.0,
    )

    vector_from_max_1 = pf.nodes.math.maximum(a=color_noise_1_spread, b=0.0001)
    vector_from_min_3 = pf.nodes.math.minimum(a=color_noise_1_sharpness, b=0.999)
    vector_from_min_2 = vector_from_max_1 * vector_from_min_3

    color_vector_1 = pf.nodes.math.map_range(
        value=color_vector_value_1.color.astype(dtype=pf.Vector),
        from_min=vector_from_min_2.astype(dtype=pf.Vector),
        from_max=vector_from_max_1.astype(dtype=pf.Vector),
        to_min=(0.0, 0.0, 0.0),
        to_max=(1.0, 1.0, 1.0),
    )
    color_11 = color_vector_1
    color_10 = pf.nodes.color.mix_rgb(
        factor=color_noise_1,
        a=color,
        b=color_11.x.astype(dtype=pf.Color),
        blend_type="SOFT_LIGHT",
    )
    color_9 = pf.nodes.color.mix_rgb(
        factor=color_noise_1,
        a=color_10,
        b=color_11.y.astype(dtype=pf.Color),
        blend_type="SOFT_LIGHT",
    )
    color_vector_value = pf.nodes.texture.noise(
        vector=coord_warp_result.vector,
        scale=0.5 / color_noise_2_size,
        detail=5.0,
    )
    color_vector_from_max = pf.nodes.math.maximum(a=color_noise_2_spread, b=0.0001)

    vector_from_min_1 = pf.nodes.math.minimum(a=color_noise_2_sharpness, b=0.999)

    color_vector_from_min = color_vector_from_max * vector_from_min_1
    color_vector = pf.nodes.math.map_range(
        value=color_vector_value.color.astype(dtype=pf.Vector),
        from_min=color_vector_from_min.astype(dtype=pf.Vector),
        from_max=color_vector_from_max.astype(dtype=pf.Vector),
        to_min=(0.0, 0.0, 0.0),
        to_max=(1.0, 1.0, 1.0),
    )
    color_8 = color_vector
    color_7 = pf.nodes.color.mix_rgb(
        factor=color_noise_2,
        a=color_9,
        b=color_8.x.astype(dtype=pf.Color),
        blend_type="SOFT_LIGHT",
    )
    color_6 = pf.nodes.color.mix_rgb(
        factor=color_noise_2,
        a=color_7,
        b=color_8.y.astype(dtype=pf.Color),
        blend_type="SOFT_LIGHT",
    )

    coord_warp_result_1 = coord_warp(
        vector=vector, size=distortion_size, strength=distortion_strength, detail=4.1
    )

    color_value_1 = pf.nodes.texture.voronoi(
        vector=coord_warp_result_1.vector,
        scale=1.0 / color_dot_size,
        detail=2.0,
        normalize=True,
    )
    color_5 = pf.nodes.math.maximum(a=color_dot_spread, b=0.0001)
    color_from_min = pf.nodes.math.minimum(a=color_dot_sharpness, b=0.999)
    color_4 = pf.nodes.math.map_range(
        value=color_value_1.distance,
        from_min=(color_5 * 0.6) * color_from_min,
        from_max=color_5 * 0.6,
    )
    color_3 = pf.nodes.color.mix_rgb(
        factor=color_dots,
        a=color_6,
        b=color_4.astype(dtype=pf.Color),
        blend_type="MULTIPLY",
    )

    coord_warp_result_2 = coord_warp(vector=vector, size=0.005, strength=6.48)

    color_value = pf.nodes.texture.noise(
        vector=coord_warp_result_2.vector,
        scale=1.0 / color_grain_size,
    )
    color_2 = pf.nodes.math.map_range(
        value=color_value.fac, from_min=0.26, from_max=0.79
    )
    color_1 = pf.nodes.color.mix_rgb(
        factor=color_micro_grain_variation,
        a=color_3,
        b=color_2.astype(dtype=pf.Color),
        blend_type="SOFT_LIGHT",
    )

    surface = pf.nodes.shader.principled_bsdf(
        base_color=color_1,
        roughness=roughness,
        ior=1.45,
        subsurface_anisotropy=0.0,
        specular_ior_level=specular_ior_level,
    )

    height_6 = color_grain_size * 0.1
    height_vector_2 = pf.nodes.math.vector_scale(
        vector=vector, scale=1.0 / displacement_noise_size
    )

    coord_warp_result_3 = coord_warp(vector=height_vector_2, size=0.3, strength=10.1)

    height_value_2 = pf.nodes.texture.noise(
        vector=coord_warp_result_3.vector, scale=1.0, detail=8.0
    )
    height_5 = pf.nodes.math.map_range(
        value=height_value_2.fac, from_min=0.4, from_max=0.63
    )
    height_4 = (color_2 * height_6) + (height_5 * displacement_noise_height)
    height_vector_1 = pf.nodes.math.vector_scale(
        vector=vector, scale=1.0 / displacement_hole_size
    )

    coord_warp_result_4 = coord_warp(vector=height_vector_1, size=0.07, strength=1.0)

    height_value_1 = pf.nodes.texture.voronoi(
        vector=coord_warp_result_4.vector,
        scale=13.44,
        detail=1.0,
        normalize=True,
    )
    height_3 = pf.nodes.math.map_range(
        value=height_value_1.distance,
        from_max=0.18,
        to_min=-1.0,
        to_max=0.0,
    )
    height_vector = pf.nodes.math.vector_scale(
        vector=vector, scale=1.0 / displacement_chip_size
    )

    coord_warp_result_5 = coord_warp(vector=height_vector, size=0.02, strength=2.0)

    height_value = pf.nodes.texture.voronoi_distance(
        vector=coord_warp_result_5.vector,
        scale=25.0,
        detail=1.0,
        lacunarity=1.62,
        normalize=True,
    )
    height_2 = pf.nodes.math.map_range(
        value=height_value / 0.39,
        from_min=1.0 - displacement_chip_spread,
        to_max=-1.0,
    )
    height_1 = (height_3 * displacement_hole_depth) + (
        height_2 * displacement_chip_depth
    )
    height = (height_4 + height_1) + displacement_additional_height

    displacement = pf.nodes.shader.displacement(
        height=height, midlevel=0.0, normal=(0.0, 0.0, 0.0)
    )
    return pf.Material(
        surface=surface,
        displacement=displacement,
    )


@pf.tracer.grammar
def brick_concrete_color_rand(
    rng: pf.RNG,
) -> t.SocketOrVal[pf.Color]:
    """
    Color which is typically red-brown-yellow, with light values tending to be unsaturated
    """

    saturation_pct = pf.random.clip_gaussian(rng, 0.5, 0.35, 0.05, 0.9)

    # more red when saturated
    hue = 0.15 * pf.random.uniform(rng, 0, 1) * (1 - saturation_pct)

    # lowsat <-> hival, hisat <-> lowval
    value = pf.random.uniform(rng, 0.1, 0.8) * (1 - saturation_pct)

    saturation = saturation_pct * 0.85
    return pf.color.hsv_color(hue=hue, saturation=saturation, value=value)


@pf.tracer.grammar
def brick_concrete_rand(
    rng: pf.RNG,
    vector: t.SocketOrVal[pf.Vector],
    color: t.SocketOrVal[pf.Color] | None = None,
    displacement_pct: t.SocketOrVal[float] = 1,
    displacement_additional_height: t.SocketOrVal[float] = 0,
):
    # Code generated by procfunc v0.4.0, tweaked by araistrick

    rng, rcolor = rng.spawn(2)

    if color is None:
        color = brick_concrete_color_rand(rcolor)

    roughness = pf.random.uniform(rng, 0.7, 0.9409)
    specular_ior_level = pf.random.uniform(rng, 0.0753, 0.1941)
    stretch_x = pf.random.uniform(rng, 1.34, 1.8)
    stretch_y = 1.0
    distortion_size = 0.1
    distortion_strength = 0.5
    color_noise_1 = pf.random.uniform(rng, 0.25, 0.6975)
    color_noise_1_size = pf.random.uniform(rng, 0.04, 0.2)
    color_noise_1_spread = pf.random.uniform(rng, 0.5, 0.8)
    color_noise_1_sharpness = 0.5
    color_noise = pf.random.uniform(rng, 0.25, 1.0)
    color_noise_2_size = pf.random.uniform(rng, 0.0001, 0.8548)
    color_noise_2_spread = 0.5
    color_noise_2_sharpness = pf.random.uniform(rng, 0.25, 0.5)
    color_dots = pf.random.uniform(rng, 0.3, 1.0)
    color_dot_size = pf.random.uniform(rng, 0.0003, 0.0222)
    color_dot_spread = 0.81
    color_dot_sharpness = 0.5
    color_micro_grain_variation = pf.random.uniform(rng, 0.5167, 1.0)
    color_grain_size = pf.random.uniform(rng, 0.001, 0.005)

    displacement_noise_height = pf.random.uniform(rng, 0.001, 0.02) * displacement_pct
    displacement_noise_size = pf.random.uniform(rng, 0.1, 1.0)

    displacement_hole_depth = pf.random.uniform(rng, 0.0, 0.03) * displacement_pct
    displacement_hole_size = pf.random.uniform(rng, 0, 1.0)

    displacement_chip_depth = pf.random.uniform(rng, 0.0, 0.01) * displacement_pct

    # prevalence 0-100%
    displacement_chip_spread = pf.random.uniform(rng, 0, 0.6)
    displacement_chip_size = pf.random.uniform(rng, 1, 2)

    brick_concrete_result = brick_concrete(
        vector=vector,
        color=color,
        roughness=roughness,
        specular_ior_level=specular_ior_level,
        stretch_x=stretch_x,
        stretch_y=stretch_y,
        distortion_size=distortion_size,
        distortion_strength=distortion_strength,
        color_noise_1=color_noise_1,
        color_noise_1_size=color_noise_1_size,
        color_noise_1_spread=color_noise_1_spread,
        color_noise_1_sharpness=color_noise_1_sharpness,
        color_noise_2=color_noise,
        color_noise_2_size=color_noise_2_size,
        color_noise_2_spread=color_noise_2_spread,
        color_noise_2_sharpness=color_noise_2_sharpness,
        color_dots=color_dots,
        color_dot_size=color_dot_size,
        color_dot_spread=color_dot_spread,
        color_dot_sharpness=color_dot_sharpness,
        color_micro_grain_variation=color_micro_grain_variation,
        color_grain_size=color_grain_size,
        displacement_noise_size=displacement_noise_size,
        displacement_noise_height=displacement_noise_height,
        displacement_hole_size=displacement_hole_size,
        displacement_hole_depth=displacement_hole_depth,
        displacement_chip_size=displacement_chip_size,
        displacement_chip_spread=displacement_chip_spread,
        displacement_chip_depth=displacement_chip_depth,
        displacement_additional_height=displacement_additional_height,
    )
    return brick_concrete_result


@pf.tracer.grammar
def brick_concrete_grout_rand(
    rng: pf.RNG,
    vector: t.SocketOrVal[pf.Vector],
    color: t.SocketOrVal[pf.Color] | None = None,
    displacement_pct: t.SocketOrVal[float] | None = None,
    displacement_additional_height: t.SocketOrVal[float] = 0,
):
    # Code generated by procfunc v0.3.0

    r1, r2 = rng.spawn(2)

    if color is None:
        color_hsv = pf.random.uniform(
            r1,
            np.array([0.0, 0.09677423, 0.05]),
            np.array([0.093, 0.1, 0.21]),
        )
        color = pf.color.hsv_to_rgba(color_hsv)

    if displacement_pct is None:
        displacement_pct = pf.random.uniform(rng, 0.03, 0.1)

    return brick_concrete_rand(
        r2,
        vector=vector,
        color=color,
        displacement_pct=displacement_pct,
        displacement_additional_height=displacement_additional_height,
    )
