# Copyright (C) 2026, Princeton University.
# This source code is licensed under the BSD 3-Clause license found in the LICENSE file in the root directory of this source tree.

# Authors:
# - Hongyu Wen: original nodegroup
# - Alexander Raistrick: transpile to procfunc/v2

from typing import NamedTuple

import numpy as np
import procfunc as pf
from procfunc.nodes import types as t

__all__ = [
    "GrainLayer001Result",
    "GrainToShaderResult",
    "grain_layer",
    "grain_layer_color_rand",
    "grain_layer_rand",
    "grain_to_shader",
    "grain_to_shader_rand",
    "marble_black_preset",
    "marble_black_spots_preset",
    "marble_gold_preset",
    "marble_gray_preset",
    "marble_navy_preset",
    "marble_orange_preset",
    "marble_presets",
    "marble_rand",
    "marble_white_preset",
    "marble_white_striped_preset",
    "marble_yellow_preset",
]


@pf.nodes.node_function
def _organic_voronoi(
    vector: t.SocketOrVal[pf.Vector],
    w: t.SocketOrVal[float],
    scale: t.SocketOrVal[float],
) -> pf.ProcNode[float]:
    # Code generated by procfunc v0.18.0-ifg
    voronoi = pf.nodes.texture.voronoi(
        vector=vector,
        scale=scale,
        lacunarity=2.5,
        normalize=True,
        voronoi_dimensions="4D",
        w=w,
    )

    voronoi_smooth_f1 = pf.nodes.texture.voronoi_smooth_f1(
        vector=vector,
        scale=scale,
        lacunarity=2.5,
        smoothness=1.0,
        normalize=True,
        voronoi_dimensions="4D",
        w=w,
    )
    numerator = pf.nodes.math.clamp(voronoi.distance - voronoi_smooth_f1.distance)

    divide = numerator / 0.17

    return divide


class _OrganicGrainResult(NamedTuple):
    vector: t.SocketOrVal[pf.Vector]
    grain_map: pf.ProcNode[float]


@pf.nodes.node_function
def _organic_grain(
    vector: t.SocketOrVal[pf.Vector],
    grain_size: t.SocketOrVal[float],
    grain_stretch: t.SocketOrVal[float],
    grain_detail: t.SocketOrVal[float],
    grain_lacunarity: t.SocketOrVal[float],
    seed: t.SocketOrVal[float],
) -> _OrganicGrainResult:
    # Code generated by procfunc v0.18.0-ifg
    grain_map_factor_1 = pf.nodes.math.clamp(grain_detail)

    organic_voronoi_scale = (1.0 / grain_size) * 10.0

    organic_voronoi_result = _organic_voronoi(
        vector=vector, w=seed, scale=organic_voronoi_scale
    )
    grain_map_factor_from_min = pf.nodes.math.constant(0.31)

    grain_map_factor_from_max = grain_map_factor_from_min + 0.1
    grain_map_factor_0 = pf.nodes.math.map_range(
        value=organic_voronoi_result,
        from_max=grain_map_factor_from_max,
        from_min=grain_map_factor_from_min,
    )
    grain_map_b_factor_1 = pf.nodes.math.clamp(grain_detail - 1.0)
    organic_scale_1 = organic_voronoi_scale * grain_lacunarity

    organic_voronoi_result_1 = _organic_voronoi(
        vector=vector, w=seed, scale=organic_scale_1
    )
    grain_map_b_factor_0 = pf.nodes.math.map_range(
        value=organic_voronoi_result_1,
        from_max=grain_map_factor_from_max,
        from_min=grain_map_factor_from_min,
    )

    grain_map_a = pf.nodes.math.clamp(grain_detail - 2.0)
    organic_scale_0 = organic_scale_1 * grain_lacunarity

    organic_voronoi_result_2 = _organic_voronoi(
        vector=vector, w=seed, scale=organic_scale_0
    )
    grain_map_b_1 = pf.nodes.math.map_range(
        value=organic_voronoi_result_2,
        from_max=grain_map_factor_from_max,
        from_min=grain_map_factor_from_min,
    )

    organic_voronoi_result_3 = _organic_voronoi(
        vector=vector, w=seed, scale=organic_scale_0 * grain_lacunarity
    )

    grain_map_b_b = pf.nodes.math.mix(
        a=organic_voronoi_result_2,
        b=organic_voronoi_result_3,
        factor=grain_map_a * grain_map_b_1,
    )

    grain_map_b_0 = pf.nodes.math.mix(
        a=organic_voronoi_result_1,
        b=grain_map_b_b,
        factor=grain_map_b_factor_1 * grain_map_b_factor_0,
    )
    grain_map = pf.nodes.math.mix(
        a=organic_voronoi_result,
        b=grain_map_b_0,
        factor=grain_map_factor_1 * grain_map_factor_0,
    )
    return _OrganicGrainResult(vector, grain_map)


class _ChipGrainResult(NamedTuple):
    vector: t.SocketOrVal[pf.Vector]
    grain_map: pf.ProcNode[float]


@pf.nodes.node_function
def _chip_grain(
    vector: t.SocketOrVal[pf.Vector],
    grain_size: t.SocketOrVal[float],
    grain_stretch: t.SocketOrVal[float],
    grain_detail: t.SocketOrVal[float],
    grain_lacunarity: t.SocketOrVal[float],
    seed: t.SocketOrVal[float],
) -> _ChipGrainResult:
    # Code generated by procfunc v0.18.0-ifg
    voronoi_distance_vector_x = 1.0 / grain_stretch

    voronoi_distance_vector = pf.nodes.math.combine_xyz(
        x=voronoi_distance_vector_x,
        y=voronoi_distance_vector_x,
        z=1.0,
    )
    voronoi_distance_scale = 1.0 / grain_size
    voronoi_distance = pf.nodes.texture.voronoi_distance(
        vector=vector * voronoi_distance_vector,
        scale=voronoi_distance_scale * 10.0,
        detail=grain_detail,
        lacunarity=grain_lacunarity,
        normalize=True,
        voronoi_dimensions="4D",
        w=seed,
    )
    grain_map = 1.0 - (voronoi_distance * 2.0)

    return _ChipGrainResult(vector, grain_map)


class _VoronoiGrainResult(NamedTuple):
    vector: t.SocketOrVal[pf.Vector]
    grain_map: pf.ProcNode[float]


@pf.nodes.node_function
def _voronoi_grain(
    vector: t.SocketOrVal[pf.Vector],
    grain_size: t.SocketOrVal[float],
    grain_stretch: t.SocketOrVal[float],
    grain_detail: t.SocketOrVal[float],
    grain_lacunarity: t.SocketOrVal[float],
    seed: t.SocketOrVal[float],
) -> _VoronoiGrainResult:
    # Code generated by procfunc v0.18.0-ifg
    voronoi_vector_x = 1.0 / grain_stretch

    voronoi_vector = pf.nodes.math.combine_xyz(
        x=voronoi_vector_x, y=voronoi_vector_x, z=1.0
    )
    voronoi_scale = 1.0 / grain_size
    voronoi = pf.nodes.texture.voronoi(
        vector=vector * voronoi_vector,
        scale=voronoi_scale * 10.0,
        detail=grain_detail,
        lacunarity=grain_lacunarity,
        normalize=True,
        voronoi_dimensions="4D",
        w=seed,
    )
    grain_map = voronoi.distance * 2.0

    return _VoronoiGrainResult(vector, grain_map)


class _SharpNoiseGrainResult(NamedTuple):
    vector: t.SocketOrVal[pf.Vector]
    grain_map: pf.ProcNode[float]


@pf.nodes.node_function
def _sharp_noise_grain(
    vector: t.SocketOrVal[pf.Vector],
    grain_size: t.SocketOrVal[float],
    grain_stretch: t.SocketOrVal[float],
    grain_detail: t.SocketOrVal[float],
    grain_lacunarity: t.SocketOrVal[float],
    seed: t.SocketOrVal[float],
) -> _SharpNoiseGrainResult:
    # Code generated by procfunc v0.18.0-ifg
    noise_vector_x = 1.0 / grain_stretch

    noise_vector = pf.nodes.math.combine_xyz(x=noise_vector_x, y=noise_vector_x, z=1.0)
    noise_scale = 1.0 / grain_size
    noise = pf.nodes.texture.noise(
        vector=vector * noise_vector,
        scale=noise_scale * 10.0,
        detail=grain_detail,
        lacunarity=grain_lacunarity,
        noise_dimensions="4D",
        normalize=False,
        w=seed,
    )
    grain_map_b = pf.nodes.math.absolute(noise.fac)

    grain_map = 1.0 - grain_map_b
    return _SharpNoiseGrainResult(vector, grain_map)


class _NoiseGrainResult(NamedTuple):
    vector: t.SocketOrVal[pf.Vector]
    grain_map: pf.ProcNode[float]


@pf.nodes.node_function
def _noise_grain(
    vector: t.SocketOrVal[pf.Vector],
    grain_size: t.SocketOrVal[float],
    grain_stretch: t.SocketOrVal[float],
    grain_detail: t.SocketOrVal[float],
    grain_lacunarity: t.SocketOrVal[float],
    seed: t.SocketOrVal[float],
) -> _NoiseGrainResult:
    # Code generated by procfunc v0.18.0-ifg
    noise_scale = 1.0 / grain_size

    noise = pf.nodes.texture.noise(
        vector=vector,
        scale=noise_scale * 10.0,
        detail=grain_detail,
        lacunarity=grain_lacunarity,
        noise_dimensions="4D",
        w=seed,
    )
    grain_map = pf.nodes.math.map_range(value=noise.fac, from_max=0.75, from_min=0.25)

    return _NoiseGrainResult(vector, grain_map)


class _GrainProcessResult(NamedTuple):
    grain: pf.ProcNode[float]
    raw_grain: pf.ProcNode[float]
    edge_mask: pf.ProcNode[float]


@pf.nodes.node_function
def _grain_process(
    grain_spread: t.SocketOrVal[float],
    grain_smoothness: t.SocketOrVal[float],
    invert: t.SocketOrVal[float],
    grain: t.SocketOrVal[float],
) -> _GrainProcessResult:
    # Code generated by procfunc v0.18.0-ifg
    raw_grain = pf.nodes.math.mix(a=grain, b=1.0 - grain, factor=invert)

    grain_from_min_b = pf.nodes.math.clamp(grain_spread)

    grain_from_min = 1.0 - grain_from_min_b
    grain_a = pf.nodes.math.clamp(grain_smoothness)
    grain_from_max_b_b = pf.nodes.math.maximum(a=grain_a, b=0.0001)
    grain_from_max_b = grain_from_min_b * grain_from_max_b_b
    grain_from_max = grain_from_min + grain_from_max_b
    grain_1 = pf.nodes.math.map_range(
        value=raw_grain,
        from_max=grain_from_max,
        from_min=grain_from_min,
    )
    edge_mask = pf.nodes.math.map_range(
        value=raw_grain,
        from_max=grain_from_max + grain_from_max_b,
        from_min=grain_from_max,
    )

    return _GrainProcessResult(grain_1, raw_grain, edge_mask)


class GrainToShaderResult(NamedTuple):
    bsdf: pf.ProcNode[pf.Shader]
    color: t.SocketOrVal[pf.Color]
    displacement: pf.ProcNode[pf.Vector]


@pf.nodes.node_function
def grain_to_shader(
    color: t.SocketOrVal[pf.Color],
    grain: t.SocketOrVal[float],
    roughness: t.SocketOrVal[float],
    specularity: t.SocketOrVal[float],
    height: t.SocketOrVal[float],
) -> GrainToShaderResult:
    # Code generated by procfunc v0.18.0-ifg
    bsdf_b_1 = roughness * 0.07

    bsdf_roughness_to_min = pf.nodes.math.clamp(roughness + bsdf_b_1)
    bsdf_roughness_to_max = pf.nodes.math.clamp(roughness - bsdf_b_1)
    bsdf_roughness = pf.nodes.math.map_range(
        value=grain,
        from_min=0.25,
        to_max=bsdf_roughness_to_max,
        to_min=bsdf_roughness_to_min,
    )
    bsdf_b_0 = specularity * 0.07
    bsdf_specular_ior_level_to_min = pf.nodes.math.clamp(specularity - bsdf_b_0)
    bsdf_specular_ior_level_to_max = pf.nodes.math.clamp(specularity + bsdf_b_0)
    bsdf_specular_ior_level = pf.nodes.math.map_range(
        value=grain,
        from_min=0.25,
        to_max=bsdf_specular_ior_level_to_max,
        to_min=bsdf_specular_ior_level_to_min,
    )
    principled = pf.nodes.shader.principled_bsdf(
        base_color=color,
        roughness=bsdf_roughness,
        ior=1.45,
        subsurface_anisotropy=0.0,
        specular_ior_level=bsdf_specular_ior_level,
    )

    displacement = pf.nodes.shader.displacement(
        height=grain,
        midlevel=0.0,
        scale=height,
        normal=(0.0, 0.0, 0.0),
    )

    return GrainToShaderResult(principled, color, displacement)


class GrainLayer001Result(NamedTuple):
    vector: t.SocketOrVal[pf.Vector]
    color: pf.ProcNode[pf.Color]
    grain: pf.ProcNode[float]
    layer_count: pf.ProcNode[float]


@pf.nodes.node_function
def grain_layer(
    vector: t.SocketOrVal[pf.Vector],
    base_color: t.SocketOrVal[pf.Color],
    grain: t.SocketOrVal[float],
    layer_count: t.SocketOrVal[float],
    opacity: t.SocketOrVal[float],
    grain_type: t.SocketOrVal[float],
    grain_color: t.SocketOrVal[pf.Color],
    mix_mode: t.SocketOrVal[float],
    grain_size: t.SocketOrVal[float],
    grain_stretch: t.SocketOrVal[float],
    grain_spread: t.SocketOrVal[float],
    random_spread: t.SocketOrVal[float],
    grain_smoothness: t.SocketOrVal[float],
    grain_rotation: t.SocketOrVal[pf.Vector],
    distortion_strength: t.SocketOrVal[float],
    distortion_size: t.SocketOrVal[float],
    distortion_details: t.SocketOrVal[float],
    seed: t.SocketOrVal[float],
    invert: t.SocketOrVal[float],
) -> GrainLayer001Result:
    # Code generated by procfunc v0.18.0-ifg
    color_factor = pf.nodes.math.floor(mix_mode)

    chip_x = pf.nodes.math.clamp(1.0 / grain_stretch)

    chip_grain_vector_a = pf.nodes.math.combine_xyz(x=chip_x, y=chip_x, z=1.0)
    chip_b = pf.nodes.math.vector_rotate_euler(
        vector=vector, rotation=grain_rotation, center=(0, 0, 0)
    )
    chip_a_scale_0 = grain_size * distortion_size
    noise = pf.nodes.texture.noise(
        vector=chip_b,
        scale=1.0 / chip_a_scale_0,
        detail=distortion_details,
        lacunarity=2.5,
        noise_dimensions="4D",
        w=seed,
    )

    chip_a_1 = pf.nodes.math.vector_scale(
        vector=noise.color.astype(dtype=pf.Vector) - (0.5, 0.5, 0.5),
        scale=distortion_strength * chip_a_scale_0,
    )

    chip_grain_vector = chip_grain_vector_a * (chip_a_1 + chip_b)
    noise_1_scale = 1.0 / grain_size

    camera_data = pf.nodes.shader.camera_data()

    chip_a_value = 1.0 / (camera_data.view_distance / 3.0)

    chip_a_0 = pf.nodes.math.logarithm(value=grain_size * chip_a_value, base=2.5)
    noise_1_detail = pf.nodes.math.minimum(a=chip_a_0 + 2.0, b=16.0)

    noise_1 = pf.nodes.texture.noise(
        vector=chip_grain_vector,
        scale=noise_1_scale * 19.099998,
        detail=noise_1_detail,
        lacunarity=2.5,
    )
    color_b_b_b = pf.nodes.math.map_range(
        value=noise_1.color.astype(dtype=pf.Vector),
        from_max=(0.75, 0.75, 0.75),
        from_min=(0.25, 0.25, 0.25),
        to_max=(1.0, 1.0, 1.0),
        to_min=(0.0, 0.0, 0.0),
    )

    color_b_b_0 = pf.nodes.math.mix(
        a=(0.0, 1.0, 1.0), b=color_b_b_b, factor=random_spread
    )
    color_b_1 = 1.0 - color_b_b_0.x
    grain_factor = pf.nodes.math.floor(grain_type)

    chip_grain_grain_detail = pf.nodes.math.minimum(a=chip_a_0 + 3.0, b=16.0)

    noise_grain_result = _noise_grain(
        vector=chip_grain_vector,
        grain_size=grain_size,
        grain_stretch=grain_stretch,
        grain_detail=chip_grain_grain_detail,
        grain_lacunarity=2.5,
        seed=seed,
    )

    sharp_noise_grain_result = _sharp_noise_grain(
        vector=chip_grain_vector,
        grain_size=grain_size,
        grain_stretch=grain_stretch,
        grain_detail=chip_grain_grain_detail,
        grain_lacunarity=2.5,
        seed=seed,
    )

    grain_a_a_a = pf.nodes.math.mix(
        a=noise_grain_result.grain_map,
        b=sharp_noise_grain_result.grain_map,
        factor=grain_factor > 1.0,
    )

    voronoi_grain_result = _voronoi_grain(
        vector=chip_grain_vector,
        grain_size=grain_size,
        grain_stretch=grain_stretch,
        grain_detail=chip_grain_grain_detail,
        grain_lacunarity=2.5,
        seed=seed,
    )

    grain_a_a = pf.nodes.math.mix(
        a=grain_a_a_a,
        b=voronoi_grain_result.grain_map,
        factor=grain_factor > 2.0,
    )

    chip_grain_result = _chip_grain(
        vector=chip_grain_vector,
        grain_size=grain_size,
        grain_stretch=grain_stretch,
        grain_detail=chip_grain_grain_detail,
        grain_lacunarity=2.5,
        seed=seed,
    )

    grain_a = pf.nodes.math.mix(
        a=grain_a_a,
        b=chip_grain_result.grain_map,
        factor=grain_factor > 3.0,
    )

    organic_grain_result = _organic_grain(
        vector=chip_grain_vector,
        grain_size=grain_size,
        grain_stretch=grain_stretch,
        grain_detail=chip_grain_grain_detail,
        grain_lacunarity=2.5,
        seed=seed,
    )

    grain_b = pf.nodes.math.float_curve(
        value=organic_grain_result.grain_map,
        curve=np.array([[0.0, 0.0], [0.1318, 0.3687], [0.5636, 0.8438], [1.0, 1.0]]),
        factor=1.0,
    )

    grain_1 = pf.nodes.math.mix(a=grain_a, b=grain_b, factor=grain_factor > 4.0)
    grain_process_result = _grain_process(
        grain_spread=grain_spread - color_b_b_0.x,
        grain_smoothness=color_b_b_0.y * grain_smoothness,
        invert=invert,
        grain=grain_1,
    )
    gamma = pf.nodes.color.gamma(
        color=grain_process_result.grain.astype(dtype=pf.Color),
        gamma=2.2,
    )

    color_b_factor = (opacity * color_b_1) * gamma.astype(dtype=float)

    color_a_a = pf.nodes.color.mix_rgb(
        factor=color_b_factor, a=base_color, b=grain_color
    )
    color_a_b = pf.nodes.color.mix_rgb(
        factor=color_b_factor,
        a=base_color,
        b=grain_color,
        blend_type="MULTIPLY",
    )
    color_a = pf.nodes.color.mix_rgb(
        factor=color_factor > 1.0, a=color_a_a, b=color_a_b
    )
    color_b_0 = pf.nodes.color.mix_rgb(
        factor=color_b_factor,
        a=base_color,
        b=grain_color,
        blend_type="SOFT_LIGHT",
    )
    color = pf.nodes.color.mix_rgb(factor=color_factor > 2.0, a=color_a, b=color_b_0)
    layer_count_1 = layer_count + opacity

    return GrainLayer001Result(vector, color, grain_1, layer_count_1)


def marble_yellow_preset(vector: pf.ProcNode[pf.Vector]):
    # Code generated by procfunc v0.18.0-ifg\

    grain_layer_vector = pf.nodes.math.vector_scale(vector=vector, scale=1.0 / 1.0)

    grain_layer_base_color = pf.color.hsv_to_rgba((0.1288, 0.867, 1.0))
    grain_layer_grain_color = pf.color.hsv_to_rgba((0.1169, 0.972, 1.0))
    grain_layer_result = grain_layer(
        vector=grain_layer_vector,
        base_color=grain_layer_base_color,
        grain=0.0,
        layer_count=0.0,
        opacity=1.0,
        grain_type=3.0,
        grain_color=grain_layer_grain_color,
        mix_mode=2.0,
        grain_size=5.21,
        grain_stretch=1.5,
        grain_spread=0.821429,
        random_spread=0.040179,
        grain_smoothness=0.310049,
        grain_rotation=(0.6109, 0.6109, 0.0),
        distortion_strength=0.5,
        distortion_size=1.0,
        distortion_details=3.0,
        seed=0.0,
        invert=1.0,
    )
    grain_grain_color_3 = pf.color.hsv_to_rgba((0.053, 0.8328, 0.646))
    grain_layer_result_1 = grain_layer(
        vector=grain_layer_result.vector,
        base_color=grain_layer_result.color,
        grain=grain_layer_result.grain,
        layer_count=grain_layer_result.layer_count,
        opacity=1.0,
        grain_type=1.0,
        grain_color=grain_grain_color_3,
        mix_mode=3.0,
        grain_size=2.35,
        grain_stretch=1.0,
        grain_spread=0.691518,
        random_spread=0.0,
        grain_smoothness=0.508021,
        grain_rotation=(0.8971, 0.9058, 0.0),
        distortion_strength=3.1,
        distortion_size=0.2,
        distortion_details=4.0,
        seed=0.0,
        invert=1.0,
    )
    grain_grain_color_2 = pf.color.hsv_to_rgba((0.0123, 0.9744, 0.43))
    grain_layer_result_2 = grain_layer(
        vector=grain_layer_result_1.vector,
        base_color=grain_layer_result_1.color,
        grain=grain_layer_result_1.grain,
        layer_count=grain_layer_result_1.layer_count,
        opacity=0.352679,
        grain_type=4.0,
        grain_color=grain_grain_color_2,
        mix_mode=2.0,
        grain_size=1.0,
        grain_stretch=2.0,
        grain_spread=0.05125,
        random_spread=0.039509,
        grain_smoothness=1.0,
        grain_rotation=(0.4852, 0.7487, 0.0),
        distortion_strength=0.5,
        distortion_size=0.5,
        distortion_details=6.0,
        seed=0.0,
        invert=0.0,
    )
    grain_grain_color_1 = pf.color.hsv_to_rgba((0.1002, 0.9735, 0.641))
    grain_layer_result_3 = grain_layer(
        vector=grain_layer_result_2.vector,
        base_color=grain_layer_result_2.color,
        grain=grain_layer_result_2.grain,
        layer_count=grain_layer_result_2.layer_count,
        opacity=1.0,
        grain_type=4.0,
        grain_color=grain_grain_color_1,
        mix_mode=2.0,
        grain_size=2.0,
        grain_stretch=3.0,
        grain_spread=0.190777,
        random_spread=0.14833,
        grain_smoothness=1.0,
        grain_rotation=(0.4712, 0.733, 0.8435),
        distortion_strength=0.5,
        distortion_size=1.0,
        distortion_details=6.0,
        seed=0.06,
        invert=0.0,
    )
    grain_grain_color_0 = pf.color.hsv_to_rgba((0.0911, 0.9735, 0.641))
    grain_layer_result_4 = grain_layer(
        vector=grain_layer_result_3.vector,
        base_color=grain_layer_result_3.color,
        grain=grain_layer_result_3.grain,
        layer_count=grain_layer_result_3.layer_count,
        opacity=1.0,
        grain_type=5.0,
        grain_color=grain_grain_color_0,
        mix_mode=2.0,
        grain_size=6.0,
        grain_stretch=4.0,
        grain_spread=1.0,
        random_spread=0.102679,
        grain_smoothness=0.830357,
        grain_rotation=(0.3508, 0.5044, 0.0),
        distortion_strength=0.3,
        distortion_size=1.0,
        distortion_details=6.0,
        seed=0.0,
        invert=0.0,
    )
    grain_to_shader_result = grain_to_shader(
        color=grain_layer_result_4.color,
        grain=grain_layer_result_4.grain,
        roughness=0.560835,
        specularity=0.238753,
        height=0.0,
    )
    return pf.Material(
        grain_to_shader_result.bsdf, pf.nodes.math.constant((0.0, 0.0, 0.0)), None
    )


def marble_white_striped_preset(vector: pf.ProcNode[pf.Vector]):
    # Code generated by procfunc v0.18.0-ifg

    grain_layer_vector = pf.nodes.math.vector_scale(vector=vector, scale=1.0 / 1.0)

    grain_layer_base_color = pf.color.hsv_to_rgba((0.1538, 0.0754, 0.517))
    grain_layer_grain_color = pf.color.hsv_to_rgba((0.0, 0.0, 0.28))
    grain_layer_result = grain_layer(
        vector=grain_layer_vector,
        base_color=grain_layer_base_color,
        grain=0.0,
        layer_count=0.0,
        opacity=0.741071,
        grain_type=1.0,
        grain_color=grain_layer_grain_color,
        mix_mode=1.0,
        grain_size=0.34,
        grain_stretch=1.0,
        grain_spread=0.758929,
        random_spread=0.020179,
        grain_smoothness=0.528798,
        grain_rotation=(0.0, 0.0, 0.0),
        distortion_strength=12.519999,
        distortion_size=1.0,
        distortion_details=8.0,
        seed=0.0,
        invert=1.0,
    )
    grain_grain_color_3 = pf.color.hsv_to_rgba((0.0, 0.0, 0.426))
    grain_layer_result_1 = grain_layer(
        vector=grain_layer_result.vector,
        base_color=grain_layer_result.color,
        grain=grain_layer_result.grain,
        layer_count=grain_layer_result.layer_count,
        opacity=1.0,
        grain_type=3.0,
        grain_color=grain_grain_color_3,
        mix_mode=2.0,
        grain_size=0.29,
        grain_stretch=6.9,
        grain_spread=0.58884,
        random_spread=0.0,
        grain_smoothness=0.669643,
        grain_rotation=(0.0, 0.0, 0.0),
        distortion_strength=0.46,
        distortion_size=0.5,
        distortion_details=8.0,
        seed=0.0,
        invert=0.0,
    )
    grain_grain_color_2 = pf.color.hsv_to_rgba((0.026, 0.8, 0.04))
    grain_layer_result_2 = grain_layer(
        vector=grain_layer_result_1.vector,
        base_color=grain_layer_result_1.color,
        grain=grain_layer_result_1.grain,
        layer_count=grain_layer_result_1.layer_count,
        opacity=0.691964,
        grain_type=1.0,
        grain_color=grain_grain_color_2,
        mix_mode=3.0,
        grain_size=0.1,
        grain_stretch=41.019997,
        grain_spread=0.825134,
        random_spread=0.097545,
        grain_smoothness=1.0,
        grain_rotation=(0.0, 0.0, 0.0),
        distortion_strength=0.32,
        distortion_size=0.5,
        distortion_details=8.0,
        seed=1.4,
        invert=0.0,
    )
    grain_grain_color_1 = pf.color.hsv_to_rgba((0.5, 0.0182, 0.44))
    grain_layer_result_3 = grain_layer(
        vector=grain_layer_result_2.vector,
        base_color=grain_layer_result_2.color,
        grain=grain_layer_result_2.grain,
        layer_count=grain_layer_result_2.layer_count,
        opacity=1.0,
        grain_type=4.0,
        grain_color=grain_grain_color_1,
        mix_mode=2.0,
        grain_size=1.25,
        grain_stretch=9.219999,
        grain_spread=0.09591,
        random_spread=0.119643,
        grain_smoothness=1.0,
        grain_rotation=(0.0, 0.0, 0.0),
        distortion_strength=0.28,
        distortion_size=0.47,
        distortion_details=6.0,
        seed=0.06,
        invert=0.0,
    )
    grain_grain_color_0 = pf.color.hsv_to_rgba((0.1111, 0.0714, 0.042))
    grain_layer_result_4 = grain_layer(
        vector=grain_layer_result_3.vector,
        base_color=grain_layer_result_3.color,
        grain=grain_layer_result_3.grain,
        layer_count=grain_layer_result_3.layer_count,
        opacity=1.0,
        grain_type=3.0,
        grain_color=grain_grain_color_0,
        mix_mode=1.0,
        grain_size=0.25,
        grain_stretch=1.0,
        grain_spread=0.647321,
        random_spread=0.174107,
        grain_smoothness=0.455357,
        grain_rotation=(0.3508, 0.5044, 0.0),
        distortion_strength=3.11,
        distortion_size=1.0,
        distortion_details=6.0,
        seed=0.0,
        invert=1.0,
    )
    grain_to_shader_result = grain_to_shader(
        color=grain_layer_result_4.color,
        grain=grain_layer_result_4.grain,
        roughness=0.560835,
        specularity=0.238753,
        height=0.0,
    )
    return pf.Material(
        grain_to_shader_result.bsdf, pf.nodes.math.constant((0.0, 0.0, 0.0)), None
    )


def marble_white_preset(vector: pf.ProcNode[pf.Vector]):
    # Code generated by procfunc v0.18.0-ifg

    grain_layer_vector = pf.nodes.math.vector_scale(vector=vector, scale=1.0 / 1.0)

    grain_layer_base_color = pf.color.hsv_to_rgba((0.1795, 0.0519, 0.501))
    grain_layer_grain_color = pf.color.hsv_to_rgba((0.0, 0.0, 0.234))
    grain_layer_result = grain_layer(
        vector=grain_layer_vector,
        base_color=grain_layer_base_color,
        grain=0.0,
        layer_count=0.0,
        opacity=0.526786,
        grain_type=1.0,
        grain_color=grain_layer_grain_color,
        mix_mode=1.0,
        grain_size=2.43,
        grain_stretch=2.4,
        grain_spread=0.790179,
        random_spread=0.040179,
        grain_smoothness=0.336834,
        grain_rotation=(-0.7854, -0.7854, 0.0),
        distortion_strength=2.01,
        distortion_size=0.3,
        distortion_details=8.0,
        seed=0.0,
        invert=1.0,
    )
    grain_grain_color_3 = pf.color.hsv_to_rgba((0.0, 0.0, 0.224))
    grain_layer_result_1 = grain_layer(
        vector=grain_layer_result.vector,
        base_color=grain_layer_result.color,
        grain=grain_layer_result.grain,
        layer_count=grain_layer_result.layer_count,
        opacity=0.330357,
        grain_type=3.0,
        grain_color=grain_grain_color_3,
        mix_mode=2.0,
        grain_size=0.4,
        grain_stretch=1.7,
        grain_spread=0.834376,
        random_spread=0.0,
        grain_smoothness=0.495536,
        grain_rotation=(-0.7854, -0.7854, 0.0),
        distortion_strength=2.51,
        distortion_size=0.2,
        distortion_details=8.0,
        seed=0.0,
        invert=1.0,
    )
    grain_grain_color_2 = pf.color.hsv_to_rgba((0.125, 0.0526, 0.076))
    grain_layer_result_2 = grain_layer(
        vector=grain_layer_result_1.vector,
        base_color=grain_layer_result_1.color,
        grain=grain_layer_result_1.grain,
        layer_count=grain_layer_result_1.layer_count,
        opacity=0.241071,
        grain_type=1.0,
        grain_color=grain_grain_color_2,
        mix_mode=2.0,
        grain_size=1.5,
        grain_stretch=1.0,
        grain_spread=0.579598,
        random_spread=0.097545,
        grain_smoothness=0.151786,
        grain_rotation=(0.0, 0.0, 0.0),
        distortion_strength=33.299995,
        distortion_size=0.5,
        distortion_details=8.0,
        seed=0.0,
        invert=0.0,
    )
    grain_grain_color_1 = pf.color.hsv_to_rgba((0.5, 0.0182, 0.44))
    grain_layer_result_3 = grain_layer(
        vector=grain_layer_result_2.vector,
        base_color=grain_layer_result_2.color,
        grain=grain_layer_result_2.grain,
        layer_count=grain_layer_result_2.layer_count,
        opacity=0.924107,
        grain_type=4.0,
        grain_color=grain_grain_color_1,
        mix_mode=2.0,
        grain_size=0.94,
        grain_stretch=3.0,
        grain_spread=0.079392,
        random_spread=0.063509,
        grain_smoothness=0.790179,
        grain_rotation=(0.2618, 0.2618, 0.0),
        distortion_strength=0.44,
        distortion_size=0.5,
        distortion_details=8.0,
        seed=0.0,
        invert=0.0,
    )
    grain_grain_color_0 = pf.color.hsv_to_rgba((0.1111, 0.0714, 0.042))
    grain_layer_result_4 = grain_layer(
        vector=grain_layer_result_3.vector,
        base_color=grain_layer_result_3.color,
        grain=grain_layer_result_3.grain,
        layer_count=grain_layer_result_3.layer_count,
        opacity=0.361607,
        grain_type=3.0,
        grain_color=grain_grain_color_0,
        mix_mode=1.0,
        grain_size=0.25,
        grain_stretch=5.3,
        grain_spread=0.491071,
        random_spread=0.183036,
        grain_smoothness=0.727679,
        grain_rotation=(0.2618, 0.2618, 0.0),
        distortion_strength=0.54,
        distortion_size=1.33,
        distortion_details=8.0,
        seed=0.0,
        invert=0.0,
    )
    grain_to_shader_result = grain_to_shader(
        color=grain_layer_result_4.color,
        grain=grain_layer_result_4.grain,
        roughness=0.560835,
        specularity=0.238753,
        height=0.0,
    )
    return pf.Material(
        grain_to_shader_result.bsdf, pf.nodes.math.constant((0.0, 0.0, 0.0)), None
    )


def marble_orange_preset(vector: pf.ProcNode[pf.Vector]):
    # Code generated by procfunc v0.18.0-ifg
    grain_layer_vector = pf.nodes.math.vector_scale(vector=vector, scale=1.0 / 1.0)

    grain_layer_base_color = pf.color.hsv_to_rgba((0.0773, 0.2018, 0.342))
    grain_layer_grain_color = pf.color.hsv_to_rgba((0.0478, 0.5918, 0.784))
    grain_layer_result = grain_layer(
        vector=grain_layer_vector,
        base_color=grain_layer_base_color,
        grain=0.0,
        layer_count=0.0,
        opacity=1.0,
        grain_type=1.0,
        grain_color=grain_layer_grain_color,
        mix_mode=2.0,
        grain_size=0.5,
        grain_stretch=30.099998,
        grain_spread=0.758929,
        random_spread=0.040179,
        grain_smoothness=0.542191,
        grain_rotation=(0.0, 0.0, 0.0),
        distortion_strength=1.0,
        distortion_size=1.0,
        distortion_details=0.0,
        seed=0.0,
        invert=1.0,
    )
    grain_grain_color_3 = pf.color.hsv_to_rgba((0.0, 0.0, 0.068))
    grain_layer_result_1 = grain_layer(
        vector=grain_layer_result.vector,
        base_color=grain_layer_result.color,
        grain=grain_layer_result.grain,
        layer_count=grain_layer_result.layer_count,
        opacity=0.75,
        grain_type=3.0,
        grain_color=grain_grain_color_3,
        mix_mode=1.0,
        grain_size=0.5,
        grain_stretch=11.970001,
        grain_spread=0.709376,
        random_spread=0.0,
        grain_smoothness=0.299107,
        grain_rotation=(0.0, 0.0, 0.0),
        distortion_strength=1.0,
        distortion_size=1.0,
        distortion_details=0.0,
        seed=0.0,
        invert=1.0,
    )
    grain_grain_color_2 = pf.color.hsv_to_rgba((0.0072, 0.9106, 0.179))
    grain_layer_result_2 = grain_layer(
        vector=grain_layer_result_1.vector,
        base_color=grain_layer_result_1.color,
        grain=grain_layer_result_1.grain,
        layer_count=grain_layer_result_1.layer_count,
        opacity=0.754464,
        grain_type=2.0,
        grain_color=grain_grain_color_2,
        mix_mode=3.0,
        grain_size=0.5,
        grain_stretch=41.019997,
        grain_spread=0.182277,
        random_spread=0.097545,
        grain_smoothness=1.0,
        grain_rotation=(0.0, 0.0, 0.0),
        distortion_strength=1.0,
        distortion_size=1.0,
        distortion_details=0.0,
        seed=0.0,
        invert=0.0,
    )
    grain_grain_color_1 = pf.color.hsv_to_rgba((0.5, 0.0182, 0.44))
    grain_layer_result_3 = grain_layer(
        vector=grain_layer_result_2.vector,
        base_color=grain_layer_result_2.color,
        grain=grain_layer_result_2.grain,
        layer_count=grain_layer_result_2.layer_count,
        opacity=0.0,
        grain_type=4.0,
        grain_color=grain_grain_color_1,
        mix_mode=2.0,
        grain_size=0.76,
        grain_stretch=9.219999,
        grain_spread=0.310196,
        random_spread=0.224223,
        grain_smoothness=1.0,
        grain_rotation=(0.0, 0.0, 0.0),
        distortion_strength=0.22,
        distortion_size=0.87,
        distortion_details=6.0,
        seed=0.06,
        invert=0.0,
    )
    grain_grain_color_0 = pf.color.hsv_to_rgba((0.1111, 0.0714, 0.042))
    grain_layer_result_4 = grain_layer(
        vector=grain_layer_result_3.vector,
        base_color=grain_layer_result_3.color,
        grain=grain_layer_result_3.grain,
        layer_count=grain_layer_result_3.layer_count,
        opacity=0.696429,
        grain_type=3.0,
        grain_color=grain_grain_color_0,
        mix_mode=1.0,
        grain_size=0.25,
        grain_stretch=1.0,
        grain_spread=0.647321,
        random_spread=0.174107,
        grain_smoothness=0.455357,
        grain_rotation=(0.3508, 0.5044, 0.0),
        distortion_strength=3.11,
        distortion_size=1.0,
        distortion_details=6.0,
        seed=0.0,
        invert=1.0,
    )
    grain_to_shader_result = grain_to_shader(
        color=grain_layer_result_4.color,
        grain=grain_layer_result_4.grain,
        roughness=0.560835,
        specularity=0.238753,
        height=0.0,
    )
    return pf.Material(
        grain_to_shader_result.bsdf, pf.nodes.math.constant((0.0, 0.0, 0.0)), None
    )


def marble_navy_preset(vector: pf.ProcNode[pf.Vector]):
    # Code generated by procfunc v0.18.0-ifg
    grain_layer_vector = pf.nodes.math.vector_scale(vector=vector, scale=1.0 / 1.0)

    grain_layer_base_color = pf.color.hsv_to_rgba((0.5882, 0.4722, 0.036))
    grain_layer_grain_color = pf.color.hsv_to_rgba((0.5903, 0.48, 0.1))
    grain_layer_result = grain_layer(
        vector=grain_layer_vector,
        base_color=grain_layer_base_color,
        grain=0.0,
        layer_count=0.0,
        opacity=0.691964,
        grain_type=1.0,
        grain_color=grain_layer_grain_color,
        mix_mode=1.0,
        grain_size=3.03,
        grain_stretch=2.23,
        grain_spread=0.741071,
        random_spread=0.142857,
        grain_smoothness=0.497549,
        grain_rotation=(0.7854, 0.7854, 0.0),
        distortion_strength=0.42,
        distortion_size=1.0,
        distortion_details=8.0,
        seed=0.0,
        invert=0.0,
    )
    grain_grain_color_3 = pf.color.hsv_to_rgba((0.5641, 0.7222, 0.018))
    grain_layer_result_1 = grain_layer(
        vector=grain_layer_result.vector,
        base_color=grain_layer_result.color,
        grain=grain_layer_result.grain,
        layer_count=grain_layer_result.layer_count,
        opacity=0.383929,
        grain_type=3.0,
        grain_color=grain_grain_color_3,
        mix_mode=2.0,
        grain_size=0.55,
        grain_stretch=2.0,
        grain_spread=1.0,
        random_spread=0.0,
        grain_smoothness=0.521875,
        grain_rotation=(0.7854, 0.7854, 0.0),
        distortion_strength=2.5,
        distortion_size=0.28,
        distortion_details=8.0,
        seed=0.0,
        invert=1.0,
    )
    grain_grain_color_2 = pf.color.hsv_to_rgba((0.5072, 0.2229, 0.933))
    grain_layer_result_2 = grain_layer(
        vector=grain_layer_result_1.vector,
        base_color=grain_layer_result_1.color,
        grain=grain_layer_result_1.grain,
        layer_count=grain_layer_result_1.layer_count,
        opacity=1.0,
        grain_type=1.0,
        grain_color=grain_grain_color_2,
        mix_mode=3.0,
        grain_size=0.5,
        grain_stretch=2.0,
        grain_spread=0.584821,
        random_spread=0.039509,
        grain_smoothness=0.294643,
        grain_rotation=(0.4852, 0.7487, 0.0),
        distortion_strength=12.4,
        distortion_size=1.0,
        distortion_details=6.0,
        seed=0.0,
        invert=0.0,
    )
    grain_grain_color_1 = pf.color.hsv_to_rgba((0.5, 0.2621, 0.641))
    grain_layer_result_3 = grain_layer(
        vector=grain_layer_result_2.vector,
        base_color=grain_layer_result_2.color,
        grain=grain_layer_result_2.grain,
        layer_count=grain_layer_result_2.layer_count,
        opacity=0.392857,
        grain_type=4.0,
        grain_color=grain_grain_color_1,
        mix_mode=1.0,
        grain_size=1.0,
        grain_stretch=6.0,
        grain_spread=0.060893,
        random_spread=0.030625,
        grain_smoothness=1.0,
        grain_rotation=(0.4712, 0.733, 0.0),
        distortion_strength=0.8,
        distortion_size=1.0,
        distortion_details=8.0,
        seed=0.06,
        invert=0.0,
    )
    grain_grain_color_0 = pf.color.hsv_to_rgba((0.6055, 0.1232, 0.641))
    grain_layer_result_4 = grain_layer(
        vector=grain_layer_result_3.vector,
        base_color=grain_layer_result_3.color,
        grain=grain_layer_result_3.grain,
        layer_count=grain_layer_result_3.layer_count,
        opacity=0.41317,
        grain_type=5.0,
        grain_color=grain_grain_color_0,
        mix_mode=1.0,
        grain_size=1.0,
        grain_stretch=8.0,
        grain_spread=0.379241,
        random_spread=0.067188,
        grain_smoothness=0.422321,
        grain_rotation=(0.4712, 0.733, 0.0),
        distortion_strength=0.4,
        distortion_size=1.5,
        distortion_details=8.0,
        seed=2.2,
        invert=0.0,
    )
    grain_to_shader_result = grain_to_shader(
        color=grain_layer_result_4.color,
        grain=grain_layer_result_4.grain,
        roughness=0.560835,
        specularity=0.238753,
        height=-0.003,
    )
    return pf.Material(
        grain_to_shader_result.bsdf, pf.nodes.math.constant((0.0, 0.0, 0.0)), None
    )


def marble_gray_preset(vector: pf.ProcNode[pf.Vector]):
    # Code generated by procfunc v0.18.0-ifg
    grain_layer_vector = pf.nodes.math.vector_scale(vector=vector, scale=1.0 / 1.0)

    grain_layer_base_color = pf.color.hsv_to_rgba((0.2083, 0.0484, 0.248))
    grain_layer_grain_color = pf.color.hsv_to_rgba((0.92, 0.0962, 0.26))
    grain_layer_result = grain_layer(
        vector=grain_layer_vector,
        base_color=grain_layer_base_color,
        grain=0.0,
        layer_count=0.0,
        opacity=1.0,
        grain_type=1.0,
        grain_color=grain_layer_grain_color,
        mix_mode=2.0,
        grain_size=1.5,
        grain_stretch=1.5,
        grain_spread=0.732143,
        random_spread=0.040179,
        grain_smoothness=0.252013,
        grain_rotation=(0.6109, 0.6109, 0.0),
        distortion_strength=33.059998,
        distortion_size=0.8,
        distortion_details=8.0,
        seed=0.0,
        invert=1.0,
    )
    grain_grain_color_3 = pf.color.hsv_to_rgba((0.0889, 0.1252, 0.719))
    grain_layer_result_1 = grain_layer(
        vector=grain_layer_result.vector,
        base_color=grain_layer_result.color,
        grain=grain_layer_result.grain,
        layer_count=grain_layer_result.layer_count,
        opacity=0.214286,
        grain_type=3.0,
        grain_color=grain_grain_color_3,
        mix_mode=1.0,
        grain_size=0.1,
        grain_stretch=3.0,
        grain_spread=0.453795,
        random_spread=0.263393,
        grain_smoothness=0.034807,
        grain_rotation=(0.5236, 0.5236, 0.0),
        distortion_strength=0.32,
        distortion_size=5.0,
        distortion_details=4.0,
        seed=10.2,
        invert=1.0,
    )
    grain_grain_color_2 = pf.color.hsv_to_rgba((0.3248, 0.3679, 0.106))
    grain_layer_result_2 = grain_layer(
        vector=grain_layer_result_1.vector,
        base_color=grain_layer_result_1.color,
        grain=grain_layer_result_1.grain,
        layer_count=grain_layer_result_1.layer_count,
        opacity=0.65625,
        grain_type=1.0,
        grain_color=grain_grain_color_2,
        mix_mode=2.0,
        grain_size=0.93,
        grain_stretch=4.0,
        grain_spread=0.491071,
        random_spread=0.039509,
        grain_smoothness=0.772321,
        grain_rotation=(0.5236, 0.5236, 0.0),
        distortion_strength=1.0,
        distortion_size=0.5,
        distortion_details=6.0,
        seed=0.0,
        invert=1.0,
    )
    grain_grain_color_1 = pf.color.hsv_to_rgba((0.0, 0.0, 0.111))
    grain_layer_result_3 = grain_layer(
        vector=grain_layer_result_2.vector,
        base_color=grain_layer_result_2.color,
        grain=grain_layer_result_2.grain,
        layer_count=grain_layer_result_2.layer_count,
        opacity=0.834821,
        grain_type=3.0,
        grain_color=grain_grain_color_1,
        mix_mode=2.0,
        grain_size=1.0,
        grain_stretch=1.0,
        grain_spread=0.763393,
        random_spread=0.402794,
        grain_smoothness=0.303571,
        grain_rotation=(0.0, 0.0, 0.0),
        distortion_strength=8.2,
        distortion_size=0.5,
        distortion_details=6.0,
        seed=0.06,
        invert=1.0,
    )
    grain_grain_color_0 = pf.color.hsv_to_rgba((0.0463, 0.1607, 0.112))
    grain_layer_result_4 = grain_layer(
        vector=grain_layer_result_3.vector,
        base_color=grain_layer_result_3.color,
        grain=grain_layer_result_3.grain,
        layer_count=grain_layer_result_3.layer_count,
        opacity=0.598214,
        grain_type=3.0,
        grain_color=grain_grain_color_0,
        mix_mode=2.0,
        grain_size=1.0,
        grain_stretch=2.45,
        grain_spread=0.5625,
        random_spread=0.214286,
        grain_smoothness=0.258929,
        grain_rotation=(0.3508, 0.5044, 0.0),
        distortion_strength=0.54,
        distortion_size=0.76,
        distortion_details=6.0,
        seed=7.5,
        invert=1.0,
    )
    grain_to_shader_result = grain_to_shader(
        color=grain_layer_result_4.color,
        grain=grain_layer_result_4.grain,
        roughness=0.194763,
        specularity=0.366071,
        height=0.005,
    )
    return pf.Material(
        grain_to_shader_result.bsdf, pf.nodes.math.constant((0.0, 0.0, 0.0)), None
    )


def marble_gold_preset(vector: pf.ProcNode[pf.Vector]):
    # Code generated by procfunc v0.18.0-ifg
    grain_layer_vector = pf.nodes.math.vector_scale(vector=vector, scale=1.0 / 1.0)

    grain_layer_base_color = pf.color.hsv_to_rgba((0.425, 0.0535, 0.374))
    grain_layer_grain_color = pf.color.hsv_to_rgba((0.1169, 0.972, 1.0))
    grain_layer_result = grain_layer(
        vector=grain_layer_vector,
        base_color=grain_layer_base_color,
        grain=0.0,
        layer_count=0.0,
        opacity=1.0,
        grain_type=3.0,
        grain_color=grain_layer_grain_color,
        mix_mode=2.0,
        grain_size=5.21,
        grain_stretch=1.5,
        grain_spread=0.928571,
        random_spread=0.040179,
        grain_smoothness=0.439513,
        grain_rotation=(0.6109, 0.6109, 0.0),
        distortion_strength=0.5,
        distortion_size=1.0,
        distortion_details=3.0,
        seed=0.0,
        invert=1.0,
    )
    grain_grain_color_3 = pf.color.hsv_to_rgba((0.053, 0.8328, 0.646))
    grain_layer_result_1 = grain_layer(
        vector=grain_layer_result.vector,
        base_color=grain_layer_result.color,
        grain=grain_layer_result.grain,
        layer_count=grain_layer_result.layer_count,
        opacity=1.0,
        grain_type=1.0,
        grain_color=grain_grain_color_3,
        mix_mode=3.0,
        grain_size=2.35,
        grain_stretch=1.0,
        grain_spread=0.754018,
        random_spread=0.0,
        grain_smoothness=0.824986,
        grain_rotation=(0.8971, 0.9058, 0.0),
        distortion_strength=3.1,
        distortion_size=0.2,
        distortion_details=4.0,
        seed=0.0,
        invert=1.0,
    )
    grain_grain_color_2 = pf.color.hsv_to_rgba((0.6202, 0.2, 0.43))
    grain_layer_result_2 = grain_layer(
        vector=grain_layer_result_1.vector,
        base_color=grain_layer_result_1.color,
        grain=grain_layer_result_1.grain,
        layer_count=grain_layer_result_1.layer_count,
        opacity=0.352679,
        grain_type=4.0,
        grain_color=grain_grain_color_2,
        mix_mode=2.0,
        grain_size=1.0,
        grain_stretch=2.0,
        grain_spread=0.05125,
        random_spread=0.039509,
        grain_smoothness=1.0,
        grain_rotation=(0.4852, 0.7487, 0.0),
        distortion_strength=0.5,
        distortion_size=0.5,
        distortion_details=6.0,
        seed=0.0,
        invert=0.0,
    )
    grain_grain_color_1 = pf.color.hsv_to_rgba((0.0509, 0.3655, 0.528))
    grain_layer_result_3 = grain_layer(
        vector=grain_layer_result_2.vector,
        base_color=grain_layer_result_2.color,
        grain=grain_layer_result_2.grain,
        layer_count=grain_layer_result_2.layer_count,
        opacity=1.0,
        grain_type=4.0,
        grain_color=grain_grain_color_1,
        mix_mode=2.0,
        grain_size=2.0,
        grain_stretch=3.0,
        grain_spread=0.23542,
        random_spread=0.27333,
        grain_smoothness=1.0,
        grain_rotation=(0.4712, 0.733, 0.8435),
        distortion_strength=0.5,
        distortion_size=1.0,
        distortion_details=6.0,
        seed=0.06,
        invert=0.0,
    )
    grain_grain_color_0 = pf.color.hsv_to_rgba((0.0485, 0.1717, 0.46))
    grain_layer_result_4 = grain_layer(
        vector=grain_layer_result_3.vector,
        base_color=grain_layer_result_3.color,
        grain=grain_layer_result_3.grain,
        layer_count=grain_layer_result_3.layer_count,
        opacity=1.0,
        grain_type=5.0,
        grain_color=grain_grain_color_0,
        mix_mode=2.0,
        grain_size=6.0,
        grain_stretch=4.0,
        grain_spread=1.0,
        random_spread=0.102679,
        grain_smoothness=0.830357,
        grain_rotation=(0.3508, 0.5044, 0.0),
        distortion_strength=0.3,
        distortion_size=1.0,
        distortion_details=6.0,
        seed=5.1,
        invert=0.0,
    )
    grain_to_shader_result = grain_to_shader(
        color=grain_layer_result_4.color,
        grain=grain_layer_result_4.grain,
        roughness=0.560835,
        specularity=0.238753,
        height=0.0,
    )
    return pf.Material(
        grain_to_shader_result.bsdf, pf.nodes.math.constant((0.0, 0.0, 0.0)), None
    )


def marble_black_spots_preset(vector: pf.ProcNode[pf.Vector]):
    # Code generated by procfunc v0.18.0-ifg
    grain_layer_vector = pf.nodes.math.vector_scale(vector=vector, scale=1.0 / 1.0)

    grain_layer_base_color = pf.color.hsv_to_rgba((0.2222, 0.0423, 0.071))
    grain_layer_grain_color = pf.color.hsv_to_rgba((0.9286, 0.0854, 0.082))
    grain_layer_result = grain_layer(
        vector=grain_layer_vector,
        base_color=grain_layer_base_color,
        grain=0.0,
        layer_count=0.0,
        opacity=1.0,
        grain_type=5.0,
        grain_color=grain_layer_grain_color,
        mix_mode=2.0,
        grain_size=2.0,
        grain_stretch=1.5,
        grain_spread=0.647321,
        random_spread=0.040179,
        grain_smoothness=0.086834,
        grain_rotation=(0.6109, 0.6109, 0.0),
        distortion_strength=0.5,
        distortion_size=0.5,
        distortion_details=8.0,
        seed=0.0,
        invert=1.0,
    )
    grain_grain_color_3 = pf.color.hsv_to_rgba((0.5278, 0.1304, 0.046))
    grain_layer_result_1 = grain_layer(
        vector=grain_layer_result.vector,
        base_color=grain_layer_result.color,
        grain=grain_layer_result.grain,
        layer_count=grain_layer_result.layer_count,
        opacity=1.0,
        grain_type=3.0,
        grain_color=grain_grain_color_3,
        mix_mode=1.0,
        grain_size=1.0,
        grain_stretch=1.0,
        grain_spread=0.695983,
        random_spread=0.263393,
        grain_smoothness=0.034807,
        grain_rotation=(0.8971, 0.9058, 0.0),
        distortion_strength=0.0,
        distortion_size=0.5,
        distortion_details=4.0,
        seed=10.2,
        invert=1.0,
    )
    grain_grain_color_2 = pf.color.hsv_to_rgba((0.6667, 0.0909, 0.011))
    grain_layer_result_2 = grain_layer(
        vector=grain_layer_result_1.vector,
        base_color=grain_layer_result_1.color,
        grain=grain_layer_result_1.grain,
        layer_count=grain_layer_result_1.layer_count,
        opacity=1.0,
        grain_type=3.0,
        grain_color=grain_grain_color_2,
        mix_mode=1.0,
        grain_size=1.0,
        grain_stretch=1.0,
        grain_spread=0.569107,
        random_spread=0.039509,
        grain_smoothness=0.0,
        grain_rotation=(0.4852, 0.7487, 0.0),
        distortion_strength=0.1,
        distortion_size=0.5,
        distortion_details=6.0,
        seed=0.0,
        invert=1.0,
    )
    grain_grain_color_1 = pf.color.hsv_to_rgba((0.0, 0.0, 0.435))
    grain_layer_result_3 = grain_layer(
        vector=grain_layer_result_2.vector,
        base_color=grain_layer_result_2.color,
        grain=grain_layer_result_2.grain,
        layer_count=grain_layer_result_2.layer_count,
        opacity=1.0,
        grain_type=1.0,
        grain_color=grain_grain_color_1,
        mix_mode=2.0,
        grain_size=1.0,
        grain_stretch=1.0,
        grain_spread=0.660714,
        random_spread=0.27333,
        grain_smoothness=0.232143,
        grain_rotation=(0.0, 0.0, 0.0),
        distortion_strength=26.299999,
        distortion_size=0.5,
        distortion_details=6.0,
        seed=0.06,
        invert=0.0,
    )
    grain_grain_color_0 = pf.color.hsv_to_rgba((0.0463, 0.1607, 0.112))
    grain_layer_result_4 = grain_layer(
        vector=grain_layer_result_3.vector,
        base_color=grain_layer_result_3.color,
        grain=grain_layer_result_3.grain,
        layer_count=grain_layer_result_3.layer_count,
        opacity=1.0,
        grain_type=3.0,
        grain_color=grain_grain_color_0,
        mix_mode=2.0,
        grain_size=1.0,
        grain_stretch=1.0,
        grain_spread=0.486607,
        random_spread=0.102679,
        grain_smoothness=0.071429,
        grain_rotation=(0.3508, 0.5044, 0.0),
        distortion_strength=0.1,
        distortion_size=1.0,
        distortion_details=6.0,
        seed=7.5,
        invert=1.0,
    )
    grain_to_shader_result = grain_to_shader(
        color=grain_layer_result_4.color,
        grain=grain_layer_result_4.grain,
        roughness=0.11887,
        specularity=0.5,
        height=0.005,
    )
    return pf.Material(
        grain_to_shader_result.bsdf, grain_to_shader_result.displacement, None
    )


def marble_black_preset(vector: pf.ProcNode[pf.Vector]):
    # Code generated by procfunc v0.18.0-ifg

    grain_layer_vector = pf.nodes.math.vector_scale(vector=vector, scale=1.0 / 1.0)

    grain_layer_base_color = pf.color.hsv_to_rgba((0.0, 0.0, 0.016))
    grain_layer_grain_color = pf.color.hsv_to_rgba((0.0, 0.0, 0.387))
    grain_layer_result = grain_layer(
        vector=grain_layer_vector,
        base_color=grain_layer_base_color,
        grain=0.0,
        layer_count=0.0,
        opacity=1.0,
        grain_type=1.0,
        grain_color=grain_layer_grain_color,
        mix_mode=2.0,
        grain_size=2.22,
        grain_stretch=3.8,
        grain_spread=0.759013,
        random_spread=0.0,
        grain_smoothness=0.64487,
        grain_rotation=(0.6109, 0.6109, 0.0),
        distortion_strength=2.29,
        distortion_size=0.44,
        distortion_details=8.0,
        seed=0.0,
        invert=0.0,
    )
    grain_grain_color_3 = pf.color.hsv_to_rgba((0.0, 0.0, 0.113))
    grain_layer_result_1 = grain_layer(
        vector=grain_layer_result.vector,
        base_color=grain_layer_result.color,
        grain=grain_layer_result.grain,
        layer_count=grain_layer_result.layer_count,
        opacity=0.508929,
        grain_type=3.0,
        grain_color=grain_grain_color_3,
        mix_mode=1.0,
        grain_size=0.89,
        grain_stretch=3.02,
        grain_spread=0.745536,
        random_spread=0.0,
        grain_smoothness=0.678571,
        grain_rotation=(0.8971, 0.9058, 0.0),
        distortion_strength=4.42,
        distortion_size=0.2,
        distortion_details=4.0,
        seed=0.0,
        invert=1.0,
    )
    grain_grain_color_2 = pf.color.hsv_to_rgba((0.0, 0.0, 0.0))
    grain_layer_result_2 = grain_layer(
        vector=grain_layer_result_1.vector,
        base_color=grain_layer_result_1.color,
        grain=grain_layer_result_1.grain,
        layer_count=grain_layer_result_1.layer_count,
        opacity=0.59375,
        grain_type=1.0,
        grain_color=grain_grain_color_2,
        mix_mode=2.0,
        grain_size=1.5,
        grain_stretch=4.2,
        grain_spread=0.636071,
        random_spread=0.0,
        grain_smoothness=0.347594,
        grain_rotation=(-0.7924, -0.946, 0.0),
        distortion_strength=35.299999,
        distortion_size=1.0,
        distortion_details=8.0,
        seed=0.0,
        invert=0.0,
    )
    grain_grain_color_1 = pf.color.hsv_to_rgba((0.0, 0.0, 1.0))
    grain_layer_result_3 = grain_layer(
        vector=grain_layer_result_2.vector,
        base_color=grain_layer_result_2.color,
        grain=grain_layer_result_2.grain,
        layer_count=grain_layer_result_2.layer_count,
        opacity=0.089286,
        grain_type=4.0,
        grain_color=grain_grain_color_1,
        mix_mode=1.0,
        grain_size=4.0,
        grain_stretch=5.0,
        grain_spread=0.130446,
        random_spread=0.236611,
        grain_smoothness=1.0,
        grain_rotation=(-0.7348, -0.473, 0.0),
        distortion_strength=2.0,
        distortion_size=1.0,
        distortion_details=8.0,
        seed=8.959999,
        invert=0.0,
    )
    grain_grain_color_0 = pf.color.hsv_to_rgba((0.0, 0.0, 1.0))
    grain_layer_result_4 = grain_layer(
        vector=grain_layer_result_3.vector,
        base_color=grain_layer_result_3.color,
        grain=grain_layer_result_3.grain,
        layer_count=grain_layer_result_3.layer_count,
        opacity=0.0,
        grain_type=2.0,
        grain_color=grain_grain_color_0,
        mix_mode=1.0,
        grain_size=4.0,
        grain_stretch=1.0,
        grain_spread=0.115027,
        random_spread=0.122192,
        grain_smoothness=0.939572,
        grain_rotation=(0.6981, 0.6981, 0.0),
        distortion_strength=0.0,
        distortion_size=0.5,
        distortion_details=8.0,
        seed=0.0,
        invert=0.0,
    )
    grain_to_shader_result = grain_to_shader(
        color=grain_layer_result_4.color,
        grain=grain_layer_result_4.grain,
        roughness=0.623335,
        specularity=0.118217,
        height=0.0,
    )
    return pf.Material(
        grain_to_shader_result.bsdf, pf.nodes.math.constant((0.0, 0.0, 0.0)), None
    )


def marble_presets(rng: pf.RNG, vector: t.SocketOrVal[pf.Vector]):
    func = pf.control.choice(
        rng,
        [
            (marble_black_preset, 1.0),
            (marble_black_spots_preset, 1.0),
            (marble_gold_preset, 1.0),
            (marble_gray_preset, 1.0),
            (marble_navy_preset, 1.0),
            (marble_orange_preset, 1.0),
            (marble_white_preset, 1.0),
            (marble_white_striped_preset, 1.0),
            (marble_yellow_preset, 1.0),
        ],
    )
    return func(vector=vector)


def grain_to_shader_rand(
    rng: pf.RNG,
    color: t.SocketOrVal[pf.Color],
    grain: t.SocketOrVal[float],
):
    # Code generated by procfunc v0.18.0-ifg
    roughness = pf.random.uniform(rng, 0.11887, 0.623335)

    specularity = pf.random.uniform(rng, 0.118217, 0.5)
    height = pf.random.clip_gaussian(rng, 0.0, 0.002, -0.005, 0.005)
    grain_to_shader_result = grain_to_shader(
        color=color,
        grain=grain,
        roughness=roughness,
        specularity=specularity,
        height=height,
    )

    return grain_to_shader_result


def grain_layer_color_rand(rng: pf.RNG, base_color: pf.Color) -> pf.Color:
    rng_h, rng_s, rng_v = rng.spawn(3)
    hue_offset = pf.random.clip_gaussian(rng_h, 0, 0.04, -0.2, 0.2)
    h = (base_color.h + hue_offset) % 1.0
    s = pf.random.clip_gaussian(rng_s, base_color.s, 0.07, 0.0, 0.95)
    v = pf.random.clip_gaussian(rng_v, base_color.v, 0.2, 0.0, 0.95)
    return pf.color.hsv_color(hue=h, saturation=s, value=v)


def grain_layer_rand(
    rng: pf.RNG,
    vector: t.SocketOrVal[pf.Vector],
    base_color: t.SocketOrVal[pf.Color],
    base_layer_color: pf.Color,
    base_rotation: pf.Vector,
):
    grain = 0.0
    layer_count = 0.0

    rng_color, rng_draws, rng_invert = rng.spawn(3)

    grain_color = grain_layer_color_rand(rng_color, base_layer_color)
    rotation_offset = pf.Vector(
        (
            pf.random.clip_gaussian(rng_draws, 0.0, 0.06, -0.2, 0.2),
            pf.random.clip_gaussian(rng_draws, 0.0, 0.06, -0.2, 0.2),
            0.0,
        )
    )
    grain_rotation = base_rotation + rotation_offset

    opacity = pf.random.uniform(rng_draws, 0.526786, 1.0)
    grain_type = pf.random.randint(rng_draws, 1, 5 + 1)
    mix_mode = pf.random.randint(rng_draws, 1, 3 + 1)
    grain_size = pf.random.uniform(rng_draws, 0.34, 5.21)
    grain_stretch = pf.random.uniform(rng_draws, 1.0, 30.099998)
    grain_spread = pf.random.uniform(rng_draws, 0.647321, 0.928571)
    random_spread = pf.random.uniform(rng_draws, 0.0, 0.142857)
    grain_smoothness = pf.random.uniform(rng_draws, 0.086834, 0.64487)
    distortion_strength = pf.random.uniform(rng_draws, 0.42, 33.059998)
    distortion_size = pf.random.uniform(rng_draws, 0.3, 1.0)
    distortion_details = pf.random.uniform(rng_draws, 0.0, 8.0)
    seed = pf.random.uniform(rng_draws, 0.0, 10.0)
    invert = pf.control.choice(rng_invert, [(0.0, 0.5), (1.0, 0.5)])
    grain_layer_result = grain_layer(
        vector=vector,
        base_color=base_color,
        grain=grain,
        layer_count=layer_count,
        opacity=opacity,
        grain_type=grain_type,
        grain_color=grain_color,
        mix_mode=mix_mode,
        grain_size=grain_size,
        grain_stretch=grain_stretch,
        grain_spread=grain_spread,
        random_spread=random_spread,
        grain_smoothness=grain_smoothness,
        grain_rotation=grain_rotation,
        distortion_strength=distortion_strength,
        distortion_size=distortion_size,
        distortion_details=distortion_details,
        seed=seed,
        invert=invert,
    )

    return grain_layer_result


def marble_rand(
    rng: pf.RNG,
    vector: t.SocketOrVal[pf.Vector],
):
    base_h_fac = pf.random.uniform(rng, 0.0, 1.0)
    base_h = 0.5882 * base_h_fac**2

    base_s_fac = pf.random.uniform(rng, 0.0, 1.0)
    base_s = 0.7 * (1 - base_h_fac) * (base_s_fac**2)  # less saturated for less red

    base_v = (1 - base_s_fac) * pf.random.uniform(rng, 0.0, 1.0)  # more sat -> less val
    base_color = pf.color.hsv_color((base_h, base_s, base_v))

    layer_h = pf.random.clip_gaussian(rng, 0.2138, 0.2700, 0.0, 0.9286)
    layer_s = pf.random.clip_gaussian(rng, 0.2871, 0.3523, 0.0, 0.9744)
    layer_v = pf.random.clip_gaussian(rng, 0.3779, 0.3125, 0.0, 1.0)
    layer_color = pf.color.hsv_color((layer_h, layer_s, layer_v))

    rotation = pf.Vector(
        (
            pf.random.uniform(rng, -0.7854, 0.7854),
            pf.random.uniform(rng, -0.7854, 0.7854),
            0.0,
        )
    )

    rng_g1, rng_g2, rng_g3, rng_shader = rng.spawn(4)

    # 5 layers flattens to ~1168 Cycles nodes per material and overflows the
    # SVM stack on CUDA/OPTIX. 3 keeps us comfortably under the 1000-node ceiling.
    g = grain_layer_rand(rng_g1, vector, base_color, layer_color, rotation)
    g = grain_layer_rand(rng_g2, g.vector, g.color, layer_color, rotation)
    g = grain_layer_rand(rng_g3, g.vector, g.color, layer_color, rotation)
    shader = grain_to_shader_rand(rng_shader, g.color, g.grain)
    return pf.Material(shader.bsdf, shader.displacement, None)
