extend = "../../pyproject.toml"

[lint.flake8-tidy-imports.banned-api]
"infinigen".msg = "infinigen_v2 cannot depend on infinigen"

[lint]
extend-select = [
    "INP001", # no implicit namespace packages
    "B", # common mis-steps https://docs.astral.sh/ruff/rules/#flake8-bugbear-b
    "C901", # too complex function
    "TID251", # custom banned imports
    "T10", # dont leave debug statements
]

extend-ignore = ["B008"]

[lint.mccabe]
max-complexity = 15