# Copyright (C) 2026, Princeton University.
# This source code is licensed under the BSD 3-Clause license found in the LICENSE file in the root directory of this source tree.

# Authors:
# - Yiming Zuo: original Infinigen v1 nodegroup (https://github.com/princeton-vl/infinigen/blob/05a09759fe9478595a3323ec2d6e26ce3513223f/infinigen/assets/materials/tiles/brick.py)
# - Alexander Raistrick: transpile to procfunc/v2

from typing import NamedTuple

import procfunc as pf
from procfunc.nodes import types as t

__all__ = [
    "BrickSelectorResult",
    "brick_selector",
    "brick_selector_rand",
]


class BrickSelectorResult(NamedTuple):
    selection: pf.ProcNode[float]
    inverted_selection: pf.ProcNode[float]


@pf.nodes.node_function
def brick_selector(
    brick_id: t.SocketOrVal[pf.Vector] = (0.0, 0.0, 0.0),
    skip_x: t.SocketOrVal[float] = 0.5,
    offset_x: t.SocketOrVal[float] = 0.0,
    skip_y: t.SocketOrVal[float] = 0.5,
    offset_y: t.SocketOrVal[float] = 0.0,
    shift: t.SocketOrVal[float] = 0.5,
    bias: t.SocketOrVal[float] = 0.0,
) -> BrickSelectorResult:
    # Code generated by procfunc v0.3.0

    selection_15 = pf.nodes.math.clamp(bias + 1.0)
    selection_vector_vector = pf.nodes.math.combine_xyz(x=offset_x, y=offset_y)
    selection_vector = pf.nodes.math.vector_floor(selection_vector_vector)
    selection_14 = brick_id - selection_vector
    selection_13 = pf.nodes.math.floor(shift * 2.0)
    selection_12 = selection_14.y * (selection_13 / 2.0)
    selection_11 = pf.nodes.math.floor(skip_x)
    selection_10 = pf.nodes.math.floor_mod(
        a=selection_14.x - selection_12, b=selection_11 + 1.0
    )
    selection_9 = selection_10 - selection_11
    selection_8 = selection_9 > 0.0
    selection_7 = pf.nodes.math.maximum(a=bias, b=0.0)
    selection_6 = 1.0 - selection_7
    selection_5 = 1.0 - selection_8
    selection_4 = (selection_15 * selection_8) + (selection_6 * selection_5)
    selection_3 = 1.0 - (selection_9 < 0.0)
    selection_2 = pf.nodes.math.floor(skip_y)
    selection_1 = pf.nodes.math.floor_mod(a=selection_14.y, b=selection_2 + 1.0)
    selection = (selection_4 * selection_3) * (selection_1 < 1.0)

    inverted_selection = 1.0 - selection
    return BrickSelectorResult(
        selection=selection,
        inverted_selection=inverted_selection,
    )


def brick_selector_rand(
    rng: pf.RNG,
    brick_id: t.SocketOrVal[pf.Vector],
):
    # Code generated by procfbunc v0.3.0

    rng, r2 = rng.spawn(2)

    skip_x = pf.random.randint(rng, 0, 2)
    offset_x = 0.0
    skip_y = pf.random.randint(rng, 0, 3)
    offset_y = 0.0
    shift = pf.control.choice(rng, [(0.0, 2.0), (0.5, 1.0)])
    bias = 1.0

    skip_choice = pf.control.choice(
        r2,
        [
            ((skip_x, 0.0), 1.0),
            ((0.0, skip_y), 1.0),
            ((skip_x, skip_y), 2.0),
        ],
    )
    skip_x, skip_y = skip_choice[0], skip_choice[1]

    brick_selector_result = brick_selector(
        brick_id=brick_id,
        skip_x=skip_x,
        offset_x=offset_x,
        skip_y=skip_y,
        offset_y=offset_y,
        shift=shift,
        bias=bias,
    )
    return brick_selector_result
