# Copyright (C) 2026, Princeton University.
# This source code is licensed under the BSD 3-Clause license found in the LICENSE file in the root directory of this source tree.

# Authors:
# - Meenal Parakh: original Infinigen v1 nodegroup (https://github.com/princeton-vl/infinigen/blob/05a09759fe9478595a3323ec2d6e26ce3513223f/infinigen/assets/materials/wear_tear/scratches.py)
# - Meenal Parakh: initial v2 version
# - Alexander Raistrick: transpile new nodegroup for v2

from typing import NamedTuple

import numpy as np
import procfunc as pf
from procfunc.nodes import types as t

from infinigen2.shaders.util.coord import coord_warp

__all__ = [
    "ScratchesLinearResult",
    "ScratchesMaskResult",
    "ScratchesRandomResult",
    "scratches_brushed_mask_preset",
    "scratches_deep_dirty_mask_preset",
    "scratches_dense_mask_preset",
    "scratches_layer_rand",
    "scratches_light_varnish_mask_preset",
    "scratches_linear",
    "scratches_linear_rand",
    "scratches_mask_rand",
    "scratches_random",
    "scratches_random_rand",
    "scratches_shallow_mask_preset",
]

_LayerParam = t.SocketOrVal[float] | t.SocketOrVal[pf.Vector]


class ScratchesMaskResult(NamedTuple):
    mask: pf.ProcNode[float]


class ScratchesRandomResult(NamedTuple):
    vector: t.SocketOrVal[pf.Vector]
    shader: pf.ProcNode[pf.Shader]
    displacement: pf.ProcNode[pf.Vector]
    scratch_shader: t.SocketOrVal[pf.Shader]
    scratch_texture: pf.ProcNode[float]


@pf.nodes.node_function
def scratches_random(
    base_shader: t.SocketOrVal[pf.Shader],
    scratch_shader: t.SocketOrVal[pf.Shader],
    vector: t.SocketOrVal[pf.Vector] = (0.0, 0.0, 0.0),
    base_displacement: t.SocketOrVal[pf.Vector] = (0.0, 0.0, 0.0),
    use_scratch_shader: t.SocketOrVal[float] = 0.0,
    random_seed: t.SocketOrVal[float] = 0.0,
    scratch_rotation: t.SocketOrVal[pf.Vector] = (0.0, 0.0, 0.0),
    scratch_spacing: t.SocketOrVal[float] = 0.1,
    scratch_thickness: t.SocketOrVal[float] = 0.001,
    scratch_depth: t.SocketOrVal[float] = 0.001,
    distortion_size: t.SocketOrVal[float] = 0.5,
    distortion_strength: t.SocketOrVal[float] = 0.5,
    distortion_detail: t.SocketOrVal[float] = 2.0,
) -> ScratchesRandomResult:
    # Code generated by procfunc v0.30.2
    coord_warp_result = coord_warp(
        vector=vector,
        size=scratch_spacing * distortion_size,
        strength=distortion_strength,
        detail=distortion_detail,
        phase=random_seed,
    )

    scratch_texture_0_vector_a = pf.nodes.math.vector_rotate_euler(
        vector=coord_warp_result.vector,
        rotation=scratch_rotation,
    )

    voronoi_distance_scale = 1.0 / scratch_spacing

    voronoi = pf.nodes.texture.voronoi(
        vector=scratch_texture_0_vector_a,
        scale=voronoi_distance_scale,
        normalize=True,
        voronoi_dimensions="4D",
        w=random_seed,
    )
    white_noise = pf.nodes.texture.white_noise(
        noise_dimensions="1D",
        w=voronoi.color.astype(dtype=pf.Vector).z,
    )

    scratch_texture_0_rotation = pf.nodes.math.vector_scale(
        vector=white_noise.color.astype(dtype=pf.Vector),
        scale=6.283185,
    )

    scratch_texture_1 = pf.nodes.math.vector_rotate_euler(
        vector=scratch_texture_0_vector_a - voronoi.position,
        rotation=scratch_texture_0_rotation,
    )
    scratch_texture_base_value = pf.nodes.math.absolute(scratch_texture_1.z)
    voronoi_distance = pf.nodes.texture.voronoi_distance(
        vector=scratch_texture_0_vector_a,
        scale=voronoi_distance_scale,
        normalize=True,
        voronoi_dimensions="4D",
        w=random_seed,
    )

    scratch_texture_base_from_max_0 = (voronoi_distance * 2.0) ** 0.5

    scratch_texture_base = pf.nodes.math.map_range(
        value=scratch_texture_base_value,
        from_max=scratch_texture_base_from_max_0 * scratch_thickness,
        from_min=-1e-05,
        to_max=0.0,
        to_min=1.0,
    )
    scratch_texture = scratch_texture_base**0.5
    mix_shader = pf.nodes.shader.mix_shader(
        factor=use_scratch_shader * scratch_texture,
        a=base_shader,
        b=scratch_shader,
    )

    displacement_1 = pf.nodes.shader.displacement(
        height=scratch_texture,
        midlevel=0.0,
        scale=scratch_depth,
        normal=(0.0, 0.0, 0.0),
    )

    displacement = base_displacement - displacement_1
    return ScratchesRandomResult(
        vector, mix_shader, displacement, scratch_shader, scratch_texture
    )


def scratches_random_rand(
    rng: pf.RNG,
    vector: t.SocketOrVal[pf.Vector],
    base_shader: t.SocketOrVal[pf.Shader],
    base_displacement: t.SocketOrVal[pf.Vector],
    scratch_shader: t.SocketOrVal[pf.Shader],
    scale: float | None = None,
) -> ScratchesRandomResult:
    # Code generated by procfunc v0.30.2
    if scale is None:
        scale = 1.0
    use_scratch_shader = pf.random.uniform(rng, 0.4, 1.0)
    random_seed = pf.random.uniform(rng, -11.2, 0.0)
    scratch_rotation = (0.0, 0.0, 0.0)
    scratch_spacing = pf.random.uniform(rng, 0.02, 0.1)
    scratch_thickness = pf.random.uniform(rng, 0.0001, 0.001) * scale
    # depth is independent of size scale so thinned scratches still carve
    scratch_depth = pf.random.uniform(rng, 0.0, 0.0015)
    distortion_size = 0.5
    distortion_strength = pf.random.uniform(rng, 0.2, 0.5)
    distortion_detail = pf.random.uniform(rng, 0.0, 1.0)
    return scratches_random(
        vector=vector,
        base_shader=base_shader,
        base_displacement=base_displacement,
        use_scratch_shader=use_scratch_shader,
        scratch_shader=scratch_shader,
        random_seed=random_seed,
        scratch_rotation=scratch_rotation,
        scratch_spacing=scratch_spacing,
        scratch_thickness=scratch_thickness,
        scratch_depth=scratch_depth,
        distortion_size=distortion_size,
        distortion_strength=distortion_strength,
        distortion_detail=distortion_detail,
    )


class ScratchesLinearResult(NamedTuple):
    vector: t.SocketOrVal[pf.Vector]
    shader: pf.ProcNode[pf.Shader]
    displacement: pf.ProcNode[pf.Vector]
    scratch_shader: t.SocketOrVal[pf.Shader]
    scratch_texture: pf.ProcNode[float]


@pf.nodes.node_function
def scratches_linear(
    base_shader: t.SocketOrVal[pf.Shader],
    scratch_shader: t.SocketOrVal[pf.Shader],
    vector: t.SocketOrVal[pf.Vector] = (0.0, 0.0, 0.0),
    base_displacement: t.SocketOrVal[pf.Vector] = (0.0, 0.0, 0.0),
    use_scratch_shader: t.SocketOrVal[float] = 0.0,
    random_seed: t.SocketOrVal[float] = 0.0,
    scratch_rotation: t.SocketOrVal[pf.Vector] = (0.0, 0.0, 0.0),
    scratch_spacing: t.SocketOrVal[float] = 0.1,
    scratch_spread: t.SocketOrVal[float] = 0.25,
    scratch_thickness: t.SocketOrVal[float] = 0.001,
    thickness_variation: t.SocketOrVal[float] = 0.0,
    scratch_depth: t.SocketOrVal[float] = 0.001,
    noise_size: t.SocketOrVal[float] = 1.0,
    distortion_size: t.SocketOrVal[float] = 1.0,
    distortion_stretch: t.SocketOrVal[float] = 3.0,
    distortion_strength: t.SocketOrVal[float] = 0.1,
    distortion_detail: t.SocketOrVal[float] = 4.0,
) -> ScratchesLinearResult:
    # Code generated by procfunc v0.30.2
    scratch_texture_b_a = pf.nodes.math.vector_rotate_euler(
        vector=vector, rotation=scratch_rotation
    )

    noise_vector_b_x = 1.0 / distortion_stretch

    noise_vector_b = pf.nodes.math.combine_xyz(
        x=noise_vector_b_x, y=noise_vector_b_x, z=1.0
    )
    noise_vector = scratch_texture_b_a * noise_vector_b
    scratch_texture_b_1 = scratch_spacing * distortion_size

    noise_scale = 1.0 / scratch_texture_b_1

    noise = pf.nodes.texture.noise(
        vector=noise_vector,
        scale=noise_scale,
        detail=distortion_detail,
        noise_dimensions="4D",
        w=random_seed,
    )
    noise_1_w = scratch_spacing * 1.5
    noise_1 = pf.nodes.texture.noise(
        vector=noise_vector,
        scale=noise_scale,
        detail=distortion_detail,
        noise_dimensions="4D",
        w=random_seed + noise_1_w,
    )
    noise_2_w = scratch_spacing * 3.0
    noise_2 = pf.nodes.texture.noise(
        vector=noise_vector,
        scale=noise_scale,
        detail=distortion_detail,
        noise_dimensions="4D",
        w=random_seed + noise_2_w,
    )
    scratch_texture_a_0 = pf.nodes.math.combine_xyz(
        x=noise.fac, y=noise_1.fac, z=noise_2.fac
    )

    scratch_texture_b_b_0 = pf.nodes.math.vector_scale(
        vector=scratch_texture_a_0 - (0.5, 0.5, 0.5),
        scale=distortion_strength * scratch_texture_b_1,
    )
    scratch_texture_b_0 = scratch_texture_b_a + scratch_texture_b_b_0
    scratch_texture_value_value_a = random_seed + scratch_texture_b_0.z
    # Original blend used 1D voronoi (vector socket disabled); procfunc requires
    # a nonzero vector arg and rejects it under 1D, so use 4D with a constant
    # vector — visually equivalent to 1D since only w varies per scratch line.
    voronoi = pf.nodes.texture.voronoi(
        vector=(1.0, 1.0, 1.0),
        scale=1.0 / scratch_spacing,
        normalize=True,
        voronoi_dimensions="4D",
        w=scratch_texture_value_value_a,
    )

    scratch_texture_value = pf.nodes.math.absolute(
        scratch_texture_value_value_a - voronoi.w
    )

    noise_3_vector_x = 1.0 / noise_size

    noise_3_vector = pf.nodes.math.combine_xyz(
        x=noise_3_vector_x, y=noise_3_vector_x, z=1.0
    )
    noise_3 = pf.nodes.texture.noise(
        vector=vector * noise_3_vector,
        scale=1.0 / scratch_spacing,
        detail=6.0,
        noise_dimensions="4D",
        w=voronoi.color.astype(dtype=pf.Vector).z + random_seed,
    )
    scratch_texture_from_max_from_min_1 = pf.nodes.math.constant(0.1)

    scratch_texture_from_max_from_min_0 = pf.nodes.math.mix(
        a=0.25 - scratch_texture_from_max_from_min_1,
        b=0.75 + scratch_texture_from_max_from_min_1,
        factor=scratch_spread,
    )
    scratch_texture_from_max_to_min_0 = pf.nodes.math.mix(
        a=1.0,
        b=voronoi.color.astype(dtype=pf.Vector).y,
        factor=thickness_variation,
    )
    scratch_texture_from_max = pf.nodes.math.map_range(
        value=noise_3.fac,
        from_max=scratch_texture_from_max_from_min_0
        + scratch_texture_from_max_from_min_1,
        from_min=scratch_texture_from_max_from_min_0
        - scratch_texture_from_max_from_min_1,
        to_max=0.0,
        to_min=scratch_texture_from_max_to_min_0 * scratch_thickness,
    )
    scratch_texture = pf.nodes.math.map_range(
        value=scratch_texture_value,
        from_max=scratch_texture_from_max,
        from_min=-0.0001,
        to_max=0.0,
        to_min=1.0,
    )
    shader_factor_0 = scratch_texture**0.5

    mix_shader = pf.nodes.shader.mix_shader(
        factor=use_scratch_shader * shader_factor_0,
        a=base_shader,
        b=scratch_shader,
    )

    displacement_1 = pf.nodes.shader.displacement(
        height=scratch_texture,
        midlevel=0.0,
        scale=scratch_depth,
        normal=(0.0, 0.0, 0.0),
    )

    displacement = base_displacement - displacement_1
    return ScratchesLinearResult(
        vector, mix_shader, displacement, scratch_shader, scratch_texture
    )


def scratches_linear_rand(
    rng: pf.RNG,
    vector: t.SocketOrVal[pf.Vector],
    base_shader: t.SocketOrVal[pf.Shader],
    base_displacement: t.SocketOrVal[pf.Vector],
    scratch_shader: t.SocketOrVal[pf.Shader],
    scale: float | None = None,
) -> ScratchesLinearResult:
    # Code generated by procfunc v0.30.2
    if scale is None:
        scale = 1.0
    use_scratch_shader = pf.random.uniform(rng, 0.0, 1.0)
    random_seed = pf.random.uniform(rng, 0.0, 12.4)
    scratch_rotation = pf.random.uniform(
        rng,
        np.array([0.0, 0.275762, 0.0]),
        np.array([1.570796, 0.539307, 0.0]),
    )
    scratch_spacing = pf.random.uniform(rng, 0.002, 0.07)
    scratch_spread = pf.random.uniform(rng, 0.357529, 0.401685)
    scratch_thickness = pf.random.uniform(rng, 0.0001, 0.0015) * scale
    thickness_variation = pf.random.uniform(rng, 0.0, 0.413127)
    # depth is independent of size scale so thinned scratches still carve
    scratch_depth = pf.random.uniform(rng, 0.0, 0.0015)
    noise_size = pf.random.uniform(rng, 4.0, 24.0)
    distortion_size = pf.random.uniform(rng, 2.31, 3.17)
    distortion_stretch = pf.random.uniform(rng, 2.6, 3.0)
    distortion_strength = pf.random.uniform(rng, 0.83, 1.0)
    distortion_detail = pf.random.uniform(rng, 1.0, 6.7)
    return scratches_linear(
        vector=vector,
        base_shader=base_shader,
        base_displacement=base_displacement,
        use_scratch_shader=use_scratch_shader,
        scratch_shader=scratch_shader,
        random_seed=random_seed,
        scratch_rotation=scratch_rotation,
        scratch_spacing=scratch_spacing,
        scratch_spread=scratch_spread,
        scratch_thickness=scratch_thickness,
        thickness_variation=thickness_variation,
        scratch_depth=scratch_depth,
        noise_size=noise_size,
        distortion_size=distortion_size,
        distortion_stretch=distortion_stretch,
        distortion_strength=distortion_strength,
        distortion_detail=distortion_detail,
    )


def _dummy_shader() -> pf.ProcNode[pf.Shader]:
    return pf.nodes.shader.diffuse_bsdf(
        color=pf.Color((0.0, 0.0, 0.0)), normal=(0.0, 0.0, 0.0)
    )


def scratches_layer_rand(
    rng: pf.RNG,
    vector: t.SocketOrVal[pf.Vector],
    base_shader: t.SocketOrVal[pf.Shader],
    base_displacement: t.SocketOrVal[pf.Vector],
    scratch_shader: t.SocketOrVal[pf.Shader],
    scale: float | None = None,
):
    """One scratch layer: pick the linear or random pattern and sample its
    parameters fresh over the given base shader/displacement."""
    rng_choice, rng_func = rng.spawn(2)
    func = pf.control.choice(
        rng_choice,
        [
            (scratches_random_rand, 1.0),
            (scratches_linear_rand, 1.5),
        ],
    )
    return func(rng_func, vector, base_shader, base_displacement, scratch_shader, scale)


def scratches_mask_rand(
    rng: pf.RNG,
    vector: t.SocketOrVal[pf.Vector],
) -> ScratchesMaskResult:
    """Raw scratch texture as a 0-1 mask: stack 1-3 independently sampled
    linear/random layers and keep their max."""
    base_shader = _dummy_shader()
    scratch_shader = _dummy_shader()
    base_displacement: t.SocketOrVal[pf.Vector] = (0.0, 0.0, 0.0)
    n_layers = pf.random.randint(rng, 1, 4)
    mask = pf.nodes.math.constant(0.0)
    for _ in range(n_layers):
        result = scratches_layer_rand(
            rng, vector, base_shader, base_displacement, scratch_shader
        )
        mask = pf.nodes.math.maximum(a=mask, b=result.scratch_texture)
    return ScratchesMaskResult(mask=mask)


def _random_texture(
    vector: t.SocketOrVal[pf.Vector], **params: _LayerParam
) -> pf.ProcNode[float]:
    shader = _dummy_shader()
    result = scratches_random(
        vector=vector, base_shader=shader, scratch_shader=shader, **params
    )
    return result.scratch_texture


def _linear_texture(
    vector: t.SocketOrVal[pf.Vector], **params: _LayerParam
) -> pf.ProcNode[float]:
    shader = _dummy_shader()
    result = scratches_linear(
        vector=vector, base_shader=shader, scratch_shader=shader, **params
    )
    return result.scratch_texture


def _max_layers(*layers: pf.ProcNode[float]) -> pf.ProcNode[float]:
    mask = layers[0]
    for layer in layers[1:]:
        mask = pf.nodes.math.maximum(a=mask, b=layer)
    return mask


def scratches_brushed_mask_preset(
    vector: t.SocketOrVal[pf.Vector],
) -> pf.ProcNode[float]:
    fine_a = _random_texture(
        vector,
        scratch_spacing=0.02,
        scratch_thickness=1e-04,
        distortion_strength=0.2,
        distortion_detail=0.0,
    )
    fine_b = _random_texture(
        vector,
        random_seed=31.4,
        scratch_spacing=0.02,
        scratch_thickness=1e-04,
        distortion_strength=0.2,
        distortion_detail=0.0,
    )
    hairline = _linear_texture(
        vector,
        scratch_rotation=(0.0, 0.275762, 0.0),
        scratch_spacing=0.002,
        scratch_spread=0.40168542,
        scratch_thickness=1e-04,
        noise_size=24.0,
        distortion_size=3.0,
        distortion_strength=1.0,
        distortion_detail=1.0,
    )
    grain_a = _linear_texture(
        vector,
        scratch_rotation=(0.0, 0.275762, 0.0),
        scratch_spacing=0.012,
        scratch_spread=0.3792135,
        scratch_thickness=0.0002,
        thickness_variation=0.48876405,
        noise_size=4.0,
        distortion_size=12.0,
        distortion_strength=0.89,
        distortion_detail=5.9300003,
    )
    grain_b = _linear_texture(
        vector,
        random_seed=15.299999,
        scratch_rotation=(0.0, 0.3595378, 0.0),
        scratch_spacing=0.012,
        scratch_spread=0.34134832,
        scratch_thickness=0.0002,
        thickness_variation=0.4494382,
        noise_size=4.0,
        distortion_size=11.57,
        distortion_strength=1.23,
        distortion_detail=6.0,
    )
    grain_c = _linear_texture(
        vector,
        random_seed=29.8,
        scratch_rotation=(0.0, 0.13264503, 0.0),
        scratch_spacing=0.012,
        scratch_spread=0.4623803,
        scratch_thickness=0.0002,
        thickness_variation=0.29126215,
        noise_size=2.0,
        distortion_size=4.0,
        distortion_strength=1.6899999,
        distortion_detail=2.3000002,
    )
    coarse = _random_texture(
        vector,
        scratch_spacing=0.05,
        scratch_thickness=0.0002,
        distortion_size=1.0,
        distortion_strength=0.3,
        distortion_detail=1.0,
    )
    return _max_layers(fine_a, fine_b, hairline, grain_a, grain_b, grain_c, coarse)


def scratches_dense_mask_preset(
    vector: t.SocketOrVal[pf.Vector],
) -> pf.ProcNode[float]:
    fine_a = _random_texture(
        vector,
        random_seed=-11.199999,
        scratch_spacing=0.02,
        scratch_thickness=1e-04,
        distortion_strength=0.2,
        distortion_detail=0.0,
    )
    fine_b = _random_texture(
        vector,
        random_seed=19.199999,
        scratch_spacing=0.017,
        scratch_thickness=1e-04,
        distortion_strength=0.2,
        distortion_detail=0.0,
    )
    fine_c = _random_texture(
        vector,
        scratch_spacing=0.015,
        scratch_thickness=1e-04,
        distortion_strength=0.2,
        distortion_detail=0.0,
    )
    fine_d = _random_texture(
        vector,
        random_seed=31.4,
        scratch_spacing=0.008,
        scratch_thickness=1e-04,
        distortion_strength=0.2,
        distortion_detail=0.0,
    )
    hairline = _linear_texture(
        vector,
        scratch_rotation=(0.0, 0.275762, 0.0),
        scratch_spacing=0.002,
        scratch_spread=0.40168542,
        scratch_thickness=1e-04,
        noise_size=4.0,
        distortion_size=3.0,
        distortion_strength=1.0,
        distortion_detail=1.0,
    )
    return _max_layers(fine_a, fine_b, fine_c, fine_d, hairline)


def scratches_deep_dirty_mask_preset(
    vector: t.SocketOrVal[pf.Vector],
) -> pf.ProcNode[float]:
    gouge = _linear_texture(
        vector,
        random_seed=12.399999,
        scratch_rotation=(1.5707964, 0.5393067, 0.0),
        scratch_spacing=0.05,
        scratch_spread=0.3918919,
        scratch_thickness=0.0015,
        thickness_variation=0.41312742,
        noise_size=5.8999996,
        distortion_size=2.31,
        distortion_strength=0.83000004,
        distortion_detail=1.0,
    )
    seam = _linear_texture(
        vector,
        random_seed=12.399999,
        scratch_rotation=(1.5707964, -0.06108652, 0.0),
        scratch_spacing=0.01,
        scratch_spread=0.2992278,
        scratch_thickness=0.002,
        noise_size=5.7800007,
        distortion_size=4.5,
        distortion_stretch=1.0,
        distortion_strength=0.3,
        distortion_detail=1.0,
    )
    cross = _linear_texture(
        vector,
        random_seed=15.699999,
        scratch_rotation=(1.5707964, 0.3089233, 0.0),
        scratch_spacing=0.02,
        scratch_spread=0.3764479,
        scratch_thickness=0.0013,
        noise_size=4.0,
        distortion_size=18.640001,
        distortion_stretch=2.0,
        distortion_strength=1.3399999,
        distortion_detail=1.0,
    )
    coarse = _linear_texture(
        vector,
        random_seed=22.699999,
        scratch_rotation=(1.5707964, 1.0332348, 0.0),
        scratch_spacing=0.04,
        scratch_spread=0.43050194,
        noise_size=4.0,
        distortion_size=2.9400024,
        distortion_strength=0.68999994,
        distortion_detail=5.9999995,
    )
    return _max_layers(gouge, seam, cross, coarse)


def scratches_light_varnish_mask_preset(
    vector: t.SocketOrVal[pf.Vector],
) -> pf.ProcNode[float]:
    sparse = _random_texture(vector, distortion_detail=1.0)
    wide = _random_texture(
        vector,
        random_seed=13.4,
        scratch_spacing=0.2,
        distortion_strength=0.2,
        distortion_detail=1.0,
    )
    fine = _random_texture(
        vector,
        random_seed=28.899998,
        scratch_spacing=0.05,
        scratch_thickness=0.0005,
        distortion_strength=0.3,
        distortion_detail=1.0,
    )
    return _max_layers(sparse, wide, fine)


def scratches_shallow_mask_preset(
    vector: t.SocketOrVal[pf.Vector],
) -> pf.ProcNode[float]:
    broad = _linear_texture(
        vector,
        scratch_rotation=(1.5707964, 0.34906584, 0.0),
        scratch_spacing=0.07,
        scratch_spread=0.35752895,
        scratch_thickness=0.0005,
        thickness_variation=0.41312742,
        noise_size=6.0,
        distortion_size=3.1699998,
        distortion_stretch=2.6,
        distortion_strength=0.8399999,
        distortion_detail=6.7000003,
    )
    medium = _linear_texture(
        vector,
        random_seed=10.0,
        scratch_rotation=(1.5707964, 0.05235988, 0.0),
        scratch_spacing=0.03,
        scratch_spread=0.42297295,
        scratch_thickness=0.0005,
        thickness_variation=0.41312742,
        noise_size=6.0,
        distortion_size=6.0999994,
        distortion_stretch=2.4299998,
        distortion_strength=0.59999996,
        distortion_detail=8.0,
    )
    fine_a = _linear_texture(
        vector,
        random_seed=30.0,
        scratch_rotation=(1.5707964, 0.7853982, 0.0),
        scratch_spacing=0.01,
        scratch_spread=0.4,
        scratch_thickness=0.0003,
        thickness_variation=0.41312742,
        noise_size=6.0,
        distortion_size=3.99,
        distortion_stretch=4.0,
        distortion_strength=1.0799999,
        distortion_detail=2.0,
    )
    fine_b = _linear_texture(
        vector,
        random_seed=64.6,
        scratch_rotation=(1.5707964, 0.54105204, 0.0),
        scratch_spacing=0.01,
        scratch_spread=0.4,
        scratch_thickness=0.0003,
        thickness_variation=0.41312742,
        noise_size=9.0,
        distortion_size=3.0,
        distortion_stretch=4.0,
        distortion_strength=0.5,
        distortion_detail=2.0,
    )
    return _max_layers(broad, medium, fine_a, fine_b)
