# Copyright (C) 2026, Princeton University.
# This source code is licensed under the BSD 3-clause license found in the LICENSE file in the root directory of this source tree.

# Authors: Karhan Kayan

from typing import NamedTuple

import numpy as np
import procfunc as pf
from procfunc.nodes import types as t

from infinigen_v2.generators.shaders.displacements.chip_noise import (
    fractal_chip_truncated as fractal_chip,
)
from infinigen_v2.generators.shaders.util.coord import space_warp
from infinigen_v2.generators.shaders.util.mix import (
    color_mix_4,
    colors_layering_5,
    values_layering_5,
)


class FieldsparResult(NamedTuple):
    alpha: pf.ProcNode[float]
    color: pf.ProcNode[pf.Color]
    height: pf.ProcNode[float]
    chisel: pf.ProcNode[pf.Color]


@pf.nodes.node_function
def fieldspar(
    vector: t.SocketOrVal[pf.Vector] = (0.0, 0.0, 0.0),
    w: t.SocketOrVal[float] = 0.0,
    size: t.SocketOrVal[float] = 1.0,
    spread: t.SocketOrVal[float] = 0.0,
    smoothness: t.SocketOrVal[float] = 0.0,
    color: t.SocketOrVal[pf.Color] = pf.Color((0.5, 0.183, 0.121)),
    color_variation: t.SocketOrVal[float] = 1.0,
    height_scale: t.SocketOrVal[float] = 1.0,
) -> FieldsparResult:
    # Code generated by procfunc v0.2.0

    space_warp_result = space_warp(
        vector=vector / size.astype(dtype=pf.Vector), w=w, size=0.003, detail=3.0
    )
    space_warp_result_1 = space_warp(
        vector=space_warp_result.vector, strength=2.19, w=w, size=0.005, detail=1.0
    )

    alpha_value_1 = pf.nodes.shader.voronoi(
        vector=space_warp_result_1.vector,
        w=w,
        scale=1.0 / 0.0067,
        detail=4.0,
        voronoi_dimensions="4D",
    )
    alpha_value = pf.nodes.func.float_curve(
        value=spread,
        curve=np.array([[0.0, 0.0], [0.4, 0.7313], [1.0, 1.0]]),
    )
    alpha_1 = pf.nodes.func.map_range(value=alpha_value, to_min=0.25, to_max=1.64)
    alpha_from_min = pf.nodes.func.mix(factor=smoothness, a=alpha_1 - 0.0001, b=0.0)
    alpha = pf.nodes.func.map_range(
        value=alpha_value_1.distance,
        from_min=alpha_from_min,
        from_max=alpha_1,
        to_min=1.0,
        to_max=0.0,
    )

    color_vector = pf.nodes.shader.voronoi(
        vector=space_warp_result_1.vector,
        w=w,
        scale=1.0 / 0.0067,
        voronoi_dimensions="4D",
    )

    space_warp_result_2 = space_warp(
        vector=vector / size.astype(dtype=pf.Vector),
        strength=3.0,
        w=w,
        size=0.001,
        detail=5.0,
        roughness=0.7417,
        lacunarity=1.5,
    )
    space_warp_result_3 = space_warp(
        vector=space_warp_result_2.vector,
        strength=8.0,
        w=w,
        size=0.05,
        detail=13.7,
        roughness=0.8833,
        lacunarity=1.5,
    )

    color_value_value = pf.nodes.shader.voronoi(
        vector=color_vector.color.astype(dtype=pf.Vector) + space_warp_result_3.vector,
        w=w,
        scale=30.34,
        detail=1.0,
        roughness=0.7529,
        lacunarity=1.6,
        voronoi_dimensions="4D",
    )
    color_value_2 = pf.nodes.func.map_range(
        value=color_value_value.distance, from_min=0.59, from_max=1.9
    )
    color_hue_value = pf.nodes.func.float_curve(
        value=color_value_2,
        curve=np.array([[0.0, 0.0], [0.3045, 0.1813], [0.7364, 0.7063], [1.0, 1.0]]),
    )
    color_hue = pf.nodes.func.map_range(value=color_hue_value, to_min=0.48, to_max=0.52)
    color_saturation = pf.nodes.func.map_range(
        value=color_hue_value, to_min=0.9, to_max=1.1
    )
    color_value_1 = pf.nodes.func.map_range(
        value=color_hue_value, to_min=0.8, to_max=2.0
    )

    height_3 = pf.nodes.shader.noise(
        vector=alpha_value_1.position,
        w=alpha_value_1.w,
        scale=267.4,
        detail=5.0,
        noise_dimensions="4D",
    )

    color_color_factor = pf.nodes.func.map_range(
        value=height_3.fac, from_min=0.4, from_max=0.6
    )
    color_color_5 = pf.nodes.func.rgb_curve(
        color=color,
        curves=[
            np.array([[0.0, 0.0], [0.5091, 0.5625], [1.0, 1.0]]),
            np.array([[0.0, 0.0], [1.0, 1.0]]),
            np.array([[0.0, 0.0], [1.0, 1.0]]),
            np.array([[0.0, 0.0], [0.5455, 0.3688], [1.0, 1.0]]),
        ],
    )
    color_color_4 = pf.nodes.func.mix_rgb(
        factor=color_color_factor, a=color, b=color_color_5
    )
    color_value = pf.nodes.shader.voronoi_distance(
        vector=vector / size.astype(dtype=pf.Vector),
        w=w,
        scale=1.0 / 0.0022,
        detail=2.0,
        roughness=0.7529,
        lacunarity=1.6,
        voronoi_dimensions="4D",
    )
    color_color_value = pf.nodes.func.map_range(
        value=color_value, from_max=0.11, to_min=1.0, to_max=0.0
    )
    color_color_3 = pf.nodes.func.float_curve(
        value=color_color_value,
        curve=np.array([[0.0, 0.0], [0.6864, 0.2187], [1.0, 1.0]]),
    )
    color_color_2 = pf.nodes.func.mix_rgb(
        factor=0.4083,
        a=color_color_4,
        b=color_color_3.astype(dtype=pf.Color),
        blend_type="SOFT_LIGHT",
    )

    fractal_chip_result = fractal_chip(
        vector=space_warp_result_2.vector,
        w=w,
        size=0.006,
        levels=2.0,
        fractal_step_size=1.5,
    )

    color_color_1 = pf.nodes.func.map_range(
        value=fractal_chip_result.height, from_min=0.1, from_max=0.25
    )
    color_color = pf.nodes.func.mix_rgb(
        factor=0.5333,
        a=color_color_2,
        b=color_color_1.astype(dtype=pf.Color),
        blend_type="SOFT_LIGHT",
    )
    color_1 = pf.nodes.shader.hue_saturation(
        hue=color_hue,
        saturation=color_saturation,
        value=color_value_1,
        fac=color_variation,
        color=color_color,
    )

    height_2 = color_value_2 - 0.5
    height_1 = height_3.fac + (height_2 * 0.5)
    height = (height_scale * height_1) + 3.0

    chisel = pf.nodes.shader.voronoi(
        vector=vector / size.astype(dtype=pf.Vector),
        w=w + 15.1,
        scale=1000.0,
        roughness=0.7529,
        lacunarity=1.6,
        voronoi_dimensions="4D",
    )
    return FieldsparResult(
        alpha=alpha,
        color=color_1,
        height=height,
        chisel=chisel.color,
    )


class QuartzResult(NamedTuple):
    alpha: pf.ProcNode[float]
    color: pf.ProcNode[pf.Color]
    depth: pf.ProcNode[float]
    height: pf.ProcNode[float]
    chisel: pf.ProcNode[pf.Color]


@pf.nodes.node_function
def quartz(
    vector: t.SocketOrVal[pf.Vector] = (0.0, 0.0, 0.0),
    w: t.SocketOrVal[float] = 0.0,
    size: t.SocketOrVal[float] = 1.0,
    spread: t.SocketOrVal[float] = 0.0,
    smoothness: t.SocketOrVal[float] = 0.2,
    color: t.SocketOrVal[pf.Color] = pf.Color((0.255, 0.255, 0.255)),
    color_variation: t.SocketOrVal[float] = 1.0,
    height_scale: t.SocketOrVal[float] = 1.0,
) -> QuartzResult:
    # Code generated by procfunc v0.2.0

    space_warp_result = space_warp(
        vector=vector / size.astype(dtype=pf.Vector),
        strength=2.0,
        w=w,
        size=0.001,
        detail=3.0,
        roughness=0.7417,
        lacunarity=1.5,
    )

    fractal_chip_result = fractal_chip(
        vector=space_warp_result.vector,
        w=w + 50.0,
        size=0.0043,
        levels=3.0,
        fractal_step_size=1.5,
    )

    alpha_value = pf.nodes.func.float_curve(
        value=spread,
        curve=np.array([[0.0, 0.0], [0.4, 0.7313], [1.0, 1.0]]),
    )
    alpha_1 = pf.nodes.func.map_range(value=alpha_value, to_min=0.61, to_max=-0.04)
    alpha_from_max = pf.nodes.func.mix(factor=smoothness, a=alpha_1 + 0.0001, b=1.0)
    alpha = pf.nodes.func.map_range(
        value=fractal_chip_result.height,
        from_min=alpha_1,
        from_max=alpha_from_max,
    )

    chisel_vector_1 = pf.nodes.shader.voronoi(
        vector=vector / size.astype(dtype=pf.Vector),
        w=w,
        scale=700.0,
        roughness=1.0,
        lacunarity=0.98,
        voronoi_dimensions="4D",
    )
    chisel_vector = chisel_vector_1.color.astype(dtype=pf.Vector) - (0.5, 0.5, 0.5)

    space_warp_result_1 = space_warp(
        vector=vector / size.astype(dtype=pf.Vector),
        strength=8.0,
        w=w,
        size=0.02,
        detail=15.0,
        roughness=0.8417,
    )

    color_hue_value = pf.nodes.shader.voronoi(
        vector=chisel_vector + space_warp_result_1.vector,
        w=w,
        scale=100.0,
        detail=1.0,
        roughness=0.7,
        lacunarity=1.5,
        voronoi_dimensions="4D",
    )
    color_hue_1 = pf.nodes.func.map_range(
        value=color_hue_value.distance, from_min=0.81, from_max=1.89
    )
    color_hue = pf.nodes.func.map_range(value=color_hue_1, to_min=0.3, to_max=0.7)
    color_saturation = pf.nodes.func.map_range(
        value=color_hue_1, to_min=0.85, to_max=1.3
    )
    color_value_1 = pf.nodes.func.map_range(value=color_hue_1, to_min=0.1, to_max=2.0)
    color_5 = pf.nodes.shader.hue_saturation(
        hue=color_hue,
        saturation=color_saturation,
        value=color_value_1,
        fac=color_variation,
        color=color,
    )
    color_4 = chisel_vector_1.color.astype(dtype=pf.Vector)
    color_3 = pf.nodes.func.mix_rgb(
        factor=0.6,
        a=color_5,
        b=color_4.x.astype(dtype=pf.Color),
        blend_type="SOFT_LIGHT",
    )
    color_value_value = pf.nodes.shader.voronoi_distance(
        vector=chisel_vector + vector / size.astype(dtype=pf.Vector),
        w=w,
        scale=529.7,
        detail=0.85,
        roughness=1.0,
        lacunarity=0.98,
        voronoi_dimensions="4D",
    )
    color_value = pf.nodes.func.map_range(
        value=color_value_value, from_max=0.07, to_min=1.0, to_max=0.0
    )
    color_2 = pf.nodes.func.float_curve(
        value=color_value,
        curve=np.array([[0.0, 0.0], [0.7955, 0.2313], [1.0, 1.0]]),
    )
    color_1 = pf.nodes.func.mix_rgb(
        factor=0.6,
        a=color_3,
        b=color_2.astype(dtype=pf.Color),
        blend_type="SOFT_LIGHT",
    )

    depth = pf.nodes.shader.voronoi_distance(
        vector=vector / size.astype(dtype=pf.Vector),
        w=w,
        scale=300.0,
        roughness=0.6583,
        lacunarity=0.98,
        voronoi_dimensions="4D",
    )

    height_2 = color_hue_1 - 0.5
    height_1 = fractal_chip_result.height + (height_2 * 0.1)
    height = (height_scale * height_1) + 2.0

    chisel = pf.nodes.shader.voronoi(
        vector=chisel_vector + vector / size.astype(dtype=pf.Vector),
        w=w,
        scale=900.0,
        roughness=0.6583,
        lacunarity=0.98,
        voronoi_dimensions="4D",
    )
    return QuartzResult(
        alpha=alpha,
        color=color_1,
        depth=depth,
        height=height,
        chisel=chisel.color,
    )


class MicaHornblendeResult(NamedTuple):
    alpha: pf.ProcNode[float]
    color: pf.ProcNode[pf.Color]
    height: pf.ProcNode[float]
    chisel: pf.ProcNode[pf.Color]


@pf.nodes.node_function
def mica_hornblende(
    vector: t.SocketOrVal[pf.Vector] = (0.0, 0.0, 0.0),
    w: t.SocketOrVal[float] = 0.0,
    size: t.SocketOrVal[float] = 1.0,
    spread: t.SocketOrVal[float] = 0.0,
    smoothness: t.SocketOrVal[float] = 0.2,
    color: t.SocketOrVal[pf.Color] = pf.Color((0.5, 0.5, 0.5)),
    color_variation: t.SocketOrVal[float] = 1.0,
    height_scale: t.SocketOrVal[float] = 1.0,
) -> MicaHornblendeResult:
    # Code generated by procfunc v0.2.0

    space_warp_result = space_warp(
        vector=vector / size.astype(dtype=pf.Vector),
        w=w,
        size=0.001,
        detail=3.0,
        roughness=0.6583,
    )

    fractal_chip_result = fractal_chip(
        vector=space_warp_result.vector,
        w=w + 50.0,
        size=0.0029,
        levels=5.0,
        fractal_step_size=1.5,
    )

    alpha_value = pf.nodes.func.float_curve(
        value=spread,
        curve=np.array([[0.0, 0.0], [0.4, 0.7313], [1.0, 1.0]]),
    )
    alpha_1 = pf.nodes.func.map_range(value=alpha_value, to_min=0.4, to_max=0.0)
    alpha_from_max = pf.nodes.func.mix(factor=smoothness, a=alpha_1 + 0.0001, b=1.0)
    alpha = pf.nodes.func.map_range(
        value=fractal_chip_result.height,
        from_min=alpha_1,
        from_max=alpha_from_max,
    )

    color_vector_scale = pf.nodes.func.constant(464.3999938964844)
    color_vector_1 = pf.nodes.shader.voronoi(
        vector=space_warp_result.vector,
        w=w,
        scale=color_vector_scale,
        roughness=0.7833,
        voronoi_dimensions="4D",
    )
    color_vector = color_vector_1.color.astype(dtype=pf.Vector) - (0.5, 0.5, 0.5)

    space_warp_result_1 = space_warp(
        vector=space_warp_result.vector,
        strength=8.0,
        w=w,
        size=0.05,
        detail=15.0,
        roughness=0.9167,
    )

    color_hue_value = pf.nodes.shader.voronoi(
        vector=color_vector + space_warp_result_1.vector,
        w=w,
        scale=33.8,
        detail=1.0,
        roughness=0.7,
        lacunarity=1.5,
        voronoi_dimensions="4D",
    )
    color_hue_1 = pf.nodes.func.map_range(
        value=color_hue_value.distance, from_min=0.59, from_max=2.0
    )
    color_hue = pf.nodes.func.map_range(value=color_hue_1, to_min=0.3, to_max=0.7)
    color_saturation = pf.nodes.func.map_range(
        value=color_hue_1, to_min=0.9, to_max=1.3
    )
    color_value = pf.nodes.func.map_range(value=color_hue_1, to_min=0.8, to_max=2.0)
    color_3 = pf.nodes.shader.hue_saturation(
        hue=color_hue,
        saturation=color_saturation,
        value=color_value,
        fac=color_variation,
        color=color,
    )
    color_2 = color_vector_1.color.astype(dtype=pf.Vector)
    color_1 = pf.nodes.func.mix_rgb(
        factor=0.25,
        a=color_3,
        b=color_2.x.astype(dtype=pf.Color),
        blend_type="SOFT_LIGHT",
    )

    height_2 = color_hue_1 - 0.5
    height_1 = fractal_chip_result.height + (height_2 * 0.1)
    height = (height_scale * height_1) + 1.0

    chisel = pf.nodes.shader.voronoi(
        vector=space_warp_result.vector,
        w=w,
        scale=1000.0,
        roughness=0.7,
        lacunarity=1.5,
        voronoi_dimensions="4D",
    )
    return MicaHornblendeResult(
        alpha=alpha,
        color=color_1,
        height=height,
        chisel=chisel.color,
    )


class GraniteResult(NamedTuple):
    surface: pf.ProcNode[pf.Shader]
    displacement: pf.ProcNode[pf.Vector]
    color: pf.ProcNode[pf.Color]


@pf.nodes.node_function
def granite(
    vector: t.SocketOrVal[pf.Vector] = (-999999.0, -999999.0, -999999.0),
    w: t.SocketOrVal[float] = 0.0,
    size: t.SocketOrVal[float] = 0.05,
    min_roughness: t.SocketOrVal[float] = 0.3,
    max_roughness: t.SocketOrVal[float] = 0.5,
    min_spec: t.SocketOrVal[float] = 0.2,
    max_spec: t.SocketOrVal[float] = 0.4,
    height_scale: t.SocketOrVal[float] = 1.0,
    height_offset: t.SocketOrVal[float] = 0.0,
    hornblende_size: t.SocketOrVal[float] = 1.0,
    hornblende_color: t.SocketOrVal[pf.Color] = pf.Color((0.009, 0.01, 0.011)),
    hornblende_color_variation: t.SocketOrVal[float] = 1.0,
    hornblende_height: t.SocketOrVal[float] = 1.0,
    mica_size: t.SocketOrVal[float] = 1.0,
    mica_spread: t.SocketOrVal[float] = 0.8833,
    mica_smoothness: t.SocketOrVal[float] = 0.2,
    mica_color: t.SocketOrVal[pf.Color] = pf.Color((0.011, 0.013, 0.014)),
    mica_color_variation: t.SocketOrVal[float] = 1.0,
    mica_height: t.SocketOrVal[float] = 1.0,
    quartz_size: t.SocketOrVal[float] = 1.0,
    quartz_spread: t.SocketOrVal[float] = 0.7917,
    quartz_smoothness: t.SocketOrVal[float] = 0.2,
    quartz_color: t.SocketOrVal[pf.Color] = pf.Color((0.028, 0.038, 0.049)),
    quartz_color_variation: t.SocketOrVal[float] = 1.0,
    quartz_height: t.SocketOrVal[float] = 1.0,
    feldspar_size: t.SocketOrVal[float] = 1.0,
    feldspar_spread: t.SocketOrVal[float] = 0.5417,
    feldspar_smoothness: t.SocketOrVal[float] = 0.02,
    feldspar_color: t.SocketOrVal[pf.Color] = pf.Color((0.006, 0.007, 0.008)),
    feldspar_color_variation: t.SocketOrVal[float] = 1.0,
    feldspar_height: t.SocketOrVal[float] = 1.0,
) -> GraniteResult:
    # Code generated by procfunc v0.2.0

    space_warp_result = space_warp(
        vector=vector / size.astype(dtype=pf.Vector),
        strength=3.0,
        size=0.0001,
        detail=3.0,
    )

    mica_hornblende_result = mica_hornblende(
        vector=space_warp_result.vector,
        w=w / size,
        size=mica_size,
        spread=mica_spread,
        smoothness=mica_smoothness,
        color=mica_color,
        color_variation=mica_color_variation,
        height_scale=mica_height,
    )

    quartz_result = quartz(
        vector=space_warp_result.vector,
        w=w / size,
        size=quartz_size,
        spread=quartz_spread,
        smoothness=quartz_smoothness,
        color=quartz_color,
        color_variation=quartz_color_variation,
        height_scale=quartz_height,
    )

    fieldspar_result = fieldspar(
        vector=space_warp_result.vector,
        w=w / size,
        size=feldspar_size,
        spread=feldspar_spread,
        smoothness=feldspar_smoothness,
        color=feldspar_color,
        color_variation=feldspar_color_variation,
        height_scale=feldspar_height,
    )

    values_layering_5_result = values_layering_5(
        layer_2_alpha=1.0,
        layer_2=0.4,
        layer_3_alpha=mica_hornblende_result.alpha,
        layer_3=1.0,
        layer_4_alpha=quartz_result.alpha,
        layer_4=1.0,
        layer_5_alpha=fieldspar_result.alpha,
        layer_5=0.7,
    )

    space_warp_result_1 = space_warp(
        vector=space_warp_result.vector,
        strength=8.0,
        w=w / size,
        size=0.02,
        detail=16.0,
        roughness=0.9,
    )

    surface_value_value = pf.nodes.shader.voronoi(
        vector=space_warp_result_1.vector,
        w=w / size,
        scale=59.61,
        voronoi_dimensions="4D",
    )
    surface_value_1 = pf.nodes.func.map_range(
        value=surface_value_value.distance, from_min=0.32
    )
    surface_value = surface_value_1 * 0.5
    surface_fac_value = pf.nodes.math.clamp(values_layering_5_result - surface_value)
    surface_fac = pf.nodes.func.map_range(
        value=surface_fac_value, to_min=min_spec, to_max=max_spec
    )

    mica_hornblende_result_1 = mica_hornblende(
        vector=space_warp_result.vector,
        w=w / size,
        size=hornblende_size,
        spread=1.0,
        smoothness=0.0,
        color=hornblende_color,
        color_variation=hornblende_color_variation,
        height_scale=hornblende_height,
    )

    colors_layering_5_result = colors_layering_5(
        layer_2_alpha=1.0,
        color_2=mica_hornblende_result_1.color,
        layer_3_alpha=mica_hornblende_result.alpha,
        color_3=mica_hornblende_result.color,
        layer_4_alpha=quartz_result.alpha,
        color_4=quartz_result.color,
        layer_5_alpha=fieldspar_result.alpha,
        color_5=fieldspar_result.color,
    )

    surface_shader_1 = pf.nodes.shader.diffuse_bsdf(color=colors_layering_5_result)

    values_layering_5_result_1 = values_layering_5(
        layer_2_alpha=1.0,
        layer_3_alpha=mica_hornblende_result.alpha,
        layer_3=0.9,
        layer_4_alpha=quartz_result.alpha,
        layer_4=0.2,
        layer_5_alpha=fieldspar_result.alpha,
        layer_5=0.35,
    )

    shader_1_color = pf.nodes.func.mix_rgb(
        factor=values_layering_5_result_1,
        a=pf.Color((0.707, 0.707, 0.707)),
        b=colors_layering_5_result,
    )

    values_layering_5_result_2 = values_layering_5(
        layer_2_alpha=1.0,
        layer_2=0.6,
        layer_3_alpha=mica_hornblende_result.alpha,
        layer_3=0.01,
        layer_4_alpha=quartz_result.alpha,
        layer_4=0.01,
        layer_5_alpha=fieldspar_result.alpha,
        layer_5=0.3,
    )

    shader_1_roughness = pf.nodes.func.map_range(
        value=values_layering_5_result_2 + surface_value,
        to_min=min_roughness,
        to_max=max_roughness,
    )

    surface_shader = pf.nodes.shader.anisotropic_bsdf(
        color=shader_1_color,
        roughness=shader_1_roughness,
    )
    surface = pf.nodes.shader.mix_shader(
        factor=surface_fac,
        a=surface_shader_1,
        b=surface_shader,
    )

    values_layering_5_result_3 = values_layering_5(
        layer_2_alpha=1.0,
        layer_2=mica_hornblende_result_1.height,
        layer_3_alpha=mica_hornblende_result.alpha,
        layer_3=mica_hornblende_result.height,
        layer_4_alpha=quartz_result.alpha,
        layer_4=quartz_result.height,
        layer_5_alpha=fieldspar_result.alpha,
        layer_5=fieldspar_result.height,
    )

    displacement_height_1 = size * height_scale
    displacement_height = values_layering_5_result_3 * (displacement_height_1 * 0.001)
    displacement = pf.nodes.shader.displacement(
        height=displacement_height + height_offset,
        midlevel=0.0,
    )
    return GraniteResult(
        surface=surface,
        displacement=displacement,
        color=colors_layering_5_result,
    )


def granite_yellow(
    vector: pf.ProcNode[pf.Vector],
) -> pf.Material:
    # Code generated by procfunc v0.2.0

    space_warp_result = space_warp(
        vector=vector, strength=16.0, size=0.05, detail=5.0, roughness=0.7
    )
    space_warp_result_1 = space_warp(
        vector=space_warp_result.vector,
        strength=20.0,
        w=24.7,
        size=0.02,
        roughness=0.775,
    )

    surface_map_value = pf.nodes.shader.voronoi(
        vector=space_warp_result_1.vector,
        scale=10.0,
        detail=3.0,
        normalize=True,
    )
    surface_map = pf.nodes.func.map_range(
        value=surface_map_value.distance, from_min=0.2, from_max=0.53
    )
    surface_color_3 = pf.color.hsv_to_rgba((0.1111, 0.3, 0.01))
    surface_color_2 = pf.color.hsv_to_rgba((0.1, 0.4444, 0.09))
    surface_color_1 = pf.color.hsv_to_rgba((0.1547, 0.5907, 0.259))
    surface_color = pf.color.hsv_to_rgba((0.1123, 0.6104, 0.231))

    color_mix_4_result = color_mix_4(
        map=surface_map,
        color_1=surface_color_3,
        color_1_position=0.0,
        color_2=surface_color_2,
        color_2_position=0.196,
        color_3=surface_color_1,
        color_3_position=0.4795,
        color_4=surface_color,
        color_4_position=1.0,
    )

    surface_mica_color = pf.color.hsv_to_rgba((0.0, 0.0, 0.007))
    surface_quartz_color = pf.color.hsv_to_rgba((0.0, 0.0, 0.695))
    surface_feldspar_color = pf.color.hsv_to_rgba((0.0417, 0.0538, 0.52))

    granite_result = granite(
        vector=vector,
        size=10.0,
        min_roughness=0.1,
        max_roughness=0.1,
        min_spec=0.1,
        max_spec=0.1,
        height_scale=0.05,
        hornblende_size=0.3,
        hornblende_color=color_mix_4_result,
        hornblende_color_variation=0.7549,
        hornblende_height=0.1,
        mica_size=0.5,
        mica_spread=0.2647,
        mica_smoothness=0.0245,
        mica_color=surface_mica_color,
        mica_color_variation=0.6716,
        mica_height=0.15,
        quartz_size=0.1,
        quartz_spread=0.3725,
        quartz_smoothness=0.02,
        quartz_color=surface_quartz_color,
        quartz_color_variation=0.452,
        quartz_height=0.22,
        feldspar_size=0.3,
        feldspar_spread=0.2059,
        feldspar_smoothness=0.1,
        feldspar_color=surface_feldspar_color,
        feldspar_color_variation=0.6078,
        feldspar_height=0.3,
    )
    return pf.Material(
        surface=granite_result.surface,
        displacement=granite_result.displacement,
    )


def granite_white_brown(
    vector: pf.ProcNode[pf.Vector],
) -> pf.Material:
    # Code generated by procfunc v0.2.0

    surface_hornblende_color = pf.color.hsv_to_rgba((0.0, 0.0, 0.002))

    space_warp_result = space_warp(
        vector=vector, strength=16.0, size=0.05, detail=5.0, roughness=0.7
    )
    space_warp_result_1 = space_warp(
        vector=space_warp_result.vector,
        strength=20.0,
        w=24.7,
        size=0.02,
        roughness=0.775,
    )

    surface_map_value = pf.nodes.shader.voronoi(
        vector=space_warp_result_1.vector, detail=3.0, normalize=True
    )
    surface_map = pf.nodes.func.map_range(
        value=surface_map_value.distance,
        from_min=0.22,
        from_max=0.36,
    )
    surface_color_3 = pf.color.hsv_to_rgba((0.012, 0.6535, 0.127))
    surface_color_2 = pf.color.hsv_to_rgba((0.1235, 0.7847, 0.497))
    surface_color_1 = pf.color.hsv_to_rgba((0.1019, 0.5281, 0.551))
    surface_color = pf.color.hsv_to_rgba((0.0, 0.0, 0.571))

    color_mix_4_result = color_mix_4(
        map=surface_map,
        color_1=surface_color_3,
        color_1_position=0.125,
        color_2=surface_color_2,
        color_2_position=0.206,
        color_3=surface_color_1,
        color_3_position=0.3095,
        color_4=surface_color,
        color_4_position=1.0,
    )

    surface_feldspar_color = pf.color.hsv_to_rgba((0.0463, 0.0525, 0.343))

    granite_result = granite(
        vector=vector,
        size=10.0,
        min_roughness=0.1054,
        max_roughness=0.4118,
        min_spec=0.026,
        max_spec=0.1299,
        height_scale=0.5,
        hornblende_color=surface_hornblende_color,
        hornblende_color_variation=0.0,
        hornblende_height=0.1,
        mica_spread=0.5,
        mica_smoothness=0.05,
        mica_color=color_mix_4_result,
        mica_color_variation=0.451,
        mica_height=0.25,
        quartz_size=0.2,
        quartz_spread=0.5,
        quartz_smoothness=0.05,
        quartz_color=color_mix_4_result,
        quartz_color_variation=0.3235,
        quartz_height=0.5,
        feldspar_size=0.3,
        feldspar_spread=0.2,
        feldspar_smoothness=0.1,
        feldspar_color=surface_feldspar_color,
        feldspar_height=0.75,
    )
    return pf.Material(
        surface=granite_result.surface,
        displacement=granite_result.displacement,
    )


def granite_no_displacement(
    vector: pf.ProcNode[pf.Vector],
) -> pf.Material:
    # Code generated by procfunc v0.2.0

    surface_hornblende_color = pf.color.hsv_to_rgba((0.0, 0.0, 0.002))

    space_warp_result = space_warp(
        vector=vector, strength=16.0, size=0.05, detail=5.0, roughness=0.7
    )
    space_warp_result_1 = space_warp(
        vector=space_warp_result.vector,
        strength=20.0,
        w=24.7,
        size=0.02,
        roughness=0.775,
    )

    surface_map_value = pf.nodes.shader.voronoi(
        vector=space_warp_result_1.vector,
        scale=10.0,
        detail=3.0,
        normalize=True,
    )
    surface_map = pf.nodes.func.map_range(
        value=surface_map_value.distance, from_min=0.1, from_max=0.43
    )
    surface_color_3 = pf.color.hsv_to_rgba((0.0833, 0.1667, 0.012))
    surface_color_2 = pf.color.hsv_to_rgba((0.0657, 0.0932, 0.354))
    surface_color_1 = pf.color.hsv_to_rgba((0.0154, 0.1094, 0.594))
    surface_color = pf.color.hsv_to_rgba((0.0, 0.0, 0.148))

    color_mix_4_result = color_mix_4(
        map=surface_map,
        color_1=surface_color_3,
        color_1_position=0.0,
        color_2=surface_color_2,
        color_2_position=0.136,
        color_3=surface_color_1,
        color_3_position=0.4395,
        color_4=surface_color,
        color_4_position=0.81,
    )

    surface_quartz_color = pf.color.hsv_to_rgba((0.0, 0.0, 0.421))
    surface_feldspar_color = pf.color.hsv_to_rgba((0.0385, 0.0535, 0.243))

    granite_result = granite(
        vector=vector,
        size=10.0,
        min_roughness=0.0824,
        max_roughness=0.1922,
        min_spec=0.05,
        max_spec=0.1,
        hornblende_size=0.3,
        hornblende_color=surface_hornblende_color,
        hornblende_color_variation=0.7549,
        hornblende_height=0.1,
        mica_size=0.5,
        mica_spread=0.5741,
        mica_smoothness=0.05,
        mica_color=color_mix_4_result,
        mica_color_variation=0.6716,
        mica_height=0.25,
        quartz_size=0.2,
        quartz_spread=0.5,
        quartz_smoothness=0.02,
        quartz_color=surface_quartz_color,
        quartz_color_variation=0.452,
        quartz_height=0.22,
        feldspar_size=0.2,
        feldspar_spread=0.25,
        feldspar_smoothness=0.2,
        feldspar_color=surface_feldspar_color,
        feldspar_color_variation=0.6078,
        feldspar_height=0.15,
    )
    return pf.Material(
        surface=granite_result.surface,
    )


def granite_crystals(
    vector: pf.ProcNode[pf.Vector],
) -> pf.Material:
    # Code generated by procfunc v0.2.0

    surface_hornblende_color = pf.color.hsv_to_rgba((0.0, 0.0, 0.002))

    space_warp_result = space_warp(
        vector=vector, strength=16.0, size=0.05, detail=5.0, roughness=0.7
    )
    space_warp_result_1 = space_warp(
        vector=space_warp_result.vector,
        strength=20.0,
        w=24.7,
        size=0.02,
        roughness=0.775,
    )

    surface_map_value = pf.nodes.shader.voronoi(
        vector=space_warp_result_1.vector, detail=3.0, normalize=True
    )
    surface_map = pf.nodes.func.map_range(
        value=surface_map_value.distance, from_min=0.1, from_max=0.43
    )
    surface_color_3 = pf.color.hsv_to_rgba((0.0833, 0.1667, 0.012))
    surface_color_2 = pf.color.hsv_to_rgba((0.1369, 0.6638, 0.354))
    surface_color_1 = pf.color.hsv_to_rgba((0.1394, 0.4731, 0.594))
    surface_color = pf.color.hsv_to_rgba((0.0, 0.0, 0.346))

    color_mix_4_result = color_mix_4(
        map=surface_map,
        color_1=surface_color_3,
        color_1_position=0.0,
        color_2=surface_color_2,
        color_2_position=0.136,
        color_3=surface_color_1,
        color_3_position=0.4395,
        color_4=surface_color,
        color_4_position=0.81,
    )

    surface_quartz_color = pf.color.hsv_to_rgba((0.0, 0.0, 0.754))
    surface_feldspar_color = pf.color.hsv_to_rgba((0.0392, 0.0535, 0.318))

    granite_result = granite(
        vector=vector,
        size=100.0,
        height_scale=0.01,
        min_roughness=0.0824,
        max_roughness=0.1922,
        min_spec=0.05,
        max_spec=0.1,
        hornblende_size=0.3,
        hornblende_color=surface_hornblende_color,
        hornblende_color_variation=0.7549,
        hornblende_height=0.1,
        mica_size=0.5,
        mica_spread=0.5741,
        mica_smoothness=0.05,
        mica_color=color_mix_4_result,
        mica_color_variation=0.6716,
        mica_height=0.25,
        quartz_size=0.15,
        quartz_spread=0.45,
        quartz_smoothness=0.02,
        quartz_color=surface_quartz_color,
        quartz_color_variation=0.452,
        quartz_height=0.3,
        feldspar_size=0.2,
        feldspar_spread=0.2608,
        feldspar_smoothness=0.2,
        feldspar_color=surface_feldspar_color,
        feldspar_color_variation=0.6078,
        feldspar_height=0.15,
    )
    return pf.Material(
        surface=granite_result.surface,
        displacement=granite_result.displacement,
    )


def granite_cobble_gray(
    vector: pf.ProcNode[pf.Vector],
) -> pf.Material:
    # Code generated by procfunc v0.3.0

    return granite(
        vector=vector,
        size=7.0,
        min_roughness=0.5013,
        max_roughness=0.8333,
        min_spec=0.0538,
        max_spec=0.0753,
        height_scale=0.25,
        hornblende_color=pf.Color((0.028, 0.032, 0.036)),
        hornblende_color_variation=0.4355,
        hornblende_height=0.0,
        mica_size=0.4,
        mica_spread=1.0,
        mica_smoothness=0.2113,
        mica_color=pf.Color((0.064, 0.071, 0.075)),
        mica_color_variation=0.5645,
        mica_height=1.8,
        quartz_size=0.5,
        quartz_spread=0.8548,
        quartz_smoothness=0.5554,
        quartz_color=pf.Color((0.068, 0.076, 0.079)),
        quartz_color_variation=0.3871,
        quartz_height=2.7,
        feldspar_size=0.3,
        feldspar_spread=0.3,
        feldspar_smoothness=0.25,
        feldspar_color=pf.Color((0.106, 0.142, 0.154)),
        feldspar_color_variation=0.6075,
        feldspar_height=0.5,
    )


def granite_masonry_gray(
    vector: pf.ProcNode[pf.Vector],
) -> pf.Material:
    # Code generated by procfunc v0.3.0
    # moved from brick demo to granite

    return granite(
        vector=vector,
        size=1.0,
        min_roughness=0.6583,
        max_roughness=0.8333,
        min_spec=0.075,
        max_spec=0.2083,
        height_scale=0.5,
        hornblende_color=pf.Color((0.002, 0.002, 0.002)),
        hornblende_height=0.1,
        mica_spread=0.45,
        mica_smoothness=0.05,
        mica_color=pf.Color((0.149, 0.149, 0.149)),
        mica_height=0.25,
        quartz_size=0.2,
        quartz_spread=0.5,
        quartz_smoothness=0.05,
        quartz_color=pf.Color((0.431, 0.431, 0.431)),
        quartz_height=0.5,
        feldspar_size=0.3,
        feldspar_spread=0.2,
        feldspar_smoothness=0.1,
        feldspar_color=pf.Color((0.151, 0.145, 0.143)),
        feldspar_height=0.75,
    )


def granite_sandy(
    vector: pf.ProcNode[pf.Vector],
) -> pf.Material:
    return granite(
        vector=vector,
        size=7.0,
        min_roughness=0.5013,
        max_roughness=0.8333,
        min_spec=0.0538,
        max_spec=0.0753,
        height_scale=0.25,
        hornblende_size=0.1,
        hornblende_color=pf.Color((0.225, 0.168, 0.106)),
        hornblende_color_variation=0.3817,
        hornblende_height=0.1,
        mica_size=0.5,
        mica_spread=0.4892,
        mica_smoothness=0.1522,
        mica_color=pf.Color((0.209, 0.152, 0.057)),
        mica_color_variation=0.5645,
        mica_height=1.8,
        quartz_size=0.2,
        quartz_spread=0.6882,
        quartz_smoothness=0.2167,
        quartz_color=pf.Color((0.534, 0.352, 0.075)),
        quartz_color_variation=0.3871,
        quartz_height=2.7,
        feldspar_size=0.1,
        feldspar_spread=0.0,
        feldspar_smoothness=0.25,
        feldspar_color=pf.Color((0.106, 0.142, 0.154)),
        feldspar_color_variation=0.6075,
        feldspar_height=0.5,
    )


def granite_presets(
    rng: pf.RNG,
    vector: t.SocketOrVal[pf.Vector],
):
    # TODO: replace with continously randomized version below

    func = pf.control.choice(
        rng,
        [
            (granite_yellow, 1.0),
            (granite_no_displacement, 1.0),
            (granite_white_brown, 1.0),
            (granite_crystals, 1.0),
            (granite_cobble_gray, 1.0),
            (granite_masonry_gray, 1.0),
            (granite_sandy, 1.0),
        ],
    )
    result = func(vector=vector)
    return pf.Material(surface=result.surface, displacement=result.displacement)


def _create_gradient_color(
    rng: pf.RNG,
    vector: t.SocketOrVal[pf.Vector],
    base_color: pf.Color,
) -> pf.ProcNode[pf.Color]:
    """Create a gradient color pattern using space_warp and voronoi.

    This creates varied stone-like color patterns similar to the demo functions,
    blending 4 shades derived from the base color.
    """
    # Apply two space_warp operations to create organic distortion
    warp_strength_1 = pf.random.uniform(rng, 10.0, 20.0)
    warp_strength_2 = pf.random.uniform(rng, 15.0, 25.0)
    warp_w = pf.random.uniform(rng, 0.0, 50.0)

    space_warp_result = space_warp(
        vector=vector,
        strength=warp_strength_1,
        w=0.0,
        size=pf.random.uniform(rng, 0.03, 0.08),
        detail=pf.random.uniform(rng, 3.0, 7.0),
        roughness=pf.random.uniform(rng, 0.6, 0.8),
        lacunarity=2.0,
        distortion=0.0,
    )
    space_warp_result_1 = space_warp(
        vector=space_warp_result.vector,
        strength=warp_strength_2,
        w=warp_w,
        size=pf.random.uniform(rng, 0.01, 0.04),
        detail=pf.random.uniform(rng, 1.5, 3.5),
        roughness=pf.random.uniform(rng, 0.7, 0.85),
        lacunarity=2.0,
        distortion=0.0,
    )

    # Create voronoi pattern
    voronoi_scale = pf.random.uniform(rng, 5.0, 15.0)
    voronoi = pf.nodes.shader.voronoi(
        vector=space_warp_result_1.vector,
        scale=voronoi_scale,
        detail=pf.random.uniform(rng, 2.0, 4.0),
        normalize=True,
    )

    # Map voronoi distance to color gradient
    from_min = pf.random.uniform(rng, 0.05, 0.25)
    from_max = pf.random.uniform(rng, 0.35, 0.55)
    color_mix_4_map = pf.nodes.func.map_range(
        value=voronoi.distance, from_max=from_max, from_min=from_min
    )

    # Derive 4 color shades from the base color using HSV manipulation
    # Color 1: Darker shade
    c1_v = max(0.01, base_color.v * pf.random.uniform(rng, 0.1, 0.3))
    color_1 = pf.color.hsv_color((base_color.h, base_color.s * 0.8, c1_v))

    # Color 2: Medium-dark shade
    c2_v = max(0.02, base_color.v * pf.random.uniform(rng, 0.4, 0.7))
    color_2 = pf.color.hsv_color((base_color.h, base_color.s, c2_v))

    # Color 3: Base shade (close to original)
    c3_v = base_color.v * pf.random.uniform(rng, 0.8, 1.1)
    color_3 = pf.color.hsv_color((base_color.h, base_color.s, min(1.0, c3_v)))

    # Color 4: Lighter/grayer shade
    c4_s = base_color.s * pf.random.uniform(rng, 0.3, 0.7)
    c4_v = pf.random.uniform(rng, 0.1, 0.5)
    color_4 = pf.color.hsv_color((base_color.h, c4_s, c4_v))

    # Randomize gradient positions
    pos_2 = pf.random.uniform(rng, 0.1, 0.25)
    pos_3 = pf.random.uniform(rng, 0.35, 0.55)
    pos_4 = pf.random.uniform(rng, 0.7, 0.95)

    return color_mix_4(
        map=color_mix_4_map,
        color_1=color_1,
        color_1_position=0.0,
        color_2=color_2,
        color_2_position=pos_2,
        color_3=color_3,
        color_3_position=pos_3,
        color_4=color_4,
        color_4_position=pos_4,
    )


def _warm_color_distribution(rng: pf.RNG) -> pf.Color:
    """Sample warm colors (yellow, orange, tan, brown) for granite background."""
    hsv = pf.random.mixture_of_gaussian(
        rng=rng,
        means=np.array(
            [
                [0.11, 0.5, 0.15],  # Yellow-orange (like granite_yellow)
                [0.08, 0.55, 0.12],  # Orange-tan
                [0.05, 0.4, 0.2],  # Tan-brown
                [0.12, 0.6, 0.25],  # Golden yellow
                [0.15, 0.45, 0.18],  # Yellow-green tint
                [0.03, 0.5, 0.15],  # Salmon/peach
            ]
        ),
        stds=np.array(
            [
                [0.02, 0.15, 0.08],
                [0.02, 0.12, 0.06],
                [0.02, 0.1, 0.08],
                [0.02, 0.15, 0.1],
                [0.02, 0.12, 0.08],
                [0.015, 0.12, 0.06],
            ]
        ),
        weights=[0.25, 0.2, 0.15, 0.15, 0.15, 0.1],
        low=np.array([0.0, 0.2, 0.01]),
        high=np.array([0.2, 0.8, 0.4]),
    )
    return pf.color.hsv_color(hsv=hsv)


def _cool_color_distribution(rng: pf.RNG) -> pf.Color:
    """Sample cool colors (grey, blue-grey, white) for granite background."""
    hsv = pf.random.mixture_of_gaussian(
        rng=rng,
        means=np.array(
            [
                [0.0, 0.05, 0.35],  # Neutral grey
                [0.6, 0.1, 0.4],  # Blue-grey
                [0.55, 0.08, 0.5],  # Light blue-grey
                [0.0, 0.0, 0.25],  # Dark grey
                [0.08, 0.1, 0.45],  # Warm grey
            ]
        ),
        stds=np.array(
            [
                [0.05, 0.03, 0.15],
                [0.05, 0.05, 0.12],
                [0.04, 0.04, 0.1],
                [0.03, 0.02, 0.1],
                [0.03, 0.05, 0.12],
            ]
        ),
        weights=[0.35, 0.2, 0.2, 0.15, 0.1],
        low=np.array([0.0, 0.0, 0.05]),
        high=np.array([1.0, 0.25, 0.7]),
    )
    return pf.color.hsv_color(hsv=hsv)


def _dark_accent_color_distribution(rng: pf.RNG) -> pf.Color:
    """Sample dark accent colors (black, dark brown, dark green) for mica/hornblende."""
    hsv = pf.random.mixture_of_gaussian(
        rng=rng,
        means=np.array(
            [
                [0.0, 0.1, 0.02],  # Near black
                [0.08, 0.4, 0.05],  # Dark brown
                [0.35, 0.3, 0.06],  # Dark green
                [0.0, 0.0, 0.01],  # Pure black
                [0.12, 0.5, 0.08],  # Dark bronze
            ]
        ),
        stds=np.array(
            [
                [0.05, 0.08, 0.015],
                [0.03, 0.1, 0.02],
                [0.05, 0.1, 0.025],
                [0.02, 0.02, 0.008],
                [0.03, 0.12, 0.03],
            ]
        ),
        weights=[0.3, 0.25, 0.15, 0.2, 0.1],
        low=np.array([0.0, 0.0, 0.005]),
        high=np.array([1.0, 0.6, 0.15]),
    )
    return pf.color.hsv_color(hsv=hsv)


def _sample_pair_bounded(
    rng: pf.RNG, min_val: float, max_val: float, std: float = 0.08
) -> tuple[float, float]:
    a = pf.random.clip_gaussian(rng, min_val, std, 0.0, 1.0)
    b = pf.random.clip_gaussian(rng, max_val, std, 0.0, 1.0)
    return min(a, b), max(a, b)


def _light_accent_color_distribution(rng: pf.RNG) -> pf.Color:
    """Sample light accent colors (white, cream, light grey) for quartz/feldspar."""
    hsv = pf.random.mixture_of_gaussian(
        rng=rng,
        means=np.array(
            [
                [0.0, 0.02, 0.7],  # Near white
                [0.08, 0.08, 0.6],  # Cream
                [0.0, 0.0, 0.5],  # Medium grey
                [0.05, 0.1, 0.55],  # Light tan
                [0.6, 0.05, 0.65],  # Light blue-grey
            ]
        ),
        stds=np.array(
            [
                [0.03, 0.02, 0.12],
                [0.03, 0.05, 0.1],
                [0.02, 0.02, 0.15],
                [0.03, 0.06, 0.1],
                [0.05, 0.03, 0.1],
            ]
        ),
        weights=[0.3, 0.25, 0.2, 0.15, 0.1],
        low=np.array([0.0, 0.0, 0.3]),
        high=np.array([1.0, 0.2, 0.85]),
    )
    return pf.color.hsv_color(hsv=hsv)


def _granite_yellow_distribution(
    vector: t.SocketOrVal[pf.Vector],
    w: float | None,
    rng: pf.RNG,
    min_roughness: float | None = None,
    max_roughness: float | None = None,
) -> pf.Material:
    """Granite yellow style - warm background dominates (uses gradient)."""
    if w is None:
        w = pf.random.uniform(rng, 0.0, 100.0)
    # Sample colors
    base_warm = _warm_color_distribution(rng)
    hornblende_color = _create_gradient_color(rng, vector, base_warm)
    mica_color = _dark_accent_color_distribution(rng)
    quartz_color = _light_accent_color_distribution(rng)
    feldspar_color = _light_accent_color_distribution(rng)

    # Sample parameters around template anchors
    # Anchor values from granite_yellow
    size = pf.random.log_normal(rng, 10.0, 0.25)
    if min_roughness is None or max_roughness is None:
        mean_roughness_min = pf.random.uniform(rng, 0.1, 0.3)
        mean_roughness_max = pf.random.uniform(rng, mean_roughness_min, 0.5)
        min_roughness, max_roughness = _sample_pair_bounded(
            rng, mean_roughness_min, mean_roughness_max, std=0.05
        )
    min_spec, max_spec = _sample_pair_bounded(rng, 0.1, 0.1, std=0.05)
    height_scale = pf.random.log_normal(rng, 0.05, 0.3)

    hornblende_size = pf.random.log_normal(rng, 0.3, 0.25)
    hornblende_color_variation = pf.random.clip_gaussian(rng, 0.7549, 0.15)
    hornblende_height = pf.random.log_normal(rng, 0.1, 0.3)

    mica_size = pf.random.log_normal(rng, 0.5, 0.25)
    mica_spread = pf.random.clip_gaussian(rng, 0.2647, 0.1)
    mica_smoothness = pf.random.clip_gaussian(rng, 0.0245, 0.02, low=0.0, high=0.2)
    mica_color_variation = pf.random.clip_gaussian(rng, 0.6716, 0.15)
    mica_height = pf.random.log_normal(rng, 0.15, 0.3)

    quartz_size = pf.random.log_normal(rng, 0.1, 0.25)
    quartz_spread = pf.random.clip_gaussian(rng, 0.3725, 0.1)
    quartz_smoothness = pf.random.clip_gaussian(rng, 0.02, 0.02, low=0.0, high=0.2)
    quartz_color_variation = pf.random.clip_gaussian(rng, 0.452, 0.15)
    quartz_height = pf.random.log_normal(rng, 0.22, 0.3)

    feldspar_size = pf.random.log_normal(rng, 0.3, 0.25)
    feldspar_spread = pf.random.clip_gaussian(rng, 0.2059, 0.1)
    feldspar_smoothness = pf.random.clip_gaussian(rng, 0.1, 0.05)
    feldspar_color_variation = pf.random.clip_gaussian(rng, 0.6078, 0.15)
    feldspar_height = pf.random.log_normal(rng, 0.3, 0.3)

    return granite(
        vector=vector,
        w=w,
        size=size,
        min_roughness=min_roughness,
        max_roughness=max_roughness,
        min_spec=min_spec,
        max_spec=max_spec,
        height_scale=height_scale,
        hornblende_size=hornblende_size,
        hornblende_color=hornblende_color,
        hornblende_color_variation=hornblende_color_variation,
        hornblende_height=hornblende_height,
        mica_size=mica_size,
        mica_spread=mica_spread,
        mica_smoothness=mica_smoothness,
        mica_color=mica_color,
        mica_color_variation=mica_color_variation,
        mica_height=mica_height,
        quartz_size=quartz_size,
        quartz_spread=quartz_spread,
        quartz_smoothness=quartz_smoothness,
        quartz_color=quartz_color,
        quartz_color_variation=quartz_color_variation,
        quartz_height=quartz_height,
        feldspar_size=feldspar_size,
        feldspar_spread=feldspar_spread,
        feldspar_smoothness=feldspar_smoothness,
        feldspar_color=feldspar_color,
        feldspar_color_variation=feldspar_color_variation,
        feldspar_height=feldspar_height,
    )


def _granite_white_brown_distribution(
    vector: t.SocketOrVal[pf.Vector],
    w: float | None,
    rng: pf.RNG,
    min_roughness: float | None = None,
    max_roughness: float | None = None,
) -> pf.Material:
    """Granite white_brown style - varied roughness, larger features (uses gradient)."""
    if w is None:
        w = pf.random.uniform(rng, 0.0, 100.0)
    # Sample colors
    base_warm = _warm_color_distribution(rng)
    gradient_color = _create_gradient_color(rng, vector, base_warm)
    hornblende_color = _dark_accent_color_distribution(rng)
    mica_color = gradient_color
    quartz_color = gradient_color
    feldspar_color = _light_accent_color_distribution(rng)

    # Sample parameters
    size = pf.random.log_normal(rng, 10.0, 0.25)
    if min_roughness is None or max_roughness is None:
        mean_roughness_min = pf.random.uniform(rng, 0.2554, 0.4118)
        mean_roughness_max = pf.random.uniform(rng, mean_roughness_min, 0.6118)
        min_roughness, max_roughness = _sample_pair_bounded(
            rng, mean_roughness_min, mean_roughness_max, std=0.08
        )
    min_spec, max_spec = _sample_pair_bounded(rng, 0.026, 0.1299, std=0.04)
    height_scale = pf.random.log_normal(rng, 0.5, 0.3)

    hornblende_color_variation = pf.random.clip_gaussian(
        rng, 0.0, 0.05, low=0.0, high=0.2
    )
    hornblende_height = pf.random.log_normal(rng, 0.1, 0.3)

    mica_spread = pf.random.clip_gaussian(rng, 0.5, 0.15)
    mica_smoothness = pf.random.clip_gaussian(rng, 0.05, 0.03)
    mica_color_variation = pf.random.clip_gaussian(rng, 0.451, 0.15)
    mica_height = pf.random.log_normal(rng, 0.25, 0.3)

    quartz_size = pf.random.log_normal(rng, 0.2, 0.25)
    quartz_spread = pf.random.clip_gaussian(rng, 0.5, 0.15)
    quartz_smoothness = pf.random.clip_gaussian(rng, 0.05, 0.03)
    quartz_color_variation = pf.random.clip_gaussian(rng, 0.3235, 0.15)
    quartz_height = pf.random.log_normal(rng, 0.5, 0.3)

    feldspar_size = pf.random.log_normal(rng, 0.3, 0.25)
    feldspar_spread = pf.random.clip_gaussian(rng, 0.2, 0.1)
    feldspar_smoothness = pf.random.clip_gaussian(rng, 0.1, 0.05)
    feldspar_height = pf.random.log_normal(rng, 0.75, 0.3)

    return granite(
        vector=vector,
        w=w,
        size=size,
        min_roughness=min_roughness,
        max_roughness=max_roughness,
        min_spec=min_spec,
        max_spec=max_spec,
        height_scale=height_scale,
        hornblende_color=hornblende_color,
        hornblende_color_variation=hornblende_color_variation,
        hornblende_height=hornblende_height,
        mica_spread=mica_spread,
        mica_smoothness=mica_smoothness,
        mica_color=mica_color,
        mica_color_variation=mica_color_variation,
        mica_height=mica_height,
        quartz_size=quartz_size,
        quartz_spread=quartz_spread,
        quartz_smoothness=quartz_smoothness,
        quartz_color=quartz_color,
        quartz_color_variation=quartz_color_variation,
        quartz_height=quartz_height,
        feldspar_size=feldspar_size,
        feldspar_spread=feldspar_spread,
        feldspar_smoothness=feldspar_smoothness,
        feldspar_color=feldspar_color,
        feldspar_height=feldspar_height,
    )


def _granite_no_displacement_distribution(
    vector: t.SocketOrVal[pf.Vector],
    w: float | None,
    rng: pf.RNG,
    min_roughness: float | None = None,
    max_roughness: float | None = None,
) -> pf.Material:
    """Granite grey style - cool background (uses gradient)."""
    if w is None:
        w = pf.random.uniform(rng, 0.0, 100.0)
    # Sample colors
    base_cool = _cool_color_distribution(rng)
    hornblende_color = _dark_accent_color_distribution(rng)
    mica_color = _create_gradient_color(rng, vector, base_cool)
    quartz_color = _light_accent_color_distribution(rng)
    feldspar_color = _light_accent_color_distribution(rng)

    # Sample parameters
    size = pf.random.log_normal(rng, 10.0, 0.25)
    if min_roughness is None or max_roughness is None:
        min_roughness, max_roughness = _sample_pair_bounded(
            rng, 0.0824, 0.1522, std=0.05
        )
    min_spec, max_spec = _sample_pair_bounded(rng, 0.05, 0.1, std=0.03)

    hornblende_size = pf.random.log_normal(rng, 0.3, 0.25)
    hornblende_color_variation = pf.random.clip_gaussian(rng, 0.7549, 0.15)
    hornblende_height = pf.random.log_normal(rng, 0.1, 0.3)

    mica_size = pf.random.log_normal(rng, 0.5, 0.25)
    mica_spread = pf.random.clip_gaussian(rng, 0.5741, 0.15)
    mica_smoothness = pf.random.clip_gaussian(rng, 0.05, 0.03)
    mica_color_variation = pf.random.clip_gaussian(rng, 0.6716, 0.15)
    mica_height = pf.random.log_normal(rng, 0.25, 0.3)

    quartz_size = pf.random.log_normal(rng, 0.2, 0.25)
    quartz_spread = pf.random.clip_gaussian(rng, 0.5, 0.15)
    quartz_smoothness = pf.random.clip_gaussian(rng, 0.02, 0.02, low=0.0, high=0.15)
    quartz_color_variation = pf.random.clip_gaussian(rng, 0.452, 0.15)
    quartz_height = pf.random.log_normal(rng, 0.22, 0.3)

    feldspar_size = pf.random.log_normal(rng, 0.2, 0.25)
    feldspar_spread = pf.random.clip_gaussian(rng, 0.25, 0.1)
    feldspar_smoothness = pf.random.clip_gaussian(rng, 0.2, 0.08)
    feldspar_color_variation = pf.random.clip_gaussian(rng, 0.6078, 0.15)
    feldspar_height = pf.random.log_normal(rng, 0.15, 0.3)

    granite_result = granite(
        vector=vector,
        w=w,
        size=size,
        min_roughness=min_roughness,
        max_roughness=max_roughness,
        min_spec=min_spec,
        max_spec=max_spec,
        hornblende_size=hornblende_size,
        hornblende_color=hornblende_color,
        hornblende_color_variation=hornblende_color_variation,
        hornblende_height=hornblende_height,
        mica_size=mica_size,
        mica_spread=mica_spread,
        mica_smoothness=mica_smoothness,
        mica_color=mica_color,
        mica_color_variation=mica_color_variation,
        mica_height=mica_height,
        quartz_size=quartz_size,
        quartz_spread=quartz_spread,
        quartz_smoothness=quartz_smoothness,
        quartz_color=quartz_color,
        quartz_color_variation=quartz_color_variation,
        quartz_height=quartz_height,
        feldspar_size=feldspar_size,
        feldspar_spread=feldspar_spread,
        feldspar_smoothness=feldspar_smoothness,
        feldspar_color=feldspar_color,
        feldspar_color_variation=feldspar_color_variation,
        feldspar_height=feldspar_height,
    )
    return pf.Material(
        surface=granite_result.surface,
    )


def _granite_crystals_distribution(
    vector: t.SocketOrVal[pf.Vector],
    w: float | None,
    rng: pf.RNG,
    min_roughness: float | None = None,
    max_roughness: float | None = None,
) -> pf.Material:
    """Granite crystals style - very fine detail (uses gradient like grey)."""
    if w is None:
        w = pf.random.uniform(rng, 0.0, 100.0)
    # Sample colors
    base_cool = _cool_color_distribution(rng)
    hornblende_color = _dark_accent_color_distribution(rng)
    mica_color = _create_gradient_color(rng, vector, base_cool)
    quartz_color = _light_accent_color_distribution(rng)
    feldspar_color = _light_accent_color_distribution(rng)

    # Sample parameters
    size = pf.random.log_normal(rng, 100.0, 0.25)
    height_scale = pf.random.log_normal(rng, 0.01, 0.3)
    if min_roughness is None or max_roughness is None:
        mean_roughness_min = pf.random.uniform(rng, 0.2, 0.3)
        mean_roughness_max = pf.random.uniform(rng, mean_roughness_min, 0.5)
        min_roughness, max_roughness = _sample_pair_bounded(
            rng, mean_roughness_min, mean_roughness_max, std=0.05
        )
    min_spec, max_spec = _sample_pair_bounded(rng, 0.05, 0.1, std=0.03)

    hornblende_size = pf.random.log_normal(rng, 0.3, 0.25)
    hornblende_color_variation = pf.random.clip_gaussian(rng, 0.7549, 0.15)
    hornblende_height = pf.random.log_normal(rng, 0.1, 0.3)

    mica_size = pf.random.log_normal(rng, 0.5, 0.25)
    mica_spread = pf.random.clip_gaussian(rng, 0.5741, 0.15)
    mica_smoothness = pf.random.clip_gaussian(rng, 0.05, 0.03)
    mica_color_variation = pf.random.clip_gaussian(rng, 0.6716, 0.15)
    mica_height = pf.random.log_normal(rng, 0.25, 0.3)

    quartz_size = pf.random.log_normal(rng, 0.15, 0.25)
    quartz_spread = pf.random.clip_gaussian(rng, 0.45, 0.15)
    quartz_smoothness = pf.random.clip_gaussian(rng, 0.02, 0.02, low=0.0, high=0.15)
    quartz_color_variation = pf.random.clip_gaussian(rng, 0.452, 0.15)
    quartz_height = pf.random.log_normal(rng, 0.3, 0.3)

    feldspar_size = pf.random.log_normal(rng, 0.2, 0.25)
    feldspar_spread = pf.random.clip_gaussian(rng, 0.2608, 0.1)
    feldspar_smoothness = pf.random.clip_gaussian(rng, 0.2, 0.08)
    feldspar_color_variation = pf.random.clip_gaussian(rng, 0.6078, 0.15)
    feldspar_height = pf.random.log_normal(rng, 0.15, 0.3)

    return granite(
        vector=vector,
        w=w,
        size=size,
        height_scale=height_scale,
        min_roughness=min_roughness,
        max_roughness=max_roughness,
        min_spec=min_spec,
        max_spec=max_spec,
        hornblende_size=hornblende_size,
        hornblende_color=hornblende_color,
        hornblende_color_variation=hornblende_color_variation,
        hornblende_height=hornblende_height,
        mica_size=mica_size,
        mica_spread=mica_spread,
        mica_smoothness=mica_smoothness,
        mica_color=mica_color,
        mica_color_variation=mica_color_variation,
        mica_height=mica_height,
        quartz_size=quartz_size,
        quartz_spread=quartz_spread,
        quartz_smoothness=quartz_smoothness,
        quartz_color=quartz_color,
        quartz_color_variation=quartz_color_variation,
        quartz_height=quartz_height,
        feldspar_size=feldspar_size,
        feldspar_spread=feldspar_spread,
        feldspar_smoothness=feldspar_smoothness,
        feldspar_color=feldspar_color,
        feldspar_color_variation=feldspar_color_variation,
        feldspar_height=feldspar_height,
    )


def _granite_cobble_distribution(
    vector: t.SocketOrVal[pf.Vector],
    w: float | None,
    rng: pf.RNG,
    min_roughness: float | None = None,
    max_roughness: float | None = None,
) -> pf.Material:
    """Granite cobble_gray style - rough, weathered (simple colors)."""
    if w is None:
        w = pf.random.uniform(rng, 0.0, 100.0)
    # Sample colors
    hornblende_color = _dark_accent_color_distribution(rng)
    mica_color = _cool_color_distribution(rng)
    quartz_color = _light_accent_color_distribution(rng)
    feldspar_color = _light_accent_color_distribution(rng)

    # Sample parameters
    size = pf.random.log_normal(rng, 7.0, 0.25)
    if min_roughness is None or max_roughness is None:
        min_roughness, max_roughness = _sample_pair_bounded(
            rng, 0.5013, 0.8333, std=0.1
        )
    min_spec, max_spec = _sample_pair_bounded(rng, 0.0538, 0.0753, std=0.02)
    height_scale = pf.random.log_normal(rng, 0.25, 0.3)

    hornblende_color_variation = pf.random.clip_gaussian(rng, 0.4355, 0.15)
    # hornblende_height stays 0 for cobble style

    mica_size = pf.random.log_normal(rng, 0.4, 0.25)
    mica_spread = pf.random.clip_gaussian(rng, 1.0, 0.1, low=0.5, high=1.0)
    mica_smoothness = pf.random.clip_gaussian(rng, 0.2113, 0.08)
    mica_color_variation = pf.random.clip_gaussian(rng, 0.5645, 0.15)
    mica_height = pf.random.log_normal(rng, 1.8, 0.3)

    quartz_size = pf.random.log_normal(rng, 0.5, 0.25)
    quartz_spread = pf.random.clip_gaussian(rng, 0.8548, 0.1)
    quartz_smoothness = pf.random.clip_gaussian(rng, 0.5554, 0.15)
    quartz_color_variation = pf.random.clip_gaussian(rng, 0.3871, 0.15)
    quartz_height = pf.random.log_normal(rng, 2.7, 0.3)

    feldspar_size = pf.random.log_normal(rng, 0.3, 0.25)
    feldspar_spread = pf.random.clip_gaussian(rng, 0.3, 0.1)
    feldspar_smoothness = pf.random.clip_gaussian(rng, 0.25, 0.1)
    feldspar_color_variation = pf.random.clip_gaussian(rng, 0.6075, 0.15)
    feldspar_height = pf.random.log_normal(rng, 0.5, 0.3)

    return granite(
        vector=vector,
        w=w,
        size=size,
        min_roughness=min_roughness,
        max_roughness=max_roughness,
        min_spec=min_spec,
        max_spec=max_spec,
        height_scale=height_scale,
        hornblende_color=hornblende_color,
        hornblende_color_variation=hornblende_color_variation,
        hornblende_height=0.0,  # Keep at 0 for cobble
        mica_size=mica_size,
        mica_spread=mica_spread,
        mica_smoothness=mica_smoothness,
        mica_color=mica_color,
        mica_color_variation=mica_color_variation,
        mica_height=mica_height,
        quartz_size=quartz_size,
        quartz_spread=quartz_spread,
        quartz_smoothness=quartz_smoothness,
        quartz_color=quartz_color,
        quartz_color_variation=quartz_color_variation,
        quartz_height=quartz_height,
        feldspar_size=feldspar_size,
        feldspar_spread=feldspar_spread,
        feldspar_smoothness=feldspar_smoothness,
        feldspar_color=feldspar_color,
        feldspar_color_variation=feldspar_color_variation,
        feldspar_height=feldspar_height,
    )


def _granite_masonry_distribution(
    vector: t.SocketOrVal[pf.Vector],
    w: float | None,
    rng: pf.RNG,
    min_roughness: float | None = None,
    max_roughness: float | None = None,
) -> pf.Material:
    """Granite masonry_gray style - medium rough (simple colors)."""
    if w is None:
        w = pf.random.uniform(rng, 0.0, 100.0)
    # Sample colors
    hornblende_color = _dark_accent_color_distribution(rng)
    mica_color = _cool_color_distribution(rng)
    quartz_color = _light_accent_color_distribution(rng)
    feldspar_color = _light_accent_color_distribution(rng)

    # Sample parameters
    size = pf.random.log_normal(rng, 1.0, 0.25)
    if min_roughness is None or max_roughness is None:
        mean_roughness_min = pf.random.uniform(rng, 0.6583, 0.8333)
        mean_roughness_max = pf.random.uniform(rng, mean_roughness_min, 0.90)
        min_roughness, max_roughness = _sample_pair_bounded(
            rng, mean_roughness_min, mean_roughness_max, std=0.1
        )
    min_spec, max_spec = _sample_pair_bounded(rng, 0.075, 0.2083, std=0.05)
    height_scale = pf.random.log_normal(rng, 0.5, 0.3)

    hornblende_height = pf.random.log_normal(rng, 0.1, 0.3)

    mica_spread = pf.random.clip_gaussian(rng, 0.45, 0.15)
    mica_smoothness = pf.random.clip_gaussian(rng, 0.05, 0.03)
    mica_height = pf.random.log_normal(rng, 0.25, 0.3)

    quartz_size = pf.random.log_normal(rng, 0.2, 0.25)
    quartz_spread = pf.random.clip_gaussian(rng, 0.5, 0.15)
    quartz_smoothness = pf.random.clip_gaussian(rng, 0.05, 0.03)
    quartz_height = pf.random.log_normal(rng, 0.5, 0.3)

    feldspar_size = pf.random.log_normal(rng, 0.3, 0.25)
    feldspar_spread = pf.random.clip_gaussian(rng, 0.2, 0.1)
    feldspar_smoothness = pf.random.clip_gaussian(rng, 0.1, 0.05)
    feldspar_height = pf.random.log_normal(rng, 0.75, 0.3)

    return granite(
        vector=vector,
        w=w,
        size=size,
        min_roughness=min_roughness,
        max_roughness=max_roughness,
        min_spec=min_spec,
        max_spec=max_spec,
        height_scale=height_scale,
        hornblende_color=hornblende_color,
        hornblende_height=hornblende_height,
        mica_spread=mica_spread,
        mica_smoothness=mica_smoothness,
        mica_color=mica_color,
        mica_height=mica_height,
        quartz_size=quartz_size,
        quartz_spread=quartz_spread,
        quartz_smoothness=quartz_smoothness,
        quartz_color=quartz_color,
        quartz_height=quartz_height,
        feldspar_size=feldspar_size,
        feldspar_spread=feldspar_spread,
        feldspar_smoothness=feldspar_smoothness,
        feldspar_color=feldspar_color,
        feldspar_height=feldspar_height,
    )


def _granite_sandy_distribution(
    vector: t.SocketOrVal[pf.Vector],
    w: float | None,
    rng: pf.RNG,
    min_roughness: float | None = None,
    max_roughness: float | None = None,
) -> pf.Material:
    """Granite sandy style - warm sandy (simple colors)."""
    if w is None:
        w = pf.random.uniform(rng, 0.0, 100.0)
    # Sample colors
    hornblende_color = _warm_color_distribution(rng)
    mica_color = _warm_color_distribution(rng)
    quartz_color = _warm_color_distribution(rng)
    feldspar_color = _light_accent_color_distribution(rng)

    # Sample parameters
    size = pf.random.log_normal(rng, 7.0, 0.25)
    if min_roughness is None or max_roughness is None:
        min_roughness, max_roughness = _sample_pair_bounded(
            rng, 0.6013, 0.8533, std=0.1
        )
    min_spec, max_spec = _sample_pair_bounded(rng, 0.0538, 0.0753, std=0.02)
    height_scale = pf.random.log_normal(rng, 0.25, 0.3)

    hornblende_size = pf.random.log_normal(rng, 0.1, 0.25)
    hornblende_color_variation = pf.random.clip_gaussian(rng, 0.3817, 0.15)
    hornblende_height = pf.random.log_normal(rng, 0.1, 0.3)

    mica_size = pf.random.log_normal(rng, 0.5, 0.25)
    mica_spread = pf.random.clip_gaussian(rng, 0.4892, 0.15)
    mica_smoothness = pf.random.clip_gaussian(rng, 0.1522, 0.08)
    mica_color_variation = pf.random.clip_gaussian(rng, 0.5645, 0.15)
    mica_height = pf.random.log_normal(rng, 1.8, 0.3)

    quartz_size = pf.random.log_normal(rng, 0.2, 0.25)
    quartz_spread = pf.random.clip_gaussian(rng, 0.6882, 0.15)
    quartz_smoothness = pf.random.clip_gaussian(rng, 0.2167, 0.08)
    quartz_color_variation = pf.random.clip_gaussian(rng, 0.3871, 0.15)
    quartz_height = pf.random.log_normal(rng, 2.7, 0.3)

    feldspar_size = pf.random.log_normal(rng, 0.1, 0.25)
    feldspar_spread = pf.random.clip_gaussian(rng, 0.0, 0.05, low=0.0, high=0.15)
    feldspar_smoothness = pf.random.clip_gaussian(rng, 0.25, 0.1)
    feldspar_color_variation = pf.random.clip_gaussian(rng, 0.6075, 0.15)
    feldspar_height = pf.random.log_normal(rng, 0.5, 0.3)

    return granite(
        vector=vector,
        w=w,
        size=size,
        min_roughness=min_roughness,
        max_roughness=max_roughness,
        min_spec=min_spec,
        max_spec=max_spec,
        height_scale=height_scale,
        hornblende_size=hornblende_size,
        hornblende_color=hornblende_color,
        hornblende_color_variation=hornblende_color_variation,
        hornblende_height=hornblende_height,
        mica_size=mica_size,
        mica_spread=mica_spread,
        mica_smoothness=mica_smoothness,
        mica_color=mica_color,
        mica_color_variation=mica_color_variation,
        mica_height=mica_height,
        quartz_size=quartz_size,
        quartz_spread=quartz_spread,
        quartz_smoothness=quartz_smoothness,
        quartz_color=quartz_color,
        quartz_color_variation=quartz_color_variation,
        quartz_height=quartz_height,
        feldspar_size=feldspar_size,
        feldspar_spread=feldspar_spread,
        feldspar_smoothness=feldspar_smoothness,
        feldspar_color=feldspar_color,
        feldspar_color_variation=feldspar_color_variation,
        feldspar_height=feldspar_height,
    )


def granite_distribution(
    rng: pf.RNG,
    vector: t.SocketOrVal[pf.Vector],
    w: float | None = None,
    min_roughness: float | None = None,
    max_roughness: float | None = None,
) -> pf.Material:
    """Granite distribution with randomized colors AND parameters.

    Colors are sampled to match template style (using gradients where demos use them).
    All other parameters are sampled around demo anchor values using appropriate distributions:
    - Scale params (size, heights): log-normal with ~25% relative std
    - Bounded params (roughness, spread, smoothness, variation): clipped normal
    """
    # Select template function and call it
    func = pf.control.choice(
        rng,
        [
            (_granite_yellow_distribution, 1.0),
            (_granite_white_brown_distribution, 1.0),
            (_granite_no_displacement_distribution, 1.0),
            (_granite_crystals_distribution, 1.0),
            (_granite_cobble_distribution, 1.0),
            (_granite_masonry_distribution, 1.0),
            (_granite_sandy_distribution, 1.0),
        ],
    )

    result = func(
        vector=vector,
        w=w,
        rng=rng,
        min_roughness=min_roughness,
        max_roughness=max_roughness,
    )
    return pf.Material(surface=result.surface, displacement=result.displacement)


def granite_smooth_distribution(
    rng: pf.RNG,
    vector: t.SocketOrVal[pf.Vector],
    w: float | None = None,
    min_roughness: float | None = None,
    max_roughness: float | None = None,
) -> pf.Material:
    """Granite distribution with smooth roughness and no displacement."""
    if min_roughness is None or max_roughness is None:
        min_roughness, max_roughness = _sample_pair_bounded(
            rng, 0.0824, 0.1522, std=0.05
        )
    result = granite_distribution(
        rng=rng,
        vector=vector,
        w=w,
        min_roughness=min_roughness,
        max_roughness=max_roughness,
    )
    return pf.Material(
        surface=result.surface,
    )


if __name__ == "__main__":
    # Code generated by procfunc v0.13.2

    yellow_result = granite_yellow(vector=(0.0, 0.0, 0.0))
