from typing import NamedTuple

import procfunc as pf
from procfunc.nodes import types as t

from infinigen_v2.generators.shaders.util.coord import coord_warp


class GravelResult(NamedTuple):
    color: pf.ProcNode[pf.Color]
    spec: pf.ProcNode[float]
    roughness: pf.ProcNode[float]
    height: pf.ProcNode[float]
    mask: pf.ProcNode[float]


@pf.nodes.node_function
def small_gravel(
    vector: t.SocketOrVal[pf.Vector],
    base_color: t.SocketOrVal[pf.Color],
    base_spec: t.SocketOrVal[float],
    base_rough: t.SocketOrVal[float],
    base_height: t.SocketOrVal[float],
    mask: t.SocketOrVal[float],
    surface_gravel_color: t.SocketOrVal[pf.Color],
    surface_hue_variation: t.SocketOrVal[float],
    surface_sat_variation: t.SocketOrVal[float],
    surface_value_variation: t.SocketOrVal[float],
    surface_min_spec: t.SocketOrVal[float],
    surface_max_spec: t.SocketOrVal[float],
    surface_min_roughness: t.SocketOrVal[float],
    surface_max_roughness: t.SocketOrVal[float],
    shape_size: t.SocketOrVal[float],
    shape_height: t.SocketOrVal[float],
    shape_height_variation: t.SocketOrVal[float],
    shape_up_down: t.SocketOrVal[float],
    shape_distortion_strength: t.SocketOrVal[float],
    shape_spread: t.SocketOrVal[float],
    shape_bevel: t.SocketOrVal[float],
    shape_w: t.SocketOrVal[float],
) -> GravelResult:
    # Code generated by procfunc v0.12.0

    voronoi_scale_denominator = shape_size * 0.015

    coord_warp_result = coord_warp(
        vector=vector,
        size=voronoi_scale_denominator,
        strength=shape_distortion_strength,
        detail=8.0,
        phase=shape_w,
    )

    voronoi = pf.nodes.texture.voronoi(
        normalize=True,
        vector=coord_warp_result.vector,
        scale=1.0 / voronoi_scale_denominator,
    )

    color_from_min = pf.nodes.math.mix(
        factor=shape_bevel, a=shape_spread - 0.0001, b=0.0
    )
    color_factor_b_a = pf.nodes.math.map_range(
        value=voronoi.distance,
        from_min=color_from_min,
        from_max=shape_spread,
        to_min=1.0,
        to_max=0.0,
    )
    color_factor_b = color_factor_b_a > 0.0
    color_factor = mask * color_factor_b
    color_x = surface_hue_variation / 2.0
    color_b_hue_to_min = pf.nodes.math.combine_xyz(
        x=0.5 - color_x,
        y=1.0 - surface_sat_variation,
        z=1.0 - surface_value_variation,
    )
    color_b_hue_to_max = pf.nodes.math.combine_xyz(x=0.5 + color_x, y=1.0, z=1.0)
    color_b_hue = pf.nodes.math.map_range(
        value=voronoi.color.astype(dtype=pf.Vector),
        from_min=(0.0, 0.0, 0.0),
        from_max=(1.0, 1.0, 1.0),
        to_min=color_b_hue_to_min,
        to_max=color_b_hue_to_max,
    )

    hue_saturation = pf.nodes.color.hue_saturation(
        fac=1.0,
        hue=color_b_hue.x,
        saturation=color_b_hue.y,
        value=color_b_hue.z,
        color=surface_gravel_color,
    )

    color = pf.nodes.color.mix_rgb(factor=color_factor, a=base_color, b=hue_saturation)

    white_noise = pf.nodes.texture.white_noise(
        noise_dimensions="1D",
        w=voronoi.color.astype(dtype=pf.Vector).x,
    )

    spec_b = pf.nodes.math.map_range(
        value=white_noise.color.astype(dtype=pf.Vector).y,
        from_min=0.1,
        from_max=0.2,
        to_min=surface_min_spec,
        to_max=surface_max_spec,
    )
    spec = pf.nodes.math.mix(factor=color_factor, a=base_spec, b=spec_b)

    roughness_b = pf.nodes.math.map_range(
        value=white_noise.color.astype(dtype=pf.Vector).z,
        from_min=0.5,
        from_max=0.7,
        to_min=surface_min_roughness,
        to_max=surface_max_roughness,
    )
    roughness = pf.nodes.math.mix(factor=color_factor, a=base_rough, b=roughness_b)

    height_b_0 = 1.0 - shape_up_down
    height_a_1 = (shape_size * shape_height) * 0.1
    height_a_a_0 = (color_factor_b_a - height_b_0) * (height_a_1 * mask)
    height_a_0 = pf.nodes.math.mix(
        factor=shape_height_variation,
        a=height_a_a_0,
        b=height_a_a_0 * white_noise.fac,
    )
    height = height_a_0 + base_height

    mask_1 = pf.nodes.math.minimum(a=mask, b=1.0 - color_factor_b)
    return GravelResult(
        color=color,
        spec=spec,
        roughness=roughness,
        height=height,
        mask=mask_1,
    )


@pf.nodes.node_function
def large_gravel(
    vector: t.SocketOrVal[pf.Vector],
    base_color: t.SocketOrVal[pf.Color],
    base_spec: t.SocketOrVal[float],
    base_roughness: t.SocketOrVal[float],
    base_height: t.SocketOrVal[float],
    mask: t.SocketOrVal[float],
    surface_gravel_color: t.SocketOrVal[pf.Color],
    surface_hue_variation: t.SocketOrVal[float],
    surface_sat_variation: t.SocketOrVal[float],
    surface_value_variation: t.SocketOrVal[float],
    surface_min_spec: t.SocketOrVal[float],
    surface_max_spec: t.SocketOrVal[float],
    surface_min_roughness: t.SocketOrVal[float],
    surface_max_roughness: t.SocketOrVal[float],
    shape_rounded_sharp: t.SocketOrVal[float],
    shape_texture_size: t.SocketOrVal[float],
    shape_height: t.SocketOrVal[float],
    shape_height_variation: t.SocketOrVal[float],
    shape_up_down: t.SocketOrVal[float],
    shape_margin: t.SocketOrVal[float],
    shape_distortion_strength: t.SocketOrVal[float],
    shape_gravel_size: t.SocketOrVal[float],
    shape_bevel: t.SocketOrVal[float],
    shape_w: t.SocketOrVal[float],
) -> GravelResult:
    # Code generated by procfunc v0.12.0

    color_0_scale_denominator = shape_texture_size * 0.15

    coord_warp_result = coord_warp(
        vector=vector,
        size=color_0_scale_denominator,
        strength=shape_distortion_strength,
        detail=8.0,
        phase=shape_w,
    )

    color_0_scale = 1.0 / color_0_scale_denominator

    voronoi = pf.nodes.texture.voronoi(
        normalize=True,
        voronoi_dimensions="4D",
        vector=coord_warp_result.vector,
        w=shape_w,
        scale=color_0_scale,
    )
    voronoi_smooth_f1 = pf.nodes.texture.voronoi_smooth_f1(
        normalize=True,
        voronoi_dimensions="4D",
        vector=coord_warp_result.vector,
        w=shape_w,
        scale=color_0_scale,
        smoothness=1.0,
    )

    height_value_a_value = pf.nodes.math.clamp(
        voronoi.distance - voronoi_smooth_f1.distance
    )
    height_value_a = pf.nodes.math.map_range(
        value=height_value_a_value,
        from_max=0.16,
        to_min=1.0,
        to_max=0.0,
    )

    voronoi_distance = pf.nodes.texture.voronoi_distance(
        normalize=True,
        voronoi_dimensions="4D",
        vector=coord_warp_result.vector,
        w=shape_w,
        scale=color_0_scale,
    )

    height_value = pf.nodes.math.mix(
        factor=shape_rounded_sharp,
        a=height_value_a,
        b=voronoi_distance * 2.0,
    )
    height_from_min = 1.0 - shape_gravel_size
    height_from_max = pf.nodes.math.mix(factor=shape_rounded_sharp, a=1.0, b=1.07)
    height_a_base_value = pf.nodes.math.map_range(
        value=height_value,
        from_min=height_from_min * height_from_max,
        from_max=height_from_max,
    )
    height_a_base_from_max = pf.nodes.math.maximum(a=shape_margin, b=0.0001)

    color_value = pf.nodes.math.map_range(
        value=height_a_base_value, from_min=height_a_base_from_max
    )
    color_from_max = pf.nodes.math.maximum(a=shape_bevel, b=0.0001)
    color_factor_b_a = pf.nodes.math.map_range(
        value=color_value, from_max=color_from_max
    )
    color_factor = mask * (color_factor_b_a > 0.0)
    color_x = surface_hue_variation / 2.0
    color_b_hue_to_min = pf.nodes.math.combine_xyz(
        x=0.5 - color_x,
        y=1.0 - surface_sat_variation,
        z=1.0 - surface_value_variation,
    )
    color_b_hue_to_max = pf.nodes.math.combine_xyz(x=0.5 + color_x, y=1.0, z=1.0)
    color_b_hue = pf.nodes.math.map_range(
        value=voronoi.color.astype(dtype=pf.Vector),
        from_min=(0.0, 0.0, 0.0),
        from_max=(1.0, 1.0, 1.0),
        to_min=color_b_hue_to_min,
        to_max=color_b_hue_to_max,
    )

    hue_saturation = pf.nodes.color.hue_saturation(
        fac=1.0,
        hue=color_b_hue.x,
        saturation=color_b_hue.y,
        value=color_b_hue.z,
        color=surface_gravel_color,
    )

    color = pf.nodes.color.mix_rgb(factor=color_factor, a=base_color, b=hue_saturation)

    white_noise_vector = pf.nodes.math.combine_xyz(
        x=voronoi.color.astype(dtype=pf.Vector).x, y=shape_w
    )
    white_noise = pf.nodes.texture.white_noise(
        noise_dimensions="2D", vector=white_noise_vector
    )

    spec_b = pf.nodes.math.map_range(
        value=white_noise.color.astype(dtype=pf.Vector).y,
        to_min=surface_min_spec,
        to_max=surface_max_spec,
    )
    spec = pf.nodes.math.mix(factor=color_factor, a=base_spec, b=spec_b)

    roughness_b = pf.nodes.math.map_range(
        value=white_noise.color.astype(dtype=pf.Vector).z,
        to_min=surface_min_roughness,
        to_max=surface_max_roughness,
    )
    roughness = pf.nodes.math.mix(factor=color_factor, a=base_roughness, b=roughness_b)

    height_a_2 = color_factor_b_a
    height_b_1 = 1.0 - shape_up_down
    height_b_0 = shape_texture_size * shape_height
    height_a_a = (height_a_2 - height_b_1) * (mask * height_b_0)
    height_a_1 = pf.nodes.math.mix(
        factor=shape_height_variation,
        a=height_a_a,
        b=height_a_a * white_noise.color.astype(dtype=pf.Vector).x,
    )
    height_a_base = pf.nodes.math.map_range(
        value=height_a_base_value, from_max=height_a_base_from_max
    )
    height_a_0 = height_a_base**3.0
    height = (height_a_1 * height_a_0) + base_height

    mask_1 = pf.nodes.math.minimum(a=mask, b=1.0 - height_a_0)
    return GravelResult(
        color=color,
        spec=spec,
        roughness=roughness,
        height=height,
        mask=mask_1,
    )


def gravel_concrete_sharp_polished(
    vector: t.SocketOrVal[pf.Vector],
) -> pf.Material:
    # Code generated by procfunc v0.12.0

    large_gravel_result = large_gravel(
        vector=vector,
        base_color=pf.Color((0.037, 0.046, 0.048)),
        base_spec=0.0,
        base_roughness=0.7,
        base_height=0.0,
        mask=1.0,
        surface_gravel_color=pf.Color((0.013, 0.017, 0.018)),
        surface_hue_variation=0.088235,
        surface_sat_variation=0.229412,
        surface_value_variation=0.376471,
        surface_min_spec=0.05,
        surface_max_spec=0.1,
        surface_min_roughness=0.2,
        surface_max_roughness=0.3,
        shape_rounded_sharp=1.0,
        shape_texture_size=0.13,
        shape_height=0.5,
        shape_height_variation=0.5,
        shape_up_down=0.864706,
        shape_margin=0.0001,
        shape_distortion_strength=0.5,
        shape_gravel_size=0.7,
        shape_bevel=0.235294,
        shape_w=0.0,
    )
    large_gravel_result_1 = large_gravel(
        vector=vector,
        base_color=large_gravel_result.color,
        base_spec=large_gravel_result.spec,
        base_roughness=large_gravel_result.roughness,
        base_height=large_gravel_result.height,
        mask=large_gravel_result.mask,
        surface_gravel_color=pf.Color((0.015, 0.019, 0.02)),
        surface_hue_variation=0.088235,
        surface_sat_variation=0.229412,
        surface_value_variation=0.376471,
        surface_min_spec=0.05,
        surface_max_spec=0.1,
        surface_min_roughness=0.2,
        surface_max_roughness=0.3,
        shape_rounded_sharp=1.0,
        shape_texture_size=0.11,
        shape_height=0.5,
        shape_height_variation=0.5,
        shape_up_down=0.864706,
        shape_margin=0.0001,
        shape_distortion_strength=0.5,
        shape_gravel_size=0.7,
        shape_bevel=0.235294,
        shape_w=4.08,
    )

    small_gravel_result = small_gravel(
        vector=vector,
        base_color=large_gravel_result_1.color,
        base_spec=large_gravel_result_1.spec,
        base_rough=large_gravel_result_1.roughness,
        base_height=large_gravel_result_1.height,
        mask=large_gravel_result_1.mask,
        surface_gravel_color=pf.Color((0.074, 0.044, 0.032)),
        surface_hue_variation=0.105882,
        surface_sat_variation=0.535294,
        surface_value_variation=0.805882,
        surface_min_spec=0.01,
        surface_max_spec=0.01,
        surface_min_roughness=0.264706,
        surface_max_roughness=0.7,
        shape_size=0.4,
        shape_height=0.5,
        shape_height_variation=0.5,
        shape_up_down=0.5,
        shape_distortion_strength=1.0,
        shape_spread=0.18,
        shape_bevel=0.394118,
        shape_w=0.0,
    )
    small_gravel_result_1 = small_gravel(
        vector=vector,
        base_color=small_gravel_result.color,
        base_spec=small_gravel_result.spec,
        base_rough=small_gravel_result.roughness,
        base_height=small_gravel_result.height,
        mask=small_gravel_result.mask,
        surface_gravel_color=pf.Color((0.44, 0.356, 0.3)),
        surface_hue_variation=0.135294,
        surface_sat_variation=0.605882,
        surface_value_variation=0.729412,
        surface_min_spec=0.01,
        surface_max_spec=0.01,
        surface_min_roughness=0.264706,
        surface_max_roughness=0.7,
        shape_size=0.6,
        shape_height=0.5,
        shape_height_variation=0.5,
        shape_up_down=0.5,
        shape_distortion_strength=1.0,
        shape_spread=0.09,
        shape_bevel=0.394118,
        shape_w=8.0,
    )
    small_gravel_result_2 = small_gravel(
        vector=vector,
        base_color=small_gravel_result_1.color,
        base_spec=small_gravel_result_1.spec,
        base_rough=small_gravel_result_1.roughness,
        base_height=small_gravel_result_1.height,
        mask=small_gravel_result_1.mask,
        surface_gravel_color=pf.Color((0.078, 0.069, 0.06)),
        surface_hue_variation=0.188235,
        surface_sat_variation=0.3,
        surface_value_variation=0.8,
        surface_min_spec=0.01,
        surface_max_spec=0.01,
        surface_min_roughness=0.576471,
        surface_max_roughness=0.741176,
        shape_size=0.1,
        shape_height=0.5,
        shape_height_variation=0.0,
        shape_up_down=0.5,
        shape_distortion_strength=1.0,
        shape_spread=0.435294,
        shape_bevel=0.523529,
        shape_w=0.0,
    )

    principled = pf.nodes.shader.principled_bsdf(
        base_color=small_gravel_result_2.color,
        roughness=small_gravel_result_2.roughness,
        subsurface_anisotropy=0.0,
        specular_ior_level=small_gravel_result_2.spec,
    )

    displacement = pf.nodes.shader.displacement(
        height=small_gravel_result_2.height,
        midlevel=0.0,
        scale=0.025,
        normal=(0.0, 0.0, 0.0),
    )
    return pf.Material(
        surface=principled,
        displacement=displacement,
    )


def gravel_concrete_bumps(
    vector: t.SocketOrVal[pf.Vector],
) -> pf.Material:
    # Code generated by procfunc v0.12.0

    large_gravel_result = large_gravel(
        vector=vector,
        base_color=pf.Color((0.111, 0.054, 0.044)),
        base_spec=0.0,
        base_roughness=0.7,
        base_height=0.0,
        mask=1.0,
        surface_gravel_color=pf.Color((0.078, 0.08, 0.081)),
        surface_hue_variation=0.088235,
        surface_sat_variation=0.776471,
        surface_value_variation=0.7,
        surface_min_spec=0.1,
        surface_max_spec=0.2,
        surface_min_roughness=0.5,
        surface_max_roughness=0.7,
        shape_rounded_sharp=0.5,
        shape_texture_size=0.3,
        shape_height=1.0,
        shape_height_variation=0.5,
        shape_up_down=0.864706,
        shape_margin=0.0001,
        shape_distortion_strength=0.5,
        shape_gravel_size=0.382353,
        shape_bevel=0.235294,
        shape_w=15.499999,
    )
    large_gravel_result_1 = large_gravel(
        vector=vector,
        base_color=large_gravel_result.color,
        base_spec=large_gravel_result.spec,
        base_roughness=large_gravel_result.roughness,
        base_height=large_gravel_result.height,
        mask=large_gravel_result.mask,
        surface_gravel_color=pf.Color((0.078, 0.08, 0.081)),
        surface_hue_variation=0.141176,
        surface_sat_variation=0.576471,
        surface_value_variation=0.588235,
        surface_min_spec=0.1,
        surface_max_spec=0.2,
        surface_min_roughness=0.5,
        surface_max_roughness=0.7,
        shape_rounded_sharp=0.0,
        shape_texture_size=0.2,
        shape_height=1.0,
        shape_height_variation=0.5,
        shape_up_down=1.0,
        shape_margin=0.0001,
        shape_distortion_strength=0.5,
        shape_gravel_size=0.147059,
        shape_bevel=0.75,
        shape_w=41.600002,
    )
    large_gravel_result_2 = large_gravel(
        vector=vector,
        base_color=large_gravel_result_1.color,
        base_spec=large_gravel_result_1.spec,
        base_roughness=large_gravel_result_1.roughness,
        base_height=large_gravel_result_1.height,
        mask=large_gravel_result_1.mask,
        surface_gravel_color=pf.Color((0.078, 0.08, 0.081)),
        surface_hue_variation=0.141176,
        surface_sat_variation=0.576471,
        surface_value_variation=0.588235,
        surface_min_spec=0.1,
        surface_max_spec=0.2,
        surface_min_roughness=0.5,
        surface_max_roughness=0.7,
        shape_rounded_sharp=1.0,
        shape_texture_size=0.15,
        shape_height=1.0,
        shape_height_variation=0.5,
        shape_up_down=0.929412,
        shape_margin=0.176464,
        shape_distortion_strength=0.5,
        shape_gravel_size=0.8,
        shape_bevel=0.3,
        shape_w=23.0,
    )

    small_gravel_result = small_gravel(
        vector=vector,
        base_color=large_gravel_result_2.color,
        base_spec=large_gravel_result_2.spec,
        base_rough=large_gravel_result_2.roughness,
        base_height=large_gravel_result_2.height,
        mask=large_gravel_result_2.mask,
        surface_gravel_color=pf.Color((0.084, 0.064, 0.053)),
        surface_hue_variation=0.105882,
        surface_sat_variation=0.541176,
        surface_value_variation=0.6,
        surface_min_spec=0.1,
        surface_max_spec=0.2,
        surface_min_roughness=0.5,
        surface_max_roughness=0.7,
        shape_size=1.0,
        shape_height=1.0,
        shape_height_variation=0.5,
        shape_up_down=0.5,
        shape_distortion_strength=1.0,
        shape_spread=0.25,
        shape_bevel=0.4,
        shape_w=0.0,
    )
    small_gravel_result_1 = small_gravel(
        vector=vector,
        base_color=small_gravel_result.color,
        base_spec=small_gravel_result.spec,
        base_rough=small_gravel_result.roughness,
        base_height=small_gravel_result.height,
        mask=small_gravel_result.mask,
        surface_gravel_color=pf.Color((0.216, 0.162, 0.145)),
        surface_hue_variation=0.188235,
        surface_sat_variation=0.3,
        surface_value_variation=1.0,
        surface_min_spec=0.1,
        surface_max_spec=0.2,
        surface_min_roughness=0.5,
        surface_max_roughness=0.7,
        shape_size=0.1,
        shape_height=0.5,
        shape_height_variation=0.0,
        shape_up_down=0.5,
        shape_distortion_strength=1.0,
        shape_spread=0.435294,
        shape_bevel=0.523529,
        shape_w=0.0,
    )

    principled = pf.nodes.shader.principled_bsdf(
        base_color=small_gravel_result_1.color,
        roughness=small_gravel_result_1.roughness,
        subsurface_anisotropy=0.0,
        specular_ior_level=small_gravel_result_1.spec,
    )

    displacement = pf.nodes.shader.displacement(
        height=small_gravel_result_1.height,
        midlevel=0.0,
        scale=0.025,
        normal=(0.0, 0.0, 0.0),
    )
    return pf.Material(
        surface=principled,
        displacement=displacement,
    )


def gravel_concrete_red(
    vector: t.SocketOrVal[pf.Vector],
) -> pf.Material:
    # Code generated by procfunc v0.12.0

    large_gravel_result = large_gravel(
        vector=vector,
        base_color=pf.Color((0.111, 0.054, 0.044)),
        base_spec=0.0,
        base_roughness=0.7,
        base_height=0.0,
        mask=1.0,
        surface_gravel_color=pf.Color((0.32, 0.16, 0.078)),
        surface_hue_variation=0.088235,
        surface_sat_variation=0.776471,
        surface_value_variation=0.864706,
        surface_min_spec=0.1,
        surface_max_spec=0.2,
        surface_min_roughness=0.5,
        surface_max_roughness=0.7,
        shape_rounded_sharp=0.0,
        shape_texture_size=0.03,
        shape_height=1.0,
        shape_height_variation=0.5,
        shape_up_down=0.623529,
        shape_margin=0.505868,
        shape_distortion_strength=0.5,
        shape_gravel_size=0.102941,
        shape_bevel=1.0,
        shape_w=15.499999,
    )
    large_gravel_result_1 = large_gravel(
        vector=vector,
        base_color=large_gravel_result.color,
        base_spec=large_gravel_result.spec,
        base_roughness=large_gravel_result.roughness,
        base_height=large_gravel_result.height,
        mask=large_gravel_result.mask,
        surface_gravel_color=pf.Color((0.221, 0.157, 0.105)),
        surface_hue_variation=0.141176,
        surface_sat_variation=0.576471,
        surface_value_variation=0.588235,
        surface_min_spec=0.1,
        surface_max_spec=0.2,
        surface_min_roughness=0.5,
        surface_max_roughness=0.7,
        shape_rounded_sharp=0.0,
        shape_texture_size=0.012,
        shape_height=1.0,
        shape_height_variation=0.5,
        shape_up_down=0.588235,
        shape_margin=0.429379,
        shape_distortion_strength=0.5,
        shape_gravel_size=0.2,
        shape_bevel=1.0,
        shape_w=6.3,
    )

    small_gravel_result = small_gravel(
        vector=vector,
        base_color=large_gravel_result_1.color,
        base_spec=large_gravel_result_1.spec,
        base_rough=large_gravel_result_1.roughness,
        base_height=large_gravel_result_1.height,
        mask=large_gravel_result_1.mask,
        surface_gravel_color=pf.Color((0.181, 0.079, 0.034)),
        surface_hue_variation=0.188235,
        surface_sat_variation=0.582353,
        surface_value_variation=0.788235,
        surface_min_spec=0.1,
        surface_max_spec=0.2,
        surface_min_roughness=0.5,
        surface_max_roughness=0.7,
        shape_size=0.04,
        shape_height=2.0,
        shape_height_variation=0.0,
        shape_up_down=0.5,
        shape_distortion_strength=1.0,
        shape_spread=0.311765,
        shape_bevel=0.523529,
        shape_w=0.0,
    )
    small_gravel_result_1 = small_gravel(
        vector=vector,
        base_color=small_gravel_result.color,
        base_spec=small_gravel_result.spec,
        base_rough=small_gravel_result.roughness,
        base_height=small_gravel_result.height,
        mask=small_gravel_result.mask,
        surface_gravel_color=pf.Color((0.147, 0.054, 0.033)),
        surface_hue_variation=0.188235,
        surface_sat_variation=1.0,
        surface_value_variation=0.711765,
        surface_min_spec=0.1,
        surface_max_spec=0.2,
        surface_min_roughness=0.5,
        surface_max_roughness=0.7,
        shape_size=0.01,
        shape_height=2.0,
        shape_height_variation=0.0,
        shape_up_down=0.5,
        shape_distortion_strength=1.0,
        shape_spread=0.435294,
        shape_bevel=0.523529,
        shape_w=0.0,
    )

    principled = pf.nodes.shader.principled_bsdf(
        base_color=small_gravel_result_1.color,
        roughness=small_gravel_result_1.roughness,
        subsurface_anisotropy=0.0,
        specular_ior_level=small_gravel_result_1.spec,
    )

    displacement = pf.nodes.shader.displacement(
        height=small_gravel_result_1.height,
        midlevel=0.0,
        scale=0.025,
        normal=(0.0, 0.0, 0.0),
    )
    return pf.Material(
        surface=principled,
        displacement=displacement,
    )


def gravel_concrete_presets(
    rng: pf.RNG,
    vector: pf.ProcNode[pf.Vector],
) -> pf.Material:
    func = pf.control.choice(
        rng,
        [
            (gravel_concrete_bumps, 1.0),
            (gravel_concrete_red, 1.0),
            (gravel_concrete_sharp_polished, 1.0),
        ],
    )
    return func(vector=vector)


def small_gravel_distribution(
    rng: pf.RNG,
    vector: t.SocketOrVal[pf.Vector],
    prev_result: GravelResult | None = None,
) -> GravelResult:
    # Code generated by procfunc v0.12.0

    base_color = (
        prev_result.color if prev_result is not None else pf.Color((0.0, 0.0, 0.0))
    )
    base_spec = prev_result.spec if prev_result is not None else 0.0
    base_rough = prev_result.roughness if prev_result is not None else 0.7
    base_height = prev_result.height if prev_result is not None else 0.0
    mask = prev_result.mask if prev_result is not None else 1.0

    surface_gravel_color = pf.color.hsv_to_rgba(
        [
            pf.random.uniform(rng, 0.0, 0.12),
            pf.random.uniform(rng, 0.0, 0.30),
            pf.random.uniform(rng, 0.05, 0.28),
        ]
    )
    surface_hue_variation = pf.random.uniform(rng, 0.105882, 0.188235)
    surface_sat_variation = pf.random.uniform(rng, 0.1, 0.45)
    surface_value_variation = pf.random.uniform(rng, 0.6, 0.805882)
    surface_min_spec = pf.random.uniform(rng, 0.01, 0.1)
    surface_max_spec = pf.random.uniform(rng, 0.01, 0.2)
    surface_min_roughness = pf.random.uniform(rng, 0.264706, 0.5)
    surface_max_roughness = 0.7
    shape_size = pf.random.uniform(rng, 0.04, 1.0)
    shape_height = pf.random.uniform(rng, 0.5, 2.0)
    shape_height_variation = pf.random.uniform(rng, 0.0, 0.5)
    shape_up_down = 0.5
    shape_distortion_strength = 1.0
    shape_spread = pf.random.uniform(rng, 0.18, 0.311765)
    shape_bevel = pf.random.uniform(rng, 0.394118, 0.523529)
    shape_w = 0.0

    small_gravel_result = small_gravel(
        vector=vector,
        base_color=base_color,
        base_spec=base_spec,
        base_rough=base_rough,
        base_height=base_height,
        mask=mask,
        surface_gravel_color=surface_gravel_color,
        surface_hue_variation=surface_hue_variation,
        surface_sat_variation=surface_sat_variation,
        surface_value_variation=surface_value_variation,
        surface_min_spec=surface_min_spec,
        surface_max_spec=surface_max_spec,
        surface_min_roughness=surface_min_roughness,
        surface_max_roughness=surface_max_roughness,
        shape_size=shape_size,
        shape_height=shape_height,
        shape_height_variation=shape_height_variation,
        shape_up_down=shape_up_down,
        shape_distortion_strength=shape_distortion_strength,
        shape_spread=shape_spread,
        shape_bevel=shape_bevel,
        shape_w=shape_w,
    )
    return small_gravel_result


def large_gravel_distribution(
    rng: pf.RNG,
    vector: t.SocketOrVal[pf.Vector],
    prev_result: GravelResult | None = None,
) -> GravelResult:
    # Code generated by procfunc v0.12.0

    if prev_result is not None:
        base_color = prev_result.color
        base_spec = prev_result.spec
        base_roughness = prev_result.roughness
        base_height = prev_result.height
        mask = prev_result.mask
    else:
        base_color = pf.color.hsv_to_rgba(
            [
                pf.random.uniform(rng, 0.0, 0.15),
                pf.random.uniform(rng, 0.0, 0.30),
                pf.random.uniform(rng, 0.04, 0.30),
            ]
        )
        base_spec = 0.0
        base_roughness = 0.7
        base_height = 0.0
        mask = 1.0

    surface_gravel_color = pf.color.hsv_to_rgba(
        [
            pf.random.uniform(rng, 0.0, 0.15),
            pf.random.uniform(rng, 0.0, 0.35),
            pf.random.uniform(rng, 0.02, 0.40),
        ]
    )
    surface_hue_variation = 0.088235
    surface_sat_variation = pf.random.uniform(rng, 0.05, 0.25)
    surface_value_variation = pf.random.uniform(rng, 0.376471, 0.864706)
    surface_min_spec = pf.random.uniform(rng, 0.05, 0.1)
    surface_max_spec = pf.random.uniform(rng, 0.1, 0.2)
    surface_min_roughness = pf.random.uniform(rng, 0.2, 0.5)
    surface_max_roughness = pf.random.uniform(rng, 0.3, 0.7)
    shape_rounded_sharp = pf.random.uniform(rng, 0.0, 1.0)
    shape_texture_size = pf.random.uniform(rng, 0.03, 0.3)
    shape_height = pf.random.uniform(rng, 0.4, 1.2)
    shape_height_variation = 0.5
    shape_up_down = pf.random.uniform(rng, 0.85, 0.98)
    shape_margin = pf.random.uniform(rng, 0.0001, 0.505868)
    shape_distortion_strength = 0.5
    shape_gravel_size = pf.random.uniform(rng, 0.102941, 0.7)
    shape_bevel = pf.random.uniform(rng, 0.235294, 1.0)
    shape_w = pf.random.uniform(rng, 0.0, 15.499999)

    large_gravel_result = large_gravel(
        vector=vector,
        base_color=base_color,
        base_spec=base_spec,
        base_roughness=base_roughness,
        base_height=base_height,
        mask=mask,
        surface_gravel_color=surface_gravel_color,
        surface_hue_variation=surface_hue_variation,
        surface_sat_variation=surface_sat_variation,
        surface_value_variation=surface_value_variation,
        surface_min_spec=surface_min_spec,
        surface_max_spec=surface_max_spec,
        surface_min_roughness=surface_min_roughness,
        surface_max_roughness=surface_max_roughness,
        shape_rounded_sharp=shape_rounded_sharp,
        shape_texture_size=shape_texture_size,
        shape_height=shape_height,
        shape_height_variation=shape_height_variation,
        shape_up_down=shape_up_down,
        shape_margin=shape_margin,
        shape_distortion_strength=shape_distortion_strength,
        shape_gravel_size=shape_gravel_size,
        shape_bevel=shape_bevel,
        shape_w=shape_w,
    )
    return large_gravel_result


def random_gravel_concrete_distribution(
    rng: pf.RNG,
    vector: t.SocketOrVal[pf.Vector],
) -> pf.Material:
    lg_result = large_gravel_distribution(rng, vector)
    lg_result = large_gravel_distribution(rng, vector, prev_result=lg_result)
    sg_result = small_gravel_distribution(rng, vector, prev_result=lg_result)
    sg_result = small_gravel_distribution(rng, vector, prev_result=sg_result)

    principled = pf.nodes.shader.principled_bsdf(
        base_color=sg_result.color,
        roughness=sg_result.roughness,
        subsurface_anisotropy=0.0,
        specular_ior_level=sg_result.spec,
    )
    displacement = pf.nodes.shader.displacement(
        height=sg_result.height,
        midlevel=0.0,
        scale=0.025,
        normal=(0.0, 0.0, 0.0),
    )
    return pf.Material(
        surface=principled,
        displacement=displacement,
    )


def gravel_concrete_distribution(
    rng: pf.RNG,
    vector: t.SocketOrVal[pf.Vector],
) -> pf.Material:
    # # TODO: replace with continously randomized version - consult / call the two _distribution functions above

    # func = pf.control.choice(
    #     rng,
    #     [
    #         (gravel_concrete_bumps, 1.0),
    #         (gravel_concrete_red, 1.0),
    #         (gravel_concrete_sharp_polished, 1.0),
    #     ],
    # )
    # return func(vector=vector)

    return random_gravel_concrete_distribution(rng, vector)
