# Copyright (C) 2025, Princeton University.
# This source code is licensed under the BSD 3-clause license found in the LICENSE file in the root directory of this source tree.

# Authors: Karhan Kayan
# Acknowledgment: This file draws inspiration
# from https://www.youtube.com/watch?v=ggYnU1iOMUc
# by Ryan King Art

import numpy as np
import procfunc as pf
from procfunc.nodes import types as t


def terrazzo_multicolor_node(
    vector: t.ProcNode[pf.Vector],
    large_chip_scale: t.SocketOrVal[float] = 16.0,
    medium_chip_scale: t.SocketOrVal[float] = 16.0,
    small_chip_scale: t.SocketOrVal[float] = 16.0,
    big_chip_detail: t.SocketOrVal[float] = 0.6,
    medium_chip_detail: t.SocketOrVal[float] = 0.0,
    small_chip_detail: t.SocketOrVal[float] = 0.0,
    big_chip_roughness: t.SocketOrVal[float] = 0.5,
    medium_chip_roughness: t.SocketOrVal[float] = 0.5,
    small_chip_roughness: t.SocketOrVal[float] = 0.5,
    large_chip_lacunarity: t.SocketOrVal[float] = 2.0,
    concrete_noise_scale: t.SocketOrVal[float] = 52.9,
    concrete_noise_detail: t.SocketOrVal[float] = 5.1,
    concrete_noise_roughness: t.SocketOrVal[float] = 0.725,
    chip_noise_scale: t.SocketOrVal[float] = 95.0,
    chip_noise_detail: t.SocketOrVal[float] = 10.7,
    chip_noise_roughness: t.SocketOrVal[float] = 0.725,
    large_chip_frequency_cutoff: t.SocketOrVal[float] = 0.186,
    medium_chip_frequency_cutoff: t.SocketOrVal[float] = 0.186,
    small_chip_frequency_cutoff: t.SocketOrVal[float] = 0.191,
    concrete_black_threshold: t.SocketOrVal[float] = 0.345,
    concrete_white_threshold: t.SocketOrVal[float] = 0.441,
    concrete_base_color: tuple | None = None,
    concrete_color_mix_factor: t.SocketOrVal[float] = 0.7533,
    small_chip_colors: list | None = None,
    medium_chip_colors: list | None = None,
    large_chip_colors: list | None = None,
) -> pf.ProcNode[pf.Shader]:
    # Code generated by procfunc v0.4.0

    if concrete_base_color is None:
        concrete_base_color = (0.43, 0.431, 0.414)

    if small_chip_colors is None:
        small_chip_colors = [
            (0.0, (0.038, 0.056, 0.076, 1.0)),
            (0.307, (0.175, 0.212, 0.181, 1.0)),
            (0.678, (0.485, 0.571, 0.584, 1.0)),
            (1.0, (0.73, 0.768, 0.638, 1.0)),
        ]
    if medium_chip_colors is None:
        medium_chip_colors = [
            (0.0, (0.042, 0.041, 0.026, 1.0)),
            (0.077, (0.042, 0.041, 0.026, 1.0)),
            (0.348, (0.141, 0.162, 0.093, 1.0)),
            (0.49, (0.042, 0.041, 0.026, 1.0)),
            (0.678, (0.539, 0.546, 0.328, 1.0)),
            (1.0, (0.73, 0.768, 0.638, 1.0)),
        ]
    if large_chip_colors is None:
        large_chip_colors = [
            (0.0, (0.028, 0.007, 0.007, 1.0)),
            (0.27, (0.12, 0.041, 0.024, 1.0)),
            (0.522, (0.084, 0.032, 0.025, 1.0)),
            (0.756, (0.361, 0.091, 0.01, 1.0)),
            (1.0, (0.624, 0.33, 0.113, 1.0)),
        ]

    result_0_factor_fac_2 = pf.nodes.shader.voronoi_distance(
        vector=vector,
        scale=large_chip_scale,
        detail=big_chip_detail,
        roughness=big_chip_roughness,
        lacunarity=large_chip_lacunarity,
    )
    result_0_factor_4 = pf.nodes.shader.color_ramp(
        fac=result_0_factor_fac_2,
        interpolation="CONSTANT",
        points=[
            (0.0, (0.0, 0.0, 0.0, 1.0)),
            (large_chip_frequency_cutoff, (1.0, 1.0, 1.0, 1.0)),
        ],
    )
    result_0_factor_fac_1 = pf.nodes.shader.voronoi_distance(
        vector=vector,
        scale=medium_chip_scale,
        detail=medium_chip_detail,
        roughness=medium_chip_roughness,
    )
    result_0_factor_3 = pf.nodes.shader.color_ramp(
        fac=result_0_factor_fac_1,
        interpolation="CONSTANT",
        points=[
            (0.0, (0.0, 0.0, 0.0, 1.0)),
            (medium_chip_frequency_cutoff, (1.0, 1.0, 1.0, 1.0)),
        ],
    )
    result_0_factor_2 = pf.nodes.func.mix_rgb(
        factor=1.0,
        a=result_0_factor_4.color,
        b=result_0_factor_3.color,
        blend_type="LIGHTEN",
    )
    result_0_factor_fac = pf.nodes.shader.voronoi_distance(
        vector=vector,
        scale=small_chip_scale,
        detail=small_chip_detail,
        roughness=small_chip_roughness,
    )
    result_0_factor_1 = pf.nodes.shader.color_ramp(
        fac=result_0_factor_fac,
        interpolation="CONSTANT",
        points=[
            (0.0, (0.0, 0.0, 0.0, 1.0)),
            (small_chip_frequency_cutoff, (1.0, 1.0, 1.0, 1.0)),
        ],
    )
    result_0_factor = pf.nodes.func.mix_rgb(
        factor=1.0,
        a=result_0_factor_2,
        b=result_0_factor_1.color,
        blend_type="LIGHTEN",
    )
    result_0_base_color_fac_3 = pf.nodes.shader.noise(
        vector=vector,
        scale=concrete_noise_scale,
        detail=concrete_noise_detail,
        roughness=concrete_noise_roughness,
        distortion=3.2,
    )
    result_0_base_color_9 = pf.nodes.shader.color_ramp(
        fac=result_0_base_color_fac_3.fac,
        interpolation="LINEAR",
        points=[
            (concrete_black_threshold, (0.0, 0.0, 0.0, 1.0)),
            (concrete_white_threshold, (1.0, 1.0, 1.0, 1.0)),
        ],
    )
    if len(concrete_base_color) == 3:
        concrete_base_color = (*concrete_base_color, 1.0)
    result_0_base_color_8 = concrete_base_color
    result_0_base_color_7 = pf.nodes.func.mix_rgb(
        factor=concrete_color_mix_factor,
        a=result_0_base_color_9.color,
        b=result_0_base_color_8,
        blend_type="COLOR",
    )
    result_1 = pf.nodes.shader.principled_bsdf(
        base_color=result_0_base_color_7,
        roughness=0.7591,
        subsurface_anisotropy=0.0,
    )
    result_0_fac = pf.nodes.shader.noise(
        vector=vector,
        scale=chip_noise_scale,
        detail=chip_noise_detail,
        roughness=chip_noise_roughness,
        lacunarity=5.0,
        distortion=4.2,
    )
    result_0_base_color_factor = pf.nodes.shader.color_ramp(
        fac=result_0_fac.fac,
        interpolation="EASE",
        points=[(0.432, (0.0, 0.0, 0.0, 1.0)), (0.586, (1.0, 1.0, 1.0, 1.0))],
    )
    result_0_base_color_fac_2 = pf.nodes.shader.voronoi(
        vector=vector,
        scale=small_chip_scale,
        roughness=small_chip_roughness,
    )
    result_0_base_color_6 = pf.nodes.shader.color_ramp(
        fac=result_0_base_color_fac_2.color.astype(dtype=float),
        interpolation="CONSTANT",
        points=small_chip_colors,
    )
    result_0_base_color_fac_1 = pf.nodes.shader.voronoi(
        vector=vector,
        scale=medium_chip_scale,
        roughness=medium_chip_roughness,
    )
    result_0_base_color_5 = pf.nodes.shader.color_ramp(
        fac=result_0_base_color_fac_1.color.astype(dtype=float),
        interpolation="CONSTANT",
        points=medium_chip_colors,
    )
    result_0_base_color_fac = pf.nodes.shader.voronoi(
        vector=vector,
        scale=large_chip_scale,
        roughness=big_chip_roughness,
    )
    result_0_base_color_4 = pf.nodes.shader.color_ramp(
        fac=result_0_base_color_fac.color.astype(dtype=float),
        interpolation="CONSTANT",
        points=large_chip_colors,
    )
    result_0_base_color_3 = pf.nodes.func.mix_rgb(
        factor=result_0_factor_4.color.astype(dtype=float),
        a=result_0_base_color_5.color,
        b=result_0_base_color_4.color,
    )
    result_0_base_color_2 = pf.nodes.func.mix_rgb(
        factor=result_0_factor_2.astype(dtype=float),
        a=result_0_base_color_6.color,
        b=result_0_base_color_3,
    )
    result_0_base_color_1 = pf.nodes.shader.hue_saturation(
        value=2.0, color=result_0_base_color_2
    )
    result_0_base_color = pf.nodes.func.mix_rgb(
        factor=result_0_base_color_factor.color.astype(dtype=float),
        a=result_0_base_color_2,
        b=result_0_base_color_1,
    )
    result = pf.nodes.shader.principled_bsdf(
        base_color=result_0_base_color,
        roughness=0.3318,
        ior=1.45,
        subsurface_anisotropy=0.0,
    )

    mix_shader = pf.nodes.shader.mix_shader(
        factor=result_0_factor.astype(dtype=float),
        a=result_1,
        b=result,
    )
    return mix_shader


def terrazzo_monocolor_node(
    vector: t.ProcNode[pf.Vector],
    large_chip_scale: t.SocketOrVal[float] = 16.0,
    medium_chip_scale: t.SocketOrVal[float] = 16.0,
    small_chip_scale: t.SocketOrVal[float] = 16.0,
    big_chip_detail: t.SocketOrVal[float] = 0.6,
    medium_chip_detail: t.SocketOrVal[float] = 0.6,
    small_chip_detail: t.SocketOrVal[float] = 0.3167,
    big_chip_roughness: t.SocketOrVal[float] = 0.5167,
    medium_chip_roughness: t.SocketOrVal[float] = 0.5,
    small_chip_roughness: t.SocketOrVal[float] = 2.0,
    concrete_noise_scale: t.SocketOrVal[float] = 52.9,
    concrete_noise_detail: t.SocketOrVal[float] = 5.1,
    roughness: t.SocketOrVal[float] = 0.725,
    chip_noise_scale: t.SocketOrVal[float] = 95.0,
    chip_noise_detail: t.SocketOrVal[float] = 10.7,
    chip_noise_roughness: t.SocketOrVal[float] = 0.725,
    large_chip_frequency_cutoff: t.SocketOrVal[float] = 0.186,
    medium_chip_frequency_cutoff: t.SocketOrVal[float] = 0.186,
    small_chip_frequency_cutoff: t.SocketOrVal[float] = 0.191,
    concrete_black_threshold: t.SocketOrVal[float] = 0.345,
    concrete_white_threshold: t.SocketOrVal[float] = 0.441,
    concrete_base_color: tuple | None = None,
    concrete_color_mix_factor: t.SocketOrVal[float] = 0.7792,
    small_chip_color: tuple | None = None,
    medium_chip_color: tuple | None = None,
    large_chip_color: tuple | None = None,
) -> pf.ProcNode[pf.Shader]:
    # Code generated by procfunc v0.4.0

    if concrete_base_color is None:
        concrete_base_color = (0.521, 0.278, 0.396)

    if small_chip_color is None:
        small_chip_color = (0.006, 0.002, 0.004)
    if medium_chip_color is None:
        medium_chip_color = (0.971, 0.18, 0.399)
    if large_chip_color is None:
        large_chip_color = (0.151, 0.042, 0.018)

    result_0_factor_fac_2 = pf.nodes.shader.voronoi_distance(
        vector=vector,
        scale=large_chip_scale,
        detail=big_chip_detail,
        roughness=big_chip_roughness,
    )
    result_0_factor_4 = pf.nodes.shader.color_ramp(
        fac=result_0_factor_fac_2,
        interpolation="CONSTANT",
        points=[
            (0.155, (0.0, 0.0, 0.0, 1.0)),
            (large_chip_frequency_cutoff, (1.0, 1.0, 1.0, 1.0)),
        ],
    )
    result_0_factor_fac_1 = pf.nodes.shader.voronoi_distance(
        vector=vector,
        scale=medium_chip_scale,
        detail=medium_chip_detail,
        roughness=medium_chip_roughness,
    )
    result_0_factor_3 = pf.nodes.shader.color_ramp(
        fac=result_0_factor_fac_1,
        interpolation="CONSTANT",
        points=[
            (0.155, (0.0, 0.0, 0.0, 1.0)),
            (medium_chip_frequency_cutoff, (1.0, 1.0, 1.0, 1.0)),
        ],
    )
    result_0_factor_2 = pf.nodes.func.mix_rgb(
        factor=1.0,
        a=result_0_factor_4.color,
        b=result_0_factor_3.color,
        blend_type="LIGHTEN",
    )
    result_0_factor_fac = pf.nodes.shader.voronoi_distance(
        vector=vector,
        scale=small_chip_scale,
        detail=small_chip_detail,
        roughness=small_chip_roughness,
    )
    result_0_factor_1 = pf.nodes.shader.color_ramp(
        fac=result_0_factor_fac,
        interpolation="CONSTANT",
        points=[
            (0.15, (0.0, 0.0, 0.0, 1.0)),
            (small_chip_frequency_cutoff, (1.0, 1.0, 1.0, 1.0)),
        ],
    )
    result_0_factor = pf.nodes.func.mix_rgb(
        factor=1.0,
        a=result_0_factor_2,
        b=result_0_factor_1.color,
        blend_type="LIGHTEN",
    )
    result_0_base_color_fac = pf.nodes.shader.noise(
        vector=vector,
        scale=concrete_noise_scale,
        detail=concrete_noise_detail,
        roughness=roughness,
        distortion=3.2,
    )
    result_0_base_color_9 = pf.nodes.shader.color_ramp(
        fac=result_0_base_color_fac.fac,
        interpolation="LINEAR",
        points=[
            (concrete_black_threshold, (0.0, 0.0, 0.0, 1.0)),
            (concrete_white_threshold, (1.0, 1.0, 1.0, 1.0)),
        ],
    )
    result_0_base_color_8 = concrete_base_color
    result_0_base_color_7 = pf.nodes.func.mix_rgb(
        factor=concrete_color_mix_factor,
        a=result_0_base_color_9.color,
        b=result_0_base_color_8,
        blend_type="COLOR",
    )
    result_1 = pf.nodes.shader.principled_bsdf(
        base_color=result_0_base_color_7,
        roughness=0.7591,
        subsurface_anisotropy=0.0,
    )
    result_0_fac = pf.nodes.shader.noise(
        vector=vector,
        scale=chip_noise_scale,
        detail=chip_noise_detail,
        roughness=chip_noise_roughness,
        lacunarity=5.0,
        distortion=4.2,
    )
    result_0_base_color_factor = pf.nodes.shader.color_ramp(
        fac=result_0_fac.fac,
        interpolation="EASE",
        points=[(0.432, (0.0, 0.0, 0.0, 1.0)), (0.586, (1.0, 1.0, 1.0, 1.0))],
    )
    result_0_base_color_6 = small_chip_color
    result_0_base_color_5 = medium_chip_color
    result_0_base_color_4 = large_chip_color
    result_0_base_color_3 = pf.nodes.func.mix_rgb(
        factor=result_0_factor_4.color.astype(dtype=float),
        a=result_0_base_color_5,
        b=result_0_base_color_4,
    )
    result_0_base_color_2 = pf.nodes.func.mix_rgb(
        factor=result_0_factor_2.astype(dtype=float),
        a=result_0_base_color_6,
        b=result_0_base_color_3,
    )
    result_0_base_color_1 = pf.nodes.shader.hue_saturation(
        value=2.0, color=result_0_base_color_2
    )
    result_0_base_color = pf.nodes.func.mix_rgb(
        factor=result_0_base_color_factor.color.astype(dtype=float),
        a=result_0_base_color_2,
        b=result_0_base_color_1,
    )
    result = pf.nodes.shader.principled_bsdf(
        base_color=result_0_base_color,
        roughness=0.3318,
        ior=1.45,
        subsurface_anisotropy=0.0,
    )

    mix_shader = pf.nodes.shader.mix_shader(
        factor=result_0_factor.astype(dtype=float),
        a=result_1,
        b=result,
    )
    return mix_shader


def terrazzo_multicolor(vector):
    # Code generated by procfunc v0.4.0

    terrazzo_result = terrazzo_multicolor_node(
        vector, medium_chip_scale=40.0, small_chip_scale=124.0
    )
    return pf.Material(
        surface=terrazzo_result,
    )


def terrazzo_monocolor(vector):
    # Code generated by procfunc v0.4.0

    terrazzo_001_result = terrazzo_monocolor_node(
        vector, large_chip_scale=23.4, medium_chip_scale=37.8, small_chip_scale=11.2
    )
    return pf.Material(
        surface=terrazzo_001_result,
    )


# Generate color palettes for multicolor terrazzo
def random_base_color(rng) -> pf.Color:
    return pf.color.rgb_color(
        r=pf.random.uniform(rng, 0.0, 1.0),
        g=pf.random.uniform(rng, 0.0, 1.0),
        b=pf.random.uniform(rng, 0.0, 1.0),
    )


def random_grayscale_color(rng) -> pf.Color:
    val = pf.random.uniform(rng, 0.0, 1.0)
    return pf.color.rgb_color(r=val, g=val, b=val)


def random_brown_color(rng) -> pf.Color:
    return pf.color.rgb_color(
        r=pf.random.uniform(rng, 0.2, 0.5),
        g=pf.random.uniform(rng, 0.1, 0.2),
        b=pf.random.uniform(rng, 0.05, 0.15),
    )


def _random_color_shade(
    rng: np.random.Generator,
    base_color: pf.Color,
    value_factor_low: float = 0.3,
    value_factor_high: float = 1.5,
    hue_shift_low: float = -0.05,
    hue_shift_high: float = 0.05,
) -> pf.Color:
    """Generate a random shade/tint of a base color using HSV manipulation.
    Modifies value (brightness) and slightly shifts hue for natural variation.
    Returns RGBA tuple for use in color_ramp points.
    """

    value_factor = rng.uniform(value_factor_low, value_factor_high)
    hue_shift = rng.uniform(hue_shift_low, hue_shift_high)
    return pf.color.hsv_color(
        hue=(base_color.h + hue_shift) % 1.0,  # hue (wrapped)
        saturation=base_color.s,  # saturation unchanged
        value=np.clip(base_color.v * value_factor, 0.0, 1.0),  # value (brightness)
    )


def terrazzo_multicolor_distribution(
    rng: pf.RNG,
    vector: pf.ProcNode[pf.Vector],
    large_chip_scale: t.SocketOrVal[float] | None = None,
    medium_chip_scale: t.SocketOrVal[float] | None = None,
    small_chip_scale: t.SocketOrVal[float] | None = None,
    big_chip_detail: t.SocketOrVal[float] | None = None,
    medium_chip_detail: t.SocketOrVal[float] | None = None,
    small_chip_detail: t.SocketOrVal[float] | None = None,
    concrete_black_threshold: t.SocketOrVal[float] | None = None,
    concrete_white_threshold: t.SocketOrVal[float] | None = None,
    concrete_base_color: tuple | None = None,
    small_base_color: pf.Color | None = None,
    medium_base_color: pf.Color | None = None,
    large_base_color: pf.Color | None = None,
) -> pf.Material:
    """Distribution function that creates random multicolor terrazzo.
    Defaults to white terrazzo settings. Use terrazzo_black_multicolor_distribution
    for black/dark terrazzo.
    """

    if large_chip_scale is None:
        large_chip_scale = pf.random.uniform(rng, 3, 50)
    if medium_chip_scale is None:
        medium_chip_scale = pf.random.uniform(rng, 5, 100)
    if small_chip_scale is None:
        small_chip_scale = pf.random.uniform(rng, 5, 250)

    if big_chip_detail is None:
        big_chip_detail = pf.random.uniform(rng, 0, 1.2)
    if medium_chip_detail is None:
        medium_chip_detail = pf.random.uniform(rng, 0.0, 1)
    if small_chip_detail is None:
        small_chip_detail = pf.random.uniform(rng, 0.0, 1)

    big_chip_roughness = pf.random.uniform(rng, 0, 1)
    medium_chip_roughness = pf.random.uniform(rng, 0, 1)
    small_chip_roughness = pf.random.uniform(rng, 0, 1)

    concrete_noise_scale = pf.random.uniform(rng, 0, 200)
    concrete_noise_detail = pf.random.uniform(rng, 0, 10)
    concrete_noise_roughness = pf.random.uniform(rng, 0.5, 1)

    chip_noise_scale = pf.random.uniform(rng, 0, 200)
    chip_noise_detail = pf.random.uniform(rng, 0, 10)
    chip_noise_roughness = pf.random.uniform(rng, 0.5, 1)

    large_chip_lacunarity = pf.random.uniform(rng, 0, 4)

    large_chip_frequency_cutoff = pf.random.uniform(rng, 0.1, 0.2)
    medium_chip_frequency_cutoff = pf.random.uniform(rng, 0.2, 0.4)
    small_chip_frequency_cutoff = pf.random.uniform(rng, 0.2, 0.4)

    # Default to white terrazzo settings
    if concrete_black_threshold is None:
        concrete_black_threshold = pf.random.uniform(rng, 0, 0.5)
    if concrete_white_threshold is None:
        concrete_white_threshold = pf.random.uniform(rng, concrete_black_threshold, 1)
    if concrete_base_color is None:
        concrete_base_color = (
            pf.random.clip_gaussian(rng, mean=1.0, std=0.15, low=0.0, high=1.0),
            pf.random.clip_gaussian(rng, mean=1.0, std=0.15, low=0.0, high=1.0),
            pf.random.clip_gaussian(rng, mean=1.0, std=0.15, low=0.0, high=1.0),
        )

    # Default to colorful chips (white terrazzo)
    if small_base_color is None:
        small_base_color = random_base_color(rng)
    if medium_base_color is None:
        medium_base_color = random_base_color(rng)
    if large_base_color is None:
        large_base_color = random_base_color(rng)

    # Generate coherent color palettes with shades of the base color (no loops)
    small_chip_colors = [
        (0.0, _random_color_shade(rng, small_base_color)),
        (pf.random.uniform(rng, 0.2, 0.4), _random_color_shade(rng, small_base_color)),
        (pf.random.uniform(rng, 0.5, 0.8), _random_color_shade(rng, small_base_color)),
        (1.0, _random_color_shade(rng, small_base_color)),
    ]

    medium_chip_colors = [
        (0.0, _random_color_shade(rng, medium_base_color)),
        (
            pf.random.uniform(rng, 0.05, 0.15),
            _random_color_shade(rng, medium_base_color),
        ),
        (
            pf.random.uniform(rng, 0.25, 0.4),
            _random_color_shade(rng, medium_base_color),
        ),
        (
            pf.random.uniform(rng, 0.45, 0.55),
            _random_color_shade(rng, medium_base_color),
        ),
        (
            pf.random.uniform(rng, 0.6, 0.75),
            _random_color_shade(rng, medium_base_color),
        ),
        (1.0, _random_color_shade(rng, medium_base_color)),
    ]

    large_chip_colors = [
        (0.0, _random_color_shade(rng, large_base_color)),
        (pf.random.uniform(rng, 0.2, 0.35), _random_color_shade(rng, large_base_color)),
        (pf.random.uniform(rng, 0.4, 0.6), _random_color_shade(rng, large_base_color)),
        (
            pf.random.uniform(rng, 0.65, 0.85),
            _random_color_shade(rng, large_base_color),
        ),
        (1.0, _random_color_shade(rng, large_base_color)),
    ]

    terrazzo_result = terrazzo_multicolor_node(
        vector,
        large_chip_scale=large_chip_scale,
        medium_chip_scale=medium_chip_scale,
        small_chip_scale=small_chip_scale,
        big_chip_detail=big_chip_detail,
        medium_chip_detail=medium_chip_detail,
        small_chip_detail=small_chip_detail,
        big_chip_roughness=big_chip_roughness,
        medium_chip_roughness=medium_chip_roughness,
        small_chip_roughness=small_chip_roughness,
        large_chip_lacunarity=large_chip_lacunarity,
        concrete_noise_scale=concrete_noise_scale,
        concrete_noise_detail=concrete_noise_detail,
        concrete_noise_roughness=concrete_noise_roughness,
        chip_noise_scale=chip_noise_scale,
        chip_noise_detail=chip_noise_detail,
        chip_noise_roughness=chip_noise_roughness,
        small_chip_colors=small_chip_colors,
        medium_chip_colors=medium_chip_colors,
        large_chip_colors=large_chip_colors,
        large_chip_frequency_cutoff=large_chip_frequency_cutoff,
        medium_chip_frequency_cutoff=medium_chip_frequency_cutoff,
        small_chip_frequency_cutoff=small_chip_frequency_cutoff,
        concrete_black_threshold=concrete_black_threshold,
        concrete_white_threshold=concrete_white_threshold,
        concrete_base_color=concrete_base_color,
    )

    return pf.Material(
        surface=terrazzo_result,
    )


def terrazzo_black_multicolor_distribution(
    rng: pf.RNG,
    vector: pf.ProcNode[pf.Vector],
    large_chip_scale: t.SocketOrVal[float] | None = None,
    medium_chip_scale: t.SocketOrVal[float] | None = None,
    small_chip_scale: t.SocketOrVal[float] | None = None,
    big_chip_detail: t.SocketOrVal[float] | None = None,
    medium_chip_detail: t.SocketOrVal[float] | None = None,
    small_chip_detail: t.SocketOrVal[float] | None = None,
) -> pf.Material:
    concrete_black_threshold = pf.random.uniform(rng, 0.5, 1)
    concrete_white_threshold = pf.random.uniform(rng, concrete_black_threshold, 1)
    concrete_base_color = (
        pf.random.clip_gaussian(rng, mean=0.15, std=0.1, low=0.0, high=1.0),
        pf.random.clip_gaussian(rng, mean=0.15, std=0.1, low=0.0, high=1.0),
        pf.random.clip_gaussian(rng, mean=0.15, std=0.1, low=0.0, high=1.0),
    )

    # For black terrazzo, choose between grayscale or brown chips
    chip_colors = pf.control.choice(
        rng,
        [
            (
                (
                    random_brown_color(rng),
                    random_brown_color(rng),
                    random_brown_color(rng),
                ),
                0.1,
            ),
            (
                (
                    random_grayscale_color(rng),
                    random_grayscale_color(rng),
                    random_grayscale_color(rng),
                ),
                0.9,
            ),
        ],
    )
    small_base_color = chip_colors[0]
    medium_base_color = chip_colors[1]
    large_base_color = chip_colors[2]

    return terrazzo_multicolor_distribution(
        rng=rng,
        vector=vector,
        large_chip_scale=large_chip_scale,
        medium_chip_scale=medium_chip_scale,
        small_chip_scale=small_chip_scale,
        big_chip_detail=big_chip_detail,
        medium_chip_detail=medium_chip_detail,
        small_chip_detail=small_chip_detail,
        concrete_black_threshold=concrete_black_threshold,
        concrete_white_threshold=concrete_white_threshold,
        concrete_base_color=concrete_base_color,
        small_base_color=small_base_color,
        medium_base_color=medium_base_color,
        large_base_color=large_base_color,
    )


def terrazzo_monocolor_distribution(
    rng: pf.RNG,
    vector: pf.ProcNode[pf.Vector],
    large_chip_scale: t.SocketOrVal[float] | None = None,
    medium_chip_scale: t.SocketOrVal[float] | None = None,
    small_chip_scale: t.SocketOrVal[float] | None = None,
    big_chip_detail: t.SocketOrVal[float] | None = None,
    medium_chip_detail: t.SocketOrVal[float] | None = None,
    small_chip_detail: t.SocketOrVal[float] | None = None,
    concrete_black_threshold: t.SocketOrVal[float] | None = None,
    concrete_white_threshold: t.SocketOrVal[float] | None = None,
    concrete_base_color: tuple | None = None,
    small_chip_color: pf.Color | None = None,
    medium_chip_color: pf.Color | None = None,
    large_chip_color: pf.Color | None = None,
) -> pf.Material:
    """Distribution function that creates random monocolor terrazzo.
    Defaults to white terrazzo settings. Use terrazzo_black_monocolor_distribution
    for black/dark terrazzo.
    """

    if large_chip_scale is None:
        large_chip_scale = pf.random.uniform(rng, 3, 50)
    if medium_chip_scale is None:
        medium_chip_scale = pf.random.uniform(rng, 5, 100)
    if small_chip_scale is None:
        small_chip_scale = pf.random.uniform(rng, 5, 250)

    if big_chip_detail is None:
        big_chip_detail = pf.random.uniform(rng, 0, 1.2)
    if medium_chip_detail is None:
        medium_chip_detail = pf.random.uniform(rng, 0.0, 1)
    if small_chip_detail is None:
        small_chip_detail = pf.random.uniform(rng, 0.0, 1)

    big_chip_roughness = pf.random.uniform(rng, 0, 1)
    medium_chip_roughness = pf.random.uniform(rng, 0, 1)
    small_chip_roughness = pf.random.uniform(rng, 0, 1)

    concrete_noise_scale = pf.random.uniform(rng, 0, 200)
    concrete_noise_detail = pf.random.uniform(rng, 0, 10)
    concrete_noise_roughness = pf.random.uniform(rng, 0.5, 1)

    chip_noise_scale = pf.random.uniform(rng, 0, 200)
    chip_noise_detail = pf.random.uniform(rng, 0, 10)
    chip_noise_roughness = pf.random.uniform(rng, 0.5, 1)

    large_chip_frequency_cutoff = pf.random.uniform(rng, 0.1, 0.2)
    medium_chip_frequency_cutoff = pf.random.uniform(rng, 0.2, 0.4)
    small_chip_frequency_cutoff = pf.random.uniform(rng, 0.2, 0.4)

    # Default to white terrazzo settings
    if concrete_black_threshold is None:
        concrete_black_threshold = pf.random.uniform(rng, 0, 0.5)
    if concrete_white_threshold is None:
        concrete_white_threshold = pf.random.uniform(rng, concrete_black_threshold, 1)
    if concrete_base_color is None:
        concrete_base_color = (
            pf.random.clip_gaussian(rng, mean=1.0, std=0.15, low=0.0, high=1.0),
            pf.random.clip_gaussian(rng, mean=1.0, std=0.15, low=0.0, high=1.0),
            pf.random.clip_gaussian(rng, mean=1.0, std=0.15, low=0.0, high=1.0),
        )

    # Default to colorful chips (white terrazzo)
    if small_chip_color is None:
        small_chip_color = random_base_color(rng)
    if medium_chip_color is None:
        medium_chip_color = random_base_color(rng)
    if large_chip_color is None:
        large_chip_color = random_base_color(rng)

    terrazzo_result = terrazzo_monocolor_node(
        vector,
        large_chip_scale=large_chip_scale,
        medium_chip_scale=medium_chip_scale,
        small_chip_scale=small_chip_scale,
        big_chip_detail=big_chip_detail,
        medium_chip_detail=medium_chip_detail,
        small_chip_detail=small_chip_detail,
        big_chip_roughness=big_chip_roughness,
        medium_chip_roughness=medium_chip_roughness,
        small_chip_roughness=small_chip_roughness,
        concrete_noise_scale=concrete_noise_scale,
        concrete_noise_detail=concrete_noise_detail,
        roughness=concrete_noise_roughness,
        chip_noise_scale=chip_noise_scale,
        chip_noise_detail=chip_noise_detail,
        chip_noise_roughness=chip_noise_roughness,
        large_chip_frequency_cutoff=large_chip_frequency_cutoff,
        medium_chip_frequency_cutoff=medium_chip_frequency_cutoff,
        small_chip_frequency_cutoff=small_chip_frequency_cutoff,
        concrete_black_threshold=concrete_black_threshold,
        concrete_white_threshold=concrete_white_threshold,
        concrete_base_color=concrete_base_color,
        small_chip_color=small_chip_color,
        medium_chip_color=medium_chip_color,
        large_chip_color=large_chip_color,
    )

    return pf.Material(
        surface=terrazzo_result,
    )


def terrazzo_black_monocolor_distribution(
    rng: pf.RNG,
    vector: pf.ProcNode[pf.Vector],
    large_chip_scale: t.SocketOrVal[float] | None = None,
    medium_chip_scale: t.SocketOrVal[float] | None = None,
    small_chip_scale: t.SocketOrVal[float] | None = None,
    big_chip_detail: t.SocketOrVal[float] | None = None,
    medium_chip_detail: t.SocketOrVal[float] | None = None,
    small_chip_detail: t.SocketOrVal[float] | None = None,
) -> pf.Material:
    concrete_black_threshold = pf.random.uniform(rng, 0.5, 1)
    concrete_white_threshold = pf.random.uniform(rng, concrete_black_threshold, 1)
    concrete_base_color = (
        pf.random.clip_gaussian(rng, mean=0.15, std=0.1, low=0.0, high=1.0),
        pf.random.clip_gaussian(rng, mean=0.15, std=0.1, low=0.0, high=1.0),
        pf.random.clip_gaussian(rng, mean=0.15, std=0.1, low=0.0, high=1.0),
    )

    # For black terrazzo, choose between grayscale or brown chips
    chip_colors = pf.control.choice(
        rng,
        [
            (
                (
                    random_brown_color(rng),
                    random_brown_color(rng),
                    random_brown_color(rng),
                ),
                0.1,
            ),
            (
                (
                    random_grayscale_color(rng),
                    random_grayscale_color(rng),
                    random_grayscale_color(rng),
                ),
                0.9,
            ),
        ],
    )
    small_chip_color = chip_colors[0]
    medium_chip_color = chip_colors[1]
    large_chip_color = chip_colors[2]

    return terrazzo_monocolor_distribution(
        rng=rng,
        vector=vector,
        large_chip_scale=large_chip_scale,
        medium_chip_scale=medium_chip_scale,
        small_chip_scale=small_chip_scale,
        big_chip_detail=big_chip_detail,
        medium_chip_detail=medium_chip_detail,
        small_chip_detail=small_chip_detail,
        concrete_black_threshold=concrete_black_threshold,
        concrete_white_threshold=concrete_white_threshold,
        concrete_base_color=concrete_base_color,
        small_chip_color=small_chip_color,
        medium_chip_color=medium_chip_color,
        large_chip_color=large_chip_color,
    )


def terrazzo_distribution(
    rng: pf.RNG,
    vector: pf.ProcNode[pf.Vector],
    large_chip_scale: t.SocketOrVal[float] | None = None,
    medium_chip_scale: t.SocketOrVal[float] | None = None,
    small_chip_scale: t.SocketOrVal[float] | None = None,
    big_chip_detail: t.SocketOrVal[float] | None = None,
    medium_chip_detail: t.SocketOrVal[float] | None = None,
    small_chip_detail: t.SocketOrVal[float] | None = None,
) -> pf.Material:
    func = pf.control.choice(
        rng,
        [
            (terrazzo_multicolor_distribution, 0.56),  # 0.8 * 0.7
            (terrazzo_black_multicolor_distribution, 0.14),  # 0.2 * 0.7
            (terrazzo_monocolor_distribution, 0.24),  # 0.8 * 0.3
            (terrazzo_black_monocolor_distribution, 0.06),  # 0.2 * 0.3
        ],
    )
    return func(
        rng=rng,
        vector=vector,
        large_chip_scale=large_chip_scale,
        medium_chip_scale=medium_chip_scale,
        small_chip_scale=small_chip_scale,
        big_chip_detail=big_chip_detail,
        medium_chip_detail=medium_chip_detail,
        small_chip_detail=small_chip_detail,
    )


if __name__ == "__main__":
    # Code generated by procfunc v0.4.0
    vector = pf.nodes.shader.uv_map()

    terrazzo_monocolor_result = terrazzo_monocolor(vector)
    terrazzo_multicolor_result = terrazzo_multicolor(vector)
