extend = "../../.ruff.toml"

[lint.flake8-tidy-imports.banned-api]
"inspect".msg = "metaprogramming is too complicated / confusing for procedural generator behavior"
"infinigen_v2.generators.scenes".msg = "objects cannot depend on scenes"

[lint]
extend-select = [
    "T201", # no print()
    "T203", # no pprint()
    "TID251", # custom banned imports
]
