import numpy as np
import procfunc as pf


def banana() -> pf.MeshObject:
    # Code generated by procfunc v0.3.0

    curve_curve = pf.nodes.geo.curve_bezier(
        start=(-0.07, 0.0, 0.0),
        middle=(0.0, 0.083, 0.0),
        end=(0.07, 0.0, 0.0),
    )
    curve = pf.nodes.geo.resample_curve_count(curve_curve)
    radius_value = pf.nodes.geo.spline_parameter()
    radius = pf.nodes.math.float_curve(
        value=radius_value.factor,
        curve=np.array([[0.0, 0.0], [0.5114, 0.975], [0.9886, 0.0]]),
        factor=1.0,
    )
    mesh_curve = pf.nodes.geo.set_curve_radius(curve=curve, radius=radius * 0.015)
    geometry = pf.nodes.geo.curve_circle(20)
    offset_value = pf.nodes.texture.noise(vector=None, scale=100.0)
    offset = pf.nodes.math.map_range(
        value=offset_value.color.astype(dtype=pf.Vector),
        from_min=(0.0, 0.0, 0.0),
        from_max=(1.0, 1.0, 1.0),
        to_min=(-0.4, -0.4, 0.0),
        to_max=(0.4, 0.4, 0.0),
    )
    mesh_profile_curve = pf.nodes.geo.set_position(geometry=geometry, offset=offset)
    mesh = pf.nodes.geo.curve_to_mesh(
        curve=mesh_curve,
        profile_curve=mesh_profile_curve,
        fill_caps=True,
    )
    result = pf.nodes.geo.subdivision_surface(mesh=mesh, level=3, uv_smooth="NONE")
    return pf.nodes.to_mesh_object(geometry=result)
