import procfunc as pf
from procfunc.nodes import types as t

from infinigen_v2.generators.shaders.masks.brick_cutter import brick_cutter
from infinigen_v2.generators.shaders.materials.wood_grain import (
    wood_color_distribution,
    wood_grain_blonde,
    wood_grain_brown,
    wood_grain_deck,
    wood_grain_flaky,
    wood_grain_generator_distribution,
    wood_shader_distribution,
)


def _grout_shader(color: t.SocketOrVal[pf.Color]) -> pf.ProcNode[pf.Shader]:
    return pf.nodes.shader.diffuse_bsdf(color=color)


def wood_planks_deck(
    vector: t.SocketOrVal[pf.Vector],
):
    # Code generated by procfunc v0.12.0

    brick_cutter_result = brick_cutter(
        vector=vector,
        brick_width=1.0,
        brick_height=0.1,
        brick_scaling=1.0,
        shift=0.0,
        irregularity=0.0,
        gab=0.03,
        round_corner=0.0,
        warp_strength=0.0,
        warp_size=1.0,
        random_coord=(5.0, 0.2, 0.26),
        seed=4.0,
        masked_coord=0.0,
        brick_extrusion=0.3,
        brick_extrusion_variation=0.0,
        brick_bevel=0.04,
        brick_bevel_concavity=0.0,
        grout_extrusion=-0.2,
        grout_bevel=1.0,
        grout_bevel_concavity=1.0,
    )

    displacement_grains_color_1 = pf.nodes.color.mix_rgb(
        blend_type="SOFT_LIGHT",
        a=pf.Color((0.142, 0.119, 0.086)),
        b=brick_cutter_result.random.astype(dtype=pf.Vector).x.astype(dtype=pf.Color),
    )
    displacement_grains_color = pf.nodes.color.mix_rgb(
        blend_type="SOFT_LIGHT",
        a=pf.Color((0.387, 0.321, 0.229)),
        b=brick_cutter_result.random.astype(dtype=pf.Vector).y.astype(dtype=pf.Color),
    )

    wood_shader_result = wood_grain_deck(
        vector=brick_cutter_result.vector,
        additional_displacement=brick_cutter_result.height,
        grains_color_1=displacement_grains_color_1,
        grains_color_2=displacement_grains_color,
    )

    mix_shader = pf.nodes.shader.mix_shader(
        factor=brick_cutter_result.mask,
        a=_grout_shader(displacement_grains_color_1),
        b=wood_shader_result.surface,
    )
    return pf.Material(
        surface=mix_shader,
        displacement=wood_shader_result.displacement,
    )


def wood_planks_brown(
    vector: t.SocketOrVal[pf.Vector],
):
    # Code generated by procfunc v0.12.0

    brick_cutter_result = brick_cutter(
        vector=vector,
        brick_width=1.0,
        brick_height=0.1,
        brick_scaling=1.0,
        shift=0.0,
        irregularity=0.0,
        gab=0.03,
        round_corner=0.0,
        warp_strength=0.0,
        warp_size=1.0,
        random_coord=(5.0, 0.2, 0.26),
        seed=4.0,
        masked_coord=0.0,
        brick_extrusion=0.3,
        brick_extrusion_variation=0.0,
        brick_bevel=0.07,
        brick_bevel_concavity=0.0,
        grout_extrusion=-0.2,
        grout_bevel=1.0,
        grout_bevel_concavity=1.0,
    )

    displacement_grains_color_1 = pf.nodes.color.mix_rgb(
        blend_type="SOFT_LIGHT",
        a=pf.Color((0.021, 0.014, 0.005)),
        b=brick_cutter_result.random.astype(dtype=pf.Vector).x.astype(dtype=pf.Color),
    )
    displacement_grains_color = pf.nodes.color.mix_rgb(
        blend_type="SOFT_LIGHT",
        a=pf.Color((0.249, 0.103, 0.035)),
        b=brick_cutter_result.random.astype(dtype=pf.Vector).y.astype(dtype=pf.Color),
    )

    wood_shader_result = wood_grain_brown(
        vector=brick_cutter_result.vector,
        additional_displacement=brick_cutter_result.height,
        grains_color_1=displacement_grains_color_1,
        grains_color_2=displacement_grains_color,
    )

    mix_shader = pf.nodes.shader.mix_shader(
        factor=brick_cutter_result.mask,
        a=_grout_shader(displacement_grains_color_1),
        b=wood_shader_result.surface,
    )
    return pf.Material(
        surface=mix_shader,
        displacement=wood_shader_result.displacement,
    )


def wood_planks_blonde(
    vector: t.SocketOrVal[pf.Vector],
):
    # Code generated by procfunc v0.12.0

    brick_cutter_result = brick_cutter(
        vector=vector,
        brick_width=1.0,
        brick_height=0.1,
        brick_scaling=1.0,
        shift=0.5,
        irregularity=0.0,
        gab=0.03,
        round_corner=0.0,
        warp_strength=0.0,
        warp_size=1.0,
        random_coord=(5.0, 0.2, 0.26),
        seed=3.0,
        masked_coord=0.0,
        brick_extrusion=0.005,
        brick_extrusion_variation=0.0,
        brick_bevel=0.14,
        brick_bevel_concavity=-1.0,
        grout_extrusion=-0.2,
        grout_bevel=1.0,
        grout_bevel_concavity=1.0,
    )

    surface_b_grains_color_1 = pf.nodes.color.mix_rgb(
        blend_type="SOFT_LIGHT",
        a=pf.Color((0.432, 0.254, 0.069)),
        b=brick_cutter_result.random.astype(dtype=pf.Vector).x.astype(dtype=pf.Color),
    )
    surface_b_grains_color = pf.nodes.color.mix_rgb(
        blend_type="SOFT_LIGHT",
        a=pf.Color((0.549, 0.359, 0.122)),
        b=brick_cutter_result.random.astype(dtype=pf.Vector).y.astype(dtype=pf.Color),
    )

    wood_shader_result = wood_grain_blonde(
        vector=brick_cutter_result.vector,
        additional_displacement=brick_cutter_result.height,
        grains_color_1=surface_b_grains_color_1,
        grains_color_2=surface_b_grains_color,
    )

    mix_shader = pf.nodes.shader.mix_shader(
        factor=brick_cutter_result.mask,
        a=_grout_shader(surface_b_grains_color_1),
        b=wood_shader_result.surface,
    )

    displacement = pf.nodes.shader.displacement(
        height=brick_cutter_result.height,
        midlevel=0.0,
        normal=(0.0, 0.0, 0.0),
    )
    return pf.Material(
        surface=mix_shader,
        displacement=displacement,
    )


def wood_planks_presets(
    rng: pf.RNG,
    vector: t.SocketOrVal[pf.Vector],
):
    func = pf.control.choice(
        rng,
        [
            (wood_planks_deck, 1.0),
            (wood_planks_brown, 1.0),
            (wood_planks_blonde, 1.0),
            (wood_planks_flaky, 1.0),
        ],
    )
    return func(vector=vector)


def wood_planks_flaky(
    vector: t.SocketOrVal[pf.Vector],
):
    # Code generated by procfunc v0.13.1

    diffuse = pf.nodes.shader.diffuse_bsdf(
        color=pf.Color((0.526, 0.526, 0.526)),
        normal=(0.0, 0.0, 0.0),
    )

    brick_cutter_result = brick_cutter(
        vector=vector,
        brick_width=1.0,
        brick_height=0.2,
        brick_scaling=1.0,
        shift=0.0,
        irregularity=0.0,
        gab=0.2,
        round_corner=0.0,
        warp_strength=0.0,
        warp_size=1.0,
        random_coord=(5.0, 0.2, 0.26),
        seed=0.0,
        masked_coord=1.0,
        brick_extrusion=1.0,
        brick_extrusion_variation=0.0,
        brick_bevel=0.1,
        brick_bevel_concavity=0.0,
        grout_extrusion=0.0,
        grout_bevel=1.0,
        grout_bevel_concavity=1.0,
    )

    wood_shader_grains_color_1 = pf.nodes.color.mix_rgb(
        a=pf.Color((0.142, 0.119, 0.086)),
        b=brick_cutter_result.random.astype(dtype=pf.Vector).x.astype(dtype=pf.Color),
        blend_type="SOFT_LIGHT",
    )
    wood_shader_grains_color = pf.nodes.color.mix_rgb(
        a=pf.Color((0.387, 0.321, 0.229)),
        b=brick_cutter_result.random.astype(dtype=pf.Vector).y.astype(dtype=pf.Color),
        blend_type="SOFT_LIGHT",
    )

    wood_shader_result = wood_grain_flaky(
        vector=brick_cutter_result.vector,
        additional_displacement=brick_cutter_result.height,
        grains_color_1=wood_shader_grains_color_1,
        grains_color_2=wood_shader_grains_color,
    )

    return pf.Material(
        surface=diffuse,
        displacement=wood_shader_result.displacement,
    )


def planks_cutter_distribution(
    rng: pf.RNG,
    vector: t.SocketOrVal[pf.Vector],
):
    brick_width = pf.random.uniform(rng, 0.8, 1.2)
    brick_height = pf.random.uniform(rng, 0.08, 0.2)
    brick_scaling = pf.random.uniform(rng, 0.5, 1.5)
    shift = pf.random.uniform(rng, 0.0, 1)
    irregularity = pf.control.choice(
        rng,
        [
            (0.0, 1.0),
            (pf.random.uniform(rng, 0.3, 0.7), 1.0),
        ],
    )
    gab = pf.random.exponential(rng, 0.015)
    round_corner = pf.random.uniform(rng, 0.0, 0.2)
    warp_strength = pf.random.exponential(rng, 0.12)
    warp_size = pf.random.uniform(rng, 0, 50.0)
    random_coord = (5.0, 0.2, 0.26)
    seed = pf.random.uniform(rng, 0.0, 100.0)
    masked_coord = 0.0
    brick_extrusion = pf.random.uniform(rng, 0.005, 0.3)
    brick_extrusion_variation = pf.random.uniform(rng, 0.0, 0.1)
    brick_bevel = pf.random.uniform(rng, 0.04, 0.14)
    brick_bevel_concavity = pf.random.uniform(rng, -1.0, 0.0)
    grout_extrusion = pf.random.uniform(rng, -0.3, -0.1)
    grout_bevel = 1.0
    grout_bevel_concavity = 1.0

    brick_cutter_result = brick_cutter(
        vector=vector,
        brick_width=brick_width,
        brick_height=brick_height,
        brick_scaling=brick_scaling,
        shift=shift,
        irregularity=irregularity,
        gab=gab,
        round_corner=round_corner,
        warp_strength=warp_strength,
        warp_size=warp_size,
        random_coord=random_coord,
        seed=seed,
        masked_coord=masked_coord,
        brick_extrusion=brick_extrusion,
        brick_extrusion_variation=brick_extrusion_variation,
        brick_bevel=brick_bevel,
        brick_bevel_concavity=brick_bevel_concavity,
        grout_extrusion=grout_extrusion,
        grout_bevel=grout_bevel,
        grout_bevel_concavity=grout_bevel_concavity,
    )
    return brick_cutter_result


def wood_planks_distribution(
    rng: pf.RNG,
    vector: t.SocketOrVal[pf.Vector],
):
    """
    Intended for indoor wooden floors and furniture - mostly smooth
    """
    brick_cutter_result = planks_cutter_distribution(rng, vector)

    color_1, color_2, flake_color, fiber_color, knot_color = wood_color_distribution(
        rng
    )

    grains_color_1 = pf.nodes.color.mix_rgb(
        blend_type="SOFT_LIGHT",
        a=color_1,
        b=brick_cutter_result.random.astype(dtype=pf.Vector).x.astype(dtype=pf.Color),
    )
    grains_color_2 = pf.nodes.color.mix_rgb(
        blend_type="SOFT_LIGHT",
        a=color_2,
        b=brick_cutter_result.random.astype(dtype=pf.Vector).y.astype(dtype=pf.Color),
    )

    generator_result = wood_grain_generator_distribution(
        rng, brick_cutter_result.vector
    )

    shader_result = wood_shader_distribution(
        rng,
        additional_displacement=brick_cutter_result.height,
        grains_grain_map=generator_result.grain_map,
        grains_color_1=grains_color_1,
        grains_color_2=grains_color_2,
        flake_flake_map=generator_result.flake_map,
        flake_flake_color=flake_color,
        fibers_fiber_map=generator_result.fiber_map,
        fibers_fiber_color=fiber_color,
        knots_knot_map=generator_result.knot_map,
        knots_knot_color=knot_color,
    )

    mix_shader = pf.nodes.shader.mix_shader(
        factor=brick_cutter_result.mask,
        a=_grout_shader(grains_color_1),
        b=shader_result.bsdf,
    )

    return pf.Material(
        surface=mix_shader,
        displacement=shader_result.displacement,
    )


def wood_siding_distribution(
    rng: pf.RNG,
    vector: t.SocketOrVal[pf.Vector],
):
    """
    Intended for outdoor wooden house siding - rough and flaky
    """

    # TODO: replace with continously randomized version
    #   must call planks_cutter_distribution and use wood_grain_flaky_distribution from wood_grain.py

    return wood_planks_flaky(vector=vector)
