
name: Lint & Test

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
    - main
    - develop*
  push:
    branches:
    - main
    - develop*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  INFINIGEN_INSTALL_TERRAIN: False
  INFINIGEN_INSTALL_CUSTOMGT: False

jobs:

  checks:
    runs-on: ${{ fromJSON(vars.CI_RUNNER || '"ubuntu-latest"') }}

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0

      - name: Validate code
        run: bash scripts/integration_v2/validate_code.sh

      - name: Set up SSH for procfunc
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PROCFUNC_DEPLOY_KEY }}

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.8.3"

      - name: Install
        run: |
          uv venv
          uv pip install -e .

      - name: Lint and Format (ruff)
        run: |
          uvx ruff==0.14.5 format --check .
          uvx ruff==0.14.5 check --output-format=github --select=E9,F63,F7,F82 .
          uvx ruff==0.14.5 check --output-format=github .
      
      # - name: Install with dev dependencies
      #   run: |
      #     uv venv
      #     uv pip install ".[dev]"

      # - name: Unit Tests (pytest)
      #   run: |
      #     uv run pytest tests/infinigen_v2 -k 'not skip_for_ci and not render_gpu'
