name: Build & Release

on:
  push:
    tags:
      - '*'

jobs:
  build_sdist_purepy:
    name: Build source/pure python wheels
    if: github.repository == 'princeton-vl/infinigen'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Build source/pure python wheels
      run: |
        python -m pip install build
        python -m build --outdir=wheelhouse
      env:
        INFINIGEN_MINIMAL_INSTALL: "True"

    - name: Upload to github
      uses: actions/upload-artifact@v4
      with:
        path: wheelhouse/*
        if-no-files-found: error

  publish_to_pypi:
    name: Publish wheels to PyPi
    # if branch main repo "infinigen"
    if: github.repository == 'princeton-vl/infinigen' && startsWith(github.event.ref, 'refs/tags')
    needs: [build_sdist_purepy]
    runs-on: ubuntu-latest
    steps:
      - name: Download packages
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Upload wheels to pypi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m pip install --upgrade twine packaging
          twine upload dist/*
